### ISSUE TITLE
filter-navigator.v2: Doesn't render filters even though they exist on facets API

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#1]
**Describe the bug**
On custom store.search pages (for example, searching by collection or seller id), the filter-navigator.v2 interface doesn't render any filters, even though when querying the same search on the facets API, it shows Brands, Department and Categories.

**To Reproduce**
1. Go to https://parquedpedro.myvtex.com/c/tng (this is a extended template to render search-result without vtex.store/SearchContext). It's filled with `storetng` and map `sellerIds`
2. Query the Facets API to see what's available fetch('/api;catalog_system/pub/facets/search/storetng?map=sellerIds')

**Expected behavior**
It should show the brands and departments from the query on filter-navigator.

**Screenshots**
![image](https://user-images.githubusercontent.com/27775611/59535279-ecdbb000-8ec6-11e9-91cc-61204d117236.png)

**Comment by klzns** [comment]
Can you give an example here?
https://storetheme.vtex.com/

**Comment by jgfidelis** [comment]
Isso ocorre porque essa página é um store.custom.

Quem faz a query de facets e faz aparecer o filter-navigator é a SearchContext, que só existe no bloco store.search. Não tem como essa página ser um store.seach#custom, algo assim?

**Comment by hapoza** [comment]
O store.search#custom vem com o SearchContext, pois isso está implementado no store.search. E o que acontece é que acaba ignorando qualquer configuração inserida no StoreFront. Isso foi uma indicação do Danilo Hirama pra fazermos assim, uma página sem context implementando o search-result, que daí passa a aceitar as opções inseridas no storefront.

**Comment by hapoza** [comment]
@jgfidelis Fui tentar criar uma página usando o `store.search#custom` só pra confirmar e te mostrar evidências, mas ela nem aparece como opção ao criar uma página nova. Veja essa página que criei https://dan--parquedpedro.myvtex.com/admin/cms/pages/vtex.store%402.x%3Astore.custom%23debug-custom-search
Nas opções só aparece o `store.custom` e outros dois templates específicos da loja, o da busca não está disponível.

Também tentei de outra forma, que é só apontar um banner para o `store.search#custom`, colocando o `terms={{url}}` para "criar" a URL `/camisariacolombo`, e configurei no StoreFront o "Resultado da Busca" como `query:camisariacolombo` e `map:sellerIds`. Porém ao acessar essa página, está tentando fazer uma busca pelo term `camisariacolombo`, e não "vendo" o que foi configurado no StoreFront. Foi assim que tentamos fazer inicialmente e vimos que não tem como controlar o search-result pelas configs do StoreFront quando o template é da interface `store.search`, e fomos indicados a fazer um novo template, o que causa o "bug" que reportei de não aparecer nenhum filtro. Veja aqui https://dan--parquedpedro.myvtex.com/camisariacolombo

Pra garantir que não é o problema da questão de rotas (estar abrindo o store.search normal em vez do custom), também tentei com o `store.search#configurable` que gera uma URL diferente, https://dan--parquedpedro.myvtex.com/s/camisariacolombo, mas o problema persiste de usar o term pra fazer a busca em vez de usar o que é configurado.

Se examinar o Searchresult na aba React, dá pra ver que ele tem as props necessárias, mas a searchQuery que foi executada fez foi usar o terms e fazer uma busca fulltext, pois só recebeu isto no variables ![image](https://user-images.githubusercontent.com/27775611/59639395-89a18600-9131-11e9-9770-4b71a4eaf4c5.png)

Em resumo, nem consegui testar mesmo de novo por não conseguir criar uma página antes de navegar até ela e preencher os props no StoreFront, e se direcionar pra uma página de busca, seja custom ou configurable sem criar a página antes, eles vão usar o terms como um termo de busca, e ignorar qualquer opçao preenchida no storefront (até opções de quantidade de itens por página e ordenação).
Espero que depois desse textão consiga entender melhor qual o problema :pray:

**Comment by hapoza** [comment]
Pode ignorar esses dois últimos testes também, que acabei de lembrar quando direcionamos para uma página arbitrária que não foi criada pela lista de páginas, o StoreFront não sabe identificar a configuração "esta URL" e portanto mesmo que funcionasse, não serviria para o meu caso pois permitiria manter apenas uma configuração, e preciso que as configurações seja únicas por URL.

**Comment by jgfidelis** [comment]
Ola, refleti e vi que o problema era nosso mesmo, corrigi aqui:
https://github.com/vtex-apps/search-result/pull/193

Jaja lançamos e vc valida aí

**Comment by jgfidelis** [comment]
Resolved in vtex.search-result@3.21.7

**Comment by hapoza** [comment]
Tá funcionando perfeitamente, já testei em 3 lojas, obrigado @jgfidelis :tada:
