### ISSUE TITLE
Fix Buy Button's Toast alignment on mobile

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#100]
**Describe the bug**
The Toast message and buttons are misaligned on small viewports.

**To Reproduce**
1. Go to https://storetheme.vtex.com/
2. Enable iPhone 5/SE crop on Chrome's Device Toolbar
3. Click BUY

**Screenshots**
320px
![storetheme vtex com_(iPhone 5_SE) (1)](https://user-images.githubusercontent.com/27775611/64426651-84dfd480-d085-11e9-8aae-6c8bff067090.png)
639px
![storetheme vtex com_](https://user-images.githubusercontent.com/27775611/64426696-a50f9380-d085-11e9-8e8b-9172a27a8d80.png)

**Smartphone (please complete the following information):**
 - Device: any device with a viewport smaller than 640px

**Comment by klzns** [comment]
Related https://github.com/vtex/styleguide/issues/644

**Comment by emersonlaurentino** [comment]
@hapoza Does this problem still persist? I can not reproduce, apparently it is resolved, can close this issue?

**Comment by hapoza** [comment]
@emersonlaurentino Sorry I missed the notification! The problem still persists: https://prnt.sc/q9ym43

**Comment by emersonlaurentino** [comment]
@hapoza I think you can solve this similar as it was done here https://github.com/vtex/styleguide/pull/859

**Comment by hapoza** [comment]
@emersonlaurentino I solved this with CSS overrides on my store's custom store-theme, but the default store-theme presents the issue as I showed on the screenshot previously, you can see it going to https://storetheme.vtex.com/

**Comment by emersonlaurentino** [comment]
apparently is correct, when it is on mobile it the "View Cart" button is on the bottom line, and when it is on a desktop screen, the button appears next to the text. Shouldn't this be the right behavior?

**Comment by hapoza** [comment]
@emersonlaurentino It just "looks" weird to me the way it's presented visually, but if you say that's the desired behavior, then it's not an issue 😄
