### ISSUE TITLE
Transparent header

### ISSUE THREAD

**Issue by rickrd** [vtex-apps/store-discussion#102]
**Is your feature request related to a problem? Please describe.** 
Header already has a prop that makes it sticky to the top of the screen but I need the content below it to bleed off the top of screen.

**Describe the solution you'd like**
Create a configuration that when applicable, system will allow for a transparent header, to let image bleed off top of screen and once user begins to scroll, header will standard change to white header.

**Describe alternatives you've considered**
I couldnt make it through CSS.

**Additional context**
Example:
![Captura de Tela 2019-09-06 às 10 59 52](https://user-images.githubusercontent.com/15057760/64434393-d775bc80-d096-11e9-8fd1-5123112b2380.png)

**Comment by micas06gua** [comment]
We have a store where we will need this feature for migration. But when scrolling, the header gets a color. I believe we should have a class to differentiate between the transparent fixed header and the color fixed scroll header.

Follows the reference store, today at vtex cms: https://www.miniprix.ro

**Comment by klzns** [comment]
That's now possible! Check how we did in store-theme https://github.com/vtex-apps/store-theme/pull/201/files
