### ISSUE TITLE
Minicart does not show discounted price.

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/store-discussion#103]
**Describe the bug**

Minicart is not showing the "was" price, only the discounted price.

**Expected behavior**

I expected the highest price to appear there, showing a difference in value.

**Screenshots**
![Captura de Tela 2019-09-06 às 16 48 48](https://user-images.githubusercontent.com/44183746/64459316-f93e6600-d0cd-11e9-811b-3d6e871f0444.png)

![Captura de Tela 2019-09-06 às 17 44 41](https://user-images.githubusercontent.com/44183746/64459368-1410da80-d0ce-11e9-9fa2-3e836fa30afd.png)

**Comment by jgfidelis** [comment]
Hello, did you pass the prop `showDiscount` to true in your minicart in blocks.json?

```
"minicart": { "props": { "showDiscount":true}}
```

**Comment by leonardkorb** [comment]
I have this props, but this is not what I want. I do not want the total discount of the products, but the discount of the product. Example: $ 150.00 for $ 90.00.

**Comment by denisebiscaro** [comment]
Already possible by using  `minicart.v2` - https://github.com/vtex-apps/minicart
