### ISSUE TITLE
 Department Page Paging Option

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/store-discussion#105]
**Is your feature request related to a problem? Please describe.**
It wouldn't be a problem, but on the department page I wish I had the option to have pagination and not just load more products.

**Describe the solution you'd like**
I wish we had the option to select pagination in storeFront, as it has with the infinite scroll option.

![Captura de Tela 2019-09-09 às 14 01 10](https://user-images.githubusercontent.com/44183746/64550925-56266000-d30a-11e9-892c-924593599c59.png)

**Comment by jgfidelis** [comment]
We probably don't want to support this because multiple studies indicate that pagination like is really bad UX. Source: https://www.smashingmagazine.com/2016/03/pagination-infinite-scrolling-load-more-buttons/
