### ISSUE TITLE
Add to bag confirmation

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/store-discussion#106]
**Is your feature request related to a problem? Please describe.**
It would not be a problem, but a new function.

**Describe the solution you'd like**
I would like that as soon as I added the item to the bag, the message would be above the buy button.
Making the message stay on the button all the time.

**Describe alternatives you've considered**
This message can be set on the storefront. This option would only be a property on the button element.

![Captura de Tela 2019-09-09 às 18 37 14](https://user-images.githubusercontent.com/44183746/64568351-e4154180-d330-11e9-9d1f-7ada74aad09a.png)
![Captura de Tela 2019-09-09 às 18 37 00](https://user-images.githubusercontent.com/44183746/64568355-e5df0500-d330-11e9-9ae7-3f9cb303d6b4.png)

**Comment by klzns** [comment]
Interesting feature. It might be simple to implement this in the https://github.com/vtex-apps/store-components [BuyButton component](https://github.com/vtex-apps/store-components/blob/master/react/components/BuyButton/index.js).
