### ISSUE TITLE
Brand Carousel for front page

### ISSUE THREAD

**Issue by mjfernandezr** [vtex-apps/store-discussion#107]
We have found in some requests that the client wishes to include a brand carousel and by talking with technical support we've got that is not possible yet.

So, it would be nice to have a component where we can include the brand ID, its image and make of it a carousel. This would benefit several clients that use this feature in their original sites.

We considered using a regular carousel with normal re directions but we are not very sure it will work without causing some issues.

![image](https://user-images.githubusercontent.com/51333473/64624654-5d5c7500-d3c1-11e9-945d-9c46394d4e71.png)

**Comment by victorhmp** [comment]
Hi @mjfernandezr !

We're currently working on a more flexible solution that will allow developers to create Sliders (basically a carousel) with pretty much anything they want inside. That should cover this use-case, and this is one of the cases we're aiming to solve!

We hope to be able to release this soon! Keep an eye on our weekly Release Notes!

**Comment by victorhmp** [comment]
Closing this since it can now be achieved using `slider-layout`.
