### ISSUE TITLE
Mobile filter side.

### ISSUE THREAD

**Issue by leonardkorb** [vtex-apps/store-discussion#108]
**Is your feature request related to a problem? Please describe.**
Not a bug, but it would be an option in mobile filter placement.

**Describe the solution you'd like**
I wish I had class for styling the whole block of the mobile menu. By default this filter opens on the right side of the screen, but could have a class or a props to define the side that it opens. Because some customers prefer the menu on the left.

**Describe alternatives you've considered**
I would advise that this could be optional, to choose which side to put the menu, through class or props.

![Captura de Tela 2019-09-10 às 14 16 38](https://user-images.githubusercontent.com/44183746/64635471-22187100-d3d6-11e9-8457-a4053bbfc686.png)
![Captura de Tela 2019-09-10 às 14 17 06](https://user-images.githubusercontent.com/44183746/64635479-25abf800-d3d6-11e9-8222-2a707f996223.png)

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/drawer/pull/10 - Done!
