### ISSUE TITLE
Implementing third party fonts

### ISSUE THREAD

**Issue by JesuFernandez** [vtex-apps/store-discussion#11]
Hello!

We are implementing a shop migration to VTEX, using vtex.io
The main requirement is that the new store is the most identical to the current, and we have found that the fonts are available from google.
Now, the font assignations come from style.json and not directly from css or html. So, is there a way we can do this implementation on the JSON for all the site?

**Comment by athoscouto** [comment]
Hello @JesuFernandez.
We're planning to deploy basic support soon (https://github.com/vtex-apps/admin-pages/pull/196).
There will be support to include font declarations on apps too.
Unfortunately on the first version we'll not be able to include native support for Google Fonts, but we plan to include it on `admin-pages` soon.

**Comment by hapoza** [comment]
@athoscouto @saviofelixmuniz I see that the PR was merged (vtex-apps/admin-pages#196), does it work only on admin-pages or with styles builder config files as well, unsing a custom font-face? Can you create documentation?

**Comment by klzns** [comment]
Sure! @saviofelixmuniz
