### ISSUE TITLE
My-Account - Validate BirthDate 

### ISSUE THREAD

**Issue by MatheusR42** [vtex-apps/store-discussion#110]
**Describe the bug**
My-account component allows future dates in birthDate.

I tested in https://storetheme.vtex.com/account#/profile

**Screenshots**
![image](https://user-images.githubusercontent.com/16908590/64812709-31cebb80-d576-11e9-9caa-87e78da582bf.png)

**Comment by arthurepc** [comment]
This was solved [here](https://github.com/vtex/profile-form/pull/53). Thus, I'm closing this issue,
