### ISSUE TITLE
Search terms break characters in breadcrumb on departament page load

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#113]
**Describe the bug**
When accessing the department: "infantil" using the render-runtime, then filtering by "idade" for instance "0 a 4 anos", the text that comes in the breadcrumbs works correctly, but when reloading the filtered page, the breadcrumb gets special characters, probably because of the white spaces between the letters.

https://ibb.co/KrKccHw
https://ibb.co/619Ct7P

**To Reproduce**
1. Go to https://www.newbalance.com.br
2. Choose the department : "infantil" , then filter by "idade"
3. Wait for the page to finish loading, then reload it
4. The breadcrumb will be broken with special characters.

**Comment by jgfidelis** [comment]
É um bug no componente da agência.
![image](https://user-images.githubusercontent.com/4925068/64898645-4e462300-d65e-11e9-9a93-cdb453dd2959.png)


Pelo que vejo esse componente que instancia o breadcrumb.

Ele está passando as categorias da maneira errada, utilizando inclusive os "categories", algo que foi deprecado. Ele tem que pegar o valor do resolver `breadcrumb` quem vem na `productSearch`, assim como fazemos nós em nossos componentes e passar isso para o breadcrumb pela prop breadcrumb hehe.

exemplo:
```
const breadcrumb = searchQuery.data.productSearch.breadcrumb
...
<Breadcrumb breadcrumb={breadcrumb} />
```

Or `<ExtensionPoint id="breadcrumb" breadcrumb={breadcrumb} />`

**Comment by klzns** [comment]
Closing the issue for now. Let us know if you need any more guidance.

**Comment by jgfidelis** [comment]
![image](https://user-images.githubusercontent.com/4925068/64898878-476be000-d65f-11e9-861a-89f7e1d1edfb.png)

Evidence the breadcrumb resolver is working and if you use it, it works fine.

**Comment by fabiofeichtinger** [comment]
thanks a lot for the analysis guys, i'll try to evaluate better next time here from my side.
