### ISSUE TITLE
Add to cart success modal

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#114]
What we need is to show up a modal when the user add a item on the cart, differently of the current behaviour: 
![image](https://user-images.githubusercontent.com/1374326/64898101-44bbbb80-d65c-11e9-8fd1-289d165fb347.png)

Basically the idea is to show a more friendly and detailed modal, e.g.
1. Go to https://www.miniprix.ro/pantofi-casual-din-piele-naturala-cu-sireturi-si-blana-aplicata-1938605081/p;
2. Then choose the specification you want for the product;
3. Click "Pune in cos" button

Expected result:
![image](https://user-images.githubusercontent.com/1374326/64898177-7df42b80-d65c-11e9-8467-f20b50f0f56c.png)

Another example is the way that we work on TokStok store, also showing recommended products to be added in the bag:
https://www.tokstok.com.br/cama-casal-138-nozes-patente/p
![image](https://user-images.githubusercontent.com/1374326/64898198-96fcdc80-d65c-11e9-91af-97c400f71fa9.png)

**Comment by Klynger** [comment]
Solved by https://github.com/vtex-apps/modal-layout/pull/12
