### ISSUE TITLE
Add clusterHighlights in search-result 

### ISSUE THREAD

**Issue by MatthausZillig** [vtex-apps/store-discussion#115]
Adding the clusterHighlights in the shelf we have flexibility so the customer is able to create collections and choose which one of them will show like 'flags'.

**pull request: add clusterHighlights in productSearchV2 querie#55**
https://github.com/vtex-apps/store-resources/pull/55

**Comment by jgfidelis** [comment]
Can you describe more of what you want to achieve?

pt-br: Se você quer mostrar uma coleção, deve usar o map=productClusterIds, tipo `minhaloja.com/745?map=productClusterIds`

**Comment by MatthausZillig** [comment]
Adicionando clusterHighlights na querie productSearchV2, o cliente vai ter mais flexibilidade, pois ele vai poder criar as coleções e escolher quais delas apareceram como flags.

**Comment by MatthausZillig** [comment]
> Can you describe more of what you want to achieve?
> 
> pt-br: Se você quer mostrar uma coleção, deve usar o map=productClusterIds, tipo `minhaloja.com/745?map=productClusterIds`

Adicionando clusterHighlights na querie productSearchV2, o cliente vai ter mais flexibilidade, pois ele vai poder criar as coleções e escolher quais delas apareceram como flags.
