### ISSUE TITLE
Floating Search Bar (Desktop and Mobile)

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#116]
**Is your feature request related to a problem? Please describe.**
We need a solution to create a floating box with the search bar when the user clicks on the search icon. That is, the website initally starts with the search input hidden, then with the user action the search bar appears along with a modal.

This is a feature that we need for desktop and mobile.

I'll leave few examples below to show the behaviour on different websites;

https://www.miniprix.ro/ (Desktop and Mobile)
![image](https://user-images.githubusercontent.com/1374326/65265882-4b2cb600-dae8-11e9-87cf-12aa41346531.png)

https://amaro.com/ (Mobile)
![image](https://user-images.githubusercontent.com/1374326/65265887-51bb2d80-dae8-11e9-9efd-5a22926bd308.png)

https://www.nike.com/ (Mobile)
![image](https://user-images.githubusercontent.com/1374326/65265931-6b5c7500-dae8-11e9-8227-5879c5f148e2.png)

![image](https://user-images.githubusercontent.com/1374326/65265917-63043a00-dae8-11e9-9dda-ce68c64aef8a.png)

**Comment by klzns** [comment]
That could be achieving using the (still in development) [popover-layout](https://github.com/vtex-apps/popover-layout).
