### ISSUE TITLE
<Container/> component is affecting layout spacings

### ISSUE THREAD

**Issue by augustocb** [vtex-apps/store-discussion#118]
**Describe the bug**
Flex-layout uses <Container/> component to wrap its content. That component has some margins/paddings that are creating wrong spacings around the component's layout.

Ref: https://github.com/vtex-apps/flex-layout/blob/a87757eea5fe6d6ca024869c24be6ec185012ac0/react/FlexLayout.tsx#L39

**To Reproduce**
Just check the margins <Container/> is creating around any block.

**Expected behavior**
Layout's spacings should be defined by using props, as any other block.

**Screenshots**
<img width="706" alt="Screen Shot 2019-09-19 at 14 56 22" src="https://user-images.githubusercontent.com/1315451/65268511-b036da80-daed-11e9-8387-b0e04930c2ec.png">

**Comment by lbebber** [comment]
@augustocb While it's generally recommended for the <Container/> to be kept, for consistency and to guarantee comfortable margins , the top-level `flex-layout.row` block accepts a prop `fullWidth` which removes the container, for components that want to take over the entire screen width
