### ISSUE TITLE
Short description below the title of a shelf

### ISSUE THREAD

**Issue by laliel06** [vtex-apps/store-discussion#119]
**Is your feature request related to a problem? Please describe.**
In the shelf component, we have the option to add a title. But we have some customers who want to add a short caption.

**Describe the solution you'd like**
I'd like a 'prop', something like 'description', to add this caption to the shelf title.

**Describe alternatives you've considered**
Today I created a line in flex-layout, added 2 rich-text, one for the title, another for the subtitle and left the shelf below with its title hidden, but in this solution the title is not necessarily linked to the collection, if for perhaps no longer has a shelf, the customer always has to remember to remove the titles and subtitles in rich-text

**Additional context**
![image](https://user-images.githubusercontent.com/1666806/65281400-ec2b6900-db08-11e9-8106-0ddca79bba0a.png)

**Comment by denisebiscaro** [comment]
The possible workaround for this feature would be to use two `rich-text` components, one for the main title and another for the description
