### ISSUE TITLE
Resize the iframe width and height dynamically

### ISSUE THREAD

**Issue by k-ashok** [vtex-apps/store-discussion#12]
I have inserted iframe using 'vtex-sandbox' app. How to change the width and height of the 'iframe' dynamically based on the content inserted in it?

`"sandbox#promospace" :
 {
    "props": {
      "initialContent": "<iframe allowtransparency ='true' class='snapwidget-widget' frameborder = '0' scrolling ='no' src='https://snapwidget.com/embed/560801' style='border: none; overflow: hidden; width: 100%; height: 1111px;' id = 'iFrameResizer0' ></iframe><script rel='nofollow' src='https://snapwidget.com/js/snapwidget.js'></script>",
      "allowStyles": true,
      "height": "1111px"
    }
  },`

**Comment by klzns** [comment]
We could use https://github.com/davidjbradshaw/iframe-resizer to achieve that in our https://github.com/vtex-apps/sandbox app.

**Comment by k-ashok** [comment]
> Currently, we don't support this.
> 
> We could use https://github.com/davidjbradshaw/iframe-resizer to achieve that in our https://github.com/vtex-apps/sandbox app.

Is that feature going to be implemented any time soon?

**Comment by klzns** [comment]
Fixed :)
