### ISSUE TITLE
Route class should change on navigation

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#120]
**Describe the bug**
On the element with the `render-container` class, there is another class that is exclusive to the route the user is visiting, for the home it is `render-route-store-home`. It's applied to the DOM on the initial load, but when navigating without reloading the page, that class does not update to reflect the new route.

**Expected behavior**
When navigating between routes, the class should update.

**Screenshots**
![Screenshot at Sep 21 17-10-14](https://user-images.githubusercontent.com/27775611/65378752-89b2a400-dc93-11e9-8563-86ecc98db3d8.png)

**Comment by micas06gua** [comment]
Same mistake here when navigating between pages does not happen to change the render-class.

**Comment by jgfidelis** [comment]
This is fixed in a PR but we are being very cautious with releases this week, thanks for the report and will close this once we release it.

**Comment by LucasCastroAcctGlobal** [comment]
In the store I'm working on, the same thing is happening, and there are some CSS customizations I need to perform on some pages and I can only do that with the correct rendering class swap between pages.

**Comment by lbebber** [comment]
The fix has been published! https://github.com/vtex-apps/render-runtime/pull/427

**Comment by fabiofeichtinger** [comment]
@lbebber Hoje pela manhã fiz novamente os testes porém mesmo assim não está trocando o render-class de forma correta! Na sexta gravei um vídeo do teste que fiz e do qual o comportamento ainda está se repetindo hj! https://cl.ly/fc3bb2bdee5b

Eu já resetei a WS no qual estava trabalhando e até criei uma nova, porém sem sucesso

E também usei o comando vtex deps update para atualizar todas as dependências tanto nas workspaces quanto na master, e estou usando a versão 8.71.2 do render-runtime

**Comment by jgfidelis** [comment]
Desculpa, erro ja corrigido em outra PR. Quando lançar fechamos e testem novamente.

**Comment by fabiofeichtinger** [comment]
@jgfidelis tem previsão? Abs

**Comment by jgfidelis** [comment]
Corrigido, com esperança de estar 100% agora 😬

**Comment by fabiofeichtinger** [comment]
@jgfidelis it works :)

**Comment by hapoza** [comment]
@jgfidelis Testei agora e está funcionando, obrigado! 🚀
