### ISSUE TITLE
Add input field "name" to Newsletter component

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#121]
**Is your feature request related to a problem? Please describe.**
Nowdays the newsletter component (https://github.com/vtex-apps/store-components/blob/d773ad0d1382705e604bae4e51d232484f166db9/docs/Newsletter.md) only has `email` field. 

What we need is to also captura the `name` information of the customer. This is useful to create personalized CRM communication more "exclusive" to the customer.

Example of https://www.magazineluiza.com.br/:
![image](https://user-images.githubusercontent.com/1374326/65515944-79c6da00-deb6-11e9-8f2a-3b950a352c72.png)

**Comment by alextalha** [comment]
There is a prediction?
