### ISSUE TITLE
Flex-layout is inserting Containers out of top level

### ISSUE THREAD

**Issue by augustocb** [vtex-apps/store-discussion#122]
**Describe the bug**
Container component should be used to set layout on top level of page, but in some cases it's being applied in other levels. There's a condition (https://github.com/vtex-apps/flex-layout/blob/master/react/FlexLayout.tsx#L25) to avoid inserting Containers out of top level, but it's not working well.

We are trying to improve `Container` component, but that bug is breaking some store's layouts like this:

![Screen Shot 2019-10-01 at 14 40 54](https://user-images.githubusercontent.com/1315451/65986058-810f5a00-e459-11e9-9802-1e86895202e0.png)

**To Reproduce**
1. Go to https://melimeloparis.myvtex.com
2. Check Footer structure and you'll see:

![Screen Shot 2019-10-01 at 14 32 21](https://user-images.githubusercontent.com/1315451/65985784-e0b93580-e458-11e9-90c8-df79a1a10414.png)

**Expected behavior**
Containers should be applied only in the top level.

**Comment by augustocb** [comment]
cc @lbebber @emersonlaurentino

**Comment by emersonlaurentino** [comment]
`container` within` container` will always cause problems because it contains defined breakpoints.

The solution is to stop using `container` when the parent element is a `container`.

**Comment by augustocb** [comment]
@emersonlaurentino unfortunately, a `container` can break the layout if it's used inside any place other than the top level of a Flex-layout structure.
