### ISSUE TITLE
How to create a new page which keeps store's header and footer

### ISSUE THREAD

**Issue by hiagolcm** [vtex-apps/store-discussion#123]
**What are you trying to accomplish? Please describe.**  
Create a new page which keeps the store's header and footer

**What have you tried so far?**  
I created a component called `Page` and declared it in `interfaces.json`.
```
{
  "store.page": {
    "component": "Page"
  }
}
```

Then, I declared a new route to `Page`:
```
{
  "store.page": {
    "path": "/newpage"
  }
}
```

Finally, I linked the app to my [workspace](https://newpage--biggy.myvtex.com/)

Unfortunately, the header and footer are broken on /newpage.

**Additional info**  
I want to keep the installation of this app as "plug and play" as possible. It means modifications in the client's store-theme are not desirable.

You can check the current store header/footer [here](https://newpage--biggy.myvtex.com/) and the broken one [here](https://newpage--biggy.myvtex.com/newpage)

| Account | Workspace |
|---|---|
|`biggy`|`newpage`|

**Comment by polishq** [comment]
I've run into the same problem before. Unfortunately because the header and footer are defined by the store-theme, I don't believe there's any way to apply them to a page defined in another app except by adding a reference to `store.page` in the store-theme's `blocks.json`.
