### ISSUE TITLE
Adicionar classe para custo de entrega - minicart

### ISSUE THREAD

**Issue by Cardosoli** [vtex-apps/store-discussion#125]
**Is your feature request related to a problem? Please describe.**
Preciso estlizar o custo de entrega no minicart, porém não existe uma classe para isso

**Describe the solution you'd like**
Inserir uma classe para essa div (custo de entrega)

**Additional context**
![custodeentrega](https://user-images.githubusercontent.com/47330689/66672331-6cd71400-ec34-11e9-973e-c6c91c64a204.png)

**Comment by victorhmp** [comment]
Hi @Cardosoli !

We've just updated the CSS handles available to enable further customization :)
