### ISSUE TITLE
Clear Button Does Not Work After Applying Filter

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#126]
## Expected Behavior
After the user selects and applies the filter information, 
clicking the clear button will reset the previous filter information.

## Current Behavior
After selecting and applying the filter information, 
clicking the clear button will not reset the previous filter information.

## Steps to Reproduce (for bugs)
1. Go to https://compras.parquedpedro.com.br, on mobile version;
2. Select the category menu (https://flic.kr/p/2hkdkKe);
3. Go to Feminino > Bolsas > Mochilas (https://flic.kr/p/2hkfWWM);
4. Select the filter option (https://flic.kr/p/2hkdkJ7);
5. Select brand option (https://flic.kr/p/2hkdkHa);
6. Select as many brands as you want (https://flic.kr/p/2hkdkGZ);
7. Apply the filter (https://flic.kr/p/2hkfcA7);
8. Select the filter option again (https://flic.kr/p/2hkfczF);
9. Then try to clear the filter selections (https://flic.kr/p/2hkfWU7);
10. Nothing happens, the filter informations are still selected (https://flic.kr/p/2hkdkEE);

This also happens on StoreTheme:

![image](https://user-images.githubusercontent.com/1374326/66873677-6d96df80-ef7f-11e9-931a-947c2a4c4371.png)

## Context
We believe the correct behavior would be to reset the previous filter information after clicking the clear button.

**Comment by iaronaraujo** [comment]
https://github.com/vtex-apps/search-result/pull/283

**Comment by LucasCastroAcctGlobal** [comment]
@klzns as we talked recently at the Office-Hours meeting, the clear button on the mobile filter again gave the same problem. Could you check again, please? Below is the workspace where we simulate the error at the meeting (https://equishopper.myvtex.com/)

**Comment by iaronaraujo** [comment]
Hi @LucasCastroAcctGlobal ! Right now, the intended behavior of the "clear" button is to clear every checkbox you have clicked _before_ clicking on the "apply" button. So if you click on some filters, then click on "apply" and then on "clear", nothing will be cleared! But if you click on "clear" before clicking on "apply", then the changes you made will be cleared!

**Comment by LucasCastroAcctGlobal** [comment]
@iaronaraujo I apologize but I have to disagree with you regarding how this component currently works.

The "clear" button MUST work even after the filter has been applied and not just before.

In my view and in the view of several customers, the correct behavior would be cleaning also after applying the filter.

So, could you correct this behavior, please?

**Comment by klzns** [comment]
FIxed
