### ISSUE TITLE
Quickview Component

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#127]
**Is your feature request related to a problem? Please describe.**
A quickview button at product-summary to open an modal that receives store-components ('product-price', 'buy-button', 'sku-selector', 'product-name'). 

We've developed this feature on some customers by customization, and they request this feature a lot. But we understand that is a better approach that VTEX has it as a native option to the shelves.

Example:

1) Click on "Comprar"
![image](https://user-images.githubusercontent.com/1374326/66874191-d7fc4f80-ef80-11e9-8774-5c9ca20f8be2.png)

2) Quickview
https://www.newbalance.com.br/
![image](https://user-images.githubusercontent.com/1374326/66874111-9f5c7600-ef80-11e9-9c10-b4e031495ccb.png)

**Comment by regis-samurai** [comment]
I also need this feature. I need to know if this is under development or not, because I need to deploy in Jan / 19, and this is a project pendency.
