### ISSUE TITLE
Second Image on Hover

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#129]
**Is your feature request related to a problem? Please describe.**
We need a way to add an second image hover at the image component:
https://github.com/vtex-apps/store-components/blob/master/docs/Image.md

**Describe the solution you'd like**
Add a second-image to appear at the hover, in that way we can create different animations on the website to make more interactive.

**Additional context**
Example1: https://s.nimbusweb.me/share/3333181/is5nuvuqd61iz2001r9v
Example2: https://s.nimbusweb.me/share/3333162/478hry5rswa5fh8h79cz

**Comment by klzns** [comment]
That can be achieved [using the prop `hoverImageLabel`](https://github.com/vtex-apps/product-summary/blob/master/docs/ProductSummaryImage.md).

**Comment by alexdinca** [comment]
@klzns how should I approach this if the images have already been imported without a proper label which I could use in the `hoverImageLabel` prop?

**Comment by klzns** [comment]
There's no other way right now. Open to suggestions though
