### ISSUE TITLE
Insert blocks(flex-layout, rich-text etc...) other than 'menu' in 'Drawer'

### ISSUE THREAD

**Issue by k-ashok** [vtex-apps/store-discussion#13]
My requirement was to place a link in the drawer, which is preceded by 'icon' (right drawer on the image). There's a way to insert links into 'Drawer' by using 'menu-item', which I have used temporarily(left drawer on the image). **How to achieve this scenario?** And what if we had to insert other blocks(flex-layout, rich-text, etc...) inside the 'Drawer', which are not allowed as only 'menu' and 'category-menu' blocks are allowed inside 'Drawer' as per 'interfaces.json'? 

![drawer](https://user-images.githubusercontent.com/52157580/60015828-0c7e8f80-96a2-11e9-84a4-feda45f2a815.PNG)

**Comment by hapoza** [comment]
@k-ashok We were able to do that using the latest version of vtex.menu, 2.16.0, which adds support for blockClass on menu-item. and as far as I can see, you can do what you need using blockClass for each of those items and styling them differently than the rest

**Comment by klzns** [comment]
That's a low hanging fruit! 

We just need to add those interfaces in the `allowed` array of the `drawer`.

**Comment by k-ashok** [comment]
> @k-ashok I was able to do that using the latest version of vtex.menu, 2.16.0, which adds support for blockClass on menu-item. and as far as I can see, you can do what you need using blockClass for each of those items and styling them differently than the rest

Thanks for the information. But how to add icons before a menu-item?  Is there any way that we can add icons into the blocks.json file using vtex.store-icons app?

**Comment by k-ashok** [comment]
> That's a low hanging fruit!
> 
> We just need to add those interfaces in the `allowed` array of the `drawer`.

Can you elaborate that?  As we use apps just by adding them into the dependencies of the manifest.json file, how to add those interfaces, as the interfaces.json file is already defined in 'vtex.store-drawer' app?  Even if we are able to add, is it recommended to modify core vtex-apps?

**Comment by klzns** [comment]
> > That's a low hanging fruit!
> > We just need to add those interfaces in the `allowed` array of the `drawer`.
> 
> Can you elaborate that? As we use apps just by adding them into the dependencies of the manifest.json file, how to add those interfaces, as the interfaces.json file is already defined in 'vtex.store-drawer' app? Even if we are able to add, is it recommended to modify core vtex-apps?

The idea was to improve our component to accept those interfaces by opening a pull request. But don't worry, @lbebber is already tackling this and might achieve this by the end of the week.

**Comment by k-ashok** [comment]
> > > That's a low hanging fruit!
> > > We just need to add those interfaces in the `allowed` array of the `drawer`.
> > 
> > 
> > Can you elaborate that? As we use apps just by adding them into the dependencies of the manifest.json file, how to add those interfaces, as the interfaces.json file is already defined in 'vtex.store-drawer' app? Even if we are able to add, is it recommended to modify core vtex-apps?
> 
> The idea was to improve our component to accept those interfaces by opening a pull request. But don't worry, @lbebber is already tackling this and might achieve this by the end of the week.

@klzns  Thank you

**Comment by hapoza** [comment]
> Thanks for the information. But how to add icons before a menu-item? Is there any way that we can add icons into the blocks.json file using vtex.store-icons app?

In my case I added a blockClass to each menu-item, and used that class to add a :before with an image URL.

**Comment by k-ashok** [comment]
> > Thanks for the information. But how to add icons before a menu-item? Is there any way that we can add icons into the blocks.json file using vtex.store-icons app?
> 
> @k-ashok In my case I added a blockClass to each menu-item, and used that class to add a :before with an image URL.

@hapoza  Thank you. That definitely works, is there any way we can use font-awesome and use :before to insert icons?

**Comment by klzns** [comment]
Follow up https://github.com/vtex-apps/drawer/pull/4

**Comment by klzns** [comment]
New version of drawer released allowing `rich-text` and `flex-layout`.

**Comment by klzns** [comment]
Also, we will soon work on the menu-item so it's possible to add an icon prop making it easier to set this up.

**Comment by k-ashok** [comment]
> Also, we will soon work on the menu-item so it's possible to add an icon prop making it easier to set this up.

@klzns  Thank you
