### ISSUE TITLE
Add title attribute to SKU Selector

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#130]
**Is your feature request related to a problem? Please describe.**
The sku selector does not have a title attribute to the user to identify the name of variation on mouseover:
![image](https://user-images.githubusercontent.com/1374326/66938782-36284180-f018-11e9-97f4-0a3d0105aaff.png)

**Describe the solution you'd like**
Add a title attribute on the HTML element that is around the specification value. 
e.g. <div title="blue"></div>

The goal is to have a tooltip focused on accessibility. 

**component**
https://github.com/vtex-apps/store-components/blob/master/react/components/SKUSelector/index.tsx

**Comment by denisebiscaro** [comment]
Hey @fabiofeichtinger! Take a look if this feature accomplishes what you need: https://github.com/vtex-apps/release-notes/blob/cb2461b715d3375cbafcaf8bd665976113e00e0f/docs/2019-week-31/color-name-sku-selector.md

It shows smth like this 
![image](https://user-images.githubusercontent.com/12139385/66939204-00378d00-f019-11e9-9c5d-76085a0e9356.png)

**Comment by fabiofeichtinger** [comment]
@denisebiscaro Hello!

I'm not sure if that suits our need, because on the customer layout the color name only appears on mouseover. 

The way that you have, the name is fixed even without mouseover, and this is needed only for image attribute.

Anyway, I'll check your solution more deeply

**Comment by Erislandio** [comment]
@denisebiscaro  Hello!

What we need is just an HTML title attribute with the name of the product variation.

each variation selector will have a title with the name of the variation.
