### ISSUE TITLE
minItemsPerPage prop changes the position while swiping

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#131]
## Expected Behavior
When swiping a carousel that has the minItemsPerPage prop the sliding effect should be smooth.

## Current Behavior
As soon as you start sliding the carousel there is a position error that changes the centered item.
Video evidence: https://nimb.ws/OjYKep

## Steps to Reproduce (for bugs)
1- Use a mobile device or the mobile mode on browser.
2- Access Store Theme: https://storetheme.vtex.com/
3- Swipe the Best Products Carousel (do not click on the arrow)

## Context
We believe the correct behavior would be to have a smooth sliding effect as happens when clicking in the arrow.

## Your Environment
* Windows 7
* Chrome 77

**Comment by victorhmp** [comment]
Closing this since this was fixed with a PR in `slider-layout`.
