### ISSUE TITLE
Missing CSS class and blockClass on product-summary

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#132]
**Is your feature request related to a problem? Please describe.**
I can't style product-summary-column with CSS overrides, only using :global, which will be deprecated soon. I also need to have two product-summary.shelf blocks styled differently

**Describe the solution you'd like**
- Add a class to product-summary.column and a `blockClass` prop.
- Add `blockClass` to product-summary.shelf

**Additional context**
![Screen Shot 2019-10-23 at 5 22 17 PM](https://user-images.githubusercontent.com/27775611/67431330-6fcdef00-f5ba-11e9-896f-55fd692f3cf3.png)
The `flex items-center` elements are the product-summary-column's

![Screen Shot 2019-10-23 at 5 36 37 PM](https://user-images.githubusercontent.com/27775611/67432006-cf78ca00-f5bb-11e9-93f4-e44032e6e5ff.png)
I added blockClass on product-summary.shelf, but it doesn't work
```
"product-summary.shelf#pwa": {
    "children": [ /* ... */ ],
    "props": {
      "blockClass": "pwa"
    }
  },
```

**Comment by iaronaraujo** [comment]
https://github.com/vtex-apps/product-summary/pull/207

**Comment by iaronaraujo** [comment]
This PR just got merged
