### ISSUE TITLE
Show Minicart container on Hover

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#134]
## Expected Behavior
When hover the minicart icon, the container of minicart informations will open. The component should have a prop to control the behaviour between click and mouseover.

Example: 
1. Go to https://www.americanas.com.br/
2. In the header of the homepage, if you mouseover the minicart icon, the container will open 

## Current Behavior
In the default component (https://github.com/vtex-apps/minicart) the opening behavior is on click and not on hover;

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/minicart/pull/187

**Comment by LucasCastroAcctGlobal** [comment]
Modal opens correctly but does not close when cursor exits minicart modal area (https://cl.ly/0df4b15bd094). I believe this should be the correct behavior (https://cl.ly/ea42148af504).

**Comment by LucasCastroAcctGlobal** [comment]
@denisebiscaro , was my feedback considered for review? https://github.com/vtex-apps/store-discussion/issues/134#issuecomment-557537816
