### ISSUE TITLE
SKUSelector sorting improvements

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#135]
## Component
https://github.com/vtex-apps/store-components/tree/master/react/components/SKUSelector

## Current Behavior
Today the variations (sku field) are being rendered out of admin order, starting with unavailable items for items available without respecting the order of sizes.

[![ProductDetailsLetter](https://i.ibb.co/DCHDXkd/err-Product-Details-Letter.jpg "ProductDetailsLetter")](https://i.ibb.co/DCHDXkd/err-Product-Details-Letter.jpg)

[![ProductDetailsNumber](https://i.ibb.co/d58k6fM/err-Product-Details-Number.jpg "ProductDetailsNumber")](https://i.ibb.co/d58k6fM/err-Product-Details-Number.jpg)

## Expected Behavior
We need the variations to be rendered from minus size to largest size.

I think the proper solution is to respect the Catalog order, but it seems that today that's not the logic: 
![image](https://user-images.githubusercontent.com/1374326/67528218-4f239900-f68f-11e9-8006-afc465f51f97.png)

## Examples
[![ProductDetailsNumberEdited](https://i.ibb.co/qB3xxn0/err-Product-Details-Number-Edited.jpg "Example product details")](https://i.ibb.co/qB3xxn0/err-Product-Details-Number-Edited.jpg "Example product details")

[![ProductDetailsLetterEdited](https://i.ibb.co/CKwj7Lw/err-Product-Details-Letter.jpg "Example product details")](https://i.ibb.co/CKwj7Lw/err-Product-Details-Letter.jpg "Example product details")

**Comment by klzns** [comment]
Fixed!
