### ISSUE TITLE
Create APP for Hotjar

### ISSUE THREAD

**Issue by abdulruiz** [vtex-apps/store-discussion#137]
**Is your feature request related to a problem? Please describe.**
There are several stores that, before implementing VTex, used the Hotjar plugin in their solution.

Hotjar is an online tool that offers information about visitor interactions on your pages.

The data generated by this tool reveal a lot about the user's behavior, such as the contents of most interest, if you “move” the page to the end, among other indicators that may be useful when diagraming the content or inserting a button CTA (Call To Action), for example.

**Describe the solution you'd like**
It is to create an app that inserts the following code in the <head> of the site in VTex IO:

`<script>
    (function(h,o,t,j,a,r){
        h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
        h._hjSettings={hjid:**<<CODE TO INSERT>>**,hjsv:6};
        a=o.getElementsByTagName('head')[0];
        r=o.createElement('script');r.async=1;
        r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
        a.appendChild(r);
    })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
</script>`

**Comment by fabiofeichtinger** [comment]
Hello @abdulruiz, I don't think this is necessary because GTM has this tag available to you use on your store.

![image](https://user-images.githubusercontent.com/1374326/67590035-52229600-f730-11e9-9dd8-087f4866871b.png)

**Comment by klzns** [comment]
@fabiofeichtinger it's a good option too.

Anyway, app created: 
https://github.com/vtex-apps/hotjar
