### ISSUE TITLE
Create back to top button

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#138]
**Is your feature request related to a problem? Please describe.**
We want a 'back to top' button that appears as a fixed element on the window, after the user scroll the page, and when the user clicks, it scroll you to the top of the page.

It is important to have control to determine where you want the button to appear, because it's mostly used on categories or search pages.

Article about this: 
https://www.nngroup.com/articles/back-to-top/

Examples:
https://www.mobly.com.br/decoracao/acessorios-decoracao/
![image](https://user-images.githubusercontent.com/1374326/67625680-7dcc7b80-f817-11e9-8679-3391a3c58d39.png)

https://www.americanas.com.br/categoria/relogios/relogios-de-pulso
![image](https://user-images.githubusercontent.com/1374326/67625689-a5234880-f817-11e9-9204-332079412b89.png)

**Comment by alextalha** [comment]
@klzns  @saviomuniz 
how is the status of this feature? or it is possible to do it in another way

**Comment by victorhmp** [comment]
Hi @fabiofeichtinger and @alextalha !
This feature is under review already, and was implemented by the community! Here is the   PR: https://github.com/vtex-apps/store-components/pull/708.
