### ISSUE TITLE
Insert tables into the storefront

### ISSUE THREAD

**Issue by k-ashok** [vtex-apps/store-discussion#14]
How to add 'tables' into the storefront using blocks.json? Which vtex block needs to be used to achieve that?

**Comment by klzns** [comment]
@k-ashok can you give a visual example of what you are trying to achieve?

**Comment by klzns** [comment]
We currently have two components that can render a table:

[`product-specificaton`](https://github.com/vtex-apps/store-components/tree/master/react/components/ProductSpecifications)

Or:

[`rich-text`](https://github.com/vtex-apps/rich-text)

Example of usage of the rich-text:
https://github.com/vtex-apps/rich-text/blob/master/react/__test__/index.test.tsx#L188-L198

**Comment by k-ashok** [comment]
> We currently have two components that can render a table:
> 
> [`product-specificaton`](https://github.com/vtex-apps/store-components/tree/master/react/components/ProductSpecifications) which renders the technical specifications of a product.
> 
> Or:
> 
> [`rich-text`](https://github.com/vtex-apps/rich-text)
> 
> Example of usage of the rich-text:
> https://github.com/vtex-apps/rich-text/blob/master/react/__test__/index.test.tsx#L188-L198

How to use the same kind of multiline markdown in the rich-text block of blocks.json file? Please provide an example.

**Comment by klzns** [comment]
Good to hear!
