### ISSUE TITLE
Measurement guide

### ISSUE THREAD

**Issue by laliel06** [vtex-apps/store-discussion#140]
**Is your feature request related to a problem? Please describe.**
I need to add a measurement guide on the product page. So that when the customer clicks on a link opens a modal with an image, video or a html table of measures. The measurement guide is a product field.

**Describe the solution you'd like**
We need a native Modal component, where we can pass as prop the ID of the product field, where it will fetch the content, a prop as text that we want to use as a link and the option to close.

**Additional context**
![4](https://user-images.githubusercontent.com/1666806/67985998-b392ab00-fbef-11e9-9657-60e9b0df5993.PNG)
![one](https://user-images.githubusercontent.com/1666806/67985928-8940ed80-fbef-11e9-9432-69b3ef8ae054.PNG)
![5](https://user-images.githubusercontent.com/1666806/67986037-c7d6a800-fbef-11e9-8eab-79c0705dce47.PNG)
![two](https://user-images.githubusercontent.com/1666806/67985935-8ba34780-fbef-11e9-8455-86d9e5799e38.PNG)
![3](https://user-images.githubusercontent.com/1666806/67985940-8e05a180-fbef-11e9-955c-f9ea41e98393.PNG)

**Comment by juliomoreira** [comment]
@klzns had proposed a `product-fit` interface so we can use it with custom components or other apps.

@klzns can you give us a status on this matter?

Thanks,

**Comment by denisebiscaro** [comment]
It can already be achieved with [Conditional Layout](https://github.com/vtex-apps/condition-layout) and [Modal Layout](https://github.com/vtex-apps/modal-layout)
