### ISSUE TITLE
Unable to use initiallyCollapsed in filter-navigator.v3

### ISSUE THREAD

**Issue by hiagolcm** [vtex-apps/store-discussion#141]
**Describe the bug**
Unable to use initiallyCollapsed in filter-navigator.v3

**To Reproduce**
Add filter-navigator and the initiallyCollapsed prop as the [documentation
](https://github.com/vtex-apps/search-result/#filter-navigator-block) suggests.

```
"filter-navigator.v3#collapsed": {
    "props": {
      "initiallyCollapsed": true,
    }
  }
```

**Expected behavior**
Facets should come initially collapsed on page reload.

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/search-result/pull/315
