### ISSUE TITLE
I want add vtex-apps/product-customizer to my store

### ISSUE THREAD

**Issue by narvaezcarlos** [vtex-apps/store-discussion#142]
i want add a custimizable product to my store, espeficly a card with a messages, see the https://github.com/vtex-apps/product-customizer and this is that i need ,but i dont know how to implemente this.

I installed vtex cli and connnected to my store: https://www.offcorss.com/, and executed the commands to install this app, first i created my workspace "customcard".

next

vtex use customcard
vtex install vtex.product-customizer

Then create de attachments in the catalog module in vtex panel

But this step: "Add the product-assembly-options block to your store's product page template." 

i dont know how to made

im new in vtex IO and not have idea for where begin

| Account | Workspace |
|offcorss|customcard|

**Comment by klzns** [comment]
Hi @narvaezcarlos, your store it's not using VTEX IO, it is using the standard VTEX CMS. In the standard VTEX CMS apps are not available.
