### ISSUE TITLE
Menu Accordion Bug

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#143]
**Describe the bug**
After the version 2.19.1 release of the menu component, the accordion effect does not work satisfactorily.

**To Reproduce**
1. Go to https://searchpages--miniprix.myvtex.com/
2. Go to the footer section
3. Then, try to open the internal submenu options.
4. Until 767px screen size, doesn't show the options (https://cl.ly/3e4041f4479e).
5. Between 768px and 1025.98px, show the options, however doesn't close the submenu options (https://cl.ly/cdf24437d9b3).

**Expected behavior**
Clicking the main button should show the internal submenus.

## Your Environment
* Windows 7
* Chrome 75

**Additional context**
We tested with version 2.19.0 and the behavior we need is working perfectly. The problem may be in commits
185c53b or 3b6e079 published on October 31, 2019

**Comment by lbebber** [comment]
I made a PR fixing this bug, except for the item 5.

The item 5 is being caused by this CSS customization:
<img width="262" alt="Screen Shot 2019-11-04 at 13 48 33" src="https://user-images.githubusercontent.com/5691711/68139988-d97ac100-ff09-11e9-8df1-c39dc6cdca26.png">
