### ISSUE TITLE
Include sku attribute "IsKit" and "kitItems"

### ISSUE THREAD

**Issue by gtoribio-webimpacto** [vtex-apps/store-discussion#144]
**Is your feature request related to a problem? Please describe.**
We need to differentiate the products that are kit from those that are not in search-result, we must be able to visualize this data in the graphql query since it is an attribute of sku

**Describe the solution you'd like**
Making the query to the api instead of with apollo we observe that this data exists like "isKit", but it is not collected within the props.
Could the "kitItems" information also arrive?

https://aguabendita.myvtex.com/api/catalog_system/pub/products/search/shop
https://aguabendita.myvtex.com/api/catalog_system/pvt/sku/stockkeepingunitbyid/829

**Comment by saviofelixmuniz** [comment]
You already have that on the Store GraphQL API, on the catalog resolver, see:

https://github.com/vtex-apps/store-graphql/blob/72dfadd944081633eaac5b75f634290864bb7cbd/node/resolvers/catalog/sku.ts#L22
