### ISSUE TITLE
Carousel autoplay strange effect

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#145]
## Expected Behavior
Carousel autoplay should scroll only one image at time, moving always forward.

## Current Behavior
When carousel's autoplay reach the last image, the next scroll moves backwards passing by all the others images until it reaches the first one.

This behavior doesn't happen when you actively click on next arrow when on the last image.

## Steps to Reproduce this bug
1. Go to https://www.spaziolusso.it.
2. Select the last image on the home carousel.
3. Wait for the autoplay scroll the last image.
4. Pay attention at the images being scrolled.

Video reproducing the bug: https://s.nimbusweb.me/share/3479525/7vnk8isoralbig9bo869

## Expected behavior example
https://www.saraiva.com.br/

Working example: https://s.nimbusweb.me/share/3495893/etbcyblh4n51e0mgfvd7

**Comment by Klynger** [comment]
Sorry about the big delay to answer you. This is not actually a bug, this is our desire behavior and now we don't recommend using this app (carousel), you should use the slider-layout, so if you still want this feature, create another issue to implement this in the slider-layout.
