### ISSUE TITLE
How to use saveV2?

### ISSUE THREAD

**Issue by laliel06** [vtex-apps/store-discussion#146]
**What are you trying to accomplish? Please describe.**  
Before using graphql-ide you need to pass a json like this:
```
{
    "save": {
        "to": "en-US",
        "messagesByProvider": [{
            "provider": "vtex.store-components@3.x",
            "messages": [{
                "id": "store/buy-button.add-to-cart",
                "content": "BUY NOW"
            }]
        }]
    }
}
```

However with the change to saveV2 I couldn't find what each key matches
```
{
    "save": {
        "to": "",
        "messages": [{
            srcLang: "",
            srcMessage:"" ,
            targetMessage: "",
            groupContext: "",
            context: ""
        }]
    }
}
```
In the documentation it is not clear what each line corresponds to.

**What have you tried so far?**  
I used it in many ways considering that groupContext and context are not required.
```
{
    "save": {
        "to": "en-US",
        "messages": [{
            srcLang: "en-US",
            srcMessage:"store/buy-button.add-to-cart",
            targetMessage: "BYU NOW"
        }]
    }
}
```

```
{
    "save": {
        "to": "vtex.store-components@3.x",
        "messages": [{
            srcLang: "en-US",
            srcMessage:"store/buy-button.add-to-cart" ,
            targetMessage: "BYU NOW"
        }]
    }
}
```

```
{
    "save": {
        "to": "vtex.store-components@3.x",
        "messages": [{
            srcLang: "en-US",
            srcMessage:"BYU NOW",
            targetMessage: "store/buy-button.add-to-cart"
        }]
    }
}
```

```
{
    "save": {
        "to": "",
        "messages": [{
            srcLang: "en-US",
            srcMessage:"BYU NOW",
            targetMessage: "store/buy-button.add-to-cart"
        }]
    }
}
```

None of these worked.
Remembering that the answer is true
```
{
  "data": {
    "saveV2": true
  }
}
```

**Additional info**  
![Captura](https://user-images.githubusercontent.com/1666806/68235420-d397e500-ffc8-11e9-8f84-a25b839d92f4.PNG)

| Account | Workspace |
redoxx | develop
https://develop--redoxx.myvtex.com/admin/graphql-ide

**Comment by klzns** [comment]
You can read a preview of the upcoming update in our docs here:
https://github.com/vtex-apps/io-documentation/blob/fix/messages-overwrite/docs/en/Recipes/store/overwriting-the-messages-app.md

**Comment by tlgimenes** [comment]
I think the doc was upgraded today in [this link](https://github.com/vtex-apps/io-documentation/pull/423)
