### ISSUE TITLE
Add option to display ProductID or EAN on ProductName

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#15]
Former issue: [#94](https://github.com/vtex-apps/product-details/issues/94)

**Describe the solution you'd like**
We would like to have the ability to choose between Product ID, EAN or Rerefence ID to be displayed below the product's name.

**Describe alternatives you've considered**
Currently there aren't many alternatives. We think extending the component functionality would be the best option.

**Comment by klzns** [comment]
In development. I expect to publish it today or tomorrow.

**Comment by klzns** [comment]
Done https://github.com/vtex-apps/product-identifier!
