### ISSUE TITLE
Free shipping bar on header top

### ISSUE THREAD

**Issue by pachecovit** [vtex-apps/store-discussion#152]
**Is your feature request related to a problem? Please describe.**
Today on CMS, we have used many benefits bars, in special a bar named 'Free Shipping', that is a simple progress bar with a message 'You win free shipping!' when our customer reached a minimum price value on your order.

**Describe the solution you'd like**
A component with a progress bar, total price order for sessions and messages.

**Additional context**
![Captura de Tela 2019-12-11 às 10 21 49](https://user-images.githubusercontent.com/6957485/70624909-12d8d780-1c00-11ea-9e89-cebf05e3f2a3.png)

**Comment by danielvsantos** [comment]
I have the same request from multiple clients. I would just recommend that this be built as a stand alone component as in my case we are using it inside of the minicart. 
![Screen Shot 2019-12-11 at 10 30 16](https://user-images.githubusercontent.com/47414363/70625582-74e60c80-1c01-11ea-9a07-7710817696ae.png)
![Screen Shot 2019-12-11 at 10 31 05](https://user-images.githubusercontent.com/47414363/70625583-74e60c80-1c01-11ea-98ea-ca8e2a55dcd8.png)

**Comment by denisebiscaro** [comment]
Hey @pachecovit.  This feature is not in our short term backlog, however you can implement it by using the sandbox app.
