### ISSUE TITLE
The names of the components are broken in the site editor

### ISSUE THREAD

**Issue by eazuviria** [vtex-apps/store-discussion#154]
**Describe the bug**
When you are in the site editor, all the "translates" (props names from the component) are "broken"

**To Reproduce**
1. Go to 'Site Editor'
2. See error

**Expected behavior**
See the prop's names correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/45159054/70739266-33368e00-1cf5-11ea-9d85-d81a6218dd36.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 - Version 78.0.3904.108

**Comment by klzns** [comment]
Fixed!
