### ISSUE TITLE
How do I change the position of the last child in a stack-layout

### ISSUE THREAD

**Issue by EmperorPidgeon** [vtex-apps/store-discussion#155]
I've made a stack-layout 

```json
 "stack-layout": {
    "children": ["info-card#button-left", "image#dias"],
    "props":{
      "blockClass":"stackMe"
    }
  }
```

but whenever I try to modify the last child position through css, it ignores me. I'm trying to move the image#dias child. 
I've tried .stackItem--stackMe{top:40} and tried to select the nth-child(odd) but did nothing.
How can I achieve this? 

Thanks!

**Comment by klzns** [comment]
You can add a blockClass to this image.

```json
"image#dias": {
  "props": {
    "blockClass": "dias"
  }
}
```

Then, target it with:

```css
/* vtex.store-components.css */
.imageElement--dias {
  top: 40;
}
```
