### ISSUE TITLE
Where to create a component

### ISSUE THREAD

**Issue by julianmendonca** [vtex-apps/store-discussion#156]
**What are you trying to accomplish? Please describe.**  

Where can i get a workspace to develop a component?
 Our clients that are migrating to VTEX IO, since the script that we were running through Google Tag Manager is now blocked.

Also when i do "render-guide" i get the following errors:
14:39:53.396 - warn: Account dressone is not whitelisted for builder "pages". You will **not** be able to publish this app. vtex.builder-hub@0.187.0-hkignore.0
14:39:53.398 - warn: Account dressone is not whitelisted for builder "react". You will **not** be able to publish this app. vtex.builder-hub@0.187.0-hkignore.0

Hope you can help me

**Comment by denisebiscaro** [comment]
Hi Julian! Not every account is allowed to develop custom components. Can you explain a little further what are you trying to build, why and for which account?

Thanks!

**Comment by julianmendonca** [comment]
Hi Denise, thank you for the reply.

We were implementing a script through gtm for a better search engine, so the question will be how to implement that script in all clients. Since we cant use gtm anymore, we should create a react component? and how do we implement that component to clients that have VTEX IO?

Thank you.

**Comment by afonso-praca** [comment]
Hello @julianmendonca, which search engine (vendor) do you want to integrate?
