### ISSUE TITLE
Problem with css

### ISSUE THREAD

**Issue by EmperorPidgeon** [vtex-apps/store-discussion#157]
![image](https://user-images.githubusercontent.com/9360514/71024822-88531500-20e4-11ea-9096-377cad307f92.png)
![image](https://user-images.githubusercontent.com/9360514/71024855-9c971200-20e4-11ea-98fc-8d85493702cd.png)
![image](https://user-images.githubusercontent.com/9360514/71024892-b173a580-20e4-11ea-9a69-da323e6a9e66.png)

Hello! I'm trying to modify the css of those elements in my custom css but I can't get them to change.

I've tried 
.link--linkuru{color:black}
.stackItem--stackMe{position:relative;top:40px}
.footerLayout{background:black}

and nothing seems to change. It's not an issue with the file because all the other elements are working as intended, but I just can't modify these ones. What am I doing wrong?

Thanks in advance

**Comment by klzns** [comment]
Do you have the apps `vtex.stack-layout`, `vtex.rich-text` and `vtex.store-footer` as a dependency of your app?

Do you have the the files `styles/css/vtex-stack-layout.css`, `styles/css/vtex-rich-text.css` and ``styles/css/vtex-store-footer.css`?

**Comment by EmperorPidgeon** [comment]
Nope, I've just got style.json and my vtex.store-components.css

What should I do?

**Comment by klzns** [comment]
The name of the file should be the name of the app your customising.

See this image from the docs:
![](https://user-images.githubusercontent.com/52087100/67318281-adab1480-f4e1-11e9-9c8f-c20b8f0647ec.png)

Docs: https://vtex.io/docs/recipes/style/using-css-handles-for-store-customization

That means that you should create a file like `styles/css/vtex.rich-text.css` and inside it add the CSS:
```css
.link--linkuru{color:black}
```

This will generate the following CSS selector `vtex-rich-text-0-x-link--linkuru`.

**Comment by EmperorPidgeon** [comment]
Thanks! That did the trick!

**Comment by alextalhaoriginal** [comment]
nice! helped mee too
