### ISSUE TITLE
Issue with flex-layout-row on menu

### ISSUE THREAD

**Issue by EmperorPidgeon** [vtex-apps/store-discussion#159]
Hello,I'm having an issue with my submenu.
Im trying to make 2 rows, one with 3 columns and an image, and then, below it a new row with 3 rich textes.
When I declare it, no matter how I do it, the new row places itself onto the right of my other column instead of below.

What am I doing wrong?

![image](https://user-images.githubusercontent.com/9360514/71176860-7f2f8880-2249-11ea-908b-294dd05038ac.png)
![image](https://user-images.githubusercontent.com/9360514/71176877-86ef2d00-2249-11ea-93c6-15c40bd47e79.png)
![image](https://user-images.githubusercontent.com/9360514/71176901-90789500-2249-11ea-864e-9b637fba0a22.png)
![image](https://user-images.githubusercontent.com/9360514/71176912-979fa300-2249-11ea-89ae-83cf58611aeb.png)

**Comment by lbebber** [comment]
@EmperorPidgeon Could you provide a workspace with this theme linked?

**Comment by EmperorPidgeon** [comment]
Itshaken--appliancetheme.myvtex.com

**Comment by lbebber** [comment]
Ah; I believe setting the prop `"orientation": "vertical"` to the `submenu` block should do the trick.

(and it looks like the documentation is lacking; sorry for that, will update it)
