### ISSUE TITLE
Add support for "Magnifier" zoom on ProductImages component

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#16]
Former issue: [#370](https://github.com/vtex-apps/store-components/issues/370)

**Describe the solution you'd like**
Would be nice to have other zoom types available like "magnifier" (see screenshot)
With the option for "adjacent" mode like in this [example](https://i-like-robots.github.io/EasyZoom/).
If we could choose the event listener to trigger the zoom like "hover" and "click" that would be very handy also.

**Describe alternatives you've considered**
Right now the only alternative is to extend the `product-images` interface entirely.

**Additional context**
![nVqEj3x](https://user-images.githubusercontent.com/1207017/60284697-9c128100-98e2-11e9-848f-85cd4fb118b7.png)

**Comment by fabiofeichtinger** [comment]
Up, this is a desirable feature of the customers @saviofelixmuniz
