### ISSUE TITLE
How to add a <select> ?

### ISSUE THREAD

**Issue by EmperorPidgeon** [vtex-apps/store-discussion#160]
Hello, I need to add an standard <select> element with 4 options inside my footer, but couldn't find the component to achieve this.

How should I do it?

**Comment by klzns** [comment]
Do you have an example? Like an image of what you're trying to achieve?

**Comment by EmperorPidgeon** [comment]
![image](https://user-images.githubusercontent.com/9360514/71197907-6509a080-2271-11ea-99f1-d16e5d7c03e0.png)
Something like this

**Comment by klzns** [comment]
What does it do?
