### ISSUE TITLE
Error when trying to delete v1.x and install v2.x of vtex.colossus-legacy-proxy

### ISSUE THREAD

**Issue by pradilla** [vtex-apps/store-discussion#161]
**What are you trying to accomplish? Please describe.**  

Follow instructions to start setting up store theme.
https://vtex.io/docs/getting-started/build-stores-with-vtex-io/3
This in particular this section: "The following apps need to be installed before downloading the Store There in your local files: vtex.store-sitemap, vtex.store, vtex.rewriter --force, vtex.admin-pages and vtex.colossus-legacy-proxy@2.x."

**What have you tried so far?**  

Success installing all except vtex.colossus-legacy-proxy

**Additional info**  
Add extra content here (code samples, screenshots,...)

Error screenshot:
![image](https://user-images.githubusercontent.com/31910293/71216836-b4f46180-2289-11ea-956a-c9e425354863.png)
Error Text:
17:16:39.480 - warn: The following app was not uninstalled: vtex.colossus-legacy-proxy
17:16:39.485 - error: 403: Forbidden. The request operation is not allowed

| Account | Workspace |
abbott--actxnow.myvtex.com

**Comment by pedrohenriqueoliveira** [comment]
Hello, @pradilla! Actually, you only need to install `vtex.colossus-legacy-proxy@2.x`. There's no need to uninstall the previous version. That previous version is part from a group of basic apps and only VTEX devs can uninstall it. That's why you're receiving that 403 error.

Run `vtex install vtex.colossus-legacy-proxy@2.x` and it should work fine.

**Comment by pradilla** [comment]
Hey @pedrohenriqueoliveira  nice to hear from you! Thanks for the quick response.  Still have the error bellow/

C:\Code\actxnow\abbott\store-theme
λ vtex install vtex.colossus-legacy-proxy@2.x
15:00:30.633 - error: Installation failed!
15:00:30.635 - error: Error simulating build of the route map
15:00:30.637 - warn: The following app was not installed: vtex.colossus-legacy-proxy@2.x

![image](https://user-images.githubusercontent.com/31910293/71288880-b8472600-2339-11ea-8b03-cb2bf160b46e.png)

**Comment by pradilla** [comment]
Hi @pedrohenriqueoliveira did you have a chance to look at this?  Do you think this has to do with other stuff not working on this account? *inventory and price not syncing correctly, hook creation with error among others.  Maybe if we fix this first I can start to understand where the rest of errors come from. Thanks in advance!

**Comment by pedrohenriqueoliveira** [comment]
@pradilla I'm try to simulate the error you've reported in order to find a solution. I'll be back soon.

**Comment by pedrohenriqueoliveira** [comment]
@pradilla I think i've found the problem. In `master`, you have the right edition installed, with all necessary apps to start developing a store.

![image](https://user-images.githubusercontent.com/19555647/71373523-356ed700-2596-11ea-9b04-b78f823c8ae1.png) 

For some reason, your workspace `abbott` is in a different edition. You need to reset the workspace `abbott` or create a new one. And you don't need to install the apps referred in the documentation, as they're already installed in master.

**Comment by pradilla** [comment]
Thanks @pedrohenriqueoliveira 👍  . somebody must have been able to update colossus in master.  Important thing is it works now! Thanks for looking into this!

**Comment by pradilla** [comment]
Hi @pedrohenriqueoliveira , me again. I created 2 sub-accounts actxnow2.myvtex.com and actxnow3.myvtex.com.  Havent done anything to those accounts yet in the CLI. As you know this colossus needs to be in v2.x to be able to use in IO storefront but cant really get this uninstalled or updated. Maybe this needs to be done by a @vtex.com user.  Can you please help me update this colossus app in these 2 accts?   actxnow2 and actxnow3. thanks!

![image](https://user-images.githubusercontent.com/31910293/71594299-62c30400-2b05-11ea-8c4f-d05ecae43d60.png)

**Comment by pedrohenriqueoliveira** [comment]
Hi, @pradilla! What happened is that subaccounts don't necessarily follow the same pattern of the main account in terms o VTEX IO setup. When you create a subaccount, our License Manager doesn't make any specific request to provide that subaccount in VTEX IO with the same configurations of the main account. So, they are created with the default edition. 

I've just installed the store edition in both subaccounts to solve the issue.

If you need anything, just call me.

Regards.

**Comment by pradilla** [comment]
yey!  works now!!!  Excellent, thanks @pedrohenriqueoliveira !! !

**Comment by pradilla** [comment]
Hey @pedrohenriqueoliveira !!  Me again! How are things going? I have the same colossus version problem for this account.  This is a live customer account, but we need to start evaluating testing a migration to IO so I created this workspace named andres that wont update. to v @2.x of colossus.  Do you think the problem is that the account doesnt have an LV # setup?  It is funny because some accounts allow this and some dont.

Error image:
http://prntscr.com/s035t5

Please help me install colossus on these workspaces.  

andres--bellapiel.myvtex.com
vtexio--bellapiel.myvtex.com
monica--bellapiel.myvtex.com
pedro--bellapiel.myvtex.com

Master workspace needs to be left as is because this is a live acct.

Thanks!!!
Andres

**Comment by pedrohenriqueoliveira** [comment]
Hi, @pradilla! I've just installed the store edition in the these workspaces, since it's the new way to setup accounts to VTEX IO. Just pay attention that these workspaces will work as demos, since they won't be updated automatically by our housekeeper. Master is still the reference for that account, that's why housekeeper can't update workspaces in other kind of setup.

**Comment by pradilla** [comment]
Excellent, thanks.
I imagine that setting store edition on master will then set the account as
being on IO? Or can it have store edition and still be live with CMS?

Regards
Andres
