### ISSUE TITLE
Allow custom breakpoints

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#162]
**Is your feature request related to a problem? Please describe.**
We need a workaround for #70 so I made two PRs:

- https://github.com/vtex-apps/device-detector/pull/10
- https://github.com/vtex-apps/carousel/pull/92 
  - I don't think that Site Editor support is necessary in this case but I've included it just in case;

**Describe the solution you'd like**
Ideally we would inherit the breakpoint definitions from the style builder but I think that in the meantime and for advances usage of `vtex.device-detector` it would be helpful to have an API that let's us define custom breakpoints when using `useDevice` hook.

**Comment by victorhmp** [comment]
Hey @juliomoreira !
Sorry about the delay, but do you still need those PRs to be merged?

**Comment by juliomoreira** [comment]
Hi @victorhmp,

No, thanks for the follow-up.
