### ISSUE TITLE
"Route is undefined" error when uninstalling app

### ISSUE THREAD

**Issue by hiagolcm** [vtex-apps/store-discussion#163]
**Describe the bug**

I have installed an app called `exitocol.search`. This apps declares the following route:

```json
{
  "store.search.v2": {
    "path": "/search/*path"
  }
}
```

In the `/admin`  console, I selected the desired interface. This `store.search.v2.exito` is declared in `store-theme`.

![image](https://user-images.githubusercontent.com/40380674/71484522-96dbb380-27eb-11ea-8786-b3f20c64f6b2.png)

Now I want to uninstall this app, but when I access the workspace with the app uninstalled I face this error:

![image](https://user-images.githubusercontent.com/40380674/71484516-8c211e80-27eb-11ea-9ce3-98a8a4909e12.png)

I have removed all the references from `exitocol.search` from `store-theme` blocks, but the error persists.

**To Reproduce**
[workspace](https://vtexsearch--exitocol.myvtex.com/)

**Comment by mcampagnaglamit** [comment]
How you fix it??? Can you tell us, I have the same issue

**Comment by regis-samurai** [comment]
I also have the same problem here
