### ISSUE TITLE
Toolbelt not updating when using yarn

### ISSUE THREAD

**Issue by pradilla** [vtex-apps/store-discussion#164]
happens on any account I have tried.

When notified about Toolbelt update and using the yarn command the process runs and notifies success but it really doesnt update.  I discovered that using the npm command it works ok. However yarn seems to be faster.

![image](https://user-images.githubusercontent.com/31910293/71594019-28a53280-2b04-11ea-9c93-a2a0b67b9a07.png)

**Comment by klzns** [comment]
This is a bug with your yarn installation and not related to Toolbelt itself. 

Please consider reinstalling yarn and that might solve the issue.
