### ISSUE TITLE
New override.css file is created when change manifest.json version.

### ISSUE THREAD

**Issue by riodajs** [vtex-apps/store-discussion#166]
**Describe the bug**
Wrong project folder is linked to my workspace with a diferent manifest.json version. Original is version 0.0.2, the wrong one is 3.21.1.

**To Reproduce**
1. Go to manifest.json file.
2. Change version property.
3. Link vtex store and save a css file.
4. new override.css build is created.

**Expected behavior**
If override.css file exist, delete it before create the new one.

**Screenshots**
[Imgur](https://i.imgur.com/RoWHDop.png)
[Imgur](https://i.imgur.com/QRk2YEI.png)

**Comment by klzns** [comment]
Since they have different major versions it is possible to have both apps running in your workspace. 

You should uninstall the v3.21.1 and then link the v0.0.2.
