### ISSUE TITLE
Fillters on search-resut for Collections

### ISSUE THREAD

**Issue by tomymehdi** [vtex-apps/store-discussion#167]
**Is your feature request related to a problem? Please describe.**
The search-result for collections does not show fillters

**Describe the solution you'd like**
Show fillters on the search-result for collections

**Describe alternatives you've considered**
There is no alternative

**Additional context**
It happends on every VTEX IO store. Is there another ticket requesting this feature?

**Comment by jgfidelis** [comment]
Please provide a workspace and a link to a search with this bug.

**Comment by tomymehdi** [comment]
Hello @jgfidelis!

We have this production: gama.myvtex.com
The URL of a Collection is the following: https://www.gamaitaly.com.ar/138?map=productClusterIds

As you will see on the URL only the categories are showed but not the fillters.
If you go to https://www.gamaitaly.com.ar/productos/d you can see all the fillters.

As I understand it looks like the collection is not fetching the categories attributes to fillter.

**Comment by campedelliluiz** [comment]
Hi, I have the same problem. Any news on this issue?

**Comment by denisebiscaro** [comment]
Hi! This is a known issue, and will be solved on the next search-results major as it is not a problem on the react component, but on the Search API that currently doesn't provide the available filters for a collections query.

It's already in progress. It will be released in april~may.
