### ISSUE TITLE
search-result desagregate products based on product attributes (Color)

### ISSUE THREAD

**Issue by tomymehdi** [vtex-apps/store-discussion#168]
**Is your feature request related to a problem? Please describe.**
The search-result today is showing a product but there is no configuration available to separate a product based on attributes that modify de image. For example de color. 
Today we are having a business requirement to open the products by color on the search-result to show a bigger and more colorful catalog.

**Describe the solution you'd like**
The solution should add a configuration on the search-result where it allow to set an id or string of the attribute with which you must open de products on the search result.

**Describe alternatives you've considered**
Couldn't think of and alternative

**Additional context**
Is there another VTEX IO store with this need?

**Comment by klzns** [comment]
Yes, there are other stores with this need. It's a feature that our Search and Catalog API lacks right now. We don't have a timeline to have this implemented.

**Comment by klzns** [comment]
Just for documentation purposes, clarifying the feature request.

The current behaviour of our search result:

1. Basic T-shirt

The expected behaviour:

1. Basic T-shirt White
2. Basic T-shirt Blue
3. Basic T-shirt Yellow

**Comment by tomymehdi** [comment]
Thank you @klzns. Let mi know if I can help you to push this feature.
