### ISSUE TITLE
Feature "from" and "to" for image or slides.

### ISSUE THREAD

**Issue by martincorebizglobal** [vtex-apps/store-discussion#170]
**What are you trying to accomplish? Please describe.**  
I need to know if there is functionality FROM and TO images or slides.
It will be so interest for special dates.

**What have you tried so far?**  
I try to find this feature in repositories and documentation

**Additional info**  
I dont have more info.

| Account | Workspace |
All workspace.

**Comment by klzns** [comment]
Can you give an example? I didn't get it.

**Comment by martincorebizglobal** [comment]
@klzns In the VTEX CMS we have this: https://monosnap.com/file/KpreBeOluKMJFOVY6OIr0pk7CFPiUN
In IO, we don't or not?

**Comment by klzns** [comment]
It is possible via site-editor:
![image](https://user-images.githubusercontent.com/284515/72620783-bcf20080-391e-11ea-931c-cfb94d75dd01.png)
