### ISSUE TITLE
One Signal App

### ISSUE THREAD

**Issue by martincorebizglobal** [vtex-apps/store-discussion#173]
**What are you trying to accomplish? 
I want to install a web push notification One Signal but I can't do it.
This app need to read two files in the root domain, but we can't do it.
https://documentation.onesignal.com/docs/web-push-typical-setup#section-span-class-step-step-6-span-upload-one-signal-sdk

Can you develop this app?

**What have you tried so far?**  
I try to install with GTM but is blocked by IO.

**Additional info**  

| Account | Workspace |
cat.cl

**Comment by klzns** [comment]
Hi, @martincorebizglobal we are in contact with the OneSignal team to build this solution.

I'll keep you posted on this.
