### ISSUE TITLE
RFC: New blocks for showing product price

### ISSUE THREAD

**Issue by klzns** [vtex-apps/store-discussion#175]
**Is your feature request related to a problem? Please describe.**

The product-price component defines the layout of the prices displayed on screen. This limits the possibilities of layout customisation. 

**Describe the solution you'd like**

This solution proposes the creation of 4 new blocks:
- product-list-price
- product-best-price
- product-price-savings
- product-installments

They would leverage our i18n framework to make it flexible. We would provide variables to the translation so it's possible for the user to render the text whatever way they want.

In the ICU Message Format [one can interpolate values](https://format-message.github.io/icu-message-format-for-translators/).

So a message could be:

Message | Rendered
---|---
"{totalValue} using {paymentName}" | "$100 using Visa"

The user might customise it, just changing the translation text to something else. Example:

Message | Rendered
---|---
"Pay with {paymentName} and only pay {totalValue}." | "Pay with Visa and only pay $100."

## product-list-price

Example of what it could render:
- "~From $300~"

Prop | type | description
---|---|---
`listPriceLabel` | TranslatableText | Text to be rendered

Variables provided to `listPriceLabel`:

Variable name | Example
---|---
`listPrice` | "$300"

## product-best-price

Example of what it could render:
- "To $100"
- "$90 paying with Boleto"

Prop | type | description
---|---|---
`teaserName` | string | Name of the teaser to be considered to calculate the price. This would make it possible to show the value paying with Boleto.
`paymentName` | string | Name of the payment. This will be passed as a variable to the `teaserPriceLabel`.
`teaserPriceLabel` | TranslatableText | Text to be rendered if the product has the specified teaser
`sellingPriceLabel` | TranslatableText | Text to be rendered if the product doesn't have the specified teaser.

Variables provided to `teaserPriceLabel`:

Variable name | Example
---|---
`paymentName` | "Boleto"
`teaserPrice` | "$ 90"
`hasListPrice` | `true` or `false`

Variables provided to `sellingPriceLabel`:

Variable name | Example
---|---
`sellingPrice` | "$ 100"
`hasListPrice` | `true` or `false`

## product-price-savings

Example of what it could render:
- "Save $200"
- "10% discount"

Prop | type | description
---|---|---
`previousPrice` | `listPrice` or `sellingPrice` | Which variable it will use as the previous price
`newPrice` |  `sellingPrice` or `teaserPrice` | Which variabe it will use as the new price
`teaserName` | string | Necessary if `teaserPrice` is used
`priceSavingsLabel` | TranslatableText | Text to be rendered

Variables provided to `priceSavingsLabel`:

Variable name | Example
---|---
`previousPrice` | "$300"
`newPrice` | "$100"
`savingsValue` | "$200"
`savingsPercentage` | "10%"

## product-installments

Example of what it could render:
-  "6x of $10 interest-free"
- "Pay $110. 11x of $11 (3.87% m.)" 

Prop | type | description
---|---|---
`installments` | `max` or `max-no-interest` | `max` will render the max installments. `max-no-interest` will render the max installments with no interest.
`installmentsLabel` | TranslatableText | Text to be rendered

Variables provided to `installmentsLabel`:

Variable name | Example
---|---
`installments` | 10
`totalValue` | "$100"
`installmentValue` | "$10"
`interestRate` | "3.87%"

**Describe alternatives you've considered**

**Additional context**

**Comment by klzns** [comment]
Some examples:

**Comment by klzns** [comment]
### Americanas shelf
![image](https://user-images.githubusercontent.com/284515/72668987-28190100-3a0b-11ea-98cc-c1bae00103eb.png)

**product-list-price**
- `listPriceLabel`: "${listPriceValue}"

**product-best-price**
- `teaserName`: "Desconto Prime"
- `paymentName`: "Americanas Prime"
- `teaserPriceLabel`: "{teaserPriceValue} {paymentName}"

**product-installments**
- `installments`: `max-no-interest`
- `installmentsLabel`: "{installments}x de {installmentValue} sem juros"

**Comment by klzns** [comment]
### Americans PDP

![image](https://user-images.githubusercontent.com/284515/72669059-171cbf80-3a0c-11ea-8729-dc42f35da126.png)


**product-best-price**
- `sellingPriceLabel `: "${sellingPriceValue}"

**product-price-savings**
- `previousPrice`: `sellingPrice`
- `newPrice`: `teaserPrice`
- `teaserName`: "Desconto Prime"
- `priceSavingsLabel`: "{savingsPercentage}"

**product-best-price**
- `teaserName`: "Desconto Prime"
- `paymentName`: "Americanas Prime"
- `teaserPriceLabel`: "{teaserPriceValue} {paymentName}"

**product-installments**
- `installments`: `max-no-interest`
- `installmentsLabel`: "em até {installments}x sem juros no cartão de crédito com Ame" (we don't have cashback)

**Comment by klzns** [comment]
### Consul PDP

![image](https://user-images.githubusercontent.com/284515/72669214-dcb42200-3a0d-11ea-99e2-6e512dabae54.png)


**product-list-price**
- `listPriceLabel `: "${listPriceValue}"

**product-best-price**
- `teaserName`: "Desconto Boleto"
- `paymentName`: "Boleto"
- `teaserPriceLabel`: "{teaserPriceValue}"
- `sellingPriceLabel`: "{sellingPriceValue}"

**product-best-price**
- `sellingPriceLabel`: "1x no cartão de crédito por {sellingPriceValue}"

**product-installments**
- `installments`: `max-no-interest`
- `installmentsLabel`: "Em até {installments}x de {installmentValue} sem juros"

**Comment by klzns** [comment]
### Brastemp

![image](https://user-images.githubusercontent.com/284515/72669272-6a900d00-3a0e-11ea-8759-ba5f688b778c.png)

**product-list-price**
- `listPriceLabel `: "De: ${listPriceValue}"

**product-best-price**
- `sellingPriceLabel`: "{hasListPrice, select, true {Por:} false {} other {}}{sellingPriceValue}"

**product-installments**
- `installments`: `max-no-interest`
- `installmentsLabel`: "{installments}x sem juros de {installmentValue}"

**product-price-savings**
- `previousPrice`: `listPrice`
- `newPrice`: `sellingPrice`
- `priceSavingsLabel`: "{savingsPercentage} OFF"

**product-best-price**
- `teaserName`: "Desconto Cartão 1x"
- `paymentName`: "cartão de crédito"
- `teaserPriceLabel`: "1x no {paymentName} (5% OFF): Por {teaserPriceValue}"
- `sellingPriceLabel`: ""

**Comment by klzns** [comment]
### Zeedog
![image](https://user-images.githubusercontent.com/284515/72669341-4aad1900-3a0f-11ea-8590-5663eb2077e3.png)

**product-best-price**
- `sellingPriceLabel`: "{sellingPriceValue}"

**product-installments**
- `installments`: `max-no-interest`
- `installmentsLabel`: "(Até {installments}x de {installmentValue} sem juros"

**Comment by klzns** [comment]
### C&A

![image](https://user-images.githubusercontent.com/284515/72669380-d4f57d00-3a0f-11ea-9fb7-758ecab0853e.png)

**product-list-price**
- `listPriceLabel `: "de: ${listPriceValue}"

**product-installments**
- `installments`: `max`
- `installmentsLabel`: "em até {installments}x de {installmentValue} no cartão"

**product-best-price**
- `sellingPriceLabel`: "ou {sellingPriceValue} à vista"

**product-price-savings**
- `previousPrice`: `listPrice`
- `newPrice`: `sellingPrice`
- `priceSavingsLabel`: "economize: {savingsValue}"

**Comment by klzns** [comment]
### Amazon BR

![image](https://user-images.githubusercontent.com/284515/72669451-84325400-3a10-11ea-9901-41ddb669d44d.png)

**product-list-price**
- `listPriceLabel `: "Preço sugerido: ${listPriceValue}"

**product-best-price**
- `teaserName`: "Oferta de Bicicletas"
- `paymentName`: ""
- `teaserPriceLabel`: "Oferta do dia: {teaserPriceValue}"
- `sellingPriceLabel`: "{sellingPrice}"

**product-price-savings**
- `previousPrice`: `listPrice`
- `newPrice`: `teaserPrice`
- `priceSavingsLabel`: "Você economiza: {savingsValue} ({savingsPercentage})"

**product-installments**
- `installments`: `max-no-interest`
- `installmentsLabel`: "Em até {installments}x sem juros"

**Comment by Klynger** [comment]
The example of amazon seems to be something like
```html
<span class="savings">
  Você economiza: <span class="savings-value">R$ 139,10 (32%)</span>
</span>
```

But in the API that you sugest you're just passing `priceSavingsLabel` that I imagine is just passed to the intl and it will return only a string that you render in a single `span` tag, so how can I change the color of just the price?

**Comment by iaronaraujo** [comment]
1. Will the list price always be strikethrough? Should that be a prop?
2. If I understood correctly `teaserPriceLabel` and `sellingPriceLabel` will never be used together. Shouldn't we have one prop `priceLabel` and then another prop `labelType` which is an enum that could be `TEASER` or `SELLING`? Or something similar?
3. `teaserPrice` and `sellingPrice` on `TranslatableText` should be only `price`, especially because this type is used in two different cases.
4. Types of `previousPrice` and `newPrice` on `product-price-savings` are weird. It should be a string/number. I understood the intention of why they are how they are right now, but that information should be on the description, not on the type.
5. Improve the description of product-price-savings props.
6. Do we really need `savingsValue` and `savingsPercentage` on `priceSavingsLabel`? Can't we generate those automatically? _Shouldn't we_?
7. Remove "Describe alternatives you've considered" and "Additional context" on the first post.
8. On Americanas example, isn't the first component the `list-price`?
9. Still on the Americanas example, how will we deal with the `a` icon?
10. On consul example, I think the second best-price also has a teaser.

Also, it would be nice to know which props are optional and which aren't.

**Comment by klzns** [comment]
@Klynger 
I created this codesandbox to give an example of how it would work and how would be possible to wrap elements to add custom CSS Handles:
https://codesandbox.io/s/example-of-best-price-using-markers-and-css-handles-jedxf

**Comment by klzns** [comment]
@iaronaraujo 
> 1. Will the list price always be strikethrough? Should that be a prop?

That's could be the default CSS, but can be changed with CSS customisations.

> 2. If I understood correctly teaserPriceLabel and sellingPriceLabel will never be used together. Shouldn't we have one prop priceLabel and then another prop labelType which is an enum that could be TEASER or SELLING? Or something similar?

No. The sellingPriceLabel will be rendered if the product doesn't have the specified teaser. That's not an option of the user, the component decides that based on the conditions of the product.

> 3. teaserPrice and sellingPrice on TranslatableText should be only price, especially because this type is used in two different cases.

I prefer going for a more explicit approach here.

> 4. Types of previousPrice and newPrice on product-price-savings are weird. It should be a string/number. I understood the intention of why they are how they are right now, but that information should be on the description, not on the type.

Yes, that was just to save time, but basically it's an enum value with `sellingPrice` and `teaserPrice` being the possible values.

> 5. Improve the description of product-price-savings props.

OK

> 6. Do we really need savingsValue and savingsPercentage on priceSavingsLabel? Can't we generate those automatically? Shouldn't we?

These things are not props they are computed values passed to the translation. So yes, we are generating them automatically. The confusion might be because they share the same name of the props.

> 7. Remove "Describe alternatives you've considered" and "Additional context" on the first post.

OK

> 8. On Americanas example, isn't the first component the list-price?

No, Americanas case it's a bit different, because that's the price you pay if you don't pay using Americanas Prime, so it's the sellingPrice.

> 9. Still on the Americanas example, how will we deal with the a icon?

CSS

> 10. On consul example, I think the second best-price also has a teaser.

Yes, it could be.

> Also, it would be nice to know which props are optional and which aren't.

I'll improve on that.

**Comment by klzns** [comment]
Just before I forgot, some notes that I took:

option best-price to fallback to render null
teaser be an array

**Comment by denisebiscaro** [comment]
@klzns Just got a new necessity related to Product Price.

Some stores need to show the price in the format of "From $9.99", meaning that the product has several SKUs  (or sellers) with different prices. This "From $9.99" relates to  the lowest skus' possible price.

**Comment by denisebiscaro** [comment]
Released 🚀 - https://github.com/vtex-apps/product-price

**Comment by mascDriver** [comment]
the block: "product-best-price" was not added at the launch of "product-price"? it's a great method with the "teaserName". This would allow showing the payment amount with Boleto. as in the description itself says
