### ISSUE TITLE
Use Login component without open a modal.

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#177]
## Expected Behavior
We intent to not use the login modal creating a link to redirect user at '/account' meanwhile we stay showing the user name of the logged user on the login component.

## Current Behavior
The login component doesn't have a props to hide the modal and create a link to redirect the user at /account page.

## Describe the solution you'd like
Add a prop to allow using a link to 'account' instead of use the modal.

## Links
Expected Behavior Example: https://i.imgur.com/QFTxHIN.png ,  https://nimb.ws/itomDe
App on github: https://github.com/vtex-apps/login

**Comment by rafarubim** [comment]
Thank you for the feature request! We are addressing it, and it should be available soon 😁

**Comment by rafarubim** [comment]
The feature was implemented in https://github.com/vtex-apps/login/pull/173 and is up and running!
Thank you again for helping improve our platform!
