### ISSUE TITLE
Add an Overlay Prop to Minicart Component

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#178]
## **Is your feature request related to a problem? Please describe.**
Currently we don't have a prop to define if we want to have overlay on desktop when minicart is opened. Nowadays it's present by default on mobile.

## **Describe the solution you'd like**
Adding a prop to enable or disable (by default) the minicart overlay when opened.

## **Additional context**
Screenshot showing the expected visual behavior:
https://nimb.ws/8kOTJS
App on Github: https://github.com/vtex-apps/minicart

**Comment by Klynger** [comment]
Just launched this feature, but we can't make default because this would be a breaking change. Just use the prop `backdropMode`.

**Comment by klzns** [comment]
The app was deprecated. I'll release it later.

**Comment by Klynger** [comment]
Fixes done!
