### ISSUE TITLE
Add "initiallyCollapsed" prop to filter-navigator.v3.

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#179]
## Expected Behavior
We should be able to use the "initiallyCollapsed" prop on the filter-navigator.v3 block the same way that we have on filter-navigator.v2. This prop is used to define if the filters should be presented as opened or closed when the page is loaded.

## Current Behavior
The prop isn't avaliable at the component code:
Filter-navigator.v3 code: https://github.com/vtex-apps/search-result/blob/master/react/FilterNavigatorFlexible.js

## Possible solution
Add the prop at the component code the same way it exists on Filter-navigator.v2.
Filter-navigator.v2 prop: https://github.com/vtex-apps/search-result/blob/master/react/FilterNavigator.js#L127

## Links
Repo: https://github.com/vtex-apps/search-result

**Comment by riodajs** [comment]
I need that prop too, please!
![image](https://user-images.githubusercontent.com/27719363/73093679-cdc1e980-3ebd-11ea-9794-b786ef8751f5.png)

**Comment by klzns** [comment]
Thanks @ygorneves10 for the contribution:
https://github.com/vtex-apps/search-result/pull/315
