### ISSUE TITLE
Add support for customizing the button label in ShowMoreLoaderResult

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#18]
Former issue: [#129](https://github.com/vtex-apps/search-result/issues/129)

**Describe the solution you'd like**
We would like to have the ability to dynamically set the ShowMoreLoaderResult button label possibly giving the user feedback of how many items are showing and how many items are left.

**Describe alternatives you've considered**
Right now the only option is to set the label in translation files but it doesn't seems to support dynamic content.

**Additional context**
![9kbCob3](https://user-images.githubusercontent.com/1207017/60288560-d5e78580-98ea-11e9-943a-27d0a726524c.png)

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/search-result/pull/222
