### ISSUE TITLE
Block classes below filterAccordionItemBox addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#181]
## **Is your feature request related to a problem? Please describe.**
In search component, divs hierarchically below filterAccordionItemBox are missing class definition.
## **Describe the solution you'd like**
It’s desired, in order to allow CSS customization, an addition of className into all divs hierarchically below filterAccordionItemBox 
## **Additional context**
That's a code screenshot providing an overview of all divs where Classname is requested, providing CSS manipulation possibilities.
https://prnt.sc/qo0v18

**Comment by denisebiscaro** [comment]
![image](https://user-images.githubusercontent.com/12139385/73300223-6b375900-41ef-11ea-9fe2-9da58031f236.png)
