### ISSUE TITLE
Block classes below filterPopupTitle addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#182]
## **Is your feature request related to a problem? Please describe.**
In search component, divs hierarchically below filterPopupTitle are missing class definition. 
## **Describe the solution you'd like**
It’s desired, in order to allow CSS customization, an addition of className into all divs hierarchically below filterPopup
## **Additional context**
That's a code screenshot providing an overview of all divs where Classname is requested, providing CSS manipulation possibilities.
https://prnt.sc/qreco6

**Comment by denisebiscaro** [comment]
![image](https://user-images.githubusercontent.com/12139385/73299910-d7fe2380-41ee-11ea-9686-457ade3cb48c.png)

**Comment by denisebiscaro** [comment]
![image](https://user-images.githubusercontent.com/12139385/73300153-4b079a00-41ef-11ea-90c6-7fa535683ff0.png)
