### ISSUE TITLE
Block classes below filterAvailable addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#184]
## Is your feature request related to a problem? Please describe.
In search component, div hierarchically below filterAvailable is missing class definition.
## Describe the solution you'd like
It's desired,  in order to allow css customization, an addition of className in the div hierarchically below the AccordionItemBox filter 
## Additional context
That's a code screenshot providing an overview of div where Classname is requested, providing CSS manipulation possibilities.
https://prnt.sc/qojjga

**Comment by denisebiscaro** [comment]
![image](https://user-images.githubusercontent.com/12139385/73300093-2ca19e80-41ef-11ea-8c4b-89d2b4617755.png)
