### ISSUE TITLE
Login Component - Show password active class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#185]
## Is your feature request related to a problem? Please describe.
 In Login Component we have no way of differentiating when the button is type "text" or "password"
## Describe the solution you'd like
Insert a class to differentiate element behavior, for when the element is active and another for when it is disabled. Thus, it will be possible to insert a new icon for each state.

## Additional context
That's a code screenshot providing an overview of div where Classname is requested, providing CSS manipulation possibilities: http://prntscr.com/quocux
And here is a screenshot of how the element is presented in the front-end : https://prnt.sc/qwtb77

**Comment by rafarubim** [comment]
Hi @luizgpriolli, thanks for opening the issue. If I understand you correctly, the class is missing in the Eye Icon container rather then the Input container, right? I'll address this issue and let you know when it's done here.

**Comment by klzns** [comment]
We will add this CSS Handle, but to unlock projects we are allowing the usage of any CSS selector on login <= 1.x.
