### ISSUE TITLE
Login Component elements classes addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#186]
## Is your feature request related to a problem? Please describe.
Some elements inside the Login component only have tachyons classes thus preventing any 
CSS customization.
1- At login it is not possible to change the link format "Forgot my password"
2- It is not possible to change the text color on the Register button
3- You cannot change the width of the Quick Access field

## Describe the solution you'd like
1- Insert a class into pertinent element in order to enable formatting/editing 
2- Insert a class into pertinent element in order to enable formatting/editing 
3- Insert a class into div that is encapsulating mentioned elements

## Additional context
That's a code screenshot providing an overview of div where Classname is requested, providing CSS manipulation possibilities.
1- http://prntscr.com/quo7gz
2- http://prntscr.com/quo8s2
3- http://prntscr.com/quoa6z

Component link: https://github.com/vtex-apps/login

**Comment by rafarubim** [comment]
Thank you for the issue! I'll address it in the next days and update you here when it's done.

**Comment by klzns** [comment]
We will add this CSS Handle, but to unlock projects we are allowing the usage of any CSS selector on login <= 1.x.
