### ISSUE TITLE
Slider-layout - Active dot class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#187]
## Expected Behavior
Add a class to the dots in order to indicate the active state and be possible styling it.

## Current Behavior
There is a change only on "isActive" between the classes 'bg-muted-3' to 'bg-emphasis'.

## Element Print
https://prnt.sc/qk25hk

Component link: https://github.com/vtex-apps/slider-layout

**Comment by klzns** [comment]
Implemented! Thanks for the suggestion
