### ISSUE TITLE
How to overwrite the `contentSchema`

### ISSUE THREAD

**Issue by hiagolcm** [vtex-apps/store-discussion#188]
**What are you trying to accomplish? Please describe.**  
I'm implementing a component that extends the `shelf`. It is called `shelf.recommendation`. I want to overwrite the `shelf` contentSchema with a new schema.

**What have you tried so far?**  
I have created a new `contentSchema.json` in the `store` folder.

```
{
  "definitions": {
    "recommendationShelf": {
      "title": "admin/editor.shelf.recommendation.title",
      "description": "admin/editor.shelf.recommendation.description",
      "type": "object",
      "properties": {
        "strategy": {
          "title": "admin/editor.shelf.recommendation.strategy.description",
          "description": "admin/editor.shelf.recommendation.strategy.description",
          "type": "string"
        }
      }
    }
  }
}
```

And I have added it to the `interface.json`:

```
{
  "shelf.recommendation": {
    "required": [
      "product-summary"
    ],
    "component": "RecommendationShelf",
    "preview": {
      "type": "grid",
      "height": 550
    },
    "content": {
      "$ref": "#/definitions/recommendationShelf"
    }
  }
}
```
Unfortunately, the schema was not overwritten. Site Editor keeps showing the `shelf` schema. Am I doing something wrong or VTEXIO doesn't support this feature?

**Additional info**  
When the component doesn't extend the `shelf`, it works fine, so I'm assuming the problem is the Inheritance.

**Comment by klzns** [comment]
There's no way to achieve that. The possible solution is to create a new interface instead.
