### ISSUE TITLE
Multiple specification badges support

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#189]
## Expected Behavior
Add a method map() to the badge.specifications array in order to handle
  multiple badges.
## Current Behavior
The function currently brings back only the first position of the array, not showing
## Component Link
https://github.com/vtex-apps/product-specification-badges/blob/master/react/components/BaseSpecificationBadges.tsx
## Prints
https://prnt.sc/qy0xb3

**Comment by klzns** [comment]
Do you mind providing an example of a product that hits that scenario?

**Comment by luizgpriolli** [comment]
Sure

![image](https://user-images.githubusercontent.com/45877287/74053621-f916ff00-49ba-11ea-8369-205b9bbc227c.png)

https://carrefourbr.myvtex.com/
