### ISSUE TITLE
Error "updateDocument" graphql mutation

### ISSUE THREAD

**Issue by Mecrano** [vtex-apps/store-discussion#190]
Documentation error "updateDocument" graphql mutation

## Expected Behavior
Be able to update fields of a document of the masterdata given the id of the document

## Current Behavior
At this time it is not possible to indicate which document I want to edit, however if the code is analyzed, it is ready to receive the document id

## Possible Solution
I think the documentation is out of date or has an error, and that the validator graphql must be updated

## Context
It is not possible to edit the fields of a document

## Images:
1. Request according to documentation:
![image](https://user-images.githubusercontent.com/26680887/73947391-59c41000-48c5-11ea-9307-1e80f28e8683.png)

2. Code in this repository (/vtex-apps/store-graphql/blob/master/node/clients/masterdata.ts):
![image](https://user-images.githubusercontent.com/26680887/73947481-82e4a080-48c5-11ea-9dc8-eac9cc983471.png)

3. Request according to code:
![image](https://user-images.githubusercontent.com/26680887/73947644-cc34f000-48c5-11ea-9239-23b3f97eac2e.png)

**Comment by klzns** [comment]
Thanks for the issue! We will take a look on it.

**Comment by steckhelena** [comment]
Hello, I investigated the issue and to pass the ID of the document you want to update, you need to do it this way:
```gql
mutation {
  updateDocument(
    acronym: "Test"
      document: {
        fields: [
          { key: "fieldName1", value: "fieldName1NewValue" }
          { key: "fieldName2", value: "fieldName2NewValue" }
          { key: "id", value: "id-here" }
        ]
      }
    ) {
      id
      href
      documentId
    }
}
```

**Comment by Mecrano** [comment]
Hi Helena, I tried to do the mutation as in your example and everything is fine, thanks:

![image](https://user-images.githubusercontent.com/26680887/74149342-86ce3680-4bd5-11ea-8737-57f912a95dcc.png)
