### ISSUE TITLE
Minicart v2 is not showing when you pass props

### ISSUE THREAD

**Issue by castilloedw** [vtex-apps/store-discussion#191]
Hello everyone, There's an issue when you pass props to the minicart component, if you don't pass anything it works!

Example, my header is like this:

`header-row#top: {
   "children": [
      ...
      "minicart.v2"
      ...
    ]
}`

Everything works! until now, but when you pass props, the minicart doesn't work! example:

`minicart.v2: {
   "props": {
      "variation": "popup"
    }
}`

I expect you can help me, thanks!

**Comment by klzns** [comment]
That's the expected behaviour. 

When you define the block `minicart.v2` on your theme, you are overriding the [default block implementation](https://github.com/vtex-apps/minicart#advanced-configuration) of the app `vtex.minicart`. 

You can add the minicart children blocks like this:

```diff
   "minicart.v2": {
     "props": {
       "variation": "popup"
     },
+    "children": ["minicart-base-content"]
   }
```

**Comment by castilloedw** [comment]
It works! Thanks for answering! @klzns
