### ISSUE TITLE
Slider-layout centermode prop request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#193]
## Expected Behavior
Add a prop that makes the slider centered, showing a small part of the next and previows slides in borders
## Current Behavior 
The current behavior shows only one slide, in center of the screen. The expected behavior can't be reproduced by css
## Component Link
https://github.com/vtex-apps/slider-layout
## Prints
https://nimb.ws/lfAtWd
https://nimb.ws/qDhU8z
## Example
There is a react slick mode, with the expected behavior
https://github.com/akiran/react-slick

**Comment by victorhmp** [comment]
Hi @luizgpriolli !
Thanks for the feature request! We've already thought about implementing this feature and plan on doing so in the future, we just haven't settled in some technical aspects yet. 
I can't give you a timeline for now, but this will surely be added to the `slider-layout`.
