### ISSUE TITLE
My account component class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#194]
## Is your feature request related to a problem? Please describe.
In ‘My-Account’ component, there's no class at disposal inside this div, necessary for developments. In example, usage of ‘vtex-account__page-body’ class is not possible.
## Describe the solution you'd like
Insert a class into ‘My-Account’ component in order to make possible customization and CSS properties changes without use any deprecated selector.
## Additional context
That's a code screenshot providing an overview of div where Classname is requested
https://ibb.co/MVHQpD5

**Comment by klzns** [comment]
My Account <= 1.x is now free to use any CSS Selector
