### ISSUE TITLE
My-Account component disabled fields class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#195]
## Is your feature request related to a problem? Please describe.
In 'My-Account' component, there's no class for disabled 'profileSummary' fields.
## Describe the solution you'd like
Add a class in order to make possible CSS properties manipulation and developments without the usage of any deprecated selector.
## Additional context
That's a code screenshot providing an overview of mentioned div where Classname is requested
https://ibb.co/pJv4whf

**Comment by klzns** [comment]
My Account <= 1.x is now free to use any CSS Selector.
