### ISSUE TITLE
Set product page content referencing the product category in site-editor

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#196]
## **Is your feature request related to a problem? Please describe.**
Currently in site-editor there is no way to set a content in the product page to be visible by the product's category. The only options at this moment in IO is to set it to "this template" or "this product" even though it was possible in the legacy system by using content placeholders.

## **Describe the solution you'd like**
Add an option in site-editor to set content to be visible by referencing the product category.

## **Additional context**
Site-editor Product page: https://nimb.ws/ofZyFD
Site-editor Category page with desired functionality: https://nimb.ws/bC5L0l

**Comment by felippenardi** [comment]
Thanks for the feature suggestion, Luiz. It is not currently planned, but I'll bring this internally.

**Comment by denisebiscaro** [comment]
Solved with Conditional Layout block 🚀  - https://github.com/vtex-apps/condition-layout
