### ISSUE TITLE
Cannot list workspace using cli: cannot perform action GET on resource

### ISSUE THREAD

**Issue by vladimireduardo** [vtex-apps/store-discussion#198]
**Description**
When attempt to list workspace using vtex list  an error occurs:

13:03:12.031 - error: API: 403 Forbidden
13:03:12.033 - error: Source: https://infra.io.vtex.com/apps/v0/**<store_name>**/master/apps
13:03:12.033 - error: Method: get
13:03:12.033 - error: Message: Role user:42707b80-b15f-4aff-ab78-2f1a58891a4b in **<store_name>**/ cannot perform action GET on resource vrn:apps:aws-us-east-1:**<store_name>**:master:/apps

**To Reproduce**
1. Open a terminal and enter `vtex login`
2. Type `vtex ls`

 - OS: Mac OS Catalina 10.5.4
 - VTEX Cli Version: 2.87.3
- Yarn version: 1.19.2
- npm version: 6.13.1

**Comment by klzns** [comment]
Does that still happen?

**Comment by riodajs** [comment]
Today I have the same problem, change the vendor of the manifest.json with your store name was the solution

**Comment by AbraaoMorais** [comment]
I had a similar problem, I realized that I was executing the command 1 directory level above where the repository files were.
