### ISSUE TITLE
Drawer component does not close when clicking in a link

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#199]
## **Describe the bug**
In the mobile menu, when pages related to the same hierarchy are exchanged in the category tree, the drawer component does not close.

## **To Reproduce**
1. Using a mobile device (or mobile mode);
2.  Go to www.tackoftheday.com ;
3. Select the mobile menu icon (https://flic.kr/p/2isj8it);
4. Select the 'Rider' option (https://flic.kr/p/2ismKKf);
5. Select the 'View all products in Rider' (https://flic.kr/p/2ismKJo);
6. We see that the drawer close and the page change (https://flic.kr/p/2isnTKc);
7. Now, select the 'Horse' option (https://flic.kr/p/2ismKHg);
8. And select the 'View all products in Horse' (https://flic.kr/p/2isj8gp);
9. We see that the page URL change, however the drawer didn't close (https://flic.kr/p/2ismKH1)

## **Expected behavior**
The expected behavior is to close the drawer component once the url changes to other pages of department, category or subcategory, regardless of the hierarchy of the category tree.

## **Screenshots**
A recording showing the problem: https://cl.ly/abd6050a564d
**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Google Chrome
 - Version: 79.0.3945.130

## **Additional context**
I carried out this verification in my current production store (tackoftheday.com) and in some other stores in the process of being implemented, such as Miniprix (miniprix.myvtex.com). I believe that this issue is important since closing of the drawer component is necessary to properly shows to the user that the page content has changed.

**Comment by klzns** [comment]
Thanks for being so detailed in your bug report 🙏 

We'll take a look on this

**Comment by klzns** [comment]
Fixed!
