### ISSUE TITLE
Home is missing

### ISSUE THREAD

**Issue by darwin1423** [vtex-apps/store-discussion#201]
Realicé una instalación desde cero de la tienda, sin embargo el home está perdido y no lo muestra, hace dos día realicé lo mismo y todo estaba funcionando correctamente. Siguiendo cuidadosamente los siguientes pasos:

vtex login my-account
vtex use workspace-name
cd store-theme
vtex link

![Captura de Pantalla 2020-02-17 a la(s) 6 32 14 p  m](https://user-images.githubusercontent.com/9994716/74694028-ffc02600-51b3-11ea-8e22-63296607317d.png)

**Comment by klzns** [comment]
That might be due to a account misconfiguration. You need to install some apps for an IO store to work. Which account is this?

**Comment by darwin1423** [comment]
my account is latorremx, my workspace is latorre
I did a clean installation in the workspace and it gives me that error.

**Comment by MatheusR42** [comment]
@darwin1423 , there are some apps that you need to install in your workspace. Try to follow this tutorial:
https://vtex.io/docs/getting-started/build-stores-with-vtex-io/3

**Comment by denisebiscaro** [comment]
https://vtex.io/docs/getting-started/build-stores-with-store-framework/3 - new url
