### ISSUE TITLE
SubmenuAccordion - Prop to close all siblings addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#202]
## Current Behavior
Currently SubmenuAccordion have the behavior of leaving opened all the submenus that were activated.

**Example :**
https://nimb.ws/dBJD3m

## Expected Behavior
We would like to have a prop that indicates that only one submenu of a determined hierarchical level can be open at the same time. This would make so that all Submenu siblings of the last clicked automatically close.

**Example :**
https://nimb.ws/GcAgtv

## Aditional Information:
Component  link: https://github.com/vtex-apps/menu/blob/master/react/SubmenuAccordion.tsx

**Comment by klzns** [comment]
That's a nice feature one could contribute.
