### ISSUE TITLE
Search-layout-switcher desktop support addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#203]
## **Is your feature request related to a problem? Please describe.**
Currently on mobile we have a option to change the search-result layout grid by using the `search-layout-switcher` to toggle the number of products shown by row. This however is a feature available only on mobile. 

Example: https://www.loom.com/share/bd9a7dd097d1445f82e19c05bd979290

## **Describe the solution you'd like**
The addition of support for desktop resolution of the same feature, adding a block class for each row in order to be possible to do a list-like search-result page.

Example: https://imgur.com/a/ikSvbHR

## **Describe alternatives you've considered**
Instead of adding/changing its block class, changing the product summary block (from shelf to list for example) would be an even better option.

## **Additional context**
Component link: https://github.com/vtex-apps/search-result

**Comment by klzns** [comment]
Makes total sense to have this. I'll add this to our backlog.

**Comment by alextalha** [comment]
@klzns  
I was going to ask just that question. already have a forecast for this feature?
