### ISSUE TITLE
 Product page stopped rendering

### ISSUE THREAD

**Issue by alextalhaoriginal** [vtex-apps/store-discussion#204]
**What are you trying to accomplish? Please describe.**  

I'm trying to display the product page but it doesn't render for some reason

**What have you tried so far?**  
in addition to trying to display. I also tried to reset the workspace and reinstall some dependencies

**Additional info**  
[novaloja--modaoriginal.myvtex.com-1582218775493.log](https://github.com/vtex-apps/store-discussion/files/4232052/novaloja--modaoriginal.myvtex.com-1582218775493.log)

[novaloja--modaoriginal.myvtex.com.har.log](https://github.com/vtex-apps/store-discussion/files/4232054/novaloja--modaoriginal.myvtex.com.har.log)

| Account | Workspace |
|---|---|
|`modaoriginal`|`novaloja`|

**Comment by gris** [comment]
What is the goal that you're trying to achieve? Do you want to create a store with VTEX IO or with CMS stable? https://novaloja--modaoriginal.myvtex.com/saia-padrao/p is rendering fine here, but it is showing the CMS stable (portal) version.

**Comment by alextalhaoriginal** [comment]
Sorry but I put the wrong workspace. the test is **comercial**
**novaloja** is not IO.

**Comment by gris** [comment]
You didn't follow the steps outlined in https://vtex.io/docs/getting-started/build-stores-with-vtex-io/3. You need to install a few dependencies to make sure the store works properly. 

```
The following apps need to be installed before downloading the Store There in your local files: vtex.store-sitemap, vtex.store, vtex.rewriter --force, vtex.admin-pages and vtex.colossus-legacy-proxy@2.x.
```

I've installed them for you and now is working properly.

**Comment by gris** [comment]
@alextalhaoriginal does it solve your problem?

**Comment by alextalhaoriginal** [comment]
@gris checking today the problem was solved I believe that only updating the vtex cli.

Thank you for your support
