### ISSUE TITLE
Cannot find module C:\Users\Corebiz\AppData\Roaming\npm\node_modules\vtex\lib\cli.js

### ISSUE THREAD

**Issue by andres310597** [vtex-apps/store-discussion#205]
Hi! What can I do in this case?
Error: Cannot find module 'C:\Users\Corebiz\AppData\Roaming\npm\node_modules\vtex\lib\cli.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

I will waiting for the answer. thanks

**Comment by klzns** [comment]
Hi!
1. What command did you type?
2. Can you type `vtex -v`, what is the result?
3. Can you type `node -v`, what is the result?
4. Can you type `npm -v`, what is the result?

**Comment by andres310597** [comment]
when I typed 
1. vtex -v the result is, the same error
2. node -v the result is, v10.16.3
3. npm -v the result is, 6.9.0

**Comment by tiagonapoli** [comment]
Could you try reinstalling?

For uninstall:
```
npm uninstall -g vtex
```

For installing:
```
npm install -g vtex
```

**Comment by andres310597** [comment]
Hi! Thank you so much for you answer. I could resolve whit that´s command since five days, that is the solution!
