### ISSUE TITLE
filter-navigator.v3 mobile filterButtons class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#207]
## **Is your feature request related to a problem? Please describe.**
In Search-result component, there's no class for divs buttons hierarchically beneath filterButtonsBox.

## **Describe the solution you'd like**
Insert a class into mentioned div in order to enable CSS properties developments without using any deprecated selector.
## **Additional context**
Here's a code screenshot providing an overview of div where Classname is requested: https://ibb.co/qNBgYjr
Component link: https://github.com/vtex-apps/search-result

**Comment by iaronaraujo** [comment]
Done! 
https://github.com/vtex-apps/search-result/pull/313
https://github.com/vtex-apps/search-result/pull/314
