### ISSUE TITLE
Change Styles for buttons of the filter navigator

### ISSUE THREAD

**Issue by calixfar** [vtex-apps/store-discussion#208]
Hi guys, how i can change the individuals styles for the buttons of the filter menu.

![image](https://user-images.githubusercontent.com/26258524/75175261-02fd6980-5700-11ea-802d-62bdc5b9e27a.png)

Not found a class that difference wich a of the buttons. 

![image](https://user-images.githubusercontent.com/26258524/75175224-f0833000-56ff-11ea-8382-569ab9d496c2.png)

I know that i can modify the file config/styles.json but this would change all the styles of the store and we no want that.

Thanks for your fast response.

**Comment by Klynger** [comment]
You should be able to customize this by following the instructions of [this article](https://vtex.io/docs/getting-started/build-stores-with-vtex-io/5), but we're missing some css handles, I'm doing a PR to fix this

**Comment by Klynger** [comment]
If you use these selectors you could achieve what you want

![image](https://user-images.githubusercontent.com/8517023/75477260-c8533580-597a-11ea-9b47-085e70a942be.png)
