### ISSUE TITLE
Shelf itemsPerPage prop revision request for tablet devices

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#209]
## Current Behavior
The current behavior shows only itemsPerPage and minItemsPerPage defined by a number and in tablet devices it not works properly, since it shows the configuration of small devices.

## Expected Behavior
Update the shelf slider with the same prop as slider-layout, where we can define visible items by phone, tablet and desktop. So that tablet devices can show a number of items adapted to its device screen size.

## Describe alternatives you've considered
Currently the only workaround we foud is to use responsive-layour and replicate a shelf in order to have the desired effect.

## Component Link
https://github.com/vtex-apps/shelf
https://github.com/vtex-apps/slider-layout

## Prints
https://nimb.ws/1T37Ic
https://nimb.ws/ghIx9p
https://nimb.ws/t4ZXTU

**Comment by denisebiscaro** [comment]
Hey @luizgpriolli you can already use our `slider-layout` to build your own shelf. We still don't have a recipe for that, but you can take a look on this PR that implements that:

https://github.com/vtex-apps/store-theme/pull/190/files

Look closely on how the `flex-layout.row#shelf` was implemented

We intend to deprecate the shelf component, so we would like to reinforce the use of `slider-layout` in this case.

Tks and let me know if you were able to implement that 🙏
