### ISSUE TITLE
Sku Selector not showing in shelf

### ISSUE THREAD

**Issue by EmperorPidgeon** [vtex-apps/store-discussion#210]
Hello, I've been trying to show an SKU selector in my shelf but I've got no success.

This is my current code:

[home.zip](https://github.com/vtex-apps/store-discussion/files/4257842/home.zip)

"shelf#home": {
    "blocks": ["product-summary.shelf"]
  },
  "product-summary.shelf": {
    "children": [
      "product-summary-name",
      "product-summary-description",
      "product-summary-image",
      "product-summary-price",
      "product-summary-sku-selector",
      "product-summary-buy-button"
    ]
  },
  "product-summary-sku-selector": {
    "props":{
      "showVariationsLabels": ["false"]
    }
  },

And this is the result: 
![image](https://user-images.githubusercontent.com/9360514/75381518-a5138200-58b7-11ea-8f73-d7c934b1c1e4.png)

In case you mind it, my account is: zapatos--delucca.myvtex.com

Thanks in advance!

**Comment by klzns** [comment]
You should use the prop `skusFilter`  with the value `"ALL_AVAILABLE"`.

![image](https://user-images.githubusercontent.com/284515/75457317-1c4e2200-595b-11ea-9eec-78fa82302ac6.png)

You can read it here https://vtex.io/docs/components/product/vtex.shelf

**Comment by EmperorPidgeon** [comment]
{
  "shelf":{
      "blocks": ["product-summary.shelf"],
      "props": {
      "category": 1,
      "orderBy": "OrderByTopSaleDESC",
      "skusFilter": "ALL_AVAILABLE",
      "paginationDotsVisibility": "desktopOnly",
      "productList": {
          "maxItems": 8,
          "itemsPerPage": 5,
          "minItemsPerPage": 1,
          "scroll": "BY_PAGE",
          "arrows": true,
          "titleText": "Más Vendidos"
      }
  }
}

IT's still not showing anything at all..

**Comment by denisebiscaro** [comment]
@EmperorPidgeon You have to add the specification names you want to show up in the prop `visibleVariations`

```
  "product-summary-sku-selector": {
    "props": {
      "visibleVariations" : ["color"]
    }
  },
```
In this case, you'll see only color variations on the SKU.

**Comment by EmperorPidgeon** [comment]
Still no luck, nothing is showing up.

Tried in shelf and home, with both Color and Talle and there's nothing on
the shelf.

[image: image.png]

**Comment by pablob300** [comment]
> @EmperorPidgeon You have to add the specification names you want to show up in the prop `visibleVariations` on your `product-summary-sku-selector` component:
> 
> ```
>   "product-summary-sku-selector": {
>     "props": {
>       "visibleVariations" : ["color"]
>     }
>   },
> ```
> 
> In this case, you'll see only color variations on the SKU selector

And what can i do to call an especific COLOR image LABEL in props?
