### ISSUE TITLE
How to change my-account orders text?

### ISSUE THREAD

**Issue by MatheusR42** [vtex-apps/store-discussion#211]
**What are you trying to accomplish? Please describe.**  
I want to change the  text of "orders" menu item of my-account component

![image](https://user-images.githubusercontent.com/16908590/75453519-cb3a3000-5952-11ea-81d4-b28de2406b2f.png)

**What have you tried so far?**  
I found all the other messages at store-messages(https://github.com/vtex-apps/store-messages/blob/master/messages/pt/vtex.my-account%401.x.json) and changed with graphql-ide(https://vtex.io/docs/recipes/store/overwriting-the-messages-app). But I could not find the orders message

apps:
store-messages@0.x
my-account@1.x

**Comment by kaisermann** [comment]
Hey @MatheusR42 👋 Firstly, sorry for taking so long to answer.

To change the `my orders` title, you should edit the messages from the `my-orders` app, not from the `my-account`. See it here: https://github.com/vtex/my-orders/blob/master/react/ExtensionLinks.js#L7

**Comment by MatheusR42** [comment]
@kaisermann , that is a private repo do you have any plans to make it public? If not can you send here all the messages? 

Thanks

**Comment by klzns** [comment]
One workaround is to:

1. Install [React Developer Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) 
2. Open the page in a development workspace
3. Inspect the element you want to know the translation ID
4. Change to the Components tab of you Chrome Dev Tools
5. Check for the nearest FormattedMessage component
6. Look for the prop `id`

In this example I've inspected the element "Order Date":
![image](https://user-images.githubusercontent.com/284515/77691635-0e081b80-6f84-11ea-9b3a-b016d7adb919.png)


For the title "Orders" is structured a bit different, but you can find it here in the prop `titleId`:

![image](https://user-images.githubusercontent.com/284515/77691742-34c65200-6f84-11ea-86e6-77a9bf8ef2b9.png)

**Comment by MatheusR42** [comment]
Thanks @klzns
