### ISSUE TITLE
quantityDropDownContainer class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#214]
**Is your feature request related to a problem? Please describe.**
We need to manipute the height of the component 'quantityDropDownContainer' and 'quantityDropDownMobileContainer'

**Describe the solution you'd like**
Insert a class into mentioned div in order to enable CSS properties developments without using any deprecated selector.

**Additional context**
Here is a code screenshot providing an overview of div where Classname is requested
https://flic.kr/p/2ixfD4w
https://flic.kr/p/2ixd5ZT

**Comment by Klynger** [comment]
Done by https://github.com/vtex-apps/product-list/pull/37
