### ISSUE TITLE
Mobile Sticky Header does not get the class "-stuck" removed

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#215]
# **Describe the bug**
Sticky header does not work properly on Mobile, not removing the class "-stuck" after going back to the top
# **To Reproduce**
1. Go to http://storetheme.vtex.com/
2. Put in mobile mode
3. Scroll down and scroll up again
# **Expected behavior**
The added css classes were expected to be removed after scrolling to the top of the page in the same way as on the desktop
# **Screenshots**
Normal Header -> https://prnt.sc/rab5gs
Sticky Header -> https://prnt.sc/rab5sx
# **Smartphone**
 - Device: Motorola Moto G5
 - OS: Android 8.1.0
 - Browser Chrome
 - Version 80.0.3987.119
 - This error can be reproduced on Chrome Mobile Dev Tools.
# **Additional context**
Prints about css classes changed
https://prnt.sc/raa9zx
https://prnt.sc/raaabp

**Comment by kaisermann** [comment]
Hey @luizgpriolli. Thanks for the detailed issue! It's been fixed in `vtex.sticky-layout@0.3.3` 🎉
