### ISSUE TITLE
colGap in vtex.flex-layout should change `mr`

### ISSUE THREAD

**Issue by goldsteinr** [vtex-apps/store-discussion#216]
When setting the `colGap` prop in `flex-layout.row` the `pr` Tachyon is changed affecting the elements width as seen in the print below:

![Screen Shot 2020-03-03 at 13 41 36](https://user-images.githubusercontent.com/6901375/75798339-30c45d00-5d55-11ea-8213-6baeca9ad4e1.png)
![Screen Shot 2020-03-03 at 13 40 31](https://user-images.githubusercontent.com/6901375/75798344-31f58a00-5d55-11ea-96a8-f29713710691.png)

Changing to affect the `mr` Tachyon the problem is solved and no width is affected.

Can it be changed?

**Comment by lbebber** [comment]
Hi, thanks for raising this issue and for your suggestion!

We will look into this change to see if this won't be a breaking change and how this will affect our current users, and if so, how else can we fix this problem.

**Comment by klzns** [comment]
As a workaround you could add a `blockClass` prop to this flex-layout and adjust this in your custom CSS.

**Comment by goldsteinr** [comment]
okay, thanks :)

**Comment by javierenciso** [comment]
> Hi, thanks for raising this issue and for your suggestion!
> 
> We will look into this change to see if this won't be a breaking change and how this will affect our current users, and if so, how else can we fix this problem.

Hi!
this issue is closed, but did the behavior change in any way, or did you decide to not change it...?
New to VTEX but can't figure out how to use colGap in any useful way to mark the gap between columns.
/best
/javier
