### ISSUE TITLE
How to use srcset prop on image component

### ISSUE THREAD

**Issue by ninasolon** [vtex-apps/store-discussion#217]
Can I use srcset prop on an Image component to change its src according to screen size? Or do I have to create separate blocks for desktop and mobile banner?

I couldn't find any example on how to use srcset and sizes props.

**Comment by klzns** [comment]
Hi! What are you trying to achieve, can you provide a screenshot of the desired output?

**Comment by ninasolon** [comment]
I have a banner that changes image source according to screen size. Do I have to create two separate image components (desktop and mobile) or is there a way to set both images url into the same image component?

<img width="721" alt="Screen Shot 2020-03-05 at 12 54 12" src="https://user-images.githubusercontent.com/46014879/75999576-2d5ddc80-5ee1-11ea-8172-d2bd2d40f481.png">

<img width="417" alt="Screen Shot 2020-03-05 at 12 54 56" src="https://user-images.githubusercontent.com/46014879/75999587-32bb2700-5ee1-11ea-9b26-5ed7126992b0.png">

**Comment by pedrohenriqueoliveira** [comment]
Hello, @ninasolon. Sorry for the delay in the response.

Yes, you can use different content for the same image component. You need to do it through Site Editor (`https://{{yourStoreName}}.myvtex.com/admin/cms/site-editor`)

In the Image List component, you can fill with the content for desktop and for mobile: 

- Desktop
![image](https://user-images.githubusercontent.com/19555647/77463099-db272180-6de3-11ea-97f8-e45e800d9b2f.png)

- Mobile
![image](https://user-images.githubusercontent.com/19555647/77463223-0b6ec000-6de4-11ea-9670-a8c359672918.png)

Best Regards,

Pedro

**Comment by johnnymartinez-moendi** [comment]
2024 y aun no encuentro 1 ejemplo de uso de srcset, seria muy util para no hacer 2 componentes de imagen
