### ISSUE TITLE
[DRAFT] RFC: Type definitions for block props

### ISSUE THREAD

**Issue by lbebber** [vtex-apps/store-discussion#218]
We've had a preliminary discussion regarding how to do type checking for block props. 

## Objective

Our main goals are:
- add robustness to the platform, breaking on build time in case of incorrect props instead of doing so on runtime
- better development experience, allowing suggestions, checking typos and inexistent props, deprecation warnings, etc
- marking certain props as "Slots" (refer to https://github.com/vtex-apps/store-discussion/issues/213)

## Proposed solution

We currently have a `schema` for each block (set on the `contentSchemas.json` file), which contains metadata for several props, such as type, title, format. It is used primarily for customisation of blocks via CMS, and as such it is more concerned with props that are relevant for the Site Editor.

We are proposing making use of schemas to define all exposed block props, and using it for build-time type checking.

Additionally, we propose adding support for a "Block" value to the `format` field, to allow passing blocks as props (https://github.com/vtex-apps/store-discussion/issues/213).

The schema currently has an `isLayout` flag, for props that are not content (thus currently unavailable on the Site Editor). We need to investigate whether we need to add another flag for other cases (e.g. a prop that is not layout but should not be edited via CMS for some other reason). If we do need to add another flag, we propose adding a field that supports an enum instead of a boolean, for future additions.

At first, there will be no limitations in regards of which kind of block a slot supports.

In the future, we intend on adding limitations regarding which context a block requires/provides, but it is a separate issue, as it is not directly related to slots/props—it also affects `children`.

### Alternatives considered

We have considered using TypeScript for type definitions. The question is that we already have to maintain the schema for CMS (and similar) purposes, so we have considered it more efficient to make use of it for type checking as well.

## Examples

(TBD)

(needs examples of props that accept objects of specific shapes)

**Comment by juliomoreira** [comment]
I have some weird example here.

I don't know if it can shine some light, I think it's more of an edge case.

```tsx
import React from 'react'
import { useLocation } from '../../contexts/Location'
import { FormattedMessage } from 'react-intl'
import { BlockClass, generateBlockClass } from '@vtex/css-handles'

import styles from './styles.css'

interface AddressProps extends BlockClass {
  tag?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'p' | 'span' | 'div'
}

const Address: StorefrontFunctionComponent<AddressProps> = ({
  blockClass,
  tag: Tag = 'p',
}) => {
  const {
    address: { number, street, city, state, postalCode },
  } = useLocation()
  const classes = generateBlockClass(styles.address, blockClass)
  return (
    <Tag className={`${classes} mv0 mb2 t-small lh-copy`}>
      <FormattedMessage
        id="store/store-locator.address"
        values={{
          number,
          street,
          city,
          state,
          postalCode,
        }}
      />
    </Tag>
  )
}

Address.schema = {
  title: 'admin/editor.store-locator.address.title',
  type: 'object',
  properties: {
    tag: {
      type: 'string',
      title: 'Tag',
      enum: ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'span', 'div'],
      default: 'p',
    },
  },
}

export default Address
```
