### ISSUE TITLE
SubmenuAccordion - class for active status addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#219]
# Is your feature request related to a problem? Please describe.
In menu component, there's no class for the div hierarchically beneath span with the styledLink className. And also the icon's div does not differentiate the class for each icon
# Describe the solution you'd like
Insert a class into mentioned div in order to enable CSS properties developments without using any deprecated selector and inside second div that shows the "+" or "-" icon, it would be useful a different className to each icon depending on which of them is currently active. 
# Additional context
Here are code screenshots providing an overview of divs where Classname is requested
https://prnt.sc/r8hbos
https://prnt.sc/r8hbf8

Component link: https://github.com/vtex-apps/menu

**Comment by klzns** [comment]
Fixed :white_check_mark:
