### ISSUE TITLE
Add native support for more payment method badges on footer

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#22]
Former issue: [#56](https://github.com/vtex-apps/store-footer/issues/56)

**Describe the solution you'd like**
Would be nice to have more payment methods badges to display;

**Describe alternatives you've considered**
As an alternative we have to extend the `accepted-payment-methods` interface;

**Comment by hapoza** [comment]
@juliomoreira Another workaround without having to extend the interface, is to use the block `image` from https://github.com/vtex-apps/store-components/tree/master/react/components/Image and use them inside a flex-layout.row block

**Comment by fpsman** [comment]
So in my understading we're moving to a solution to deprecated `PaymentMethodIcon`, agree? haha

**Comment by hapoza** [comment]
@fpsman The case for using `image` would be applicable only if the footer is implemented with `footer-row` and `flex-layout`, if the store uses the default footer it's still necessary to have `accepted-payment-methods`

**Comment by denisebiscaro** [comment]
@juliomoreira which payment methods are you missing?

**Comment by juliomoreira** [comment]
@denisebiscaro you can check in the [original issue](https://github.com/vtex-apps/store-footer/issues/56) there we have a list with the most commonly used.

**Comment by Klynger** [comment]
Since this was already solved I'm going to close this issue
