### ISSUE TITLE
Change checkbox label color

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#220]
**What are you trying to accomplish? Please describe.**  
I'm trying to change the label color of all checkboxes in the filter section

**What have you tried so far?**  
I've tried targeting the label from css but I get a deprecation error. The label has "c-on-base" class on it. If I change the color from styles.json, all checkboxes in the site are affected.

**Additional info**  
Add extra content here (code samples, screenshots,...)
![image](https://user-images.githubusercontent.com/42587916/76082324-c0ffdd80-5fb3-11ea-8d9e-d6011f120604.png)

| Account | Workspace |
|---|---|
|dacris|doru

https://doru--dacris.myvtex.com/articole-de-birou/organizare-si-arhivare

Thanks!

**Comment by klzns** [comment]
That will be fixed on Monday. Thanks for creating this issue.

**Comment by doruradu** [comment]
Ok, thanks!

**Comment by klzns** [comment]
Fixed! You may now use the class `vtex-checkbox__label` to achieve that.
