### ISSUE TITLE
filterNavigator label class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#221]
**Is your feature request related to a problem? Please describe.**
In 'search-result' component, there's no className for department's filter options. It's impossible change CSS properties of this label without a className.

**Describe the solution you'd like**
Insert a className in this label to enable CSS properties individually without using any deprecated selector.

**Additional context**
That's a code screenshot providing an overview of mentioned label where Classname is requested
https://ibb.co/K789MTG

**Component link**
https://github.com/vtex-apps/search-result

**Comment by kaisermann** [comment]
That was fixed recently. We now have a `vtex-checkbox__label` css handle there 😁
