### ISSUE TITLE
SocialMedia share buttons class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#222]
**Is your feature request related to a problem? Please describe.**
In 'store-components' component, there's no different classes for different social media share buttons.

**Describe the solution you'd like**
Insert a different class to each social media button in order to enable CSS properties developments without using any deprecated selector.

**Additional context**
That's a code screenshot providing an overview of mentioned div where Classname is requested
https://ibb.co/Tv7ymnN

**Component link**
https://github.com/vtex-apps/store-components/tree/master/react/components/Share

**Comment by iaronaraujo** [comment]
Hi @luizgpriolli ! In this example you showed me there are different classes for each social media:
`SocialMediaShareButton--facebook`
`SocialMediaShareButton--whatsapp`
`SocialMediaShareButton--twitter`

**Comment by iaronaraujo** [comment]
Closing this issue since this seems to be already done! Please reopen it if necessary!
