### ISSUE TITLE
GradientCollapse Show More button class addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#223]
**Is your feature request related to a problem? Please describe.**
In 'store-components', there's a button inside the 'pointerEventsAuto class' div, and this button don't have any class.

**Describe the solution you'd like**
Insert a class into this button in order to enable CSS properties developments without using any deprecated selector.

**Additional context**
Here's a code screenshot providing an overview of mentioned div where Classname is required
https://ibb.co/HYJ2HNP

Component Link: https://github.com/vtex-apps/store-components/blob/master/docs/GradientCollapse.md

**Comment by kaisermann** [comment]
Hey @luizgpriolli 👋 The handles were added in `vtex.store-components@3.107.0` 😁
