### ISSUE TITLE
Addition of Outline-color CSS property to style.json

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#224]
# **Is your feature request related to a problem? Please describe.**
Currently there is only a way to change the outline-color of the elements: changing one by one using CSS properties of each element, however some tags doesn't have a className making it impossible.

# **Describe the solution you'd like**
Add outline color to styles.json so that you can change this property and make it default for the entire store.

# **Additional context**
Here is a code screenshot providing an example of a tag without className which is impossible change the outline color property.
https://ibb.co/LdcH8tz

**Comment by kaisermann** [comment]
The `outlineColor` token was added in https://github.com/vtex/tachyons-generator/pull/29. If a string is provided, it adds a `* { outline-color: stringValue; }` rule to the store's tachyons css file. If none provided, nothing is added.
