### ISSUE TITLE
Add active csshandles to sku selector

### ISSUE THREAD

**Issue by riodajs** [vtex-apps/store-discussion#226]
**Is your feature request related to a problem? Please describe.**
Can't change style of sku selected button, only frameAround. 

**Describe the solution you'd like**
Add a csshandle.

**Additional context**
When is selected, I want to change button background color and hide framearound border.
![image](https://user-images.githubusercontent.com/27719363/76565282-ffe8d400-6488-11ea-9938-1fb594644a65.png)

**Comment by Klynger** [comment]
Done! The selected SKU will have an extra handle called `vtex-store-components-3-x-skuSelectorItem--selected`
