### ISSUE TITLE
Absolute center Logo

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#227]
**What are you trying to accomplish? Please describe.**  
Hi, I'm trying to center the logo in the header, without using the spacer. Is it possible?

**What have you tried so far?**  
Using "header-force-center" but I dont think I've added it in the right place.

**Additional info**  

| Account | Workspace |
|`louche`|`dragos`|

**Comment by klzns** [comment]
Can you provide the JSON of your blocks so we can see how you are doing it?

**Comment by doruradu** [comment]
Sure! Here's the json for the logo: 

`"logo#desktop": {
    "props": {
      "title": "Logo",
      "href": "/",
      "url": "https://louche.vtexassets.com/assets/vtex.file-manager-graphql/images/Logo-louche___031c5c1dd9e2f6b7c40d9610a31137c1.png",
      "width": "180",
      "blockClass":"forceCenter",
      "forceCenter":true
    }
  },`

And here's the wholse json for the header:
`{
  "header": {
    "blocks": ["header-layout.desktop", "header-layout.mobile"]
  },
  "header.full": {
    "blocks": ["header-layout.desktop", "header-layout.mobile"],
    "title": "Header"
  },

  "header-layout.desktop": {
    "children": [
      "header-row#1-desktop",
      "header-row#2-desktop"
      
    ],
    "title": "Header - Desktop",
    "props": {
      "fullWidth":true
    }
  },

  "header-row#1-desktop": {
    "children": ["notification.bar#home"],
    "props":{
      "blockClass":"notificationBarWrapper"
    }
  },
  "notification.bar#home": {
    "props": {
      "content": "FREE SHIPPING OVER £75 & FREE RETURNS"
    }
  },
  "header-row#2-desktop": {
    "children": [
      "header-row#3-desktop",
      "header-row#about-us-header",
      "header-spacer",
      "header-spacer",  
      "header-spacer", 
      "header-spacer", 
      "header-spacer",
      "logo#desktop",
      "header-spacer",
      "header-spacer",
      "header-spacer",
      "search-bar",
      "minicart"
    ],
    "props": {
      "sticky": true,
      "fullWidth":true,
      "blockClass": "main-header"
    }
  },

  "header-row#about-us-header":{
    "children":[
      "rich-text#about-us-header"
    ]
  },
  "rich-text#about-us-header":{
    "props":{
      "text": "About",
      "blockClass":"link-about-header"
    }
  },
  "search-bar": {
    "props": {
      "placeholder": "Search"
    }
  },
  "logo#desktop": {
    "props": {
      "title": "Logo",
      "href": "/",
      "url": "https://louche.vtexassets.com/assets/vtex.file-manager-graphql/images/Logo-louche___031c5c1dd9e2f6b7c40d9610a31137c1.png",
      "width": "180",
      "blockClass":"forceCenter",
      "forceCenter":true
    }
  },
  "header-row#3-desktop": {
    "children": ["header-spacer", "menu#category-menu", "header-spacer"],
    "props": {
      "sticky": false,
      "blockClass": "category-menu-row"
    }
  },

  "minicart": {
    "blocks": ["product-summary"],
    "props": {
      "type": "sidebar",
      "showRemoveButton": true,
      "showDiscount": true,
      "showSku": true,
      "labelMiniCartEmpty": "",
      "labelButtonFinishShopping": "Proceed to Checkout",
      "enableQuantitySelector": true,
      "maxQuantity": 10,
      "labelClasses": "gray"
    }
  },

  "header-layout.mobile": {
    "children": [
      "header-row#2-mobile",
      "header-row#3-mobile"
    ],
    "title": "Header - Mobile"
  },
  "header-row#1-mobile": {
    "children": ["notification.bar#home"],
    "props": {
      "sticky": false,
      "blockClass": "topbar-mobile"
    }
  },
  "header-row#2-mobile": {
    "children": [
      "drawer",
      "header-spacer",
      "header-spacer",
      "header-spacer",
      "header-spacer",
      "logo#desktop",
      "header-spacer",
      "header-spacer",
      "minicart"
    ],
    "props": {
      "sticky": false,
      "blockClass": "main-header-mobile"
    }
  },
  "header-row#3-mobile": {
    "children": ["search-bar"],
    "props": {
      "sticky": false,
      "blockClass": "search-row-mobile"
    }
  },

  "logo#mobile": {
    "props": {
      "title": "Logo",
      "href": "/",
      "url": "https://storecomponents.vteximg.com.br/arquivos/store-theme-logo-mobile.png",
      "width": "70"
    }
  }
}
`

**Comment by klzns** [comment]
We are you adding the block header-force-center?

**Comment by doruradu** [comment]
I never understood that it's actually a block, not a class or a prop. It's working now, thanks for your help. I'll leave the code here, just in case someone else stumbles across this.

`"header-row#2-desktop": {
    "children": [
      "header-row#3-desktop",
      "header-row#about-us-header",
      "header-spacer",
      "header-force-center",
      "header-spacer",
      "search-bar",
      "minicart"
    ],
    "props": {
      "sticky": true,
      "fullWidth":true,
      "blockClass": "main-header"
    }
  },`

**Comment by klzns** [comment]
You are right, there's no reference to it in the docs. I'll fix this! Thanks for the feedback
