### ISSUE TITLE
Clear OrderForm data when a Telemarketing user logout from a customer account

### ISSUE THREAD

**Issue by gustavopvasconcellos** [vtex-apps/store-discussion#228]
**What are you trying to accomplish? Please describe.**  
I need to develop a feature into store-graphql on `depersonify` to clear the orderForm products.

**What have you tried so far?**  
My idea is get orderForm and send to `checkout.updateItem` the items array with `quantity: 0` on each item. Everything on `depersonify` resolver.
My problems with this are:
- Is fine to you guys this solution to "reset" the orderForm when a Telemarketing operator logout?
- There is other way to clear the orderForm data, including the products?

**Comment by klzns** [comment]
Yes, I think it makes sense to reset the cart! 

About the second point, I think the right solution is to call the checkout API to get the orderform without passing any cookies.

**Comment by gustavopvasconcellos** [comment]
@klzns Ok! I thought to call this method from checkout client, it's right?

![image](https://user-images.githubusercontent.com/49173685/76638463-3c6d0c00-652b-11ea-92e7-b7977e55674f.png)

**Comment by klzns** [comment]
Kinda of, this method already includes cookies, because it uses the `post` method from here:

https://github.com/vtex-apps/store-graphql/blob/d6952f867d4839cf7d003a2e44ffc8b0bc89ca09/node/clients/checkout.ts#L205-L213

Which uses the method `getCommonHeaders`:

https://github.com/vtex-apps/store-graphql/blob/d6952f867d4839cf7d003a2e44ffc8b0bc89ca09/node/clients/checkout.ts#L23-L31

Which add the cookies.

So you should create a new method like `newOrderForm` that uses the basic `this.http.post` without including the checkout cookie.

**Comment by gustavopvasconcellos** [comment]
@klzns Understood! But, why this request should be done without cookies? 🤔

**Comment by klzns** [comment]
The Checkout API checks the cookies passed to know if the user already have a cart or not. If we dont pass those cookies, Checkout API will think that is the first time the user opens the store and will create a cart for it. Got it? Let me know if I was not clear.

**Comment by gustavopvasconcellos** [comment]
@klzns hummmmmmmm, ok... But I have to do this on frontend right? Because, how GraphQL will update the OrderForm of the Telemarketing session?

I try to do this, only making the request without the cookies, but the session's OrderForm on the website don't reset the cart data =/

So, I will do the clear of items, sending the items with quantity zero, ok?

**Comment by klzns** [comment]
Good point. 

The `depersonify` should return the Set-Cookie header of the response of the new method of `newOrderForm` and then the front end should trigger a refresh on the page after the mutation is complete. That will make the front end fetch the new orderForm, since the cookies are updated.

**Comment by gustavopvasconcellos** [comment]
@klzns please help me!
I've done a push to the repository to you can check if what I do is the correct way, because it isn't working. The logout of impersonate email works, but not to reset orderForm =/

Obs: I will improve the code to avoid errors

https://github.com/vtex-apps/store-graphql/pull/451
https://gus--unimarcdev.myvtex.com/

**Comment by gustavopvasconcellos** [comment]
@klzns Do you have any suggestion in this case?

**Comment by klzns** [comment]
Checking right now

**Comment by klzns** [comment]
Still trying here

**Comment by gustavo-vasconcellos** [comment]
@klzns I updated the PR with the changes you have asked to do... This is the way I got the loggout the impersonate user, removing the email from cookie, but the orderForm wasn't reseted =/

**Comment by klzns** [comment]
I managed to make it work. I'll push the commits in a couple of hours.

**Comment by klzns** [comment]
Merged and deployed! Thanks for the contribution!
