### ISSUE TITLE
Modal component usage example

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#229]
Hi! Do you have an example of the modal app usage? I can't seem to figure it out just based on the documentation. Thanks!

**Comment by klzns** [comment]
Yes, we have an example of using it in our store-theme. We use it to render the quickview. You can see the pull request that added that feature here:

https://github.com/vtex-apps/store-theme/pull/195/files

@Klynger will give you a more throughout answer

**Comment by Klynger** [comment]
Hi, just go to the [storetheme](https://app.clubhouse.io/vtex/story/30439/prop-to-specify-the-color-spec-type-on-sku-selector) and hover a product of the shelf, you will see this expand icon
![image](https://user-images.githubusercontent.com/8517023/76640174-3c224000-652e-11ea-8146-aa04a5b058c1.png)
Just click on it and you will see the quickview
![image](https://user-images.githubusercontent.com/8517023/76640248-5825e180-652e-11ea-870e-fac8cfaad1eb.png)

[Here is the code of it](https://github.com/vtex-apps/store-theme/blob/master/store/blocks/quickview.json)

we forgot to update the documentation, thx for the issue.

**Comment by klzns** [comment]
A small example:

```json
{
  "store.home": {
    "children": [
      "modal-trigger#example"
    ]
  },
  "modal-trigger#example": {
    "children": [
      "rich-text#example",
      "modal-layout#example"
    ]
  },
  "rich-text#example": {
    "props": {
      "text": "Click me"
    }
  },
  "modal-layout#example": {
    "children": [
      "rich-text#modal-content"
    ]
  },
  "rich-text#modal-content": {
    "props": {
      "text": "Hello"
    }
  }
}
```

**Comment by doruradu** [comment]
Thank you so much! :D
