### ISSUE TITLE
Add text to the cart icon

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#230]
**Is your feature request related to a problem? Please describe.**
I needed to remove the mini cart icon and replace it with a text (that was the design we got from the client). 

**Describe the solution you'd like**
A prop like contentType: "Icon" (Icon / Icon + Text / Text) would have been nice.

**Describe alternatives you've considered**
We achieved this by adding content to the :before psudo element and hiding the div containing the icon.

**Comment by victorhmp** [comment]
Hi @doruradu !

Thanks for the suggestion, we'll look into implementing this feature in the future :)
