### ISSUE TITLE
Is it possible to change appearance of the SKUSelector

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#231]
**What are you trying to accomplish? Please describe.**  
I want to customise the css of the states in the SKUSelector, but the blocks don't have state clases (default, selected, out-of-stock)

**What have you tried so far?**  
I tried customising using the frameAround and diagonalCross classes, but I also need to change the text appearance and I have no way of targeting it.

**Additional info**  
![image](https://user-images.githubusercontent.com/42587916/76679828-473ba580-65ec-11ea-8f05-84ae75135acd.png)

| Account | Workspace |
|---|---|
|`louche`|`dragos`|

**Comment by denisebiscaro** [comment]
Hey @doruradu! There's already an issue about it, let's discuss it together here? https://github.com/vtex-apps/store-discussion/issues/226
