### ISSUE TITLE
Do you have a hoverImageLabel example?

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#233]
**What are you trying to accomplish? Please describe.**  
I'm trying to add the second image at hover in the category page.

**What have you tried so far?**  
I've tried adding the hoverImageLabel on the "product-summary-image" block, but because I'm a rokie at this, I'm getting an error and I don't know how to fix it.

Here's my code:
`"gallery": {
    "blocks": ["product-summary#category"],
    "props":{
      "blockClass":"louche-product-cotainer"
    }
  },
  "product-summary#category": {
    "blocks":[
      "product-summary-image#imageCategorie",
      "product-summary-name",
      "product-summary-price"
    ],
    "props": {
      "isOneClickBuy": false,
      "showBadge": true,
      "badgeText": "OFF",
      "buyButtonText": "Add to bag",
      "displayBuyButton": "displayButtonHover",
      "showCollections": false,
      "showListPrice": true,
      "labelSellingPrice": "To",
      "labelListPrice": "From",
      "showLabels": true,
      "showInstallments": true,
      "showSavings": true,
      "name": {
        "showBrandName": true,
        "showSku": true,
        "showProductReference": true
      }
    }   
  },
  "product-summary-image#imageCategorie":{
    "props":{
      "hoverImageLabel":"Second"
    }
  }`

The error I'm getting is:

`6:42:12.384 - error: App build failed with message: Error resolving block "product-summary#category":
Unable to find an extension point declared for block 'product-summary-image#imageCategorie' on block 'product-summary#category'. Check 'allowed' blocks on interface 'vtex.product-summary@2.x:product-summary'  
16:42:12.387 - error: Error resolving block "product-summary#category":
Unable to find an extension point declared for block 'product-summary-image#imageCategorie' on block 'product-summary#category'. Check 'allowed' blocks on interface 'vtex.product-summary@2.x:product-summary' vtex.builder-hub@0.222.2  `

**Additional info**  
The images have the label "Second" in the admin.

Thank you!

| Account | Workspace |
|---|---|
|`louche`|`dragos`|

**Comment by denisebiscaro** [comment]
Hey!

**Comment by denisebiscaro** [comment]
Hey! Try to use `product-summary.shelf`  with composition `children`. The props should be declared in each of its children components, not in `product-summary.shelf`.

It should look like this:

```
{
   "gallery":{
      "blocks":[
         "product-summary.shelf#category"
      ],
      "props":{
         "blockClass":"louche-product-cotainer"
      }
   },
   "product-summary.shelf#category":{
      "children":[
         "product-summary-image#imageCategorie",
         "product-summary-name",
         "product-summary-price"
      ]
   },
   "product-summary-image#imageCategorie":{
      "props":{
         "hoverImageLabel":"Second"
      }
   }
}
...
```
There's an example of implemented `product-summary.shelf` here at Store Theme code - https://github.com/vtex-apps/store-theme/blob/1c1b3cd5a5022615afffaedbfcbafc3bd40d5fe5/store/blocks.jsonc#L39

Check the available props for the children apps at:
[product-summary-buy-button](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-buy-button)
[product-summary-name](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-name)
[product-summary-description](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-description)
[product-summary-price](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-price)
[product-summary-image](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-image)
[product-summary-specification-badges](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-specification-badges)
[product-summary-sku-selector](https://vtex.io/docs/components/content-blocks/vtex.product-summary/product-summary-sku-selector)


More info about how to control the second image through the site editor here: https://github.com/vtex-apps/release-notes/blob/cb2461b715d3375cbafcaf8bd665976113e00e0f/docs/2019-week-31/change-image-on-hover.md

**Comment by denisebiscaro** [comment]
@doruradu If you are interested in learning more about our native components, take a look on our course - https://lab.github.com/vtex-trainings/store-framework 

:)

**Comment by doruradu** [comment]
Got it, thanks!

**Comment by doruradu** [comment]
It worked! Thanks x2359725923!
