### ISSUE TITLE
 Button label when not available in department

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#238]
**Describe the bug**

button label when not available

**To Reproduce**

in department, scroll until there is no product available

![Capturar](https://user-images.githubusercontent.com/4852136/77183365-fbd23d00-6aac-11ea-9026-53723cc762a6.PNG)

**Comment by klzns** [comment]
Can you provide a workspace with the issue?

**Comment by alextalha** [comment]
https://newstore--fensacl.myvtex.com/linea-blanca/freezer

**Comment by klzns** [comment]
Thanks for the report! That's a bug that will be fixed soon with [this pull request](https://github.com/vtex-apps/add-to-cart-button/pull/15).

**Comment by klzns** [comment]
Fixed :)
