### ISSUE TITLE
 How to insert new icons in the store?

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#239]
**What are you trying to accomplish? Please describe.**  

I would like to add new icons in the store and how to call them.
example, would you call an icon within a rich text?
furthermore i would like to know how to change their respective colors

**Comment by klzns** [comment]
Hi @alextalha!

> I would like to add new icons in the store and how to call them.

There's no way to add new icons, but you can customize the existing ones to your need. You can read more on [how to customize the icons of the store](https://vtex.io/docs/recipes/style/customizing-your-stores-icons). It might be helpful in your case.

> example, would you call an icon within a rich text?

There's no way to do that right now. You can however, add a block of the icon you want:
https://github.com/vtex-apps/store-icons/blob/master/store/interfaces.json

> furthermore i would like to know how to change their respective colors

You can use the CSS `color` property to do that. All icons use the currentColor property of CSS (`color: currentColor`) so it will use the text color.

**Comment by alextalha** [comment]
thanks @klzns
