### ISSUE TITLE
sliderTrackContainer max-width

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#241]
**What are you trying to accomplish? Please describe.**  
I'm trying to add a full-width hero slider on the homepage. I saw that sliderTrackContainer has a max-width of 1520px.  I need a full width slider with auto height.

**What have you tried so far?**  
Read the docs, tried to use the carousel app but I saw it's deprecated. I tried adding the fullwidth prop on the slider-layout, but no luck.

**Additional info**  
The code used is the store-theme default. I've tried adding the fu

![image](https://user-images.githubusercontent.com/42587916/77228155-1af4cb80-6b8e-11ea-8b06-b23324ba92f4.png)

`  "list-context.image-list#hero-banner": {
    "children": ["slider-layout#hero-banner-images"],
    "props": {
      "height": 720,
      "images": [
        {
          "image": "assets/banner-catei.jpg",
          "mobileImage": "assets/banner-catel-mobile.jpg"
        },
        {
          "image": "assets/banner-pisici.jpg",
          "mobileImage": "assets/banner-pisica-mobile.jpg"
        }
      ]
    }
  },
  "slider-layout#hero-banner-images": {
    "props": {
      "itemsPerPage": {
        "desktop": 1,
        "tablet": 1,
        "phone": 1
      },
      "infinite": true,
      "showNavigationArrows": "desktopOnly",
      "blockClass": "carousel",
      "fullWidth":true
    }
  },`

| Account | Workspace |
|---|---|
|`vetro`|`develop`|

Thank you!

**Comment by kid-three** [comment]
Hi, how did you fix this?
