### ISSUE TITLE
Image app link prop

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#242]
**What are you trying to accomplish? Please describe.**  
I'm trying to add a link to an image.

**What have you tried so far?**  
I added the following code, with the link as prop. When clicked, the image redirects to the homepage.

**Additional info**  
Code used:

`"image#banner-caini":{
    "props":{
      "src":"assets/bannere-categorie-caini.jpg",
      "link":"/caini/accesorii-caini"
    }
  },`

| Account | Workspace |
|---|---|
|`vetro`|`develop`|

**Comment by klzns** [comment]
@doruradu the Link object specified in the docs has the following format:

```json
"link": {
  "attributeNofollow": false,
  "attributeTitle": "",
  "newTab": false,
  "url": ""
}
```

Reading the docs that is not clear. We'll fix it.

**Comment by doruradu** [comment]
ok, thanks!
