### ISSUE TITLE
Table in rich text

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#245]
**What are you trying to accomplish? Please describe.**  

I'm trying to add a table with markdown to table

**What have you tried so far?**  

I tried, but without success to add a table. and honestly I don't know if I really have to use rich-text for that

**Additional info**  

I would like to be doing something like this
https://www.tiendafensa.cl/institucional/bases-legales-de-promociones/freezer

**Comment by klzns** [comment]
Can you provide the markdown you are inputting?

rich-text can render tables, you can see a unit test rendering it:

https://github.com/vtex-apps/rich-text/blob/master/react/__test__/index.test.tsx#L188-L198

**Comment by alextalha** [comment]
Hi @klzns 
i was using that way
``
  "rich-text#block__menu-8__title-2--slot-2": {
        "props": {
            "text": " FREEZERS  | FENSA | 240074747 | FFH Z300      | HORIZONTALES \n-----------|-------|-----------|---------------|--------------\n FREEZERS  | FENSA | CA0008144 | FFV 4765 INOX | VERTICALES   \n FREEZERS  | FENSA | 240074745 | FFH Z200      | HORIZONTALES \nFREEZERS  | FENSA | 240074745 | FFH Z400      | HORIZONTALES ",
            "blockClass": "instucional__item"
        }
    }
``

At first I replaced this table with an image. but the client wanted a table even

**Comment by klzns** [comment]
I've tried the same code here and it worked:


```json
  "rich-text#1": {
    "props": {
      "text": " FREEZERS  | FENSA | 240074747 | FFH Z300      | HORIZONTALES \n-----------|-------|-----------|---------------|--------------\n FREEZERS  | FENSA | CA0008144 | FFV 4765 INOX | VERTICALES   \n FREEZERS  | FENSA | 240074745 | FFH Z200      | HORIZONTALES \nFREEZERS  | FENSA | 240074745 | FFH Z400      | HORIZONTALES "
    }
  },
```
![image](https://user-images.githubusercontent.com/284515/77672188-582ed400-6f67-11ea-8ed3-881dcdecde62.png)

**Comment by alextalha** [comment]
@klzns 
so how could you be putting borders on that table?
 
taking advantage of the subject this text field do I have to escape?

because everything in one line is tense

**Comment by klzns** [comment]
> so how could you be putting borders on that table?
I thought it was just adding some CSS properties, but I think we need to add new CSS Handles to the `th` and `td` elements to make this possible.

> taking advantage of the subject this text field do I have to escape?
> because everything in one line is tense

hahah yeah, I know, but currently no

**Comment by klzns** [comment]
Added the CSS Handles @alextalha 
https://github.com/vtex-apps/rich-text/pull/36/files#
