### ISSUE TITLE
 Image dimension change when inserting a parameter in the slider-layout

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#247]
**Describe the bug**
Image size change when inserting a parameter in the slider-layout. more precisely the" link "parameter

**To Reproduce**

Insert link parameter 

```jsonc
 "list-context.image-list#demo": {
        "children": ["slider-layout#demo-images"],
        "props": {
            "height": 720,
            "images": [
                {
                    "image": "https://electroluxcl.vteximg.com.br/arquivos/ids/162730/SlideHome-Freezer-Fensa-1920x500.jpg?v=637111746296200000",
                    "mobileImage": "https://electroluxcl.vteximg.com.br/arquivos/ids/163116/bannertv-mobile-blackweeks-fensa-cl.png?v=637184931744470000",
                    "link": "https://www.tiendafensa.cl/linea-blanca/freezer"
                },
                {
                    "image": "https://electroluxcl.vteximg.com.br/arquivos/ids/163289/bannertv-desk-otono-fensa-cl-vfinal.png?v=637201553413100000",
                    "mobileImage": "https://electroluxcl.vteximg.com.br/arquivos/ids/162689/Banner-mobile-temporadarefrigeracion-fensa-cl%20(1).jpg?v=637105755322200000"
                },
     ]
        }
    },
```
**Expected behavior**
That all images had the same resolution 

**Screenshots**

![Capturar](https://user-images.githubusercontent.com/4852136/77653915-198d1f80-6f4f-11ea-95d3-4b6341be7fd8.PNG)
![segunda imagem](https://user-images.githubusercontent.com/4852136/77654006-33c6fd80-6f4f-11ea-9a92-2f4eb6260149.PNG)

**Comment by victorhmp** [comment]
Hi @alextalha !
Could you provide a workspace where this behavior is observed? That would really help in the debug process.

**Comment by alextalha** [comment]
@victorhmp  
https://bannertvrich--fensacl.myvtex.com/

**Comment by alextalha** [comment]
> Hi @alextalha !
> Could you provide a workspace where this behavior is observed? That would really help in the debug process.

@victorhmp

**Comment by victorhmp** [comment]
Hi @alextalha ! Sorry for the delay, I could not set aside some time to look further into this.
But taking a quick look into the workspace you've sent, the images look fine 🤔 

This one has a link:

<img width="1680" alt="Screen Shot 2020-04-06 at 13 03 14" src="https://user-images.githubusercontent.com/27777263/78579254-0a3b8b00-7807-11ea-9180-c3bfe785f993.png">

And this one doesn't: 
<img width="1680" alt="Screen Shot 2020-04-06 at 13 03 23" src="https://user-images.githubusercontent.com/27777263/78579235-014ab980-7807-11ea-9127-b32e8b05bf98.png">
