### ISSUE TITLE
 Shelf title

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#248]
**Describe the bug**
I removed the title from the shelf and instead of coming empty came the name of the component

**To Reproduce**
Leave the title of empty shelf in the code and enter the home store

```json
    "shelf#colecao-2": {
        "blocks": ["product-summary.shelf"],
        "props": {
            "blockClass": "shelf_colecao_2",
            "orderBy": "OrderByTopSaleDESC",
            "paginationDotsVisibility": "desktopOnly",
            "skusFilter": "FIRST_AVAILABLE",
            "productList": {
                "maxItems": 10,
                "itemsPerPage": 4,
                "minItemsPerPage": 1,
                "scroll": "BY_PAGE",
                "arrows": true,
                // "titleText": "Selecionados del mes",
                // "displayBuyButton": "displayButtonOnHover",
                "isfullModeStyle": true
            }
        }
    },
```

**Screenshots**
![shelf](https://user-images.githubusercontent.com/4852136/77671276-1d786c00-6f66-11ea-9a60-e8a2a3fa0033.PNG)

**Additional context**
workspace :  https://store2--fensacl.myvtex.com/

**Comment by klzns** [comment]
I opened the workspace and it's not showing anymore.

**Comment by alextalha** [comment]
for me it continues. something needs to be updated?

**Comment by klzns** [comment]
oh, sorry, I saw the first shelf! It's happening here too

**Comment by klzns** [comment]
I don't know what happened, but can you try removing the content of this field in the site-editor?
![image](https://user-images.githubusercontent.com/284515/77673375-d770d780-6f68-11ea-906d-e5b94c50d7c1.png)

**Comment by alextalha** [comment]
ok @klzns

**Comment by alextalha** [comment]
@klzns  

if i edit through the page builder i can no longer use the project to change the text?
I added the text field again with a message and it didn't appear

does this also apply to the images in the slider layout?

**Comment by klzns** [comment]
Yes, the user settings always wins.

But since those changes we made were only made in a workspace you can reset the workspace or create a new workspace to have the user settings clean to get the config from your blocks
