### ISSUE TITLE
 Slider layout using rich text

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#250]
**What are you trying to accomplish? Please describe.**  

Is there a possibility to be able to use the slider-layout with text instead of image? I tried to use it but instead of bringing it one by one I brought it all at once

I would like something similar to what can be seen on tipbar on this site
 
https://www.tiendafensa.cl/

**Comment by victorhmp** [comment]
Hi @alextalha !
I should already work, this might be a bug, but I'm going to need a bit more information regarding your test. What did you try?

**Comment by victorhmp** [comment]
Hi @alextalha ! I've just coded a simple test and could achieve what I think you want:

```json
"slider-layout#text-test": {
    "props": {
      "itemsPerPage": {
        "desktop": 1,
        "tablet": 1,
        "phone": 1
      },
      "infinite": true,
      "showNavigationArrows": "desktopOnly",
      "blockClass": "carousel"
    },
    "children": ["rich-text#1", "rich-text#2", "rich-text#3"]
  },

  "rich-text#1": {
    "props": {
      "text": "Test1"
    }
  },
  "rich-text#2": {
    "props": {
      "text": "Test2"
    }
  },
  "rich-text#3": {
    "props": {
      "text": "Test3"
    }
  },
```

This bit of code gave me this:


![Mar-26-2020 16-27-34](https://user-images.githubusercontent.com/27777263/77688365-bfa44e00-6f7e-11ea-9a90-1f0725de0fc5.gif)

**Comment by alextalha** [comment]
In fact, he was doing something wrong. maybe some css was changing or behaving
