### ISSUE TITLE
 How to enable pwa for a workspace?

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#251]
**What are you trying to accomplish? Please describe.**  
I followed the steps of this article in the documentation, however in the cms I did not display the option

**What have you tried so far?**  

Follow the steps
of this tutorial and I didn't see the option in the admin of my account
https://vtex.io/docs/recipes/store/enabling-the-stores-pwa-notice

**Additional info**  

![image](https://user-images.githubusercontent.com/4852136/77774404-c5a33900-7029-11ea-8c67-5e34d5857a79.png)

| Account | Workspace |
|---|---|
|`fensacl`|`store2`|

**Comment by victorhmp** [comment]
Hi @alextalha !
We're sorry about that, but this recipe is outdated. This "Store" button should not be visible anymore.
However, you can still find these configuration options here:

![Screen Shot 2020-04-17 at 14 29 31](https://user-images.githubusercontent.com/27777263/79596996-ddfdf500-80b7-11ea-9821-94a9c439bb5c.png)

The "Store" button was moved into the Admin sidebar. Thanks for pointing this out! We'll update the documentation :)

**Comment by victorhmp** [comment]
The docs should be fine now: https://vtex.io/docs/recipes/store/enabling-the-stores-pwa-notice/
Thanks again! 😄
