### ISSUE TITLE
SKU-Selector dropdown ordination bug

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#252]
**Describe the bug**
The Sku items of the Sku-Selector component are being displayed in alphabetical order, where the right would be in order of registration in the Admin, as was the case with the CMS.

**To Reproduce**
1. Go to "https://tackoftheday.myvtex.com/";
2. Choose the "Rider" option from the header menu (https://flic.kr/p/2iJd682);
3. Choose the "Rider Apparel" option in the navigation filter on the left (https://flic.kr/p/2iJd68h);
4. Choose the following product as an example "Irideon Kid's Cordova Knee Patch Tights - Cayenne" (https://flic.kr/p/2iJd68N);
5. You can see that the items are sorted alphabetically (https://flic.kr/p/2iJfPb9);
6. The correct thing would be to pull in order of registration (https://flic.kr/p/2iJhzHV).

**Expected behavior**
I believe that the correct thing would be to show by the order of registration elaborated in the VTEX admin.

**Desktop environment:**
-   OS: [Windows 7]
-   Browser [Google Chrome]
-   Version [80.0.3987.149]

**Additional context**
Our client Tack Of The Day (https://tackoftheday.myvtex.com/) registered the items in the correct order by the admin, but the site appears in alphabetical order.

Admin Screenshot:

![order-1](https://user-images.githubusercontent.com/45877287/77783368-80860380-7037-11ea-8972-3b1102e06cb1.png)

VTEX IO Screenshot:

![order-2](https://user-images.githubusercontent.com/45877287/77783432-9c89a500-7037-11ea-802d-7d9de41fd4e9.png)

CMS Enviroment (vtexcommercestable) Screenshot:

![order-commerce-stable](https://user-images.githubusercontent.com/45877287/77783357-7bc14f80-7037-11ea-9044-0108b427357f.png)

**Comment by iaronaraujo** [comment]
Hi @luizgpriolli  ! Thank you for your report! I've investigated this issue and the data is coming on alphabetical order from the API. Have you reindexed the products after you reordered the variations in the catalog?

**Comment by luizgpriolli** [comment]
Hey @iaronaraujo reindexing the product did work. 

I'm gonna proceed with a full catalog reindexation.
Thank you very much for your support!
