### ISSUE TITLE
Minicartv2 doesn't work with product-summary-buy-button

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#258]
**Describe the bug**
When building the product summary in search.json, I used product-summary-buy-button for the product list. This button doesn't update the minicart.

**To Reproduce**
Use the store theme, change the product-summary layout and include "product-summary-buy-button" as a child.

**Expected behavior**
Update the minicart once the "add to cart" button is pressed in the category page

**Comment by klzns** [comment]
Can you confirm which minicart block is defined in your theme? 

`minicart.v2`or just `minicart`

**Comment by klzns** [comment]
It should be using the `minicart.v2`. In this case you should use the [Add To Cart Button ](https://vtex.io/docs/components/all/vtex.add-to-cart-button@0.8.1/)

![image](https://user-images.githubusercontent.com/284515/78039387-72d8c280-7344-11ea-8dae-18879ba02bfc.png)

https://vtex.io/docs/components/product/vtex.minicart@2.45.0

**Comment by doruradu** [comment]
Hi! I can confirm that we're using minicart 2.x and the minicart is not working when using a produc-summary-buy-button. Ok, we can update the shelf and make it use the add-to-cart-button, but shouldn't all buy buttons work with the minicart?
