### ISSUE TITLE
Shelf without carrousel

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#259]
**What are you trying to accomplish? Please describe.**  

It is possible to assemble a shelf without being a carousel. and how would it be to do?

Example in screenshot
![image](https://user-images.githubusercontent.com/4852136/78087676-31720280-7398-11ea-8215-e49003e86d23.png)

**Comment by klzns** [comment]
For that you will need to use the `search-result-layout.customQuery`

You can read how to use it here:
https://vtex.io/docs/components/search/vtex.search-result

**Comment by alextalha** [comment]
from the documentation the model comes very similar to the search page. however I would just like the products to be returned. could you show an example?

**Comment by victorhmp** [comment]
Hi @alextalha !
Yes, that's easy to do using `search-result-layout.customQuery`, since you have full control over the rendered layout. Something like this should do it:

```json
"search-result-layout.desktop": {
    "children": ["flex-layout.row#result"],
    "props": {
      "pagination": "show-more",
      "preventRouteChange": true,
      "mobileLayout": {
        "mode1": "small",
        "mode2": "normal"
      }
    }
  },
"flex-layout.row#result": {
    "children": ["flex-layout.col#content"],
    "props": {
      "preventHorizontalStretch": true,
      "fullWidth": true
    }
  },
"flex-layout.col#content": {
    "children": ["flex-layout.row#products"],
    "props": {
      "width": "grow",
      "preventVerticalStretch": true
    }
  },
"flex-layout.row#products": {
    "children": ["search-content"]
  },
```
