### ISSUE TITLE
Add support for positioning product images thumbnails to the bottom

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#26]
Former issue: [#359](https://github.com/vtex-apps/store-components/issues/359)

**Describe the solution you'd like**
Add support for positioning product images thumbnails to the bottom of the main image;

**Describe alternatives you've considered**
Alternatives are to extend the `product-images`;

**Comment by klzns** [comment]
@giovanapereira opened this PR:
https://github.com/vtex-apps/store-components/pull/498

It still need some fixes before we merge. Help is welcome here

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/store-components/pull/542
