### ISSUE TITLE
Change the first level links from category-menu app

### ISSUE THREAD

**Issue by doruradu** [vtex-apps/store-discussion#260]
**What are you trying to accomplish? Please describe.**  
I'm trying to change the font properties on the department link from the category-menu app.

**What have you tried so far?**  
Set properties with !important on the parent

| Account | Workspace |
|---|---|
|`vetro`|`develop`|

**Comment by klzns** [comment]
Hi @doruradu we don't encourage the usage of category-menu. A better option would be to use the vtex.menu component.

You can read how to use it here: https://vtex.io/docs/components/navigation/vtex.menu

**Comment by doruradu** [comment]
Hi @klzns ! Thanks for the answer. I don't think that "vtex.menu" can be called a "better option" :)) The client has over 120 categories and building that thing with one menu.item at a time would be suicide. 
+ A menu update will be necessary for each category change.

The category-menu app gets all the cats dynamically from the admin, so it's definitely a better choice in this case. Any other options for building the menu automatically ? I'm trying to achive this:

<img width="725" alt="Screenshot 2020-04-03 at 14 38 27" src="https://user-images.githubusercontent.com/42587916/78380761-0e846000-75dd-11ea-83ff-5f1f904bfa2c.png">

**Comment by klzns** [comment]
Hey @doruradu, it should now be possible to customize the first level links of category-menu. I just [published a new version with new CSS Handles](https://github.com/vtex-apps/category-menu/pull/88).

Btw, our menu creation has some flaws that might prevent you from achieving the desired layout, which is kind of a "mega menu". 

Today we have two options when creating a menu:
- Render all menu elements automatically using category-menu with no possibility of adding new links or customizing it's submenu content (like mega menu)
- Use menu and add all menu items manually. This case you have full control over the layout, making it possible to create mega menus.

We understand those limitations and we are addressing them developing a new menu solution that have the benefits of both. You can read more about our proposed solutions in [this RFC](https://github.com/vtex-apps/rfcs/blob/master/text/0001-menu-navigation.md). We are in the stage of development of this solution, but I can't assure you a deadline.

**Comment by doruradu** [comment]
Hi @klzns! Sorry I didn't reply sooner, I must have missed the notification. I'll try a combination of menu-item and category-menu, see what happens. Thanks for answer & help!
