### ISSUE TITLE
VTEX Course Hub not working

### ISSUE THREAD

**Issue by fabiowood** [vtex-apps/store-discussion#261]
**Description:**

When carrying out the ** VTEX Training Store-Framework **, in ** step 4 (Hello World) **, I cannot proceed to the next step, as the VTEX Course Hub indicates that I did not fulfill the assigned task. However, the task is correct, exactly as performed by the instructor himself in a step-by-step video.

**Steps to reproduce the behavior:**

I perform all stages of the course, from items 1 to 3, in the exact sequence indicated.
In step 4, I develop the code in the home.jsonc file and, when committing the task via VSCode and pushing to the branch determined in the course (helloworld), I get the standard message from the VTEX Course Hub, that something is wrong.

**Expected behavior**

The expected result should be the approval of the code developed by the VTEX Course Hub.

**Desktop environment:**

**Account:** MarinBrasil
**Workspace:** vtexiofabio

**Code:**

`{
  "store.home": {
    "blocks": [
      "rich-text"
    ]
  },
  "rich-text": {
    "props": {
      "text": "**Hello, World!**",
      "textPosition": "RIGHT"
    }
  }
}`

**My GitHub Repository:**

https://github.com/fabiowood/store-framework

**Comment by lucis** [comment]
Hey, @fabiowood, what's up?

As described on the **Course Functioning** step, our course platform **doesn't support pull requests!** 😢 

![image](https://user-images.githubusercontent.com/18706156/78260391-4c499180-74d4-11ea-93b5-d20ae40a2d68.png)

I've seen that you've opened [this PR](https://github.com/fabiowood/store-framework/pull/5), which makes our correction algorithm fail. Unfortunately, there's no way to fix or revert it. You have to:

1. Delete your _fabiowood/store-framework_ repository
2. Start the course again
3. Refrain from open other issues or PR's (under the hood, every PR is also an issue)

**Why does it fail?** 🤔 

The Github Learning Lab framework identifies the step you're on based on **the issue id**. For example, it maps the **Hello, world!** step with **issue 3**, and we use it to correct your solution. When you (or anyone) creates an issue or a PR on your repository, we lost track of it.
