### ISSUE TITLE
Info card children

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#262]
Is it possible to put a child to info-card, specifically that it is rich-text ?, since I have tried it and could not make it possible

**Comment by klzns** [comment]
Can you give an example of what you are trying to achieve?

**Comment by jorgerubik** [comment]
yes, this is my code so far:
{
  "store.home": {
    "blocks": [
      /* You can make references to blocks defined in other files.
       * For example, `flex-layout.row#deals` is defined in the `deals.json` file. */
      "stack-layout#home"
    ]
  },

  "stack-layout#home":{
    "children":["flex-layout.row#fondo", "flex-layout.row#texto"],
    "props":{
      "className":"mainrow"
    }
  },
  "flex-layout.row#fondo":{
    "children":["info-card#home"]
  },
  "flex-layout.row#texto":{
    "children":["rich-text#home"]
  },
  "info-card#home": {
    "props": {
      "id": "info-card-home",
      "isFullModeStyle": true,
      "imageUrl": "https://placehold.it/1920x1080",
      //"headline": "<span class='text-black'>Busca la tienda con</span><br>Productos Royal Canin",
     // "subhead": "más cercana",
      //"callToActionText": "DISCOVER",
      "callToActionUrl": "/sale/d",
      "blockClass": "info-card-home",
      "textPosition": "center",
      "textAlignment": "center",
      "height": 720,
      "zIndexOffset":1
    }
  },
  "rich-text#home":{
      "props": {
        "textAlignment": "CENTER",
        "textPosition": "CENTER",
        "text": "Visit our [help](https://help.vtex.com/en/faq/what-is-vtex-io) section.\n*Be Bold!*\n**This is italic**",
        "textColor": "c-on-emphasis",
        "font": "t-heading-5",
        "zIndexOffset":2
      }
  }

}

///
what I'm trying to achieve is to have a background image, with 3 texts centered vertically and horizontally to the image along with an input text and a button

**Comment by klzns** [comment]
You can achieve that using [stack-layout](https://vtex.io/docs/apps/layout-blocks/vtex.stack-layout@0.1.0/)

Example:
```jsonc
{
  "stack-layout#example": {
    "children": [
      "image#background",
      "flex-layout.row#text"
    ]
  },
  "image#background": {
    "props": {
      "src": "https://placehold.it/500x500"
    }
  },
  "flex-layout.row#text": {
    "children": [
      "flex-layout.col#text"
    ]
  },
  "flex-layout.col#text": {
    "children": [
      "rich-text#line",
      "rich-text#line",
      "rich-text#line"
    ]
  },
  "rich-text#line": {
    "props": {
      "text": "Hello world"
    }
  }
}
```
Result:
![image](https://user-images.githubusercontent.com/284515/78822174-00ee2200-79b1-11ea-8979-8cfded81c227.png)

**Comment by jorgerubik** [comment]
Thank you!
I have got it. I know it may not be part of this doubt, but they know how I can add products from the vtex admin to a workspace, since I can't see products in a search-content

**Comment by victorhmp** [comment]
Hi @jorgerubik !
I don't think I understand what you're asking... could you clarify on what you mean?
