### ISSUE TITLE
 menu opacity similar to minicart

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#263]
**What are you trying to accomplish? Please describe.**  
I wonder if it is possible to maintain opacity between the elements in order to have that result

**Additional info**  

![image](https://user-images.githubusercontent.com/4852136/78571539-b035c800-77fc-11ea-975a-7d72a5fd0f3d.png)

**Comment by klzns** [comment]
@alextalha I don't get it, can you clarify which elements are you changing opacity and when?

**Comment by alextalha** [comment]
@klzns 

I would like to know if it is possible to add a div as a header container so when I open a submenu I can add an opacity to the rest of the page, as shown in the image above
