### ISSUE TITLE
Search-result price range filter not being applied

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#266]
**Describe the bug**
The price range filter is not being correctly applied to the search result.

**To Reproduce**
1. Go to https://tackoftheday.myvtex.com/home-and-gifts
2. Select some prices on price-range;
3. The content shown does not match the value of the price range. 

**Expected behavior**
The expected behavior is to filter products with the right price according to the range component value.

**Screenshots**
Here's a print with the configuration of the price range in the VTEX Admin o(https://flic.kr/p/2iNfz9i).
Here is a video showing the current behaviour https://nimb.ws/Tt48u0

**Additional context**
We are currently using filter-navigator.v3 in version 3.54.0 of the App search-result.

**Comment by LucasCastroAcctGlobal** [comment]
@klzns as we talked on last Office-hours meeting, here's the link where you can reproduce the bug: https://www.tackoftheday.com/home-or-gifts

**Comment by LucasCastroAcctGlobal** [comment]
@klzns we had talked about this problem in the stores' price range for a while. It was at an Office-Hours meeting.

One of its developers asked us for an example in a store. As seen in the previous comment to this, I passed an example for testing but nothing was done.

Here is a new workspace link: https://categorias--mundopet.myvtex.com/cao/alimentos

Could you correct it, please?

**Comment by klzns** [comment]
Hi @LucasCastroAcctGlobal the price range only works in vtex.search-resolver@1.x. 

We don't intend to make it work in vtex.search-resolver@0.x, it's not an easy fix, it's an issue with the Search API. 

Price range though works in vtex.search-resolver@1.x and you can migrate the store to use it.
Docs: https://vtex.io/docs/app/vtex.search
