### ISSUE TITLE
CategoryTree condition-layout intermittent behaviour

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#268]
**Describe the bug**
In the "condition-layout" app, the "categoryTree" option is not working as it should.

**To Reproduce**
1. Go to 'https://condition--tackoftheday.myvtex.com/barn-and-arena-supplies' (https://flic.kr/p/2iPZ32X);
2. The following code has been implemented (https://flic.kr/p/2iPZ33P);
3. Choose any product on the page (https://flic.kr/p/2iPXmNs);
4. The block configured in the condition-layout is not displayed (https://flic.kr/p/2iPZ2ZH);
5. Click on the breadcrumb option to return to the department page (https://flic.kr/p/2iPZ2Yq);
6. Select the previously chosen product again;
7. See that now, with the same product, the block inside the condition-layout appears (https://flic.kr/p/2iPUC6Q);

**Expected behavior**
The expected behavior is that the block determined in the condition-layout appears right at the first access to the product page, not the second.

**Screenshots**
Here is a video showing the inappropriate behavior (https://cl.ly/b58f7ee235f8).

**Additional context**
Here is the workspace where we are performing the tests: https://condition--tackoftheday.myvtex.com.

**Comment by klzns** [comment]
This PR will fix this: https://github.com/vtex-apps/condition-layout/pull/7

**Comment by kaisermann** [comment]
Fixed 🎉
