### ISSUE TITLE
Title tag for multiples languages and bindings

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#269]
**What are you trying to accomplish? Please describe.**  
Currently with the new Binding feature attached with the locale-switcher app for automatic translations I found no way to automatically translate te store's title or set it manually on admin panel. How could this content be updated by the client?

**What have you tried so far?**  
I've tried changing the store's biding from https://powerplanet.myvtex.com/?__bindingAddress=www.powerplanetonline.com/es to https://powerplanet.myvtex.com/?__bindingAddress=www.powerplanetonline.com/pt (which automatically translates it) 
I also tried manually changing the language option with the locale-switcher on header: https://nimb.ws/jwdoU7

**Additional info**  
Admin store page: https://powerplanet.myvtex.com/admin/cms/store

**Comment by Klynger** [comment]
Hi @luizgpriolli , this is currently not possible, we will working on it
