### ISSUE TITLE
Generic URL component

### ISSUE THREAD

**Issue by tomymehdi** [vtex-apps/store-discussion#27]
Hello VTEX-IO Team! How are you? 

We have been working on a component that fetches data and list branches. We will use it on many of our stores. Here it is:

[branches generic.zip](https://github.com/vtex-apps/store-discussion/files/3340887/branches.generic.zip)

We tried many ways to send parameters from the react component `branches/react/branches.tsx` to the constructor of urlclient (`branches/node/clients/urlclient/index.ts`) called on  `branches/node/resolvers/getJsonResolver.ts`.

To be specific here:
`export const getJsonResolver = (_a: any, _variables: any, { clients: { urlclient } }: Context) => {...`

Because of this we had to use a static call `HttpClient.forExternal` (`branches/node/clients/urlclient/index.ts`) and we know this won't take all the advantages of the `ExternalClient` functions.

The question is:
¿How can we send a parameter to the constructor of the `urlclient` on the the `getJsonResolver`?
¿Is there any bestpractice we are missing?

Thank you in advance VTEX-IO Team! :D:D

**Comment by klzns** [comment]
Why do you need to set those variables in the constructor? I guess you need to change the base url, right?

**Comment by tomymehdi** [comment]
Yes, we just realized we can use the context.account and generate new domains that point to the subdomain account name

**Comment by klzns** [comment]
Good to hear! I'm closing the issue for now
