### ISSUE TITLE
Problems to install colossus 2.x

### ISSUE THREAD

**Issue by pradilla** [vtex-apps/store-discussion#270]
**Describe the bug**
I am working on several accounts to test VTEX IO migrations.  I have noticed that accounts that have null LV dont allow installation of colossus on workspaces.  But accounts that do have a filled in LV-123456 allow this install.
![image](https://user-images.githubusercontent.com/31910293/79470813-76687c80-7fc7-11ea-8cbf-e3c83375545c.png)

Let me know if you can add LVs to these accounts to figure if this helps.

diageocol
bellapiel
mdlzcol

**To Reproduce**
Try and install colossus vtex.colossus-legacy-proxy@2.x on any workspace NOT MASTER pls LIVE Accts on any of these.

diageocol
bellapiel
mdlzcol

error
![image](https://user-images.githubusercontent.com/31910293/79470731-605abc00-7fc7-11ea-81b0-3c7bc5ba44d2.png)

Thnks
Andres

**Comment by regis-samurai** [comment]
The same problem here ... My product page processes cms content instead of vtex io. I think the problem is related to not installing the app colossus@2.x

**Comment by jorgerubik** [comment]
I have the same problem, I could not install the vtex.store-sitemap and vtex.colossus-legacy-proxy@2.x, so the search sends me an error and when reloading it sends me to the cms view
