### ISSUE TITLE
"add-to-cart-button" on shelf is not working well

### ISSUE THREAD

**Issue by alexandreTrino** [vtex-apps/store-discussion#273]
**Description**
The render of this component `add-to-cart-button`, put the element inside of an tag `<a>`. This make conflict with the button function and not add to cart by shelf

**To Reproduce**
Need able to see the minicart.v2

1. Go to any page with a list of products on shelf (ex: category page or Home)
2. Click on buy-button

**Expected behavior**
We expect the item add to minicart, but this not work

<img width="992" alt="Captura de Tela 2020-04-22 às 01 28 39" src="https://user-images.githubusercontent.com/14322380/79948028-aafd8d80-8438-11ea-95e8-511100a8883d.png">

**Comment by Klynger** [comment]
Hi @alexandreTrino , when the user wants to add to the cart it stops the event and adds the item to the cart, could you share a workspace?

**Comment by klzns** [comment]
Also keep in mind that the component does not add to the cart if the product has variations, eg, more than one SKU.

**Comment by klzns** [comment]
We implemented a feature in the old buy button to configure this property:
https://github.com/vtex-apps/product-summary/pull/249

Maybe the same could be done to add-to-cart-button

**Comment by alexandreTrino** [comment]
@Klynger 

you can see that here: https://developer--maraga.myvtex.com/ but this happen on all stores i ahve been worked

@klzns all the products not have variations.

what I realized is that the button is being inserted inside a link tag and maybe this is related, because if I manually move the button out of the link and click again, the product is added to the cart

**Comment by Klynger** [comment]
Sorry for the delay, I went to your workspace and everything seems to be working, is this still a problem @alexandreTrino ?

**Comment by alexandreTrino** [comment]
Hello! It was solved!
