### ISSUE TITLE
How change viewBox of svg icons from iconpack

### ISSUE THREAD

**Issue by igorpoubel** [vtex-apps/store-discussion#278]
**What are you trying to accomplish? Please describe.**  
When I try to change the icons inside iconpack, sometimes it's showing in a different size. Screenshot bellow.

**What have you tried so far?**  
Looking at the docs (https://vtex.io/docs/recipes/style/customizing-your-stores-icons/), it recommends to follow the *SVG frament identifiers* (https://css-tricks.com/svg-fragment-identifiers-work/). There, there is an instruction to use the <view /> tag inside the SVG (our iconpack). But it stil not changing anything.

**Additional info**  
How it is showing:
![image](https://user-images.githubusercontent.com/6241622/80498344-fb498380-8941-11ea-9b85-92cdc206bf2e.png)

How should be:
![image](https://user-images.githubusercontent.com/6241622/80498456-1fa56000-8942-11ea-9619-2e0915401623.png)

| Account | Workspace |
|---|---|
|`corebiz`|`igorpoubel`|

**Comment by alexdinca** [comment]
@igorpoubel I'm also trying to figure out the same thing. Have you resolved it?

**Comment by igorpoubel** [comment]
@alexdinca not yet :(
