### ISSUE TITLE
Iframe dynamics

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#281]
hello !, my question is, if it is possible to generate a dynamical iframe through which information can be sent (something from the user, purchase order), this to track the personalized order

**Comment by klzns** [comment]
We have the sandbox block that creates an iframe passing some context to it:
https://vtex.io/docs/components/all/vtex.sandbox@0.4.2/

There are 2 contexts available:
- `sandbox.order` passes the user cart information
- `sandbox.product` passes the current product context

**Comment by klzns** [comment]
Also the purchased order data is passed to the dataLayer, so you may create a Custom Image tag in GTM passing that info:

![image](https://user-images.githubusercontent.com/284515/80638743-4db89c00-8a37-11ea-97cd-89150bd350af.png)

**Comment by klzns** [comment]
The event orderPlaced provide this data to the dataLayer:

https://github.com/vtex-apps/google-tag-manager/blob/master/react/typings/events.d.ts#L150-L184

**Comment by jorgerubik** [comment]
Thanks for the information, with this I can then get the order already paid and be able to connect to the shipping service ?, I was also testing the product and I saw this: window.props.productQuery.product.items., How could I do something like this but for orders, since I tried but without success
