### ISSUE TITLE
Bug order-by  not change

### ISSUE THREAD

**Issue by rebecastilho** [vtex-apps/store-discussion#282]
**Describe the bug**
order-by in the app search-result not change.

**To Reproduce**

1.  https://bugreport--umbro.myvtex.com/admin/cms/site-editor/calcado/chuteira-campo
2. Click on ' Resultado da pesquisa > Order by field'
3. See error

**Expected behavior**
changing the order by field I expected you to change the filter from "Relevância" to "Mais Recentes"

**Comment by iaronaraujo** [comment]
Hello @rebecastilho ! Thank you very much for your report! We have already added this issue to our backlog and we will update this issue once we know more about it!

**Comment by rebecastilho** [comment]
@iaronaraujo do you have a return forecast?
