### ISSUE TITLE
Quickorder error GraphQL

### ISSUE THREAD

**Issue by mroffe** [vtex-apps/store-discussion#283]
**Describe the bug**
When I try to add products in the cart, the console give me an error:
Error: GraphQL error: Variable "$items" got invalid value "43095" at "items[0].id";

**To Reproduce**
1.- Go to /quickorder
2.- Select product from Category and add qty 
2. Click on Adicionar Items
4. See error in console

**Screenshots**
https://monosnap.com/file/nyAFCwGi2by9LBBdLo6AwbzKnhMyN1

**Smartphone environment (please complete the following information, if applicable):**

-   Device: desktop
-   OS: Windows 10
-   Browser Chrome

**Comment by wender** [comment]
Thanks @mroffe for the report, there was some update on a dependency, a few fields had their Types changed, I'll push an update for that today

**Comment by wender** [comment]
@mroffe we've got a new version already with this fix, please "link" again and make sure you've got the `0.7.1`
