### ISSUE TITLE
 Questions in the minicart

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#287]
**What are you trying to accomplish? Please describe.**  

I would like to ask or know if there would be a header with the following topics:
cart icon
title and quantity of products

![image](https://user-images.githubusercontent.com/4852136/81119879-05e7b800-8f02-11ea-866c-b019f6dffb55.png)

In the content, if it is possible to switch from combo to a plus and minus selector

![image](https://user-images.githubusercontent.com/4852136/81120116-6b3ba900-8f02-11ea-9816-27b0cd4096c7.png)

and finally if in the totalizer I can show the number of installments and it would be like the discount coupon and how to do it

![image](https://user-images.githubusercontent.com/4852136/81120249-b2c23500-8f02-11ea-8791-fa7070e6e156.png)

**Comment by victorhmp** [comment]
Hi @alextalha !
Regarding your first question, I don't think there is a way right now, and I don't see us implementing that in the near future.

Regarding your other questions, I suggest you take a look at the following documentation, as pointed out by the Minicart's documentation:

- https://vtex.io/docs/app/vtex.product-list
- https://vtex.io/docs/app/vtex.checkout-summary

These should give you the information you need :)
