### ISSUE TITLE
list-context.image-list Open in a new tab setting not working

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#289]
**Describe the bug**
After defining a Link in the site-editor and selecting the "Open in a new tab" option, the link does not get a `target=blank` property and opens at the same tab.

**To Reproduce**

1. Go to [acctglobal.myvtex.com/admin/cms/site-editor](acctglobal.myvtex.com/admin/cms/site-editor)
2. Click on the main banner, add a link and select the open in a new tab setting ( https://nimb.ws/3mSHG8 )
3. Go to [acctglobal.myvtex.com](acctglobal.myvtex.com)
4. Click on the image

**Expected behavior**
When clicking at the image, the link should open in a new tab.

**Screenshots**
Video showing the current behaviour: https://nimb.ws/0lu92K

**Comment by victorhmp** [comment]
Hi @luizgpriolli !
Thanks for the bug report. Btw, thanks for making it so easy to reproduce as well :)
I'll look into it and implement a proper fix.
