### ISSUE TITLE
Enable customization of "drawer-header" in the Minicart

### ISSUE THREAD

**Issue by igorpoubel** [vtex-apps/store-discussion#292]
**What are you trying to accomplish? Please describe.**  
How can I use Icomoon on my css files? I need to put an icon before the word "Carrinho" on *vtex-minicart-2-x-minicartTitle* class.

**What have you tried so far?**  
Import icomoon css file to minicart.css.

**Additional info**  
![image](https://user-images.githubusercontent.com/6241622/81743842-b7459b00-9478-11ea-8a01-3f97130bd71e.png)

| Account | Workspace |
|---|---|
|`corebiz`|`minicartmob`|

**Comment by klzns** [comment]
Hi! Here is the document explaining how to customize the store icons:
https://vtex.io/docs/recipes/style/customizing-your-stores-icons/

**Comment by igorpoubel** [comment]
@klzns please, read my question.

There is no icon before the word "Carrinho". That is, there is no way to "change" the icon, as the doc suggest.

**Comment by victorhmp** [comment]
Hi @igorpoubel !

Unfortunately, this "header" you're referring to that is shown when a `drawer` block is open cannot be customized in the `minicart.v2` :(

The `drawer` supports custom headers, through the use of the `drawer-header` block (documentation here: https://vtex.io/docs/app/vtex.store-drawer), but this is not exposed by the `minicart.v2`.

We'll add this feature to our backlog and keep this issue open, with a different title, if you don't mind. Once we do implement this feature, we'll link a PR to this issue and it should close.

Sorry for not being able to solve your problem right now, but thanks for the feature request!

**Comment by igorpoubel** [comment]
@victorhmp Hi!

Ok! Thanks! :)
