### ISSUE TITLE
vtex link return error 

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#293]
**What are you trying to accomplish? Please describe.**  
run the vtex link.
`
11:11:01.438 - error: Maximum call stack size exceeded vtex.builder-hub@0.248.1
11:11:01.444 - error: App build failed with message: Maximum call stack size exceeded
`

Is there anything I can be doing to solve this problem?

I tried to create another workspace and the same thing happens

| Account | Workspace |
|---|---|
|`modaoriginal`|`acostamento`|

**Comment by klzns** [comment]
Which version of Toolbelt are you using?

Can you update it to the latest version?

**Comment by alextalha** [comment]
$ vtex --version
vtex/2.100.1 win32-x64 node-v10.13.0

$ vtex update
11:52:49.906 - info: No updates available

**Comment by klzns** [comment]
I could not reproduce. I linked an app successfully. What I did:

```
vtex switch modaoriginal
vtex use brenovtex
vtex link
```

![image](https://user-images.githubusercontent.com/284515/81829211-0939ff80-9511-11ea-9757-1aee4e4a6d3c.png)

Maybe it has something to do with you app. Can you try removing changes recently introduced so you can pin point which file change lead to the issue?

**Comment by alextalha** [comment]
@klzns ,
 
Bingo.
I went back to what I had done in the product and stopped the error.
but why would this code be giving this error?


```json
"flex-layout.row#especifications": {
        "children": ["menu-item#description__product"],
        "props": {
            "blockClass": "especifications"
        }
    },

    "menu-item#description__product": {
        "props": {
            "id": "description__product",
            "type": "custom",
            "iconId": null,
            "highlight": false,
            "blockClass": "description__product",
            "itemProps": {
                "type": "internal",
                //"href": "/clothing/d",
                "noFollow": true,
                "tagTitle": "Descrição do Produto",
                "text": "Descrição do Produto"
            }
        },

        "blocks": ["vtex.menu@2.x:submenu.accordion#description__product"]
    },

    "vtex.menu@2.x:submenu.accordion#description__product": {
        "children": ["vtex.menu@2.x:submenu.accordion#description__product"]
    },

    "vtex.menu@2.x:menu#description__product": {
        "props": {
            "orientation": "vertical"
        },
        "children": ["product-specifications#description__product"]
    },

    "product-specifications#description__product": {
        "props": {
            //"showSpecificationsTab": true,
            // "showSpecificationsTab" : true,
            "visibleSpecifications": ["SpecialContent"]
        }
    },
```

**Comment by klzns** [comment]
I think because that's a loop. It is self referencing

```
    "vtex.menu@2.x:submenu.accordion#description__product": {
        "children": ["vtex.menu@2.x:submenu.accordion#description__product"]
    },
```

**Comment by alextalha** [comment]
I think that's it. this would be an infinite loop? 
json```
 "vtex.menu@2.x:submenu.accordion#description__product": {
        "children": ["vtex.menu@2.x:submenu.accordion#description__product"]
    },

```

**Comment by alextalha** [comment]
> I think because that's a loop. It is self referencing
> 
> ```
>     "vtex.menu@2.x:submenu.accordion#description__product": {
>         "children": ["vtex.menu@2.x:submenu.accordion#description__product"]
>     },
> ```


we think the same thing

thx for support @klzns

**Comment by klzns** [comment]
hahaha you're welcome!
