### ISSUE TITLE
Clear Minicart quantity when a order completed 

### ISSUE THREAD

**Issue by H1berto** [vtex-apps/store-discussion#296]
**Describe the bug**
The error occurs when, when making the purchase, at the end of the process, the minicart remains with the same quantity of products and is not updated after the purchase is completed.

**To Reproduce**

1. Go to https://extrafarma.myvtex.com
2. Add any product to cart
3. Go to checkout
4. Complete the order
5. You will be redirected to Orderplaced
6. Check the minicart quantity

**Expected behavior**
The minicart quantity it won't be empty

**Screenshots**
![Bug image 1](https://user-images.githubusercontent.com/14927925/81854379-3a77f700-9534-11ea-8be8-64793d0650fd.png)
![Bug image 2](https://user-images.githubusercontent.com/14927925/81854391-3ea41480-9534-11ea-858f-85c9a2302585.png)

**Desktop environment (please complete the following information, if applicable):**

**Smartphone environment (please complete the following information, if applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**

**Comment by lucasayb** [comment]
I saw this issue also in https://miriadeit.myvtex.com

**Comment by alexdinca** [comment]
Also in https://veranda.myvtex.com/

**Comment by regis-samurai** [comment]
It's happening here too https://pentruanimale.myvtex.com/

**Comment by klzns** [comment]
We have a workaround in place:
https://vtex.io/docs/recipes/store-management/enabling-order-form-optimization/

We added to a backlog to work on a more robust solution to this issue.
