### ISSUE TITLE
Add "Buy Together" app or component

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#3]
## Expected Behavior
Former Issue: [#373](https://github.com/vtex-apps/store-components/issues/373);
We would like to have a component or app similar to `<vtex.cmc:BuyTogether/>`;
We understand that [Product Kit](https://github.com/vtex-apps/product-kit) may serve as an alternative in some cases but no all of them;

## Current Behavior
We do not have a app/component compatible with `<vtex.cmc:BuyTogether/>`;

## Screenshots and Examples
![image](https://user-images.githubusercontent.com/1207017/59791339-3ef64a00-92a8-11e9-9e19-51cd981b1290.png)

**Comment by klzns** [comment]
Can you describe when product-kit doesn't fit all the cases?

**Comment by juliomoreira** [comment]
Sorry @klzns.

To summarize:

- The [Product Kit](https://github.com/vtex-apps/product-kit) is tied to benefits as mentioned in [#18](https://github.com/vtex-apps/product-kit/issues/18) althought our problem doesn't relate to `kits`;
- We need a simpler way to relate the products like how it's done in CMS using `<vtex.cmc:BuyTogether/>` and the `Show Together` in the SKU admin page as in this example: 
![Screenshot from 2019-06-19 17-31-58](https://user-images.githubusercontent.com/1207017/59798664-0ca11880-92b9-11e9-9e11-40cbeabbc2b9.png)
- We need more control over the layout that is rendered by default;

Please let me know if it's clear now.

Thanks,
