### ISSUE TITLE
Add support for a custom preview component or interface

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#30]
**Describe the solution you'd like**
We would like to specify a custom preview component or interface to override the `type` property of `preview` in some cases.

**Describe alternatives you've considered**
The alternative we have today is to extend the interface with a new component and implement the preview ourselves but it's not practical if you just want to customize the preview itself.

**Additional context**
Think of an animated logo loader or a "progress bar".

**Comment by klzns** [comment]
You are talking about those gray boxes, right?

**Comment by fpsman** [comment]
Yes Breno.

Nowadays you have this options " `box` `transparent` `grid` `text` `spinner`"

But we'd like to have a custom solution like the logo of the customer or a custom spinner.
