### ISSUE TITLE
Sku-selector in view product detail

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#303]
In the product detail view the sku-selector is not displayed and I already have it declared in the code, do you know why?

**Comment by Klynger** [comment]
Hi,\ @jorgerubik could you provide a running workspace that we can edit?

**Comment by jorgerubik** [comment]
workspace: https://farmacia1--multifarmaciasmx.myvtex.com/
Here you do not have the latest version, but if you already had the declared sku-selector

**Comment by Klynger** [comment]
I don't know what is going on exactly, the product page is not in IO. Could you help me here @klzns ?

**Comment by jorgerubik** [comment]
The problem has just been solved, the sku field for the categories needed to be configured in the admin, thanks for your help.
