### ISSUE TITLE
 Inconsistency menu on desktop.

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#304]
**Describe the bug**
When hovering the mouse over the menu when moving the mouse out of focus the menu does not close or takes a long time to close

**To Reproduce**

hover over the masculino and feminino category and then exit.
At some point it will generate inconsistency

account
tfbsmy

workspace
acostamento

![bug2](https://user-images.githubusercontent.com/4852136/82829742-62e3e780-9e8a-11ea-8160-31229757278e.png)
![masculino](https://user-images.githubusercontent.com/4852136/82829747-64151480-9e8a-11ea-9654-7f908ca4ba3f.png)

**Comment by pedrohenriqueoliveira** [comment]
Hi, @alextalha. We've just put that issue in our backlog, ok?

Regards,

Pedro

**Comment by pedrohenriqueoliveira** [comment]
Hello, @alextalha. The team just solved the problem in the last sprint.

Regards,

Pedro

**Comment by alextalha** [comment]
thanks
