### ISSUE TITLE
Slider-layout items page breakpoints additions request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#305]
**Is your feature request related to a problem? Please describe.**
Currently while using the slider-layout `items per page` prop  we can only set three different breakpoints (desktop, tablet and mobile) which means that shelfs that may look good at 1500px with 6 items ( https://nimb.ws/m2krWz ) will look crowded in 1025px. ( https://nimb.ws/SM0YQD ).

**Describe the solution you'd like**
The addition of more than these breakpoints mentioned to the items per page pro for each device would fix this issue. I do understand that this may happen due to server-side rendering using `RUNTIME` `hints`, but I still believe that having this flexibility would be of great use. This client-side rendering with customizable breakpoints is done by sliders such as React Slick.

**Describe alternatives you've considered**
We considered using multiples of the same block and hiding it with CSS media queries, but this would lead to a very troublesome CMS.

**Additional context**
Component link: https://vtex.io/docs/apps/layout-blocks/vtex.slider-layout@0.11.0/
Workspace used: https://itemsperpage--acctglobal.myvtex.com/ 
https://react-slick.neostack.com/docs/get-started

**Comment by klzns** [comment]
Fixed on https://github.com/vtex-apps/slider-layout/pull/37
