### ISSUE TITLE
Style sheet 

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#308]
Hello, I have come to make an inquiry, as seen in the image that I present, my style sheet is the second one. But the first one has those styles and it is not allowing me to change the height to 400px, do you know where or how to make me not take the first style sheet?
![Captura de Pantalla 2020-05-27 a la(s) 11 39 22](https://user-images.githubusercontent.com/3172828/83048968-0f9ba180-a010-11ea-88b3-a974da3d03a2.png)

**Comment by klzns** [comment]
I think there are two themes installed in your store. You should uninstall the vtex.store-theme from it.

**Comment by jorgerubik** [comment]
Ok and how could I do that and not affect the other theme?

**Comment by klzns** [comment]
Sorry, I don't get it. What do you mean?

Having two themes installed might lead to weird behaviours in the store, like: blocks overriding, styles overriding (like the one you pointed out), etc.

If the store is in production, I would recommend creating a production workspace, uninstall the vtex.store-theme and test it. It might have a chance that the store was relying on some block or customization of the vtex.store-theme that you will need to move to the multifarmaciasmx.store-theme.
