### ISSUE TITLE
Add CSS class namespaces to Filter Navigator direct children

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#31]
**Describe the solution you'd like**
We need to be able to sort the blocks inside filter navigator in a different order.
We believe that adding CSS namespace classes would be ideal, something like:
```css
. filtersItem {}
. filtersItem--header {}
. filtersItem--selected {}
. filtersItem--department {}
. filtersItem--filter-slug {}
```
**Describe alternatives you've considered**
The only option right now is to use `nth-child` which we would like to avoid and doesn't cover all the cases;

**Additional context**
![issue-cotidiana](https://user-images.githubusercontent.com/1207017/60671978-b1d7f700-9e4a-11e9-9cfa-48554a6f7fc9.png)

**Comment by saviofelixmuniz** [comment]
@all-contributors please add @juliomoreira  for feature-requesting

**Comment by saviofelixmuniz** [comment]
@all-contributors please add @juliomoreira for ideas

**Comment by klzns** [comment]
Fixed the issue related of adding CSS classes, not about sorting the elements.
