### ISSUE TITLE
PWA Push Notification

### ISSUE THREAD

**Issue by mroffe** [vtex-apps/store-discussion#312]
**What are you trying to accomplish? Please describe.**  
Hello everyone!
I want to know how to send push notifications to users who have the pwa app installed. I didn't find anything in the documentation.

**What have you tried so far?**  
I install de pwa and can´t find how send notifications from admin panel.

**Comment by Klynger** [comment]
Hi @mroffe , thank you for your issue! Currently, this is not possible on our platform, but we understand that this feature is important and there are other people looking for it as well. So we are setting priority to this and trying to measure how much effort we need to put to have this feature

**Comment by cristianmdev** [comment]
Estoy tiene una solución al día de hoy?
