### ISSUE TITLE
Hide specific filter in department

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#317]
**Describe the bug**

In the application I'm working on, I need to hide Department, Brand.
He had succeeded, but both appeared again. it's like the code has been ignored

**To Reproduce**

When entering the department screen both filters should not appear (brand, department)

**Screenshots**

![image](https://user-images.githubusercontent.com/4852136/83769698-9119b200-a656-11ea-80ae-57eb95928694.png)

![image](https://user-images.githubusercontent.com/4852136/83769792-a8f13600-a656-11ea-952e-b4981bd3d3a5.png)

Account : tfbsmy
Workspace: teste

**Comment by klzns** [comment]
Can you try this?
```json
"hiddenFacets": {
  "brands": false,
  "categories": false
}
```

https://vtex.io/docs/components/all/vtex.search-result@3.53.1/
![image](https://user-images.githubusercontent.com/284515/85784331-8ce52f80-b6fe-11ea-88f1-a5a23bd1e602.png)

**Comment by IvanLopezLuna** [comment]
Hi @klzns!

I tried your suggestion but it doesn't work either.

![IMG-20200628-WA0005](https://user-images.githubusercontent.com/23274114/85961735-16506800-b972-11ea-8b1c-ab684e288502.jpg)

**Comment by juliomoreira** [comment]
Hi @IvanLopezLuna according to https://github.com/vtex-apps/search-result/blob/master/react/constants/propTypes.js#L143-L147 and https://github.com/vtex-apps/search-result/blob/master/react/index.js#L240-L256 the `hiddenFilters` property of `hiddenFacets` is in fact an Array of objects but the documentation is a bit misleading as I'm looking at it.

Can you try to specify the `hiddenFilters` as an array of objects with the name of the filter in a key named `name` like so: `"hiddenFilters": [{"name": "Estilo"}]` and see if that works.

**Comment by MatheusR42** [comment]
Thanks @juliomoreira , I was with the same problem here
