### ISSUE TITLE
Custom Shelf with a list of product Ids

### ISSUE THREAD

**Issue by pmarignan** [vtex-apps/store-discussion#323]
**What are you trying to accomplish? 
I want to create a app which shows a products list like a shelf layout

**What have you tried so far?**  
I want to take advantage of the shelf app because it has all I need but instead of using a collection or a products category as expected the shelf component I want to use a list of product ids or custom products list. Is that possible?

**Additional info**  
![customShelf](https://user-images.githubusercontent.com/32361926/84908783-300dc780-b0b5-11ea-9325-dbbb78153ade.jpg)

| Account : drimjuguetes
| Workspace | drimtest2

**Comment by klzns** [comment]
Hi @pmarignan, 

That's not possible. The ideal is to create a collection for that, so the results can be cached, and then use the collection id in the shelf params.

If one could list each product id we would have to make N requests for each product which is not desirable.

**Comment by pmarignan** [comment]
Ok thanks Brenan!

But the fact is that I get the the list of product Ids from a cookie and want to show them like a carousel as a shelf component. That's wht I can't use a collection. I know that I need to call n times the request to get product datas but it is the only solution I think. Of course I can define a limit of items to show (8 for example).

So, if I can't use the shelf component maybe is there any easy way to use the CSS style and the JS logic for the carousel and maybe the add cart button component inside my app?

Best regards,
