### ISSUE TITLE
Apply cutom style to login button

### ISSUE THREAD

**Issue by vbelda-ecomm360** [vtex-apps/store-discussion#326]
**Is your feature request related to a problem? Please describe.**
I need to apply a cutom style to the login button in the vtex-login app

**Describe the solution you'd like**
I need a unique class to select this button.
![image](https://user-images.githubusercontent.com/53079383/85034962-f0adac80-b182-11ea-94d4-e70577419f97.png)

**Describe alternatives you've considered**
I have tried to style the button through the vtex.login.css like this:
![image](https://user-images.githubusercontent.com/53079383/85035061-0de27b00-b183-11ea-8beb-455061c54a66.png)
But it's not working

**Comment by klzns** [comment]
Hi @vbelda-ecomm360 

Try this:

```css
.container :global(.vtex-button) {
  padding: 0;
  line-height: 16px;
}
```

https://vtex.io/docs/recipes/style/using-css-handles-for-store-customization/#best-practices

**Comment by vbelda-ecomm360** [comment]
Yes that works, thanks!
