### ISSUE TITLE
Menu accordion "problem" with isOpen props

### ISSUE THREAD

**Issue by EdEsteves** [vtex-apps/store-discussion#328]
Does this component have any applicable configuration via props (json) to start with accordion already open? I'm using props `"isOpen": true,` at `vtex.menu@2.x:submenu.accordion` but the accordion doesn't close even with click event.

**Comment by alextalha** [comment]
@klzns  
about what I talked about accordion at PDP

**Comment by rodrigogsn** [comment]
Hey guys! Any news on that? I stumbled upon the same problem. I noticed that when `"isOpen": true` is on, the menuItem gets the class `--isClosed`. It must be related. 

![image](https://user-images.githubusercontent.com/25557751/107517582-aef7c900-6b8c-11eb-920e-849a3df8eadd.png)

**Comment by victorhmp** [comment]
Hi guys! Pretty sure this is not happening anymore, and https://github.com/vtex-apps/menu/pull/126 introduced a CSS handle that changes according to the menu state also :)
