### ISSUE TITLE
Vtex Link (start proyect)

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#329]
I have a problem, I am part of an agency. When trying to create a workspace it sends me an error and does not allow me to configure it properly, since it stays as Business Edition and it does not allow me to put the vtex.edition-store@2.x. In addition to this error when doing reset. My doubt or question is how as an agency I can do this or if I need help from someone inside vtex for this. Regards!
<img width="648" alt="Captura de Pantalla 2020-06-29 a la(s) 10 17 22" src="https://user-images.githubusercontent.com/3172828/86024356-81418380-b9f2-11ea-958a-79336571642f.png">

**Comment by tiagonapoli** [comment]
I checked the error and was a network timeout, nothing serious apparently. I entered the account and tested resetting the workspace and everything worked. Can you try again?

**Comment by jorgerubik** [comment]
Yes I allowed it, but when trying to configure vtex.edition-store@2.x it gives me an error and the workspace sends an error in the browser. I attach two captures, the one of the restart and where I try to do the vtex edition set vtex.edition-store@2.x

<img width="1063" alt="Captura de Pantalla 2020-06-29 a la(s) 10 36 50" src="https://user-images.githubusercontent.com/3172828/86026084-9b7c6100-b9f4-11ea-9cb4-673c13f58a7e.png">
<img width="1058" alt="Captura de Pantalla 2020-06-29 a la(s) 10 34 43" src="https://user-images.githubusercontent.com/3172828/86026099-a0411500-b9f4-11ea-9e7e-5b9a3aa95dd3.png">

**Comment by tiagonapoli** [comment]
The 403 forbidden means that you don't have access to do this operation in this account

**Comment by jorgerubik** [comment]
Ok, how could I have that access here? Do I need any special permission ?, since right now for development I have owner permissions

**Comment by tiagonapoli** [comment]
I think you'll need the `VTEX IO Developer` access profile. The admin of your account can set it using the `admin page -> account settings -> account management -> users`
The access profiles can be visualized by the account admin on `admin page -> account settings -> account management -> access profiles`

**Comment by jorgerubik** [comment]
Yes, my profile has the Vtex IO permissions (as I show in the screenshot), with those it should be possible, right?
![Captura de Pantalla 2020-06-29 a la(s) 11 05 27](https://user-images.githubusercontent.com/3172828/86029320-a46f3180-b9f8-11ea-8c5c-55d0155c362b.png)

**Comment by Jeymisson** [comment]
This is a weird behaviour about the edition usage. You can only set your edition in master workspace.
This flow looks broken, it is sending you to VTEX account to change configs there.
Because you can't change configs in VTEX's account, you're correctly getting a forbidden message.

**Comment by jorgerubik** [comment]
Yes, try it on the master as well, but the error is the same. I don't know if it is because I don't have a vtex account for being part of an agency, but how could I solve this? Attached view where you run it on master

<img width="1061" alt="Captura de Pantalla 2020-06-29 a la(s) 12 02 19" src="https://user-images.githubusercontent.com/3172828/86034702-bd7be080-ba00-11ea-8469-3833bf14be47.png">

**Comment by tiagonapoli** [comment]
@jorgerubik  Unfortunately for changing editions for now you'll have to open a ticket. If you want I can update it for you

**Comment by jorgerubik** [comment]
Done, yesterday I raised the ticket and in the morning I stay, thank you very much, only now when making a vtex link with the demo store it gives me this error
![flexigtdev--flexigt-error](https://user-images.githubusercontent.com/3172828/86153457-55dc9880-bac7-11ea-9063-c7c7442b4316.png)

**Comment by tiagonapoli** [comment]
That error happens in another account right? the problem about the edition was in the `anaisgt`, the error you sent is in account `flexigt`

**Comment by jorgerubik** [comment]
ohhhh yes yes, sorry. 
This is the one with the naisgt error, but it's just the same, I think that's why I got confused by screenshot
![anaisgtdev--anaisgt-error](https://user-images.githubusercontent.com/3172828/86162849-0b621880-bad5-11ea-82e1-ed9ef8448432.png)

**Comment by tiagonapoli** [comment]
I just checked, you'll have to `vtex install vtex.search-resolver@0.x`

**Comment by jorgerubik** [comment]
Perfect! my demo store is ready, thank you very much

**Comment by pvaldebe** [comment]
Hi!

I have a problem, when wanted to do login in this project https://learn.vtex.com/docs/course-store-performance-step01fold-block-lang-en 

I get error!

You help my please, Regards!


![img](http://imgfz.com/i/Ca1E4Dc.png)
