### ISSUE TITLE
download code

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#332]
Hello!.
Is there a way to download the code from a workspace? Any command to do it?

**Comment by Klynger** [comment]
Code from which app? In which context?

**Comment by alextalha** [comment]
I think I'm referring to the theme installed in a workspace

**Comment by klzns** [comment]
@jorgerubik Is the code lost or something? You can open a ticket to request the code to be retrieved.

**Comment by jorgerubik** [comment]
Ok, is that it was, if for some reason I did not upload my code to github or the like how to recover it if I lost it

**Comment by klzns** [comment]
@jorgerubik if the code is linked we can recover some bits, but not 100%, if the app is published we can recover it completely. 

If that happens feel free to open a ticket so we can recover it for you ✌️

**Comment by jorgerubik** [comment]
Thanks!
