### ISSUE TITLE
How can I remove outline css?

### ISSUE THREAD

**Issue by igorpoubel** [vtex-apps/store-discussion#336]
**What are you trying to accomplish? Please describe.**  
How can I safely and properly remove outline at all?

**What have you tried so far?**  
I know there is an issue([224](https://github.com/vtex-apps/store-discussion/issues/224)) that talk about the color. But it's not enough to me.

**Additional info**  
Maybe instead of have an entry `outlineColor` on style.json, could accept an object `outline` with the props `outlineColor`, `outlineStyle`, `outlineWidth` to make it more flexible.

Like this:
remove: `"outlineColor": "lorem"`

include: `"outline": { "outlineColor": "lorem", "outlineStyle": "lorem", "outlineWidth": "lorem" }`

**Comment by kaisermann** [comment]
Hey @igorpoubel 👋 

Visually removing the outline can lead to accessibility issues. With that said, you can use a `transparent` color.

**Comment by igorpoubel** [comment]
Hi @kaisermann 

Ok. I'm pretty sure that I tried `transparent` color on style.json e it didn't worked. But I moved to another task, so I'll check this again alter.

Thanks!

**Comment by Dracenco** [comment]
HI @kaisermann  @igorpoubel  could you please share the solution that you came with ? I am having the exact same issue. Inside filters container an outline is used on the buttons that have no css handles and therefore cannot be targeted. i have tried passing 

        "outlineColor": {
          "outline-color": "transparent"
        },
        
     inside styles.json but it has no effect. At some point i just went and inserted "outline-color": "transparent" inside most of the objects within json but still no luck.

**Comment by jpesce** [comment]
> i have tried passing
> 
> ```
>     "outlineColor": {
>       "outline-color": "transparent"
>     },
>   ```
>  inside styles.json but it has no effect. At some point i just went and inserted "outline-color": "transparent" inside most of the objects within json but still no luck. 

@Dracenco The correct syntax is
```json
  "outlineColor": <color>,
```
on the root of the `style.json` object
