### ISSUE TITLE
How do I develop my store code in a testing environment?

### ISSUE THREAD

**Issue by lucalves** [vtex-apps/store-discussion#337]
**What are you trying to accomplish? Please describe.**  

Hello everyone, everything good?

In the company I work for, we have implemented vtex in our e-commerce.

I will be responsible for the development part, but I had some doubts about the process and the CMS, they are:

- How do I get the entire source code of the store on my machine?
- How can I work with the production and approval environment at VTEX?
- Where is there a style guide to base myself on creating patterns?
- Can I develop my store's code only via CMS, or is there another way?

Sorry if it is very obvious, but as the VTEX platform is new to me, naturally these questions arose.

**Additional info**  

I am getting to know how the platform works now, I hope to contribute to the open source projects that exist about VTEX.

| Account | Workspace |
|---|---|
|`carajas`|`vtexcommercestable`|

**Comment by iaronaraujo** [comment]
Hi @lucalves ! Thank you very much for this question!
I am going to leave some links here to our documentation so you can learn more about our framework and the development process as a whole!
https://vtex.io/docs/home/
https://vtex.io/docs/getting-started/build-stores-with-store-framework/1/
The documentation is always evolving, so even after you read it you could still have some questions. In this case, feel free to ask us anything again!
About the questions:

1. I believe what you are looking for is the `account` on VTEX IO. When going to the account you will have access to the store with every app installed! You can run `vtex browse` to check the workspace you are at!
2. I am not sure I understand this question very well, but if you are talking about developing a theme app, I think you and your company can decide with the client where the code will be and the development process! If you are talking about contributing to our existing apps, I believe there is a link on the apps' README explaining how you can make a contribution!
3. We do have a [styleguide](https://styleguide.vtex.com/)!
4. Unfortunately, no D: You need to create a `theme` app for your store, which uses our `Store Framework` to create a store using JSON blocks!

I hope things get more clear with my answer and feel free to ask more questions!

**Comment by gris** [comment]
Hello @lucalves, thanks for the question!

Today in VTEX we have 2 options of CMS that you can use (both of them use the same APIs for checkout, catalog and all the other commerce capabilities of the platform):

- A legacy CMS,  which is the one that the store you listed is using
- A new one, called Store Framework, which this repo is mainly focused on.

If you choose to continue using the legacy one, there is a nice tutorial to start here https://help.vtex.com/tracks/cms--2YcpgIljVaLVQYMzxQbc3z/6OCY6S9tqBXPD5mgpbBInC.

- How do I get the entire source code of the store on my machine? The development experience will be mainly based on updating code to the admin section. And you can download the folders from the templates at any time.

- How can I work with the production and approval environment at VTEX? unfortunately there is no staging environment for this old CMS.

- Where is there a style guide to base myself on creating patterns? You can find some clues in this section of the documentation https://help.vtex.com/subcategory/layout--2g6LxtasS4iSeGEqeYUuGW

- Can I develop my store's code only via CMS, or is there another way? The other way is to use Store Framework, about which you can find some helpful links [here](https://vtex.io/docs/home/) and [here](https://vtex.io/docs/getting-started/build-stores-with-store-framework/1/).
The documentation is always evolving, so even after you read it you could still have some questions. In this case, feel free to ask us anything again!

If you choose instead to use Store Framework, we do have a styleguide, or being more precise, a theme, where you can base yourself to create the store front https://github.com/vtex-apps/store-theme

Also, if you choose to use Store Framework, you will have a staging environment by using workspaces: https://vtex.io/docs/concepts/workspace/

If you have any questions, feel free to answer this comment 😁
