### ISSUE TITLE
What is the correct way to put comments

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#338]
Hi there, I have noticed that when putting comments inside the .jsonc files of the form // it sends an error, I wanted to ask, in what way can I comment on these files and that the vtex link does not send an error?

**Comment by klzns** [comment]
Hi!

Can you provide an example of the content of your file that threw errors? 

Also, can you verify if the file extension is .jsonc and it's located inside the `store/blocks/` folder?

We have an example here: https://github.com/vtex-apps/store-theme/blob/master/store/blocks.jsonc

**Comment by lucalves** [comment]
Hello!

Including your comments between `/*` and `*/`, don't work?
