### ISSUE TITLE
store-components - ProductBrand - textWithLink Prop addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#344]
**Is your feature request related to a problem? Please describe.**
Currently while using the ProductBrand component on Product page there is no way to include a link to the brand page while using text as `displayMode`.

**Describe the solution you'd like**
A prop that renders a link to the brand page as it does while using the `logoWithLink` prop.

**Additional context**
Component documentation: https://github.com/vtex-apps/store-components/blob/master/docs/ProductBrand.md

**Comment by klzns** [comment]
As a workaround you can also use the store-link component in this case:
https://github.com/vtex-apps/store-link

```json
{
  "link.product": {
    "props": {
      "href": "/{brand}",
    },
   "children": [
    "product-brand"
   ]
}
```

**Comment by luizgpriolli** [comment]
Oh great, @klzns  thank you very much
