### ISSUE TITLE
Problem with filterTitle and request for css handle at accordionFilter(mobile).

### ISSUE THREAD

**Issue by EdEsteves** [vtex-apps/store-discussion#345]
I would like to know where the filterTitle of department filter comes from, it is coming wrong.( "Departmento" instead of "Departamento")

![Screenshot_359](https://user-images.githubusercontent.com/20341622/87825497-a422c300-c84d-11ea-97c5-3c1b8942872a.png)

On the desktop I can mask this problem using css because the element has a css handle with the title.
![Screenshot_360](https://user-images.githubusercontent.com/20341622/87825556-ba308380-c84d-11ea-9079-21e471d4ec03.png)

But in the accordionTitle (mobile) we don't have this handle, so I need to know where the title 'department' comes from in order to fix it.

**Comment by klzns** [comment]
Can you provide the account and workspace that is happening?

**Comment by EdEsteves** [comment]
@klzns 
tfbsmy  | ene( or master )

**Comment by hiagolcm** [comment]
@EdEsteves Solved!

It was a problem with our indexing process! There was a hardcoded typo in the stores with the Portuguese language. It is working now! 🙏 

![image](https://user-images.githubusercontent.com/40380674/87992117-f5d18480-cabd-11ea-9a74-c506218be0f3.png)
