### ISSUE TITLE
Hot to get PLP (search.jsonc) to work with Vtex Intelligent Search

### ISSUE THREAD

**Issue by kid-three** [vtex-apps/store-discussion#346]
I cannot get the PLP or any search page to work with Vtex Intelligent Search.

I have the default [Store-Theme](https://github.com/vtex-apps/store-theme) installed.

I followed all the instructions shown [here](https://vtex.io/docs/app/vtex.search@1.0.11/)  and I actually got the Intelligent Search working.

However I cannot get any plp page to work.

If I revert back to vtex.search-resolver 0.x the PLPs seem to work.

I cannot find info in the documentation regarding the setup for the file `search.jsonc` or anything about PLP

| thenorthfacemx |  kinich2 |

**Comment by iago1501** [comment]
Hello @kid-three, is this still a problem? Do you have any error message to share with us?
