### ISSUE TITLE
Custom minicart button?

### ISSUE THREAD

**Issue by kid-three** [vtex-apps/store-discussion#347]
I need to change the default cart button to an Icon with some text.

IS there a way to declare a custom cart button?
|---|---|
|`timberlandmx`|`mrodriguez`|

**Comment by MatheusR42** [comment]
@kid-three , you can change store-icons following this doc: https://vtex.io/docs/recipes/style/customizing-your-stores-icons/

If you need a custom text I think you can put it on svg icon or with custom css using :before or :after selectors.
