### ISSUE TITLE
Search-result pageInfo event addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#349]
**Is your feature request related to a problem? Please describe.**
Currently while using the search-result app  adding a filter or changing the order does not trigger an usable taggable event, even though the result has been updated.

**Describe the solution you'd like**
The addition of a new `pageInfo` event that indicates that the search-result content has changed.
The desired triggers are:

- When a filter is selected/unselected

- When the `Show More` button is clicked

- When the `order by` selector is selected

**Additional context**
search-result documentation: https://github.com/vtex-apps/search-result/tree/master/docs

**Comment by iago1501** [comment]
Already merged, issue solved
