### ISSUE TITLE
Stacked layout or z-layout

### ISSUE THREAD

**Issue by klzns** [vtex-apps/store-discussion#35]
Idea by @juliomoreira

**Is your feature request related to a problem? Please describe.**
Native way to stack, that is, place one block above another.

Example:

![image](https://user-images.githubusercontent.com/284515/60687742-df429600-9e86-11e9-8014-6ca6a795f2a7.png)

Product Highlights and Wishlist button are stacked above the product image.

**Describe the solution you'd like**

Develop a solution like flex-layout, to achieve that.

**Describe alternatives you've considered**

Only way right now is with custom CSS.

**Comment by lbebber** [comment]
Open to suggestions regarding API (e.g. how should the alignment be defined?)

**Comment by juliomoreira** [comment]
I think would be great to have a `position` prop object like in `background-position` something like `center`, `top left`...

```json

**Comment by lbebber** [comment]
This feature has been published: https://github.com/vtex-apps/stack-layout/

As for the API: the block just concerns itself with stacking one element on top of another, alignment is done by inserting `flex-layout` blocks inside each layer.

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/stack-layout
