### ISSUE TITLE
Add to Cart Button - shouldOpenMiniCart prop addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#350]
**Is your feature request related to a problem? Please describe.**
I need to implement in the "Add to Cart Button" a prop similar to "shouldOpenMinicart" made in the "Buy Button"

- Add to Cart Button: https://vtex.io/docs/components/all/vtex.add-to-cart-button@0.13.4/
- Buy Button: https://vtex.io/docs/components/all/vtex.store-components@3.120.8/buy-button/

**Describe the solution you'd like**
Use "shouldOpenMiniCart" in Minicart.v2

**Prop Description**
Whether the Minicart should be opened when the Add to Cart Button is clicked

**Comment by Klynger** [comment]
Related to https://github.com/vtex-apps/store-discussion/issues/246

**Comment by iago1501** [comment]
Solved in #246
