### ISSUE TITLE
[vtex.product-summary] Undocumented block "product-summary-space"

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#353]
The block `product-summary-space` is not documented in https://vtex.io/docs/components/all/vtex.product-summary@2.58.2/

Example of usage in https://vtex.io/docs/components/all/vtex.product-summary@2.58.2/product-summary-sku-selector/
```
"product-summary.shelf": {
   "children": [
     "product-summary-add-to-list-button",
     "stack-layout#prodsum",
     "product-summary-name",
     "product-rating-inline",
     "product-summary-space", <--------------------------
     "product-summary-sku-selector",
     "product-summary-price",
     "product-identifier.summary",
     "product-summary-buy-button"
   ]
 },
```

**Comment by klzns** [comment]
Thanks! We will update our docs.

Until then that's what it does:
https://github.com/vtex-apps/product-summary/blob/master/react/Spacer.js#L9

It's basically a flex-grow
