### ISSUE TITLE
[product-images] Undocumented prop "maxHeight"

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#358]
The prop `maxHeight` isn't documented in https://developers.vtex.com/docs/vtex-store-components-productimages#product-images

It was super useful for me, I think it might be useful for others 🙂

Related code:
https://github.com/vtex-apps/store-components/blob/5241e2ce57902986917b79828bb206fdae7303fc/react/components/ProductImages/Wrapper.js#L83

**Comment by klzns** [comment]
Thanks again @jpesce! We will add it to our backlog!
