### ISSUE TITLE
[vtex.wish-list] » Wishlist page

### ISSUE THREAD

**Issue by fpinhodev** [vtex-apps/store-discussion#360]
**Describe the bug**
The product inside wishlist page don't have a "href" attribute assembled correctly.

**To Reproduce**
1. Go to your wishlist page
2. Click on product

**Expected behavior**
When we click on the product we should go to their product detail.

**Screenshots**

*Code*
![image](https://user-images.githubusercontent.com/19345522/89325889-5b5a6f00-d681-11ea-8012-9dd3109d79a1.png)

**Desktop environment (please complete the following information, if applicable):**
*System:*
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 4.72 GB / 15.87 GB
 *Binaries:*
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  *Browsers:*
    Chrome: 84.0.4147.105
    Edge: Spartan (44.19041.1.0)
    Internet Explorer: 11.0.19041.1

**Comment by klzns** [comment]
Hi @fpinhodev thanks for the bug report. The app vtex.wishlist is deprecated and it's no longer maintained: https://github.com/vtex-apps/wishlist

We recommend you to use the app vtex.wish-list (with a dash): https://github.com/vtex-apps/wish-list

**Comment by klzns** [comment]
Can you provide a link to the page?

**Comment by fpinhodev** [comment]
Account: quebramar
Workspace: develop
Link: [Wishlist page](https://develop--quebramar.myvtex.com/wishlist)

**Comment by fpinhodev** [comment]
Hello @klzns, we have news about this situation ?

**Comment by dapoz** [comment]
Hi @klzns I'm experiencing the same issue, https://wishlist--hopelingerie.myvtex.com/wishlist

**Comment by wender** [comment]
@fpinhodev @dapoz It's related to this one https://github.com/vtex-apps/wish-list/issues/22

I'll take a look at it, that page only provides the product context the default blocks structure uses `product-summary.shelf` to list

**Comment by wender** [comment]
@fpinhodev @dapoz Guys, a fix to this is on the way, it will be published in the next hour under the version `vtex.wish-list@1.0.8` it's on the queue already
