### ISSUE TITLE
Customizing your store's icons

### ISSUE THREAD

**Issue by MatheusR42** [vtex-apps/store-discussion#365]
**Describe the bug**
Every time that I want to change a icon I get the following bugs:

1- I need to resize the svg to work
2- After change the icon it only update in the store after F5 (there is no hotreload)

I think this was needed to be warned in the on docs or handle in a "native way"(without need of any resizes or reload)

**To Reproduce**

1. vtex init and select "store"
2. Follow the doc(https://vtex.io/docs/recipes/style/customizing-your-stores-icons/) to create the styles/iconpacks/iconpack.svg
3. Change some icon
4. The icon only change after F5
5. You will need to resize the icon to work

Video showing the behavor: https://drive.google.com/file/d/1r_pM-jy7iz80CWspmGVJG_YzQ4gz-0aZ/view?usp=sharing
Website to resize svg: https://www.iloveimg.com/resize-image/resize-svg
Cart icon that I used: https://gist.github.com/MatheusR42/432e55869eb6c08e6fd377c281aa1ff0

**Comment by iago1501** [comment]
We already did it 
![image](https://user-images.githubusercontent.com/13649073/103943240-7dfd2200-5110-11eb-812a-bd7f15900053.png)

Thanks for the reply
