### ISSUE TITLE
Product Brand Props not working

### ISSUE THREAD

**Issue by cristian-milea** [vtex-apps/store-discussion#372]
**Describe the bug**
"vtex.store-components:product-brand" doesn't apply props. Logo is still used instead of text. The same applies to **any prop used**, they end up `undefined` in the react tree.

**To Reproduce**
```
"flex-layout.col#pri-left": {
    "children": [
      "vtex.store-components:product-brand"
    ],
  },
  "vtex.store-components:product-brand": { 
    "props": {
      "displayMode": "text"
    }
  }
```

```  "name": "store-theme",
  "version": "0.0.3",
  "builders": {
    "assets": "0.x",
    "styles": "2.x",
    "store": "0.x",
    "sitemap": "0.x",
    "docs": "0.x"
  },
```

```
"vtex.store-components": "3.x",
```

**Screenshots**
<img width="1680" alt="Screenshot 2020-02-23 at 15 39 56" src="https://user-images.githubusercontent.com/4988454/75117736-d3f1e400-567c-11ea-95ee-f83d227ed979.png">

**Comment by klzns** [comment]
Investigating

**Comment by klzns** [comment]
It's a bug on our side. A workaround is to add the major version to the block: `vtex.store-components@3.x:product-brand`.

It would be something like:

```json
"flex-layout.col#pri-left": {
    "children": [
      "vtex.store-components@3.x:product-brand"
    ],
  },
  "vtex.store-components@3.x:product-brand": { 
    "props": {
      "displayMode": "text"
    }
  }
```
