### ISSUE TITLE
client network socket disconnected error

### ISSUE THREAD

**Issue by alberto-casuso** [vtex-apps/store-discussion#377]
**Describe the bug**
The error message "client network socket disconnect" pops up sometimes after trying to query an specific API that works on other apps. The same API queried with the same parameters on curl or postman works fine. This query works from time to time what leads me to think that it is in fact a bug.

**To Reproduce**

1. First we must have a node app made in vtex io that requests an specific API.This code should do the trick (it is a testing api so no worries about user and password) node service example can work for this purpose
```
 axios({
    method: "POST",
    url: `https://api.ivoy.dev/rest/get-token-by-credentials`,
    data: {
        input: {
            user: "integracion-sameday@ivoy.mx",
            password: "sandbox"
        }
    }
}).then(console.log);
```
2. Execute the code
3. the query above will work some times, and some others will return this error

**Expected behavior**
The query should return the api response every time (unless the api is down, of course)

**Screenshots**
**Error output**
![Error output](https://user-images.githubusercontent.com/61762222/90184667-11f1da00-dd7b-11ea-8a29-b0c826f2631a.png)
**Expected output**
![Expected output](https://user-images.githubusercontent.com/61762222/90184724-29c95e00-dd7b-11ea-959f-0c4f4374973e.png)

**Desktop environment**

This problem happens in nodejs, no browser involved

```
  System:
    OS: Linux 5.7 Fedora 32 (Workstation Edition) 32 (Workstation Edition)
    CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
    Memory: 1.94 GB / 15.38 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
```

**Comment by lucis** [comment]
Hello, @alberto-casuso. Please verify the following:

1) The host `api.ivoy.dev` is listed on the app's policies (`manifest.json`). Example [here](https://github.com/vtex-apps/service-example/blob/master/manifest.json#L22).
2) The request is using VTEX's  **External Client**. Details [here](https://www.notion.so/How-to-use-and-create-Clients-on-VTEX-IO-1dbd20c928c642d0ba059d5efbe7874b).
3) Instead of using `https` on the URL called on client's constructor, use `http` and add a `X-VTEX-Use-Https` header with value `"true"` and a `Proxy-Authorization` header with `ctx.authToken` value.

**Comment by alberto-casuso** [comment]
Hi. Thank you for such a fast answer. 
Here are my findings:
1. Yes, i have this policy enabled
2. No i am not using vtex's external client
3. Also no
I have implemented these last two points and it is working now. So this issue can be closed.
Thank you very much!!

**Comment by lucis** [comment]
Nice, @alberto-casuso!

I didn't quite get the last point. Could you elaborate?

It's possible to set both the `timeout` and the number of `retries` on the client's constructor

**Comment by alberto-casuso** [comment]
Sure, let me elaborare.
This would be the flow of a normal call to my endpoint:

1. A webhook makes a POST request to my endpoint on Vtex IO
2. I immediately have to return a 200 response to the webhook service (mandatory as per webhook specs)
3. The middleware executes some business logic that takes a long time(using the clients and after the response)

It would be something like:

const handler=(ctx)=>{

    ctx.status=200
    //200 response to the webhook must be sent here

    executeMiddleware(ctx)
    // clients must be called in the middleware after the response has been already sent

}

**Comment by alberto-casuso** [comment]
Don't worry about it, i've managed to solve it.
What i've done (in case anyone else has the same doubts)
`
//this is an import of a function that executes business logic
import { getVtexOrder } from "../middlewares/vtexOrderHandler";

//this is the hook handler
export async function orderHookHandler(ctx: any) {
  const body = await json(ctx.req);
  if (body.hookConfig) {
    await ping(ctx);
  } else {
//we execute the businesss logic without await and pass the context and already processed body
//at the same time we respond with status 200
    getVtexOrder(ctx,body);
    ctx.status = 200;
  }
}`
