### ISSUE TITLE
Image component should have HREF and be allowed on header/footer

### ISSUE THREAD

**Issue by denisebiscaro** [vtex-apps/store-discussion#38]
**Is your feature request related to a problem? Please describe.**
Currently, the image component is not clickable. There's a use case we'd like to cover of an image with a link that redirects the user either to an internal page, or to an external url.

Also, this image component should be allowed to be inserted on the **header** and on the **footer**

**Describe the solution you'd like**
The easiest solution would be to improve the current image component to support an HREF that  sends the user either to an internal page or to an external website.

**Comment by saviofelixmuniz** [comment]
https://github.com/vtex-apps/store-components/pull/527
