### ISSUE TITLE
New sitemap@2.x request problem

### ISSUE THREAD

**Issue by JoseMeneghetti** [vtex-apps/store-discussion#381]
**What are you trying to accomplish? Please describe.**  

I'm trying to install the new sitemap@2.x ( https://github.com/vtex-apps/store-sitemap ), but I'm having trouble making the request via Postman.

**What have you tried so far?**  

I already tried to reset the workspace and redo everything, generate a new token (which doesn't seem to change)

**Additional info**  
![image](https://user-images.githubusercontent.com/43099776/90272584-ff87a700-de33-11ea-91f7-2176d93e3e37.png)

![image](https://user-images.githubusercontent.com/43099776/90272620-07474b80-de34-11ea-9430-81c32ff0f81e.png)

The request always returns this Forbidden, the app is installed normally but I can't make the request to test it.

https://map2--aurelia.myvtex.com/
|---|---|
|aurelia|map2|

**Comment by vwraposo** [comment]
This was happening because the endpoint to generate the sitemap was private and your token did not have the access to make requests to it. The PR https://github.com/vtex-apps/store-sitemap/pull/86, makes the endpoint public. Now you should be able to call the new endpoint, it is: `https://{{workspace}}--{{account}}.myvtex.com/_v/generate-sitemap`

**Comment by JoseMeneghetti** [comment]
@vwraposo Let me see if I got it right, was the route replaced by the one you sent? Why the one on the `bootstrap` keeps giving the error, the one you sent me is ok.

**Comment by vwraposo** [comment]
Sorry for the confusion, we talked more over this problem and concluded that it wouldn't be secure to have these APIs public. Therefore you still need a valid token to call them. So the correct procedure for you to generate the sitemap would be to open a ticket.

**Comment by vwraposo** [comment]
@JoseMeneghetti as we talked I have generated the sitemap in your workspace, you can check it https://map2--aurelia.myvtex.com/sitemap.xml. We will think on a better solution and update this issue and the documentation.

**Comment by vwraposo** [comment]
We have updated our sitemap APIs, they are now Graphql APIs which you can call via the Graphql IDE in the admin. The [docs ](https://github.com/vtex-apps/store-sitemap/blob/master/docs/README.md) are updated and explains them.
