### ISSUE TITLE
Change Select Quantity to Plus(+) / Minus (-) Input

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#385]
Can the product select quantity be changed? I'm trying to change the product select quantity to de plus (+), minus (-) input.

I have tried placing the "product-summary", but it does not accept it, is there any way

| Account        | Workspace        |
| -------------- | ---------------- |
| `lyracons` | `test` |

**Comment by klzns** [comment]
No, there's no way to do this right now.

**Comment by chrisar45** [comment]
Tried in my own partner store, but it is for poccarrefourarg

| Account        | Workspace        |
| -------------- | ---------------- |
| `poccarrefourarg` | `dev` |
