### ISSUE TITLE
Collection Badge not shown in search page

### ISSUE THREAD

**Issue by gfmattia** [vtex-apps/store-discussion#388]
**What are you trying to accomplish? Please describe.**  
Show collection badge on search page, products, and related products. **it only shows in home**

**What have you tried so far?**  
I use the same product-summary-shelf

**Additional info**  
`"search-result-layout": {
    "blocks": [
      "search-result-layout.desktop"
    ]
  },
"search-result-layout.desktop": {
    "children": [
      "flex-layout.row#result"
    ],
    "props": {
      "pagination": "show-more",
      "preventRouteChange": false,
      "mobileLayout": {
        "mode1": "small",
        "mode2": "normal"
      }
    }
  },
"flex-layout.row#result": {
    "children": ["flex-layout.col#filter", "flex-layout.col#content"],
    "props": {
      "preventVerticalStretch": true,
      "rowGap": 0
    }
  },
"flex-layout.col#content": {
    "children": [
      "flex-layout.row#products"
    ],
    "props": {
      "preventVerticalStretch": true,
      "marginLeft":4
    }
  },
"flex-layout.row#products": {
    "children": ["search-content"]
  },

  "search-content": {
    "blocks": ["gallery"]
  },
"gallery": {
    "blocks": ["product-summary.shelf"]
  },
"product-summary.shelf": {
    "children": [
      "stack-layout#shelf"
    ]
  },
  "stack-layout#shelf": {
    "children": ["product-summary-image"]
  },
  "product-summary-image": {
    "props": {
      "showBadge": true,
      "badgeText":"OFF",
      "showCollections": true
    }
  },
`

| Account | Workspace |
|---|---|
|`sarachoneumaticos`|`dev`|

**Comment by gfmattia** [comment]
...

**Comment by klzns** [comment]
See https://github.com/vtex-apps/store-discussion/issues/441
