### ISSUE TITLE
Our components that support href prop, should allow open page new tab

### ISSUE THREAD

**Issue by denisebiscaro** [vtex-apps/store-discussion#39]
**Is your feature request related to a problem? Please describe.**
Sometimes our store owners would like to make some links to be opened in new tabs.
Currently, all of our navigation is made on the same tab. 

**Describe the solution you'd like**
I'd like to have an option (prop) to choose when an href should send the user to another tab.
The main components that should possess it are:
- Infocard
- menu-item
- rich-text
- Image

**Describe alternatives you've considered**
Provide prop that will add `target="_blank"`on links

**Comment by klzns** [comment]
This can be achieved using vtex-apps/store-link
