### ISSUE TITLE
How to get the `price range slider` in my filters

### ISSUE THREAD

**Issue by kid-three** [vtex-apps/store-discussion#394]
I cannot seem to find any info regarding the price range slider. 

![image](https://user-images.githubusercontent.com/32473931/90658912-b8b9f880-e209-11ea-8058-7a287ce66578.png)

This is what comes with my stores. I want to change the price range fitler to the slider everyone else seems to be using.

Any help would be greatly appreciated

**Comment by klzns** [comment]
Can you provide the account and workspace, please?

**Comment by kid-three** [comment]
thenorthfacemx

https://kinich2--thenorthfacemx.myvtex.com/Ropa/

https://thenorthfacemx.myvtex.com/Ropa/


It seems that the price filter you see there is a 'Specification Filter'

**Comment by kid-three** [comment]
It is also missing from another account of mine

timberlandmx

https://timberlandmx.myvtex.com/Calzado

Is it some sort of setting or configuration we are missing?

**Comment by kid-three** [comment]
Price ranges have been set up in the admin, and still nothing shows.

**Comment by iago1501** [comment]
This is already working, probably a locale problem
