### ISSUE TITLE
How to Change page title

### ISSUE THREAD

**Issue by yanethvg** [vtex-apps/store-discussion#395]
change the title of the page that has the search intelligent implemented (https://help.vtex.com/tracks/vtex-intelligent-search--19wrbB7nEQcmwzDPl1l4Cb/3qgT47zY08biLP3d5os3DG) and currently it puts me undefined.

It only happens when I select a category from the category-menu (https://vtex.io/docs/components/all/vtex.category-menu@2.14.0/) I would like you to help me because I need to fix it, thanks in advance

![image](https://user-images.githubusercontent.com/21286767/90677935-481bd780-e21b-11ea-8add-2955eed3f1c7.png)

![image](https://user-images.githubusercontent.com/21286767/90677953-4c47f500-e21b-11ea-9bad-1d655326b3e3.png)

![image](https://user-images.githubusercontent.com/21286767/90677967-50741280-e21b-11ea-9369-51bce4547deb.png)

**Comment by Klynger** [comment]
Hi @yaneth94 , try going to [this URL](https://vetrob2c.myvtex.com/admin/cms/store) and changing the `Default title tag`. (**I advise you to test this in a workspace before changing in master**)

**Comment by yaneth94** [comment]
Hi @Klynger thanks for answering, I need the name of the category to appear, do you know any configuration that I could do to make the name of the category appear?
To put it in context, I have a page that does not have the search intelligent implemented and in this page you can see the category in the title of the page

![image](https://user-images.githubusercontent.com/21286767/90684074-c92b9c80-e224-11ea-8a72-825db9652f1b.png)

![image](https://user-images.githubusercontent.com/21286767/90684050-c03acb00-e224-11ea-8879-a2d0d70ebc5c.png)

**Comment by klzns** [comment]
@yaneth94 Can you allow the user breno@vtex.com.br to open this page, please?

**Comment by hiagolcm** [comment]
@yaneth94  Can you allow the hiago.cardeal@vtex.com.br as well?

**Comment by yaneth94** [comment]
@klzns I already sent you the mail, can you please check
