### ISSUE TITLE
menu-link/menu-item: Add optional icon

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#4]
**Is your feature request related to a problem? Please describe.**
We are migrating https://www.eriksbikeshop.com/ to VTEX IO. It has some links on header (on store-theme they'll be inside a `header-row` for desktop and `drawer` for mobile) and those links have icons.

**Describe the solution you'd like**
Option to provide an icon id on blocks.json, or to use an image uploader on storefront.

**Describe alternatives you've considered**
- Use info-card: It has options for an image and a link, but it's not allowed on header-row and drawer.
- Use logo + menu-link: both are allowed on header-row but not on drawer. Furthermore, it's bad UX on storefront because the logo component is identified as "Logo" and it won't show up as being related to the menu-link on the UI, being very confusing to manage (because it would generate 12 different configurations on storefront, 6 for mobile and 6 for desktop)
- Use CSS: It's possible to upload the image to a CDN, but that would be hardcoded on CSS file. Also, menu-item doesn't allow `blockClass` prop, so identifying which link has which image will be very verbose.

**Additional context**
StyledLink component probably at some point allowed icons, but now it seems to just have leftover code, `iconId` is even being destructured but never used https://github.com/vtex-apps/menu/blob/master/react/components/StyledLink.tsx#L29

**Screenshots**
header-row (desktop)
![image](https://user-images.githubusercontent.com/27775611/59789003-5aab2180-92a3-11e9-9fa4-9603c57c5f90.png)
store-drawer (mobile)
![image](https://user-images.githubusercontent.com/27775611/59789048-79a9b380-92a3-11e9-98a1-5e67e1bf1cf1.png)

**Comment by hapoza** [comment]
This was solved on https://github.com/vtex-apps/menu/pull/50, version 2.16.0, with the possibility to add blockClass prop to each menu-item and then adding the icons with CSS

**Comment by klzns** [comment]
Thanks!

**Comment by saviofelixmuniz** [comment]
I'm reopening this, because we'll soon provide support for Store Icons on Menu Items

**Comment by iaronaraujo** [comment]
Submitted a PR to solve this issue: https://github.com/vtex-apps/menu/pull/59

**Comment by iaronaraujo** [comment]
The PR just got merged @saviofelixmuniz !
