### ISSUE TITLE
Store-framework throws Render Server error.

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-discussion#401]
**Description**

After cloning linking my own store-framework repo, everything is fine on vscode:

![image](https://user-images.githubusercontent.com/45275689/91231789-3eefa680-e704-11ea-94ac-581945008305.png)

It says the website is live and linked, but when I access it, it opens Render Server error:

![image](https://user-images.githubusercontent.com/45275689/91231866-65addd00-e704-11ea-9183-37f28c188840.png)

**Comment by lucis** [comment]
Hey, @leomuzicarvalho!

It seems that your account is not configureD to use Store Framework, as it needs other base apps besides the theme.

I've done the work installing such apps and you should be good to go now: https://test2--lojaccm.myvtex.com/

For further configuration, please contact the Account Manager responsible on VTEX.

**Comment by MatheusR42** [comment]
I think you may need to ask to vtex install the edition app. Here is the documentation:
https://vtex.io/docs/getting-started/build-stores-with-store-framework/2/

**Comment by leomuzicarvalho** [comment]
Thanks! I'm contacting Vtex team to set my edition to **vtex.edition-store@3.x**, and I've also installed both apps:
`vtex install vtex.admin-search vtex.search-resolver@1.x`
I'll wait for them to set my edition and I hope that's enough for me to get started with a blank page as the tutorial shows.

@lucis thanks for changing the backend, but I wasn't able to change stuff on the page, probably because of theses configurations that were lacking. But thanks all the same!

**Comment by vitorcrovador** [comment]
@leomuzicarvalho did you get a response from the VTEX team? I made the same request 3 days ago and still have no answer.
I was excited to learn about the Store Framework, so in this period I ended up finishing the course without seeing the result of the code :(

**Comment by leomuzicarvalho** [comment]
@vitorcrovador no response yet. I'm looking forward to receiving an answer as well :( I'll keep waiting until they config my account before moving on with the course.

**Comment by lucis** [comment]
@vitorcrovador and @leomuzicarvalho for learning purposes, we have already set up the account `appliancetheme`. Please, email me on lucis[at]vtex.com with your e-mail addresses that I'll whitelist both of you to that account. After that, you'll be able to login and create workspaces. 

Changing the editions on production accounts is a delicate operation and should be made with the account's representative on VTEX. For educational purposes, `appliancetheme` will serve you just fine :)

**Comment by iago1501** [comment]
Solved in other issue
