### ISSUE TITLE
Wish-list app stuck on infinite loading

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#403]
**Describe the bug**
-   In some cases, the wish list button has infinite loading.
-   A pattern was not identified when the bug occurs.
-   The bug occurs on all pages, home, shelves, product page and wishlist page.

**To Reproduce**
1. Access: https://vtexwish--cybelar.myvtex.com/
2. Log in
3. Add some products to the wishlist
4. Reload the page a couple of times

**Screenshots**
-   loading: https://i.imgur.com/EzR6toJ.gif
-   video: https://www.awesomescreenshot.com/video/707534?key=e0cab640a63107bc80bfa509b967d202

**Desktop environment (please complete the following information, if applicable):**
-   OS: [Windows 10]
-   Browser [Google Chrome]
-   Version [84.0.4147.125]

**Additional Info**
-   workspace link: https://vtexwish--cybelar.myvtex.com/
-   app documentation https://github.com/vtex-apps/wish-list

**Comment by iago1501** [comment]
This is already fixed
