### ISSUE TITLE
Identify Badges on Summary and product view

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#406]
**What are you trying to accomplish? Please describe.**  
I am trying to identify the different highlights within the product Summary, how it was done in portal

**What have you tried so far?**  
Place all the highlights available, both promotions, collections, discounts, and specifications

**Additional info**  
Add extra content here (code samples, screenshots,...)

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`chef`|

**Comment by klzns** [comment]
@chrisar45 just published this app! 🚀 

https://github.com/vtex-apps/product-highlights

**Comment by klzns** [comment]
For specifications you can use: https://github.com/vtex-apps/product-specifications
