### ISSUE TITLE
Component identification in site editor

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#407]
**What are you trying to accomplish? Please describe.**  
It is possible to make a prop to identify each component in the site editor

**Additional info**  
Add extra content here (code samples, screenshots,...)
![image](https://user-images.githubusercontent.com/19915537/91474908-3cf72600-e871-11ea-8f2b-d6dbab0e84aa.png)
![image](https://user-images.githubusercontent.com/19915537/91474939-46808e00-e871-11ea-9a90-6969652c92e6.png)
![image](https://user-images.githubusercontent.com/19915537/91474967-4c766f00-e871-11ea-8791-06a7f04a3646.png)

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`dev`|

**Comment by klzns** [comment]
Yes, you can use the property `title`. Example:

```json
{
  "rich-text#foo": {
    "title": "Custom Name",
    "props": {
      "text": "Message"
    }
  }
}
```

**Comment by chrisar45** [comment]
Thank you very much.
