### ISSUE TITLE
Minicart should show Total value added to cart on icon

### ISSUE THREAD

**Issue by denisebiscaro** [vtex-apps/store-discussion#41]
**Is your feature request related to a problem? Please describe.**
Currently on our minicart, it is only possible to show the total items added to cart. Some use cases need to show the total value added to cart.

**Describe the solution you'd like**
The user should be able to choose what should be shown in the preview, either the amount of itens or the total value of items added.

**Describe alternatives you've considered**
A prop of Value on Icon preview, that could have the values "Value", "Quantity", _undefined_
When undefined, no number is shown on the preview icon.

**Comment by iaronaraujo** [comment]
Fixed by:
https://github.com/vtex-apps/minicart/pull/164
https://github.com/vtex-apps/minicart/pull/163
