### ISSUE TITLE
is there a way to create a page with data related to CL entity from master data?

### ISSUE THREAD

**Issue by erickvh** [vtex-apps/store-discussion#410]
I was wondering if it's possible to create a custom page with some data from entities on Master Data.

**Comment by klzns** [comment]
Hi @erickvh can you give an example of what you are trying to achieve?

**Comment by erickvh** [comment]
Hello @klzns, well I've been working on a store with a B2B environment so I'll create a master data entity that it'll be updated from the current ERP of the company, this data is necessary to show it in a page because is related to the salesperson who attend physically the customers.

**Comment by klzns** [comment]
You will have to develop a custom React and GraphQL app to achieve that. This app does something similar:
https://github.com/vtex-apps/organizations
