### ISSUE TITLE
Slider Layout - Props - centerMode - to-the-left - Its alot

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#411]
**What are you trying to accomplish? Please describe.**  
I am trying to make a slider that displays a small part of the next slide

**What have you tried so far?**  
I am implementing the slider layout with the centerMode props in to-the-left, but it is too much what each slide makes me smaller

**Additional info**  
**Design**
![image](https://user-images.githubusercontent.com/19915537/91671179-a0e04f80-eafa-11ea-91ec-af682f6b61ad.png)

**Code**
"slider-layout#03-infoBox": {
    "children": [
      "flex-layout.col#03-infoBox-1",
      "flex-layout.col#03-infoBox-2",
      "flex-layout.col#03-infoBox-3",
      "flex-layout.col#03-infoBox-4"
    ],
    "props": {
      "itemsPerPage": {
        "desktop": 4,
        "tablet": 2,
        "phone": 1
      },
      "navigationStep": 1,
      "infinite": false,
      "showNavigationArrows": "never",
      "showPaginationDots": "mobileOnly",
      "centerMode": {
        "mobile": "to-the-left"
      }
    }
  },

**Result**
![image](https://user-images.githubusercontent.com/19915537/91671167-8908cb80-eafa-11ea-929c-bf1232a45156.png)

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`dev`|

**Comment by jpesce** [comment]
+1
Suggestion: the size of the gaps should be configurable via props.

**Comment by victorhmp** [comment]
Implemented here: https://github.com/vtex-apps/slider-layout/pull/68
