### ISSUE TITLE
Search bar not closing when the content of a search page changes

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#412]
**Describe the bug**
When the user is already in the search page `/example?map=ft` and clicks in another option in the top searches at biggy-search-bar, the bar keeps appearing in the screen after the page contents chage. The same problem occurs when clicking in the "see all" on the autocomplete.

**To Reproduce**
1. Go to 'http://www.stcroixshop.com/'
2. Click on the search-bar to open Top Searches Options.
3. Choose a option from Top Searches Options.
4. After load the page, click again to open search-bar top searches options.
5. Choose one again of the top searches and the page function `.map()` will be reload.
6. See the error, search-bar is still opened even after "on-click" from user.

**Expected behavior**
Close the biggy-search-bar after the page contents change.

**Additional context**
Video: https://nimb.ws/qcZ9Ka
We used to have a similar issue when navigating between categories using the mega-menu, perhaps a similar fix can be achieved

**Comment by hiagolcm** [comment]
Hey @luizgpriolli!
Thanks for the report!
I was able to reproduce the bug. We will fix it in the next weeks.
Once we have an update, I'll let you know.
