### ISSUE TITLE
Search 1.x not rendering product images on autocomplete

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#415]
**Describe the bug**
It has been noticed that stores that are using the autocomplete from search@1.x are having problems rendering the product images on autocomplete.

**To Reproduce**

1. Access https://www.melimeloparis.ro/
2. Click on the search bar
3. Type "Ce"
4. See the error

**Expected behavior**
Render the product image correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/45877287/92251987-025e4080-eea4-11ea-9145-9df9b7829b66.png)

**Additional context**
This behaviour can also be seem at https://www.spaziolusso.it/ and at https://reidosestojos.myvtex.com/

**Comment by klzns** [comment]
I think you need to update the autocomplete component used.

`autocomplete-result-list.v2`
https://vtex.io/docs/app/vtex.search@2.0.0/

**Comment by klzns** [comment]
We had an issue with a release of the Search API. It should be fine now.
