### ISSUE TITLE
Reviews and Ratings - Number of open reviews prop addition request

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#416]
**Is your feature request related to a problem? Please describe.**
Native Vtex Reviews and Ratings lack adequate possibilities to a valid business rule.
Right now, this native component does not allow to display a certain number of reviews/ratings already opened, its switches in between show all or nothing.
- Reviews and Rating: https://vtex.io/docs/components/all/vtex.reviews-and-ratings@2.0.2/
- GitHub doc: https://github.com/vtex-apps/reviews-and-ratings

**Describe the solution you'd like**
Possibility to set a specific amount of Reviews/Ratings to be shown already opened for a better UX.

**Prop Description**
A prop that allows to set a specific amount/number of Reviews/Ratings to display already opened.

**Comment by polishq** [comment]
Thanks @luizgpriolli . The US First Party Apps team will review this request.

**Comment by klzns** [comment]
Fixed https://github.com/vtex-apps/reviews-and-ratings/pull/35
