### ISSUE TITLE
Minicart component should become Flexible

### ISSUE THREAD

**Issue by denisebiscaro** [vtex-apps/store-discussion#42]
**Is your feature request related to a problem? Please describe.**
Our minicart forces one single Layout. It is not flexible, and cannot be composed by rows and columns yet.

**Describe the solution you'd like**
The minicart should be broken into smaller blocks and be compatible with flex layout - rows and columns. Also, there should be plenty of css handles on it.

**Comment by juliomoreira** [comment]
I would like to extend this request and point that would be awesome if we could set the `type` other than `sidebar` on mobile also.

**Comment by juliomoreira** [comment]
Would be great to have a React context also so we can add custom close buttons to toggle the minicart visibility.

**Comment by klzns** [comment]
Implemented. You can now use minicart.v2 for that.
