### ISSUE TITLE
Search result doesn't appear

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-discussion#424]
Hi, I'm almost done with the course, which is super cool by the way.

The bot approved me for the next step, although I can't see the results of step 21 - Building a custom landing page - on my page:
https://leomuzi--appliancetheme.myvtex.com/landing

It only loads the banner. The learning bot approved me, which means I've added all the blocks and props. I tried linking the code again and reloading the page with clean cache. But nothing solved the problem.

I appreciate any help, cause I really want to understand and learn how to use the custom query on a custom page.
Thanks!

**Comment by leomuzicarvalho** [comment]
Solved. Needed to add:
```json
"blocks":[
            "search-result-layout.desktop",
            "search-result-layout.mobile",
            "search-not-found-layout"
        ]
```
inside my **"search-result-layout.customQuery#home"**, so it will render the blocks =)

but still, the bot allows you to move on without it.

**Comment by FabianaFerreira** [comment]
Thank you for your contribution, @leomuzicarvalho! 🚀 
This was fixed on [this PR](https://github.com/vtex-apps/store-framework-course/pull/14)
