### ISSUE TITLE
trigger "load-session" not work in modal-layout

### ISSUE THREAD

**Issue by srhblacksip** [vtex-apps/store-discussion#427]
This trigger doesn't work, I have put this property in the modal-trigger block and it never loads the modal on the site

**To Reproduce**

```json
"modal-trigger#cookies": {
        "props": {
            "trigger": "load-session"
        },
        "children": [
            "modal-layout#cookies"
        ]
   },
```

According to the documentation, it loads once per session but never loads, neither in incognito mode nor by deleting the site's cookies.

**Comment by Klynger** [comment]
Hi, could you post a link with the problem?

**Comment by srhblacksip** [comment]
Hi
of course
Link: https://www.coolbox.pe/

**Comment by Klynger** [comment]
Oh, I mean, could you give me a dev workspace with the modal-layout and this trigger?

**Comment by srhblacksip** [comment]
This is correct?
https://sebastest--coolboxpe.myvtex.com/

**Comment by srhblacksip** [comment]
> This is correct?
> https://sebastest--coolboxpe.myvtex.com/

Hi @Klynger 
Can you help me with this?

**Comment by Klynger** [comment]
Hi @srhblacksip , I didn't have time last week or yesterday, gonna try to check it today
