### ISSUE TITLE
Problems with my account extended app

### ISSUE THREAD

**Issue by giovanapereira** [vtex-apps/store-discussion#429]
I extend my account app, but I'm make changes that VTEX doesn't reflect on front. 
I'm linking the new app, but when I make a change in a component, like ProfileBox, don't show nothing on the front.
What Am I supposed to do for see my changes in this app? I need to include inputs and change the behavior, the "extension" example it's not for the client necessities.

**Comment by klzns** [comment]
Can you provide a link to the development workspace? 
Which version of my account are you using? 

If the store is using IO you should follow these instructions: https://github.com/vtex-apps/my-account/tree/1.x
If the store is not using IO: https://github.com/vtex-apps/my-account

**Comment by giovanapereira** [comment]
Of course I can! There's: https://gipol--portaldolojistahomo.myvtex.com/account#/profile

But I realized that I'm using IO and the link I saw for my account isn't for IO. I'll try with the correct version of my account for IO!

I'll be back if something doesn't work as well, I luv u <3 

Thanks.

**Comment by giovanapereira** [comment]
I got it! Thanks for the help, my love! <3

**Comment by klzns** [comment]
You're welcome!
