### ISSUE TITLE
Store Form - Cascading Select

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#431]
**What are you trying to accomplish? Please describe.**  
Generate a form where the user places his email, province and city.
The idea is that when the user selects the province, he reloads the city selector corresponding to that province

**What have you tried so far?**  
I tried with dependencies, conditional, but it does not give result, I did the test in a web app to test the behavior and it behaves as I expect. but when I take it to the framework store with the form app it does not perform the same behavior.
[Web APP](https://rjsf-team.github.io/react-jsonschema-form/)

**Additional info**  
```json
{
  "title": "TestDependencis",
  "type": "object",
  "properties": {
    "email": {
      "type": "string",
      "format": "email",
      "title": "Email",
      "description": "Email del cliente"
    },
    "state": {
      "title": "Provincia",
      "type": "string",
      "enum": ["Provincia", "Hola", "Chau"]
    },
    "city": {
      "title": "Ciudad",
      "type": "string",
      "enum": ["Ciudad"]
    }
  },
  "dependencies": {
    "state": {
      "oneOf": [
        {
          "properties": {
            "state": {
              "enum": ["Provincia"]
            },
            "city": {
              "enum": ["Ciudad"]
            }
          }
        },
        {
          "properties": {
            "state": {
              "enum": ["Hola"]
            },
            "city": {
              "enum": ["Hola-1", "Hola-2", "Hola-3"]
            }
          },
          "required": ["city"]
        },
        {
          "properties": {
            "state": {
              "enum": ["Chau"]
            },
            "city": {
              "enum": ["Chau-1", "Chau-2", "Chau-3"]
            }
          },
          "required": ["city"]
        }
      ]
    }
  },
  "required": ["email", "status"],
  "v-security": {
    "publicWrite": ["email", "status", "city"],
    "publicJsonSchema": true
  }
}
```

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`news`|

**Comment by klzns** [comment]
Hi @chrisar45 it would be possible with the `dependencies` feature of JSON Schema but it's currently not implemented in store-form.

I would suggest you to create your own React component in this case.
