### ISSUE TITLE
Store Form - Auto Fill Selectors Options

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#432]
**What are you trying to accomplish? Please describe.**  
Is there a way to auto-fill the values of the selectors? either by the records of a data entity, the domains within a varchar field, or some other way that is not static by schema?

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`news`|

**Comment by klzns** [comment]
It's not possible. As suggested in #431, I would go with creating your own component.
