### ISSUE TITLE
 Workspace loading and not ending

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#433]
**Describe the bug**

working in a workspace sometimes the page is loading and does not finish, after about 5 to 10 minutes I can work again. even in anonymous tab this problem persists.

**To Reproduce**

it is difficult to reproduce. but after a few updates to the page it happens that the environment gets stuck

**Screenshots**

![terminal](https://user-images.githubusercontent.com/4852136/93344424-10974f80-f808-11ea-9cbe-c42e17839af7.png)
![Screenshot_3](https://user-images.githubusercontent.com/4852136/93344466-1c831180-f808-11ea-9983-b7c4a1c20750.png)
![Screenshot_4](https://user-images.githubusercontent.com/4852136/93344476-1f7e0200-f808-11ea-9c1b-37a9067420ba.png)

**Comment by klzns** [comment]
It happens if you create another workspace?

**Comment by alextalha** [comment]
yes @klzns . 

I work for a while and it happens

**Comment by iago1501** [comment]
This is already solved
