### ISSUE TITLE
product brand don't accept #

### ISSUE THREAD

**Issue by pablim** [vtex-apps/store-discussion#434]
vtex.store-components:product-brand#tes don't working

```
   "link.product#brandlink": {
        "props": {
            "href": "/{brand}",
            "blockClass": "link-product-brand"
        },
        "children": [
            "rich-text#tes",
            "vtex.store-components:product-brand#tes"
        ]
    },

    "vtex.store-components:product-brand#tes": {
        "props": {
            "displayMode": "text",
            "blockClass": "brand-link-teste"
        }
    }
```

error: App build failed with message: Error resolving block "link.product#brandlink":
I couldn't find a block "vtex.store-components:product-brand#tes". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies..
12:33:54.891 - error: Error resolving block "link.product#brandlink":
I couldn't find a block "vtex.store-components:product-brand#tes". You need to declare the block or have your app depended on another app that declares it. This error may be caused by a change in behavior resolving blocks from indirect app dependencies. Further info here: https://vtex.io/docs/releases/2019-12-12/declaring-blocks-stemming-from-indirect-dependencies..

**Comment by Klynger** [comment]
Hi @pablim, do you have `vtex.store-components` installed in your workspace? Could you run `vtex ls` in your workspace and post the output here?

**Comment by klzns** [comment]
It's a known issue, can you try this:
https://github.com/vtex-apps/store-discussion/issues/372#issuecomment-672226546

**Comment by pablim** [comment]
Thanks @klzns 

https://github.com/vtex-apps/store-discussion/issues/372#issuecomment-672226546
