### ISSUE TITLE
Button in Flex Row

### ISSUE THREAD

**Issue by yanethvg** [vtex-apps/store-discussion#436]
Hello, I would like to make a question is it possible to create a button inside a flex-layout-row, or there is a vtex io app that can do this job, they ask me in design something like the image 
![image](https://user-images.githubusercontent.com/21286767/93388756-6da2fd80-f828-11ea-9aaa-9bea34d4670a.png)

I have only been able to do what is in the following image:

![image](https://user-images.githubusercontent.com/21286767/93388270-b4442800-f827-11ea-9620-3d46303b31ac.png)

I share the code both in json and css:
```
"flex-layout.row#pasari": {
    "children": ["flex-layout.col#pasari"],
    "props":{
      "blockClass": "ofertele"
    }
  },
  "flex-layout.col#pasari": {
    "children": ["shelf#pasari"],
    "props": {
      "paddingLeft": 5,
      "paddingRight": 5
    }
  },
```
CSS:

```
.flexRow--ofertele{
    background-image: url("https://res.cloudinary.com/s-c-vetro-solutions-s-r-l/image/upload/v1600275539/vetro-assets/Oferte_new__t0atyj.png");
    background-size: cover;
    background-image: fixed;
    background-repeat: no-repeat;
    background-position: center;
}
```
Thank you very much in advance

**Comment by klzns** [comment]
You can use the [store-link component](https://github.com/vtex-apps/store-link).

**Comment by yanethvg** [comment]
thanks @klzns :D
