### ISSUE TITLE
Add class scope to search bar's product summaries

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#439]
**Is your feature request related to a problem? Please describe.**
When styling the search popup that appears when the user types into the search bar, I noticed that product summaries don't have a specific context class. So the only options to style them that I see are changing the base product-summary css (which may cause undesired changes elsewhere) or using `:global()` to scope it within the search bar context.

**Describe the solution you'd like**
Add a class that makes the product summary specific to the search bar result.
For example:
Add `vtex-product-summary-2-x-container--searchBar` to `vtex-product-summary-2-x-container` 

**Describe alternatives you've considered**
What I'm currently doing is using `:global()` to scope it properly, which is not ideal

**Additional context**
![Screen Shot 2020-09-17 at 17 14 00](https://user-images.githubusercontent.com/1228352/93523302-3c4e2e80-f909-11ea-8e04-529c705d5941.png)

**Comment by thalytafabrine** [comment]
Hi @jpesce, how are you?
You can handle with it using a `blockClass` in the `product-summary` that you want to customize.
[Here is a documentation on how to use `blockClass`](https://vtex.io/docs/recipes/style/using-css-handles-for-store-customization/)

**Comment by jpesce** [comment]
Hi @thalytafabrine , thank you very much! I wasn't aware we could overwrite the default `product-summary`. However, the only way I could make it work was to use a `product-summary.shelf` to add a `blockClass`.

For future reference, if anyone looks into this as well. This is how I did it:
```json
  "search-bar": {
    "blocks": ["autocomplete-result-list.v2"]
  },
  "autocomplete-result-list.v2": {
    "blocks": ["product-summary.shelf#search-bar"]
  },
  "product-summary.shelf#search-bar": {
    "props": {
      "blockClass": "search-bar"
    },
    "children": [
      "product-summary-image",
      "product-summary-name",
      "flex-layout.row#selling-price-savings",
      "product-installments"
    ]
  },
  "flex-layout.row#selling-price-savings": {
    "props": {
      "colGap": 2,
      "preserveLayoutOnMobile": true,
      "preventHorizontalStretch": true,
      "marginBottom": 3
    },
    "children": [
      "product-selling-price",
      "product-list-price"
    ]
  },
```
