### ISSUE TITLE
Product highlight does not appear on search pages. only at home

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#441]
**Describe the bug**

today I implemented the product-highlight of a collection. on the home shelf is showing off perfectly. but on the search pages nothing appears

**To Reproduce**

1. Go to  https://flags--iofensacl.myvtex.com/
2. Scroll down to any shelf
3. see that there is a flag on the shelf
4. Go to https://flags--iofensacl.myvtex.com/linea-blanca/refrigerador
5. see that none of the products have a flag

**Expected behavior**
I would like both pages to display the flags

**Screenshots**
![image](https://user-images.githubusercontent.com/4852136/93531183-2e060f80-f915-11ea-8b09-bc47f8d9b6bd.png)
![image](https://user-images.githubusercontent.com/4852136/93531246-46762a00-f915-11ea-83bc-0c6576ed96fe.png)
![image](https://user-images.githubusercontent.com/4852136/93531432-9e149580-f915-11ea-9985-c93119c85254.png)

**Additional context**
the flag configuration is inside the product-summary.shef which is used by both pages

**Comment by alextalha** [comment]
@klzns

**Comment by klzns** [comment]
By default, in search-resolver@1.x, we don't send all product properties to the client-side. If you are having problems with missing properties, you can use the `__unstableProductOriginVtex` prop.

PLP:

```json
{
  "store.search": {
    "props": {
      "context": {
        "__unstableProductOriginVtex": true
      }
    }
  }
}
```

Autocomplete:

```json
{
  "autocomplete-result-list.v2": {
    "blocks": [
      "product-summary.shelf"
    ],
    "props": {
      "__unstableProductOriginVtex": true
    }
  }
}
```

Search Result - CustomQuery:

```json
{
  "search-result-layout.customQuery#example": {
    "props": {
	"querySchema": {
	   "__unstableProductOriginVtex": true
        }
    },
    "blocks": []
}
```

**Comment by klzns** [comment]
It's in our backlog to add this to the product-highlights docs

**Comment by alextalha** [comment]
@klzns 
It is possible to use the product-highlight on the product page
 inside "product-images"?

![image](https://user-images.githubusercontent.com/4852136/93614834-06f91d80-f9a9-11ea-8af1-1c80340e3f59.png)

**Comment by klzns** [comment]
Yes, just use stack-layout to place it on top of the product-images block
