### ISSUE TITLE
URI Malformed when searching for collections with "%" in the name

### ISSUE THREAD

**Issue by luizgpriolli** [vtex-apps/store-discussion#442]
**Describe the bug**
When trying to access collections pages using the format `/{collectionId}?map=productClusterIds` there is an URI malformed error if the product cluster have a "%" character in its name.

**To Reproduce**

1. Go to https://acctglobal.myvtex.com/141?map=productClusterIds
2. See the error in the console

**Expected behavior**
The rendering of the search-result page.

**Screenshots**

![image](https://user-images.githubusercontent.com/45877287/93912391-1befec80-fcda-11ea-876e-63a6df930dbd.png)

![image](https://user-images.githubusercontent.com/45877287/93912439-2ad69f00-fcda-11ea-811b-f53c7153cb83.png)

**Additional context**
workspace in order to see the full error log: https://raissateste--acctglobal.myvtex.com/141?map=productClusterIds

**Comment by thalytafabrine** [comment]
hi @luizgpriolli, the bug was fixed in the latest version of search-result, so I will close the issue. thanks!
