### ISSUE TITLE
checkout-summary, I don't wont to summary shipping value 

### ISSUE THREAD

**Issue by chrisar45** [vtex-apps/store-discussion#445]
**What are you trying to accomplish? Please describe.**  
I'm trying to minicart totalizer to not add up to the shipping amount

**What have you tried so far?**  
I set the checkout-summary.compact and the summary-totalizers

**Additional info**  
```json
"minicart-summary": {
    "blocks": [
      "checkout-summary.compact#discounts"
    ]
  },
  "checkout-summary.compact#discounts": {
    "children": ["summary-totalizers#minicart"],
    "props": {
      "totalizersToShow": ["Discounts", "Items"],
      "blockClass": "summary-minicart"
    }
  },
  "summary-totalizers#minicart": {
    "props": {
      "showTotal": true,
      "showDeliveryTotal": false
    }
  }
```

Step by Step

- search "coca"
- Add "palta" to cart
- Open Minicart
- Look totalaizers

![image](https://user-images.githubusercontent.com/19915537/94074689-2b516180-fdd0-11ea-9479-6e2305748886.png)
![image](https://user-images.githubusercontent.com/19915537/94074777-563bb580-fdd0-11ea-9638-0c9132f3de71.png)
![image](https://user-images.githubusercontent.com/19915537/94074807-66539500-fdd0-11ea-9b98-6a741f2fc985.png)

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`dev`|

**Comment by klzns** [comment]
We can't change the calculation, in this case, it's better to hide the Total and change the Subtotal to be shown as Total.

What do you think?

**Comment by chrisar45** [comment]
mmmm, The problem is that I have to show both the Sub total and the Total
it is not uncommon that it automatically places the legend below
"Shipping costs and taxes calculated at checkout"

Any idea?

**Comment by lbauleo** [comment]
Chris, as we talked, this is a feature request and it was added to our backlog.

**Comment by klzns** [comment]
Fixed at https://github.com/vtex-apps/checkout-summary/pull/38
