### ISSUE TITLE
Error: Entry point create component

### ISSUE THREAD

**Issue by nelsonrTitamedia** [vtex-apps/store-discussion#447]
I am creating a new component for my store theme, I get the following error:
Error: Entry point "titamedia.santafe-theme@0.1.0/Empty" not found. Make sure it's the correct name and that it's in the root of the `react` directory.

create a folder react/Empty.js and another folder with react /components/empty/Empty.js

in interfaces.json it was added:
```
 "empty": {
  "component": "Empty"
}
```

| Account | Workspace |
|---|---|
|`titamedia`|`santafedevs`|

**Comment by lucis** [comment]
@nelsonrTitamedia is the component being `export default` on the file?

**Comment by nelsonrTitamedia** [comment]
Hi @lucis thanks for your support, my code is:
code react/Empty.js :

`import Empty from './components/empty/Empty'

export default Empty
`
code react /components/empty/Empty.js
`import React, { Component } from 'react'

class Empty extends Component {
    render() {
        return <h3>Hola</h3>
    }
}

export default Empty
`

**Comment by riodajs** [comment]
That's because in your manifest.json you don't have the react builder. Remember that you cannot link extended components if you did not fill out the form.
![image](https://user-images.githubusercontent.com/27719363/94368450-8cbc4d80-00ba-11eb-933d-26e3c766f9b8.png)
