### ISSUE TITLE
Cannot get specification values with useProduct since 7 days

### ISSUE THREAD

**Issue by pmarignan** [vtex-apps/store-discussion#448]
**Describe the bug**
Now useProduct doesn't return specifications properties when you call it from a component.

**To Reproduce**
Go on a vtex web store with vtex.io

1. Go to a vtex web store with vtex.io (all vtex.io webs)
2. Go to a category page
3. Inspect the page
4. Go to Component Toolbar
5. Inspect a product of the grid
6. Search the Product Component
7. As you can see, all the properties (specifications) have null value

**Expected behavior**
2 weeks ago, all the properties had value with useProduct and we can use it but now not.

**Screenshots**
[
![ScreenShot-ProductsGrid](https://user-images.githubusercontent.com/32361926/94377907-494af900-0125-11eb-89e3-a3995bf6e361.PNG)
](url)

**Smartphone environment (please complete the following information, if applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
No

Best regards,
Philippe.

**Comment by klzns** [comment]
Hi @pmarignan which store is this happening?

**Comment by pmarignan** [comment]
Hi,
I'm working on development workspace but you can test him on a public site like  https://www.als.com/clothing/shirts/Mens?map=c,c,specificationFilter_7721

**Comment by klzns** [comment]
Thanks, we'll investigate and let you know.

**Comment by pmarignan** [comment]
Ok thanks

**Comment by LucasTornai** [comment]
The fix is already deployed, it's rolling out for all stores right now 
![Screen Shot 2020-09-30 at 11 13 14](https://user-images.githubusercontent.com/28491720/94696960-0009cd80-030e-11eb-8ded-95d7a1866d03.png)

**Comment by pmarignan** [comment]
Great!

Thanks,

Best regards,
Philippe.
