### ISSUE TITLE
Oops not found state page should be flexible

### ISSUE THREAD

**Issue by denisebiscaro** [vtex-apps/store-discussion#45]
**Is your feature request related to a problem? Please describe.**
Currently, our "Oops not found" state page - that shows up whenever a search finds zero results - is very rigid. It only allows the user to show a Title and a Description. Some stores require different behaviors on this state, such as showing
- Shelfs
- Recommended products
- Main researched terms
- Infocards
- Carousels
- Banners
etc...

**Describe the solution you'd like**
Our empty state page should be flexible enough to allow different blocks and customization.

**Comment by klzns** [comment]
One can achieve that using the [block `not-found`](https://vtex.io/docs/components/search/vtex.search-result)
