### ISSUE TITLE
Fail to save file

### ISSUE THREAD

**Issue by alextalha** [vtex-apps/store-discussion#450]
**Describe the bug**

I'm trying to run my project. but the following error returns to me
"App build failed with message: Fail to save file"

I tried to check with the vtex link --verbose if I would return a more specific error but only give the same message.

**To Reproduce**

run the vtex link in both workspaces

natal--niazi.myvtex.com

newstore.somelacl.myvtex.com

**Screenshots**

![image](https://user-images.githubusercontent.com/4852136/94478790-244c9980-01aa-11eb-8d2c-b67ce410d6ce.png)

**Comment by iago1501** [comment]
This is already solved

**Comment by GabrielScopel** [comment]
não foi resolvido, erro acontece pra mim.

**Comment by marialuizaaires** [comment]
Hey, guys! I'm having the same problem here. What did you do to solve it, @alextalha?

Screenshot: 

![error-terminal](https://user-images.githubusercontent.com/84691125/181859162-9ed261d6-aae3-43f0-9780-1ec7d30ab580.png)

**Comment by Felipelourenco-dev** [comment]
Hey, guys! how did you solve this problem?

**Comment by marialuizaaires** [comment]
Hey, @Felipelourenco-dev! I only managed to solve this problem when I cloned the repository again.

**Comment by hugo-expe** [comment]
Are multiples causes. try first with vtex `link --clean` if it doesn't work, check if you are using Assets Builder and check which extension files you have there

> Any image extension is allowed, such as JPEG , PNG and GIF . Videos are not allowed yet. SVG o PDF.... 
https://developers.vtex.com/docs/guides/vtex-io-documentation-using-the-assets-builder

i'm not sure, i have a lot a project with SVG there and working, but the documentation is clear about that.

Or other problems with assets is filename with special characters. 

Or check file size of your files on Assets builder. 

If any of these work, write to vtex in the forum of community https://community.vtex.com/
