### ISSUE TITLE
Form Inputs placeholders and required labels

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-discussion#451]
Hello, everyone. I'm trying to customize a Form for my store. But I came into a problem.

I want to customize the text for my input **placeholder** and the **required** message it displays.

I looked for the props or infos about how to do it in the documentation but didn't find anything. 
I even looked in the JSX components codes to see if I find any props related to that.

![image](https://user-images.githubusercontent.com/45275689/94760585-4f391800-0379-11eb-9dc4-9e4c80a5e6c3.png)

Is is possible in this way, or should I try another one?

Thanks in advance.

**Comment by klzns** [comment]
Hi @leomuzicarvalho! Are you using store-form?

**Comment by leomuzicarvalho** [comment]
Hey, yes that's store form.

**Comment by leomuzicarvalho** [comment]
> Hi @leomuzicarvalho! Are you using store-form?

Hi, yes, I'm using store-form app. Any ideas? :) I'm facing the same problem with other blocks.

**Comment by klzns** [comment]
For the required message we use the native browser `required`. So there's no way to customize it.
See https://www.w3schools.com/tags/att_input_required.asp

For the placeholder, can you try adding the property `placeholder` to the field in the schema? I think that might work

**Comment by leomuzicarvalho** [comment]
Got it, @klzns , sorry for taking so long to reply. Placeholder works. Thanks!
