### ISSUE TITLE
How can I get the promotion highlight with cluster client active?

### ISSUE THREAD

**Issue by giovanapereira** [vtex-apps/store-discussion#454]
**What are you trying to accomplish? Please describe.**  
I need to bring the price with my promotion. And this promotion has cluster client, but I need to show this in product page and summary, not just in the checkout.
I'm use this app: https://github.com/vtex-apps/product-highlights/tree/master/react . But I don't know where I can change to bring the promotion if has cluster client.

**What have you tried so far?**  
I just extend the product-price app, but the values come to the page automatically with promotion when doesn't have cluester client with product-context. But where, in product-context or wherever, can I change the rule to bring the promotion with cluster client as well ? 

| Account | Workspace |
|---|---|
|`portaldolojistahomo`|`gipol`|

**Comment by klzns** [comment]
How can I test this? Which product and can you add me to the cluster? breno@vtex.com.br

**Comment by giovanapereira** [comment]
Sorry!

The link of the product:

https://gipol--portaldolojistahomo.myvtex.com/renault-logan-expression-2020-C89321-42/p

The promotion is: Promoção Flat 1.0 

Actually I removed the check of "Cluster de clientes" here:

![image](https://user-images.githubusercontent.com/26018620/95484981-83a76800-0967-11eb-824a-ea2151d08dbb.png)

But the other promotion is: Promoção Flat Acima 1.0

![image](https://user-images.githubusercontent.com/26018620/95485296-e7ca2c00-0967-11eb-84b5-718a76a544f5.png)

And the car with this promotion: 
https://gipol--portaldolojistahomo.myvtex.com/audi-a4-attraction-2018-A48707-42/p

I add you on the clusters! <3

**Comment by klzns** [comment]
OK, in the first product there's a promotion without restrictions available, so it shows up in the `discountHighlights` array:

![image](https://user-images.githubusercontent.com/284515/95492600-b5bdc780-0971-11eb-8faf-f48a73f3cc1c.png)

On the second, there's nothing because the promotion does not fit in those cases:
https://help.vtex.com/en/tutorial/configuring-promotions-with-a-highlightflag--tutorials_2295?locale=en

For the first you can use product-highlights with type `promotion` to show that this product is available to this promotion.

Something like this:
```json
{ 
  "vtex.product-highlights@2.x:product-highlights#promotion": {
    "props": {
      "type": "promotion"
    },
    "children": ["product-highlight-wrapper"]
  },
  "product-highlight-wrapper": {
    "children": ["product-highlight-text"]
  },
  "product-highlight-text": {
    "props": {
      "message": "{highlightName}"
    }
  }
}
```

There is no way to show the calculated price with the promotion applied though

**Comment by giovanapereira** [comment]
So, there is no way to send the price/promotion into second product with cluster of customers, like first product? There's no way I can develop this option on my own? ):

**Comment by klzns** [comment]
Sorry, I don't know how to achieve this.

Btw, if you are developing a B2B store there are some B2B apps that might be helpful:
https://github.com/search?q=topic%3Ab2b+org%3Avtex-apps+fork%3Atrue

**Comment by giovanapereira** [comment]
Ok, thanks! 
Now I don't know why into shelf the promotion doesn't appear, same with price. This link have products with the promotion without cluster customer:

https://gipol--portaldolojistahomo.myvtex.com/AUDI

I need to open a new issue @klzns ?
