### ISSUE TITLE
Selling Price 

### ISSUE THREAD

**Issue by yanethvg** [vtex-apps/store-discussion#455]
I would like to know if there is a component in vtex io that helps me to cross out the "NO DISCOUNT PRICE" but when there is no such "DISCOUNT" do not cross out the "NO DISCOUNT PRICE" I currently use https://vtex.io/docs/components/all/vtex.product-price@1.9.0/ and the code I use is this
```
 "product-selling-price#sellingPriceWithTaxProduct",
```
![image](https://user-images.githubusercontent.com/21286767/95537010-bb370400-09a9-11eb-8799-bbd5b623e544.png)
and in the admin I have configured this and applied styles with css

Currently displayed on screen
![image](https://user-images.githubusercontent.com/21286767/95537093-fe917280-09a9-11eb-864c-0cb13ac4fe01.png)

**Comment by iaronaraujo** [comment]
Hi @yanethvg ! Let me see if I got what you want correctly:
Let's suppose an item costs $10 but it has a discount of 10%, so you want to show ~~$10~~ and $9, right?
But when this discount isn't present, do you want to show it twice, or only $10 once?
If you want to show it only once, you can use the `product-list-price` to show the value without the discount and if there isn't any discount, this block will not be rendered!

**Comment by yanethvg** [comment]
thanks
