### ISSUE TITLE
Permission denied for install pixel app (Chaordic)

### ISSUE THREAD

**Issue by viniiciusmarques** [vtex-apps/store-discussion#457]
**What are you trying to accomplish? Please describe.**  
I'm trying to install the Linx (Chaordic) pixel, but I'm getting a permission denied message.

**What have you tried so far?**  
I tried to install pixel app from: https://github.com/vtex-apps/chaordic

**Additional info**  
![image](https://user-images.githubusercontent.com/25970024/96144260-5b28ec00-0eda-11eb-9cf1-40ea4e36c563.png)

| Account | Workspace |
|---|---|
|`mundoverde`|`vinicius`|

**Comment by lucis** [comment]
@viniiciusmarques do you have permissions to install app on this account? 

Can you post here the output of `vtex whoami`?

**Comment by viniiciusmarques** [comment]
@lucis 
I believe I am not allowed.

Output of vtex whoami:
![image](https://user-images.githubusercontent.com/25970024/96255215-e8c51400-0f8c-11eb-8525-7bbbf2fc5fce.png)

**Comment by lucis** [comment]
@viniiciusmarques Can you verify the permissions for your user regarding the **Billing** product?

This app, specifically, has a set of `billingOptions`. Despite it being "free", its installation requires a different kind of authorization on VTEX's Billing module. I've checked here, and the `Owner (Admin Super)` lacks some permissions on this module, so you might want to check that out or ask for the account's admin to install this app.

On our end, we'll work to improve the feedback message on theses cases.

**Comment by viniiciusmarques** [comment]
@lucis I will check my user's permissions.

Thank you for your attention.

**Comment by lucis** [comment]
@viniiciusmarques I'm sorry, I was wrong on my last comment.

Your user's roles on VTEX License Manager are fine and this was supposed to work. We've identified a problem within our code and are on our way to fix it. As soon as it hits production, I'll update it here. 

Same problem as #460

**Comment by lucis** [comment]
@viniiciusmarques can you try it now?

If you have `VTEX IO (Install App)` and `VTEX IO (Buy App)` permissions on your account, you should be good to go :)

Thanks for your patience!
