### ISSUE TITLE
Search Result Common Pagination (Numbers and Arrows)

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-discussion#459]
Hello, Vtex dev team.

I was looking into the GitHub code to find out properties values for **"pagination"** on **search-result-layout** block, as it's not described in the documentation.

Unfortunately I only found infinite scroll or the "show-more" to load more products:

![image](https://user-images.githubusercontent.com/45275689/96450373-7eaaaa00-11ec-11eb-87fa-8710320b50c6.png)

Based on that, I'd like to request the usual pagination approach, with numbers and arrows, if possible.

![image](https://user-images.githubusercontent.com/45275689/96450743-f8db2e80-11ec-11eb-8913-4721833f86f1.png)

Thanks in advance!

**Comment by Dracenco** [comment]
Is there any known ETA for this feature ? It is something I am also in need of.

**Comment by chrisar45** [comment]
I also need this functionality

**Comment by daniel-beta** [comment]
I would also like to apply this functionality on my website...

**Comment by jaimesanchezgalvisRicoh** [comment]
Hi VTEX team, Could you please provide information on whether the functionality for traditional pagination (with page numbers and navigation) is currently in development or if there are plans to include it in the future?

Thank you for your assistance.
