### ISSUE TITLE
Overriding iconpack.svg

### ISSUE THREAD

**Issue by blaurenzano** [vtex-apps/store-discussion#46]
I'm trying to override iconpack.svg as explained in the readme and can't make it to work, the store still uses the original iconpack.

I downloaded iconpack.svg from git and inserted it in the folder iconpacks/ in my store-theme, then I made some changes in some icons inside the file to test it. (for example, I deleted the little circles in hpa-cart directly in the svg file)
I added store-icons to the dependencies.

## Expected Behavior

Should see the changes in the icons in the linked workspace.

## Current Behavior

I keep seeing the same icons. The #styles_iconpack element in the DOM is still loaded with all the default icons instead of the overriden iconpack.

**Comment by saviofelixmuniz** [comment]
https://github.com/vtex-apps/store-discussion/issues/58
