### ISSUE TITLE
Steps for creating Usersnap pixel app

### ISSUE THREAD

**Issue by mauriciodinamarca** [vtex-apps/store-discussion#463]
**Is your feature request related to a problem? Please describe.**
We'd like to create [Usersnap](https://usersnap.com/) Pixel app.

**Describe the solution you'd like**
Tutorial with steps for creating a pixel app (as for example, fork the vtex-apps/pixel-app-template repository, and recommendations for creating a custom pixel).

**Describe alternatives you've considered**
Using GTM app for adding custom HTML, but it's blocked

**Additional context**
We'd like to build some pixel apps:

- [Usersnap](https://usersnap.com/)
- [Adere.so](https://www.adere.so/)

But we need some insights for doing it.
Best!,

**Comment by mauriciodinamarca** [comment]
Adere.so has a tag for example as:
`<script type="text/javascript">
(function() {
  var tc = document.createElement("script"); tc.type = "text/javascript"; tc.async = true;
  tc.src = "https://app.talkcenter.io/v2/talkcenter.min.js";
  var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(tc, s);
  })();
  window.TalkCenter = {token: "**TOKENHERE**"};
</script>`
We'd only need to modify [pixel/head.html](https://github.com/vtex-apps/pixel-app-template/blob/master/pixel/head.html) file, and create an app as by the form for submitting new apps?

Thanks!

**Comment by klzns** [comment]
> We'd only need to modify pixel/head.html file, and create an app as by the form for submitting new apps?

Yes, pretty much it!

You should also change the app `settingsSchema`: 
https://github.com/vtex-apps/pixel-app-template/blob/master/manifest.json#L27-L37

This will create a form to set the app settings just like this one:
![image](https://user-images.githubusercontent.com/284515/97005963-841e3200-1515-11eb-9d20-cbe291fa2512.png)

And then, change the `**TOKENHERE**` with `{{ settings.token }}` which will use the settings field mentioned above:
```html
<script type="text/javascript">
(function() {
  var tc = document.createElement("script"); tc.type = "text/javascript"; tc.async = true;
  tc.src = "https://app.talkcenter.io/v2/talkcenter.min.js";
  var s = document.getElementsByTagName("script")[0]; s.parentNode.insertBefore(tc, s);
  })();
  window.TalkCenter = {token: "{{ settings.token }}"};
</script>
```

**Comment by klzns** [comment]
We created docs for it:
https://vtex.io/docs/getting-started/develop-native-integrations-with-pixel-apps/1/
