### ISSUE TITLE
Zendesk App widget button

### ISSUE THREAD

**Issue by Marc4444** [vtex-apps/store-discussion#465]
**Describe the bug**
The Zendesk widget button is white with white text, fixed to the right of the screen, and not customizable 
 
**To Reproduce**
1. install the vtex zedesk chat first party app (y curent version vtex.zendesk-chat@1.3.1)
2.   i)  enter a valid key and Theme color (not black), and click save
      ii) on the zendesk dashboard ([youraccountname].zendesk.com/agent/admin/widget, scroll to "position" and select "left", then save
3. open your store
4. See error in button the bottom right
5. click on the white button, and it will open the zendesk chat
6. close the zendesk chat
7. the base zendesk chat button will appear with the styles set in the zendesk.com/agent/widget settings

**Expected behavior**
1.The vtex setup menu of the zendesk chat app should modify the styles of the "fake-zendesk-button"
2. Closing the zendesk chat should make the fake button reappear and not that of the zendesk/agent/admin

**Screenshots**
![White "fake-zendesk-btn"](https://user-images.githubusercontent.com/64534053/96995190-16cacb00-152e-11eb-85d6-cc9d70e9460b.png)
![zendesk chat with agent admin settings](https://user-images.githubusercontent.com/64534053/96995405-75904480-152e-11eb-8fac-1009f083545d.png)

**Additional context**
If the app setup menu is remade with these specs, the settings of the zendesk.com/agent/widget will be irrelevant, specifically:
 i) the color of the button's background and specify the input type (e.g. "use hex form #FFFFFF or rgb(255,255,255)")
![theme color input](https://user-images.githubusercontent.com/64534053/96996957-167fff00-1531-11eb-879f-9695ed7e3eaa.png)
 ii) the font color and style of the button
 iii) the position of the button in the window (at least "bottom-left" and "bottom-right")
 iv) the string to write on the button (for internationalization)

**Comment by klzns** [comment]
Hi can you provide a link to this workspace, please?

**Comment by klzns** [comment]
Recently we implemented a performance improvement on in https://github.com/vtex-apps/zendesk-chat/pull/13 that might be related to this issue

**Comment by Marc4444** [comment]
Here is our production workspace: https://storekimbo.myvtex.com/

**Comment by kaisermann** [comment]
Hey, @Marc4444 👋 thanks for detailing your issue!

Your suggestions about adding these settings to the app's settings page will be done. However, the zendesk API unfortunately doesn't allow us to detect if the user closed the chat window or not, which means we can't show/hide the `fake-zendesk-button` whenever we want. For now, we would have to configure the same appearance for the button on both zendesk and the zendesk pixel app settings.

**Comment by Marc4444** [comment]
Hi @kaisermann thank you for doing that. Recently I used the zendesk API to do the a similar task, i.e. a custom button to open the chat and reappear on closing the chat.
May I propose you could use the fake-button for the first open (for optimization purposes) but then reveal the "permant" fake-button with the API's on-close event e.g. zE("webWidget:on", "close", function { #permanentFake-button { display:block} }) ?

**Comment by kaisermann** [comment]
@Marc4444 Were you able to make the `close` event work? I'm unable to capture the moment a user closes/minimizes the chat widget. However, I managed to configure both the fake and real buttons through the app's settings, making the configuration from the Zendesk side unnecessary.

Check it here: https://kiwi--storecomponents.myvtex.com

The button that appears after you close the widget is the real one. It's not a 100% safe solution yet, but it's better than what we have today.

**Comment by Marc4444** [comment]
> @Marc4444 Were you able to make the `close` event work? I'm unable to capture the moment a user closes/minimizes the chat widget.

@kaisermann yes, you can see an example on the right side of this [website](https://www.manilagrace.com/it/). See if that solves the problem you're having, the "close" event happens on clicking the "x" on the chat window to be clear.
I'm happy to help you out if you like. Email me at marco.jones@filoblu.com.

> Check it here: https://kiwi--storecomponents.myvtex.com

Please could you grant me access marco.jones@filoblu.com to the kiwi workspace?

**Comment by kaisermann** [comment]
@Marc4444 I managed to make the event work, but how did you manage to hide the actual zendesk button?

**Comment by Marc4444** [comment]
@kaisermann the doc is very confusing about it, but it is "window.zE("webWidget", "hide");" to hide it. you must also hide it before in the "on:close" event because the on:close will try to show it again
`window.zE("webWidget:on", "close", function () {
window.zE("webWidget", "hide");
<reveal your real button here>
});`
