### ISSUE TITLE
specificationFilters prop of list-context.product-list doesn't work

### ISSUE THREAD

**Issue by giovanapereira** [vtex-apps/store-discussion#466]
**Describe the bug**
I'm using the specificationFilters into list-context.product-list and an error appears to me.
Initially, the products appear without category or collection, but just don't work anymore, just with collection id or category, but when I put one of this, my product-summary doesn't work with specification, just don't show the data specification. And when I use filters, the error occurs and show me nothing.
I try use "search-result.customQuery" on home, but I need to show the products with carroussel. 

**To Reproduce**
I'm using the normal blocks of store, and the error occurs. 

**Expected behavior**
Appears a product shelf with the products filtred with my props. It's a B2B enviroment, an user for test:

email: giovana.pereira@localiza.com
password: Acesso@1996

**Screenshots**

![image](https://user-images.githubusercontent.com/26018620/97017833-c4d17780-1524-11eb-8d67-b69227a2ca5b.png)

![image](https://user-images.githubusercontent.com/26018620/97017861-ce5adf80-1524-11eb-852f-9e4ae170cd45.png)

**Additional context**
My account was `portaldolojistahomo` and my workspace `gipol`.

**Comment by klzns** [comment]
Hi! `specificationFilters` is an array!
![image](https://user-images.githubusercontent.com/284515/97030690-82fcfd00-1535-11eb-982a-59a98648250a.png)

https://vtex.io/docs/components/all/vtex.product-summary@2.62.0/product-summary-list/

**Comment by giovanapereira** [comment]
Right! Now it's work the shelf with carousel, but the specification into shelf not working... Just with "custom-query" or in the search page. 

![image](https://user-images.githubusercontent.com/26018620/97031214-509fcf80-1536-11eb-8190-af1eedae72cc.png)

It's same block "product.summary.shelf"

**Comment by klzns** [comment]
Can you open a separate issue for that?
