### ISSUE TITLE
Vtex Component for Buy Together promo

### ISSUE THREAD

**Issue by jcdlyracons** [vtex-apps/store-discussion#468]
**What are you trying to accomplish? Please describe.**  
I am trying to show a Buy Together promo in the product view section and can not find an specific component for that functionality. 

**What have you tried so far?**  
I already found how to create the promotion in the admin section (https://help.vtex.com/es/tutorial/comprar-juntos-registro-de-promocion) but not how to implement that module in the store.

**Additional info**  
![image](https://user-images.githubusercontent.com/69350902/97036728-9f516780-153e-11eb-9cb6-640d7bf7fd9c.png)

| Account | Workspace |
|---|---|
|`poccarrefourarg`|`jcd`|

**Comment by thalytafabrine** [comment]
hi @jcdlyracons, how are you? 
today, we don't have any specific component to deal with the buy together promotions, but we have a shelf component in [this repository](https://github.com/vtex-apps/shelf-components/tree/master/react/components/BuyTogether) that has the possibility to buy products together in a single click.

example of what the component looks like: 
![image](https://user-images.githubusercontent.com/20840671/97043005-41c21880-1548-11eb-83a9-df13e55f96f6.png)

I believe this component could help you to implement what you want, however you need to pass directly to this component the list of products you want to display (with the exception of the PDP product that we take directly from the context)

I hope this helps, and if you have any more related questions feel free to ask me 😄

**Comment by jcdlyracons** [comment]
Hi @thalytafabrine. Thank you!. i really appreciate your answer, that component is exactly what i need. 

I have some issues with the component, can't find the way to link the products. I tried with show together feature for the sku and a buy together promo but it is showing only the base product and not the related products to sell together. Have u any guide or information that can help me with the configuration in the admin side?

Thank you again for your help. :smiley:

**Comment by thalytafabrine** [comment]
Hi @jcdlyracons,

since this component was not made to deal with buy together promotions, it will not get the related products from the promotion, you will need to pass these products directly to it through the [`suggestedProducts` prop](https://github.com/vtex-apps/shelf-components/blob/master/react/components/BuyTogether/index.tsx#L21). 

in your case, you want to show only 3 specific products that can be purchased together, so you would need to pass the two extra products (other than the PDP product) each in an array, so they will be displayed correctly on the screen.

when implementing this component we focused on using it for product recommendations from our Intelligent Search, so we didn't think about the promotions scenario, but we are already mapping this based on your use case and a few more people to implement in the next sprints.

**Comment by jcdlyracons** [comment]
Hi @thalytafabrine,

Have u any example of the value that should be passed in the suggestedProducts prop? I was trying with some product data formats for testing purposes but did not work. Is there any data model to use as base?. 

Thanks again for ur response and help.

**Comment by thalytafabrine** [comment]
@jcdlyracons the `suggestedProducts` prop is an array containing product lists. we use it this way because, as you can see in the image I put above, it is possible to change a product that is being displayed by clicking on the `change` button. 
each list within the `suggestedProducts` array will be a product to be displayed. if you don't want to use the option that change the displayed product, you can pass each list containing a single product.
e.g:
```
suggestedProducts: [
  [{name: "blouse", brand: "b1", brandId: "1", items: ...}],
  [{name: "product 2", brand: "pink", brandId: "2", items: ...}]
]
```
the product follows our current product structure

**Comment by thalytafabrine** [comment]
I will close this issue since there was no new question 🙂

**Comment by imediatadesign** [comment]
@thalytafabrine boa noite! Este [componente](https://github.com/vtex-apps/shelf-components/tree/master/react/components/BuyTogether)  está liberado para usarmos em IO?

**Comment by thalytafabrine** [comment]
@imediatadesign você pode usar, porém no momento não estamos dando manutenção a ele pois o projeto de recomendação de produtos foi pausado por um tempo. 
nesse caso você teria que fornecer as listas de produto a serem exibidas, então ficaria algo estático e não uma recomendação real baseada nos dados da loja (para o qual esse componente foi pensado)
lembrando também que ele não tem relação com as promoções de compre junto da loja.

**Comment by imediatadesign** [comment]
@thalytafabrine e seria possível usar o componente de " compre junto " , ou indicar alguma App que esteja ativa hoje pra utilizarmos em IO ?

**Comment by thalytafabrine** [comment]
@imediatadesign não entendi, qual componente de "compre junto" seria esse?
atualmente acredito que não temos nenhum componente para as promoções de compre junto, especificamente, portanto as lojas criam seus próprios componentes.
para o futuro desejamos evoluir a vitrine de buy together para suportar também essas promoções, mas não é algo que estamos priorizando agora.

**Comment by EduLeiteCorebiz** [comment]
@thalytafabrine , boa tarde. Estou tentando seguir esta documentação para criar uma shelf de "Compre Junto" na página de produto: https://developers.vtex.com/vtex-developer-docs/docs/vtex-recommendation-shelf. Mas me parece estranho ter que abrir um ticket para criar esta shelf. No meu caso os produtos do "Compre Junto" estão cadastrados como "Acessórios". Pode me indicar o componente ideal pra fazer isso ? Desde já agradeço

**Comment by fabiojarppi** [comment]
Hola @thalytafabrine  estoy intentando implementar el buyTogheter pero no entiendo muy bien como meter los productos de las promociones en la prop para que sean tomados que datos del array son necesarios tienes algun ejemplo claro y completo de esto ?

**Comment by amhaase** [comment]
Hi @jcdlyracons, did you find any way to make this component work?
I'm trying to follow the guidelines but I still haven't found a way to insert the suggestedProducts prop.

**Comment by 1SrGhost** [comment]
@amhaase  lograste integrarlo con la promocion de productos sugeridos? (https://help.vtex.com/es/tutorial/comprar-juntos-registro-de-promocion)  como lo comenta @jcdlyracons

**Comment by jcdlyracons** [comment]
Hi there @amhaase @1SrGhost @fabiojarppi  yeah, it worked but i had to create a new app with some customizations to get suggested products for the current product in context and inject the data to the App logic. You can create a custom app to get the product context, request the suggested products for that specific ID and finally inject those products in the "suggestedProducts" prop of the buy-together block. They need to have all the product fields and each product should to be inside an array as you can see in this answer. [thalytafabrine](https://github.com/thalytafabrine) commented [on Oct 29, 2020](https://github.com/vtex-apps/store-discussion/issues/468#issuecomment-718805761)
