### ISSUE TITLE
ProductID is undefined in related products shelf

### ISSUE THREAD

**Issue by fernandesmi** [vtex-apps/store-discussion#47]
**Describe the bug**
Related Products shelf has undefined productID.

**To Reproduce**
1. Go to https://miproduct--eriksbikeshop.myvtex.com/bianchi-2019-intenso-disc-ultegra-road-bike/p
2. Inspect RelatedProducts component and source code.

**Expected behavior**
It should return the shelf or an error.

**Additional context**
When adding a relatedProducts shelf in product page, the shelf is not displayed. 
The console and terminal don't return any error. However, the RelatedProducts source code shows that productid is undefined.

**Comment by denisebiscaro** [comment]
@fernandesmi are you trying to show the Related Products shelf, registered on the catalog as `Similar (Alternate Products)`? 
![image](https://user-images.githubusercontent.com/12139385/61551839-a3820180-aa2c-11e9-8b3f-b15386b903a3.png)
This option is available to be registered on each SKU

In our store theme, we have an example of product that have this option set: https://storetheme.vtex.com/classy--sunglasses/p

If this is not the case, how this RelatedProducts are being registered on de Catalog?

Tks
