### ISSUE TITLE
Size error

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#472]
I have a Sizes field, but on the front-end it tries to translate me. I attached screenshots
![Captura de Pantalla 2020-10-29 a la(s) 11 31 27](https://user-images.githubusercontent.com/3172828/97623514-622c2000-19eb-11eb-8925-40983e3eecc2.png)
![Captura de Pantalla 2020-10-29 a la(s) 11 31 16](https://user-images.githubusercontent.com/3172828/97623522-648e7a00-19eb-11eb-925f-7ad7335ea96c.png)

**Comment by klzns** [comment]
We are investigating.

Adding a link and some other info for debug:

https://anaisgtdev--anaisgt.myvtex.com/Hombre?fuzzy=0&map=department,category&operator=and&query=/hombre/textil

![image](https://user-images.githubusercontent.com/284515/97624165-7d0b8e00-1a05-11eb-893b-e456bf91742a.png)

**Comment by jorgerubik** [comment]
Yes, what I don't know is why you are trying to translate it or change the size, I don't know if I should put a parameter in the sku-selector block or what to do to change it

**Comment by klzns** [comment]
Fixed!

The tenant language was set to `en-US`, we changed it.

**Comment by jorgerubik** [comment]
Si, ya quedo en cada producto, pero en los filtros sigue apareciendo con dicho error.


![Captura de Pantalla 2020-10-30 a la(s) 8 55 25](https://user-images.githubusercontent.com/3172828/97720269-b12a9180-1a8d-11eb-9ad0-d82504ab9ee3.png)

**Comment by jorgerubik** [comment]
Sorry, I put it in English.
Yes, I am in each product, but the filters keep showing up with this error.
You can also tell me how I can make that change you made, thank you very much

**Comment by klzns** [comment]
Fixed!

For the record, the binding was also set with `en-US` we changed to `es-GT`

**Comment by jorgerubik** [comment]
Thank you very much for your support, I would only like to know if that can be changed by us from the vtex administration or from where we could change it for future occasions

**Comment by klzns** [comment]
Only by VTEX for now

**Comment by jorgerubik** [comment]
okay, to keep in mind. thanks
