### ISSUE TITLE
Go to payment button does not appear

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#476]
Hello, I am attaching screenshots, I do not know if it is a bug or that some configuration is incorrect, but sometimes it does not show the button
![Captura de Pantalla 2020-10-30 a la(s) 9 42 17](https://user-images.githubusercontent.com/3172828/97726264-aaebe380-1a94-11eb-8a46-0481bd90f7e0.png)
![Captura de Pantalla 2020-10-30 a la(s) 9 41 37](https://user-images.githubusercontent.com/3172828/97726276-acb5a700-1a94-11eb-95d5-a8c48c57775c.png)
![Captura de Pantalla 2020-10-30 a la(s) 9 42 27](https://user-images.githubusercontent.com/3172828/97726282-ad4e3d80-1a94-11eb-9a10-7084e86e12f1.png)

**Comment by klzns** [comment]
Sorry, this issue is out of the scope of store-discussion since the Checkout pages are out of VTEX IO and Store Framework.

Can you please open a ticket about this? Thanks in advance!
