### ISSUE TITLE
Sending Emails from App

### ISSUE THREAD

**Issue by khrizzcristian** [vtex-apps/store-discussion#477]
Hello,
Is there any way to send emails from a vtex app? With API / triggers / doesn't matter.

Thank you!

**Comment by lucis** [comment]
Hello, @khrizzcristian!

We do not yet offer such functionality directly on VTEX IO, but it's easy to accomplish it using **Master Data.**

You can read more about it [here](https://help.vtex.com/tutorial/setting-up-triggers--54eVOFGhS0EWyAUieoqKWo).

VTEX IO backend services are already baked with a `ctx.clients.masterdata` client to ease such connection :)

Let me know if that helps you.
