### ISSUE TITLE
Search result show-more freeze

### ISSUE THREAD

**Issue by cristian-milea** [vtex-apps/store-discussion#479]
**Describe the bug**
Show-more button doesn't show products until scroll on mobile
Used block: `search-result-layout.desktop.product-comparison`

**To Reproduce**

1. Go to https://www.f64.ro/aparate-foto
2. Scroll down to "vezi mai multe produse" (show more) and click
3. wait for button to load

**Expected behavior**
After the loading is complete, it should show the products

**Screenshots**
![image](https://user-images.githubusercontent.com/4988454/98268591-b3dc2980-1f5a-11eb-87c1-b236fe0f8e25.png)![image](https://user-images.githubusercontent.com/4988454/98268608-b9d20a80-1f5a-11eb-9125-07280a8de386.png)![image](https://user-images.githubusercontent.com/4988454/98268618-bd659180-1f5a-11eb-9a8d-63f20034ed0a.png)

**Smartphone environment (please complete the following information, if applicable):**
Tested on iOS with Safari,Chrome and Firefox and Android with Chrome and Firefox

**Comment by iago1501** [comment]
That's the behavior of lazy rendering that you set in performance store

![image](https://user-images.githubusercontent.com/13649073/103942699-8f91fa00-510f-11eb-9d2f-576755c792d3.png)

You can change it in Admin => CMS => Store => Advanced
