### ISSUE TITLE
wish-list - Can't add products to list

### ISSUE THREAD

**Issue by dapoz** [vtex-apps/store-discussion#480]
**Describe the bug**
When trying to add products to list with add-to-list-btn, it shows an error message

**To Reproduce**
- Access https://wishlist--hopelingerie.myvtex.com/sutias
- When clicking the button with a guest user, it correctly shows the message asking for login
- After loggin in and trying again, it does not allow to add

**Expected behavior**
Allow adding product to wishlist

**Screenshots**
<img width="405" alt="Screen Shot 2020-11-05 at 3 13 09 PM" src="https://user-images.githubusercontent.com/7804885/98281006-f57ccc80-1f7a-11eb-9406-365e308d8bab.png">
<img width="776" alt="Screen Shot 2020-11-05 at 3 13 39 PM" src="https://user-images.githubusercontent.com/7804885/98281023-f9105380-1f7a-11eb-8db6-d0bba2b1c844.png">

**Comment by wender** [comment]
@dapoz We're investigating this issue

**Comment by wender** [comment]
@dapoz we couldn't find any reason for that to stop working, It's working properly now, I did managed to get an error at first, started debugging but it suddenly start working, I guess it was some communication issue between the dependencies 
![image](https://user-images.githubusercontent.com/24723/98290592-a5a50200-1f88-11eb-8ca5-581564640459.png)

**Comment by dapoz** [comment]
@wender Confirmed it's working again, thank you!

**Comment by MatheusR42** [comment]
@wender 

We are with the same issue at this workspace: https://wishlist--consul.myvtex.com/eletrodomesticos/geladeira---refrigerador

![image](https://user-images.githubusercontent.com/16908590/115913523-18c30780-a447-11eb-91fa-ebeff6316f72.png)

**Comment by wender** [comment]
@MatheusR42 Hi Matheus, can you please try again using our latest version? (Deployed 1 hour ago) I just tested it with an 
 empty email and it worked [https://github.com/vtex-apps/wish-list/releases/tag/v1.6.0](https://github.com/vtex-apps/wish-list/releases/tag/v1.6.0)

**Comment by MatheusR42** [comment]
@wender now I can save to wish-list (when I updated the page the hearth icon keeps red), but when I go to https://wishlist--consul.myvtex.com/account/#/wishlist  I can't see the products.

**Comment by MatheusR42** [comment]
Thank you @wender  :)

**Comment by MatheusR42** [comment]
Thank you @wender! Now it works!
