### ISSUE TITLE
Modify the design of home page blog of app wordpress-integration

### ISSUE THREAD

**Issue by lyzmarpadilla** [vtex-apps/store-discussion#491]
**Is your feature request related to a problem? Please describe.**

I want to modify the design to homepage blog of app wordpress-integration, but can't update this app, what steps should I follow to modify this design?

**Describe the solution you'd like**
access to create a patch version

But need some insights for doing it.
Best regard!,

**Comment by polishq** [comment]
@lyzmarpadilla Hi, can you describe the modifications you'd like to make? There are several different blocks provided by this app that can be added to the blog homepage, providing for a variety of designs, and of course the styling can be customized as well. The design you're trying to accomplish may already be possible with the existing app.

**Comment by lyzmarpadilla** [comment]
@polishq I would like to do something like this filters
[https://www.atika.cl/blog/](url)

The idea is that clicking on any of these filters will show only those blog posts

**Comment by polishq** [comment]
@lyzmarpadilla I see. You could achieve a similar result with the existing app by placing links at the top of the blog homepage that would take the user to a URL like /blog/category/example-category . The VTEX store Worldwide Golf Shops is doing something similar here: https://www.worldwidegolfshops.com/insider (note the links at the top of the blog content - "Products and Brands", "Watts in the Bag", etc).
