### ISSUE TITLE
How to scroll to a section using Link block or Menu item?

### ISSUE THREAD

**Issue by leomuzicarvalho** [vtex-apps/store-discussion#494]
Hi, I've been trying to make this **menu item** scroll to my **newsletter section**:

![image](https://user-images.githubusercontent.com/45275689/100628141-a8d0ab00-3306-11eb-82c3-f2abb30b9617.png)

I tried using **Link block** with **scrollTo** prop, but I didn't really get by the documentation if that's this prop's purpose or how to use it...

I didn't find as well a way to define the ID of the HTML element, so I could simply do a href to its ID.

I appreciate any help, thoughts or ideas :)

**Comment by klzns** [comment]
Here is an example

Using the prop `scrollTo`:
https://github.com/vtex-apps/app-store-theme/blob/master/store/blocks/home/blocks/categories.jsonc#L141

Defining a rich-text with an ID:
https://github.com/vtex-apps/app-store-theme/blob/master/store/blocks/all-apps/blocks/categories.json#L156

You can check it running here:
https://apps.vtex.com/

![image](https://user-images.githubusercontent.com/284515/100631885-f6e7ad80-330a-11eb-99a2-930e6431cb1c.png)

Let me know if that helps! ✌️

**Comment by leomuzicarvalho** [comment]
Thanks, Breno! Problem solved. 💯 👍 🚀
