### ISSUE TITLE
Add modifier CSS class namespace to selected filter on Filter Navigator of Search Result app

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#5]
## Expected Behavior
As mentioned in [#128](https://github.com/vtex-apps/search-result/issues/128) we need to be able to identify which filters are selected and style them accordingly;

## Current Behavior
There is no CSS class namespace to distinguish which filters are selected or not.

## Possible Solution
Add a modifier CSS class namespace to `.filterItem` something like `.filterItem--selected`.

## Screenshot
![Screenshot from 2019-06-19 17-59-02](https://user-images.githubusercontent.com/1207017/59800559-4c69ff00-92bd-11e9-8e3b-a3df1f24e999.png)

**Comment by juliomoreira** [comment]
Hi @saviofelixmuniz can you please provide some feedback explaining why it's marked as `blocked 😢`?

**Comment by klzns** [comment]
Hi @juliomoreira we are checking on our side. We'll give some feedback in a couple of hours.

**Comment by klzns** [comment]
We will tackle this next week.

**Comment by jgfidelis** [comment]
Closed by: https://github.com/vtex-apps/search-result/pull/197

please take a look at the filterItem--selected class
