### ISSUE TITLE
Landing Pages with Search Context

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#50]
**Is your feature request related to a problem? Please describe.**
Today is not possible to create landing pages using Search Context on the Admin.

**Describe the solution you'd like**
We'd like to have an option to create pages on the "Pages" tab on VTEX new CMS, set a category template and a Search Context. (e.g. fq=H:123 fq=C:/1/2/3 etc...).

The old CMS has it and it works, the idea is the same but now using the the new CMS Admin.

![image](https://user-images.githubusercontent.com/1374326/60842053-9dc52a00-a1a9-11e9-919a-5e72de1917fc.png)

**Comment by klzns** [comment]
Adding more context:

Make it possible for a user to create search results page with a custom URL. Example:

1. User clicks to create a new page
2. User types the URL:  `/smartphones/sale`
3. User types in another field the query that will be made: `/smartphones/?map=c&clusterId=10`
4. User clicks Save

If a user navigate to `/smarphones/sales` it should open a search result page and pass to the search component the query defined previously. It should not happen a 301, the idea here is to basically mask the query searched.

**Comment by denisebiscaro** [comment]
There's also a request to do the opposite. When the user selects the filter "sale in the search result page of a category called "smartphones", for instance, the URL should be something as `/smarphones/sale` instead of `/smartphones/?map=c&clusterId=10`.

**Comment by klzns** [comment]
One can achieve that creating a `store.custom#fooBar` and using the block [`search-result-layout.customQuery`](https://vtex.io/docs/components/search/vtex.search-result#flexible-layout-update)
