### ISSUE TITLE
search-result-layout.customQuery with variable in queryField

### ISSUE THREAD

**Issue by mascDriver** [vtex-apps/store-discussion#500]
**What are you trying to accomplish? Please describe.**  
I would like to acquire the collection id by the url parameter so that it is not necessary to replicate the block infinite times

**What have you tried so far?**  
I've been using the link tutorial:
https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-associating-a-custom-page-to-a-content-type
but I was unable to get the param value for the queryField

**Additional info**  
the search code works with a fixed value, I would like to leave it variable, 
`collection_id = 158`

```
"search-result-layout.customQuery#collecion": {
    "props": {
      "querySchema": {
        "orderByField": "OrderByReleaseDateDESC",
        "hideUnavailableItems": true,
        "maxItemsPerPage": 8,
        "queryField": "{collection_id}",
        "mapField": "productClusterIds"
        ,"__unstableProductOriginVtex": true
      }
    },
    "blocks": [
      "search-result-layout.desktop",
      "search-result-layout.mobile",
      "search-not-found-layout"
    ]
  }
```

| Account | Workspace |

|`tfcov3`|`clinimenu`|

**Comment by klzns** [comment]
Btw, we are going to update the docs to have that more clear! Thanks
