### ISSUE TITLE
[google-customer-reviews] - Badge visible in home

### ISSUE THREAD

**Issue by mascDriver** [vtex-apps/store-discussion#502]
**What are you trying to accomplish? Please describe.**  

i'm trying to add my google customer review note badge on home

**What have you tried so far?**  
the only way i found to add it would be using the sandbox and adding the google generation script, but in the generated url one of the information comes out as null, origin=null

**Additional info**  
https://www.google.com/shopping/customerreviews/badge?usegapi=1&merchant_id=250973744&origin=null
correct is the 
https://www.google.com/shopping/customerreviews/badge?usegapi=1&merchant_id=250973744&origin=clinicompras.com.br
or the app generate badge for all site

| Account | Workspace |
|---|---|
|`tfcov3`|`clinimenu`|

**Comment by klzns** [comment]
Can you try using this app? https://github.com/vtex-apps/iframe

**Comment by mascDriver** [comment]
the url is generated with the google script, i don't know the consequences of using the direct url
https://support.google.com/merchants/answer/7105655?hl=en&ref_topic=7105160
the doc of script

**Comment by mascDriver** [comment]
the app https://github.com/vtex-apps/google-customer-reviews already makes the badge appear on the order placed, what is the possibility of extending the functionality to home?

**Comment by klzns** [comment]
Created a solution for this here: https://github.com/vtex-apps/google-customer-reviews/pull/9

**Comment by klzns** [comment]
@mascDriver do you mind testing this feature?

1. Install a beta version of this app in your workspace:
`vtex install vtex.google-customer-reviews@v1.0.8-beta.2`

2. Add the app to your theme peerDependency (when publishing this will require a new major version of the theme to be published, you will lose the site-editor settings, so you should update the app theme settings with this [tutorial](https://vtex.io/docs/recipes/development/migrating-CMS-settings-after-major-update)):

```diff
   "peerDependencies": {
     "vtex.reviews-and-ratings": "2.x",
+    "vtex.google-customer-reviews": "1.x"
   },
```

3. Add the block anywhere in your theme, example:

```diff
   "flex-layout.row#footer-1-desktop": {
     "children": [
       "vtex.menu@2.x:menu#Products",
       "vtex.menu@2.x:menu#footer-clothing",
       "vtex.menu@2.x:menu#footer-decoration",
       "vtex.menu@2.x:menu#footer-bags",
       "footer-spacer",
       "social-networks",
+      "google-customer-review-badge"
     ],
     "props": {
       "blockClass": "menu-row",
       "paddingTop": 6,
       "paddingBottom": 3
     }
   },
```

**Comment by mascDriver** [comment]
@klzns its correct the install line comand?
Invalid app format, please use <vendor>.<name>[@<version>]

**Comment by mascDriver** [comment]
@klzns its correct the install line comand?
Invalid app format, please use <vendor>.<name>[@<version>]

**Comment by mascDriver** [comment]
@klzns its correct the install line comand?
Invalid app format, please use `<vendor>.<name>[@<version>]`

**Comment by klzns** [comment]
sorry, fixed the command
vtex install vtex.google-customer-reviews@1.0.8-beta.2

**Comment by mascDriver** [comment]
is not working, if you want to access my workspace is the
https://clinimenu--tfcov3.myvtex.com/
at the bottom I add 2 places

**Comment by klzns** [comment]
Google it's returning 404 because it's not the origin/domain it's registered on Merchant Center

I had the same issue on my tests. We can only test this on production URL.  

Is this store published? If it is, we can try using the production url with the query string `?workspace=clinimenu`

**Comment by mascDriver** [comment]
yes, using the query string the badge has been working, great bro

**Comment by klzns** [comment]
That's good to hear! I'll publish the app

**Comment by mascDriver** [comment]
I have a problem when putting it into production using this app, returns the following error
`App build failed with message: Error with dependency vtex.google-customer-reviews@1.x: App cannot contain billing options: vtex.google-customer-reviews@1.x `
what can I do to fix?
