### ISSUE TITLE
How to define size col/row?

### ISSUE THREAD

**Issue by brunotda** [vtex-apps/store-discussion#504]
**What are you trying to accomplish? Please describe.**  
I need center "Logo" and two "Menu" inner center "sticky-header".

**What have you tried so far?**  

```
"sticky-layout#4-desktop": {
    "props": {
      "blockClass": "sticky-header"
    },
    "children": [
      "flex-layout.row#4-desktop"
    ]
  },
  "flex-layout.row#4-desktop": {
    "props": {
      "blockClass": "main-header",
      "verticalAlign": "middle",
      "horizontalAlign": "center",
      "preventHorizontalStretch": true,
      "preventVerticalStretch": true,
      "fullWidth": false
    },
    "children": [
      "flex-layout.col#search",
      "flex-layout.col#category-menu1",
      "flex-layout.col#logo-desktop",
      "flex-layout.col#category-menu2",
      "flex-layout.col#loginCart"
    ]
  }
```
**Additional info**  
![preciso](https://user-images.githubusercontent.com/15007670/102657585-b1254480-4154-11eb-995c-36fddea774a1.png)

**Comment by klzns** [comment]
You can try using the block `header-force-center`

**Comment by brunotda** [comment]
Not working, this block defined "absolute" and broke menu.

Menu and logo inner `header-force-center `result:
![image](https://user-images.githubusercontent.com/15007670/102691875-6f48dc80-41ee-11eb-9b35-c6e04a1f81b1.png)

Logo inner `header-force-center `result:
![image](https://user-images.githubusercontent.com/15007670/102691907-ab7c3d00-41ee-11eb-93c5-58ed74fe6cfa.png)
