### ISSUE TITLE
Product brand not working in PDP

### ISSUE THREAD

**Issue by alexandreTrino** [vtex-apps/store-discussion#505]
**Describe the bug**
I am tring to use *"vtex.product-list:product-brand"* and "product-brand" on json but return error.

**Expected behavior**
See the product brand

**Screenshots**

**Desktop environment (please complete the following information, if applicable):**

**Smartphone environment (please complete the following information, if applicable):**

ALL DEVICES

**Additional context**

ERROR BELOW:

Error rendering extension point
Error: useItemContext must be used within a ItemContextProvider
    at useItemContext (https://development--trovestyle.myvtex.com/_v/public/assets/v1/published/vtex.product-list@0.27.1/public/react/ProductList.js:49:11)
    at ProductBrand (https://development--trovestyle.myvtex.com/_v/public/assets/v1/published/vtex.product-list@0.27.1/public/react/ProductBrand.js:83:92)
    at renderWithHooks (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:15246:18)
    at mountIndeterminateComponent (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:17480:13)
    at beginWork$1 (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:18624:16)
    at HTMLUnknownElement.callCallback (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:341:14)
    at Object.invokeGuardedCallbackDev (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:391:16)
    at invokeGuardedCallback (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:448:31)
    at beginWork$$1 (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:23355:7)
    at performUnitOfWork (https://development--trovestyle.myvtex.com/_v/public/assets/v1/npm/react-dom@16.9.0/umd/react-dom.development.js:22346:12)

    in ProductBrand (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in ExtensionPoint (created by ExtensionPoint)
    in div (created by Col)
    in div (created by Col)
    in FlexLayoutContextProvider (created by Col)
    in Col (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in ExtensionPoint (created by ExtensionPoint)
    in div (created by Row)
    in div (created by Row)
    in FlexLayoutContextProvider (created by Row)
    in Row (created by FlexLayout)
    in section (created by ForwardRef(Container))
    in ForwardRef(Container) (created by FlexLayout)
    in div (created by FlexLayout)
    in FlexLayout (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in ExtensionPoint (created by withErrorBoundary(ExtensionPoint))
    in ErrorBoundary (created by withErrorBoundary(ExtensionPoint))
    in withErrorBoundary(ExtensionPoint) (created by Container)
    in div (created by Container)
    in Container (created by Container)
    in div (created by Container)
    in Container (created by LayoutContainer)
    in div (created by LoadingWrapper)
    in LoadingWrapper (created by LayoutContainer)
    in LayoutContainer (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in Content (created by ProductWrapper)
    in ProductContextProvider (created by ProductWrapper)
    in div (created by WrapperContainer)
    in div (created by WrapperContainer)
    in WrapperContainer (created by ProductWrapper)
    in ProductWrapper (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in ExtensionPoint (created by ExtensionPoint)
    in div (created by WrapperContainer)
    in div (created by WrapperContainer)
    in WrapperContainer (created by StoreWrapper)
    in OrderItemsProvider (created by StoreWrapper)
    in OrderFormProvider (created by StoreWrapper)
    in OrderQueueProvider (created by StoreWrapper)
    in OrderFormProvider (created by Mutation)
    in Mutation (created by Apollo(OrderFormProvider))
    in Apollo(OrderFormProvider) (created by Mutation)
    in Mutation (created by Apollo(Apollo(OrderFormProvider)))
    in Apollo(Apollo(OrderFormProvider)) (created by Mutation)
    in Mutation (created by Apollo(Apollo(Apollo(OrderFormProvider))))
    in Apollo(Apollo(Apollo(OrderFormProvider))) (created by Mutation)
    in Mutation (created by Apollo(Apollo(Apollo(Apollo(OrderFormProvider)))))
    in Apollo(Apollo(Apollo(Apollo(OrderFormProvider)))) (created by Mutation)
    in Mutation (created by Apollo(Apollo(Apollo(Apollo(Apollo(OrderFormProvider))))))
    in Apollo(Apollo(Apollo(Apollo(Apollo(OrderFormProvider))))) (created by Query)
    in Query (created by Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(OrderFormProvider)))))))
    in Apollo(Apollo(Apollo(Apollo(Apollo(Apollo(OrderFormProvider)))))) (created by StoreWrapper)
    in ToastManager (created by ToastProvider)
    in ToastProvider (created by StoreWrapper)
    in PWAProvider (created by Query)
    in Query (created by Apollo(PWAProvider))
    in Apollo(PWAProvider) (created by StoreWrapper)
    in PixelProvider (created by StoreWrapper)
    in StoreWrapper (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in ExtensionPoint (created by ExtensionPoint)
    in DefaultChallenge (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by ExtensionPoint)
    in ExtensionPoint (created by ExtensionPoint)
    in ExtensionPoint (created by withErrorBoundary(ExtensionPoint))
    in ErrorBoundary (created by withErrorBoundary(ExtensionPoint))
    in withErrorBoundary(ExtensionPoint) (created by RenderPage)
    in ProductContext (created by Query)
    in Query (created by Apollo(ProductContext))
    in Apollo(ProductContext) (created by Query)
    in Query (created by Apollo(Apollo(ProductContext)))
    in Apollo(Apollo(ProductContext)) (created by Query)
    in Query (created by Apollo(Apollo(Apollo(ProductContext))))
    in Apollo(Apollo(Apollo(ProductContext))) (created by Context.Consumer)
    in ApolloConsumer (created by withApollo(Apollo(Apollo(Apollo(ProductContext)))))
    in withApollo(Apollo(Apollo(Apollo(ProductContext)))) (created by ComponentLoader)
    in TreePathContextProvider (created by ComponentLoader)
    in ComponentLoader (created by MaybeContext)
    in MaybeContext (created by RenderPage)
    in RenderPage (created by RenderProvider)
    in div (created by RenderProvider)
    in PrefetchContextProvider (created by RenderProvider)
    in IntlProvider (created by RenderProvider)
    in ApolloProvider (created by RenderProvider)
    in TreePathContextProvider (created by RenderProvider)
    in RenderContextProvider (created by RenderProvider)
    in RenderProvider (created by WithDevice)
    in WithDevice

**Comment by pedromtec** [comment]
Hello @alexandreTrino, try to use `product-brand` from `store-components`. Ex: `vtex.store-components:product-brand`.

**Comment by klzns** [comment]
https://github.com/vtex-apps/store-discussion/issues/372#issuecomment-672226546
