### ISSUE TITLE
How to Scroll to an element within the same page?

### ISSUE THREAD

**Issue by Dracenco** [vtex-apps/store-discussion#509]
**What are you trying to accomplish? Please describe.**  
While having a product page with lots of information I want to have a link towards a specific element within the bottom of the  same page. For instance if I have a reviews section at the very end of the product page I want to have a "see reviews" text right next to the product image which will scroll the page to reviews section
**What have you tried so far?**  

I have tried building html structure within rich text element on both ends (top and bottom of the page) and giving href='element_name/class/id' to the sender while trying to give those parameters to the receiver at the bottom. the problem is that vtex is stripping the elements of anything except href, target and class. and those seem to be the props that cannot be given as an href target. 

I have also tried using the vtex.store-link component which seems to have a "scrollTo" prop but it does not seem to help when taking the trial and error approach. The documentation is very shallow and does not explain what is that props supposed to be accepting as value in a manner that would leave no questions. 

**Additional info**  

storeido account. currently no published version of this approach.  I am in a designing stage right now and wanted to find a way to do it before implementing. 

These lines of code :
```
    "rich-text#reviewTarget": {
          "props": {
            "text": "​<a id='anchor-tag' class='anchor-tag-class' name='anchor-tag-name'>s</a><div class='reviewTarget' name='reviewTarget' id='4'>‎</div>",
            "id": "reviewTarget"
          }
    },
```

Are resulting in this within the browser: 
https://prnt.sc/wg8sdi

Which, as you can see has no useful data for a sender element.

**Comment by Dracenco** [comment]
Issue fixed by giving "htmlId" prop to rich text section. this is one that is not mentioned in the documentation but does the trick. thanks a lot

**Comment by klzns** [comment]
Just documenting here for future users:

```json
{
  "link#anchor": {
    "props": {
      "label": "Go to lorem ipsum",
      "href": "#loremipsum",
      "scrollTo": "loremipsum"
    }
  },
  "rich-text#target": {
    "props": {
      "text": "Lorem ipsum",
      "htmlId": "loremipsum"
    }
  }
}
```

**Comment by klzns** [comment]
Also just added `htmlId` to the rich text docs
