### ISSUE TITLE
Add support for multiples classes on BlockClass

### ISSUE THREAD

**Issue by pachecovit** [vtex-apps/store-discussion#51]
**Is your feature request related to a problem? Please describe.**
Currently we pass only one class to 'blockClass' on vtex components, sometimes we need pass any modifier to some element, like this: blockClass: "class-element class-element--blue".

**Describe the solution you'd like**
blockClass must accept multiples classes

**Comment by klzns** [comment]
I'm more inclined to go this way:
https://github.com/vtex-apps/store-discussion/issues/23

**Comment by pachecovit** [comment]
> I'm more inclined to go this way: #23
> 
> So one could:
> 
> ```css
> .row--base {
>   margin: 10px;
>   color: red;
> }
> 
> .row--blue {
>    composes: row--base;
>    color: blue;
> }
> ```

Looks good! But why not enchanted with this two solutions? :)

**Comment by klzns** [comment]
You can pass multiple blockClasses using `"blockClass": ["foo", "bar"]`
