### ISSUE TITLE
Question - Installing service worker

### ISSUE THREAD

**Issue by Spadanera** [vtex-apps/store-discussion#513]
Hi,
I know it is not correct using Bug Report for this question, but the links to 'Ask a question' and 'Request feature' redirect to 404.

I would like to know if it is possible to install a service worker in the VTEX IO environment.

Thank you

**Comment by klzns** [comment]
Hi, @Spadanera VTEX IO provides a default service worker. If you want to develop your own, you should develop an app and deactivate our service worker.

You can see this app as an example:
https://github.com/vtex-apps/onesignal

We intend to ship a new way to do this in a couple of months, right now, that's the only way.
