### ISSUE TITLE
New Pixel App for dito.com.br

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#514]
**Is your feature request related to a problem? Please describe.**
I can't integrate Dito (See: https://store.vtex.com/servicos/?id=ditoapp / https://www.dito.com.br/) through GTM because it blocks Custom HTML Tags. It's an essential marketing tool for the business.

**Describe the solution you'd like**
A Dito Pixel App

**Describe alternatives you've considered**
There's a third-party app with a cost that is unviable (https://apps.vtex.com/acupula-ditocrm/p)

**Comment by gris** [comment]
Hi @jpesce . We now allow the use of custom HTML tags with a toggle on GTM settings. Check https://{workspace}--{account}.myvtex.com/admin/apps/vtex.google-tag-manager@2.8.0/setup/

<img width="488" alt="Screen Shot 2021-01-07 at 3 31 56 PM" src="https://user-images.githubusercontent.com/11340665/103930428-7c762e80-50fd-11eb-9cab-bc9e542b4dbf.png">

**Comment by jpesce** [comment]
Nice, thanks! That will do for now.

Would it have an increased performance if this was implemented through a Pixel App? If so, the original request is still valid.

**Comment by gris** [comment]
Humm I'm not sure. But the heads up is more because custom HTML tags can possibly get out of control as people put all kinds of scripts on GTM.

**Comment by iago1501** [comment]
Hello @jpesce look at this, this might help if you want to create a pixel app, like you saw, using custom HTML tags might cause some loss of performance 

https://vtex.io/docs/getting-started/develop-native-integrations-with-pixel-apps/1/

**Comment by jpesce** [comment]
Thank you very much @iago1501 !

It'd be helpful to update the current documentation:
https://vtex.io/docs/components/pixel/vtex.google-tag-manager@2.8.0/
<img width="580" alt="Screen Shot 2021-01-07 at 17 52 17" src="https://user-images.githubusercontent.com/1228352/103943669-3c20ab80-5111-11eb-9219-10455ec6ca4d.png">
