### ISSUE TITLE
SKU Selector in product summary

### ISSUE THREAD

**Issue by Gabriel637** [vtex-apps/store-discussion#516]
I am using the Product Summary in a shelf, and when I use the Sku Selector the product was expected to change the picture to the option selected in SKU

1. Use the product-summary-sku-selector
2. Click on sku-selector option
3. See error

**Expected behavior**
When select an option, changes the picture

**Screenshots**
![image](https://user-images.githubusercontent.com/37639798/104184213-dde61800-53f1-11eb-8263-373deb3e33ce.png)
![image](https://user-images.githubusercontent.com/37639798/104184239-e9394380-53f1-11eb-9823-db72b08bcd0c.png)

**Comment by klzns** [comment]
Can you provide account and workspace, please?

**Comment by Gabriel637** [comment]
sure 
https://gabrieldev--motorolaes.myvtex.com/

**Comment by thalytafabrine** [comment]
@Gabriel637 we already have this issue mapped to solve in the next weeks. as soon as it is fixed I update this issue. thank you 🙂

**Comment by pscruzzz** [comment]
Hello everyone! Got this issue fixed in my workspace by adding `"__unstableProductOriginVtex": true` as a prop to my `store.search` blocks (also added to `store.search#brand` , `store.search#department` and so on). As Thalyta said, this is a temporary prop, that will help you out until it's fixed!

@Gabriel637

**Comment by hugocostadev** [comment]
Hi All, the product-summary-sku-selector block does not work with "list-context.product-list" just in the gallery (search result page).
Is there any deadline to be fixed? Thanks

**Comment by thalytafabrine** [comment]
Hi everyone! I just launched a fix for this problem, so I will close this issue. Thank you all for your patience, and if you have any questions, you can mark me here 🙂
