### ISSUE TITLE
modify button text buy button when not available

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#518]
I want to know how I can modify only the text when a product is not available, since it places it as "Indisponible" and you want to change it to "No disponible".
Attachment screenshot
![Captura de Pantalla 2021-01-12 a la(s) 17 52 07](https://user-images.githubusercontent.com/3172828/104620619-d1adc500-5654-11eb-8542-0e8baa92f6eb.png)

**Comment by brunotda** [comment]
Did you try to change the messages in the GraphQL IDE?
https://vtex.io/docs/recipes/development/overwriting-the-messages-app/

**Comment by jorgerubik** [comment]
No, since I don't know how to use it and I didn't know that it could be done from here

**Comment by iago1501** [comment]
You need to use the doc that @brunotda send, and switch this text label that you can found in messages/es.json

https://github.com/vtex-apps/add-to-cart-button/blob/e56e6e4c5f45cff59737be7fb40f9ddcfa39250c/messages/es.json#L6
