### ISSUE TITLE
Extend Gallery and make editable by storefront

### ISSUE THREAD

**Issue by fernando143** [vtex-apps/store-discussion#52]
**What are you trying to accomplish? Please describe.**  
I extended Gallery of search-result, I would like do a editable customGallery. I know the syntax. But in the storefront customGallery doesn't appears.
I would like to do like this but with customGallery:
https://subefotos.com/ver/?ce5befde38a7dc0b9f585693f2e51537o.png
Regards

**Comment by klzns** [comment]
To appear in the CMS the component need to define a static property called `schema` with at least the property `title`.

Example: https://github.com/vtex-apps/rich-text/blob/master/react/index.tsx#L242-L287
