### ISSUE TITLE
[vtex-subscription] create page to config subscritption (client store)

### ISSUE THREAD

**Issue by mascDriver** [vtex-apps/store-discussion#523]
**Is your feature request related to a problem? Please describe.**
in vtex io the module subscription not have page to edition of subscription config, in the painel admin the redirect is
 `https://{}.myvtex.com/account#/subscriptions`  but this page is blank

**Describe the solution you'd like**
maybe create page with configs of yourself subscription(cancel, alter date or payment)

**Comment by klzns** [comment]
I think the app my-subscriptions is missing in your store:

If the account is provisioned by the Subscriptions API v2: vtex install vtex.my-subscriptions@1.x
If the account is provisioned by the Subscriptions API v3: vtex install vtex.my-subscriptions@3.x

**Comment by mascDriver** [comment]
taking advantage, my workspace is experiencing an error, but the reason is not anything new that I have added, can you help me?
wokspace is clinimenu

**Comment by mascDriver** [comment]
of course man, the page was rendered after installing `vtex install vtex.my-subscriptions@1.x`
