### ISSUE TITLE
Error 403 into graphql app into production url 

### ISSUE THREAD

**Issue by giovanapereira** [vtex-apps/store-discussion#527]
**What are you trying to accomplish? Please describe.**  
We are testing our website into final url and all our apps with graphql connection receive a 403 error.
In myvtex.com url it's work perfect, but into final url not working.
Anyone can help with a tip to why this happens?

Final url: https://portaldolojistaseminovos.localiza.com/fale-conosco (login and contact form receive the same error into console)

**What have you tried so far?**  
We tried to put into graphql app connection an outbond access with this url, but don't work.

**Additional info**  
Video: https://recordit.co/qyOyAPCCNL

| Account | Workspace |
|---|---|
|`portaldolojista`|`master`|

**Comment by klzns** [comment]
Oi, quando funciona no myvtex e não funciona em produção é um sinal que pode ser problema de uso de APIs que precisam de permissão de usuário. 

Em myvtex, estamos sempre logados com uma conta de admin. Em um ambiente de produção não.

Recomendo verificar quais APIs são usadas na chamada GraphQL. Se for o Masterdata, provavelmente a entidade não esta marcada para escrita publica.

**Comment by giovanapereira** [comment]
Oi coração! É isso mesmo, percebi que mudei em várias apps menos nessas duas do exemplo!
Criei o esquema no graphql para usar os headers para não tirar os campos do privado, obrigada!
