### ISSUE TITLE
Login app message. Can't find login app repository.

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#529]
**What are you trying to accomplish? Please describe.**  
I'm trying to rewrite the translation of the following message on vtex.login app:
"Receber código de acesso por e-mail"
<img width="216" alt="Screen Shot 2021-02-04 at 08 33 39" src="https://user-images.githubusercontent.com/1228352/106887312-c124c380-66c3-11eb-9bc6-a2d911200a8f.png">

However, I can't find the app's repository to see the message key. I need to run the following GraphQL query (as noted in https://vtex.io/docs/recipes/development/overwriting-the-messages-app/) and need the `srcMessage` for the message above.
<pre><code>{
  "saveArgs": {
    "to": "pt-BR",
    "messages": [
      {
        "srcLang": "en-DV",
        <strong>"srcMessage": "XXXXXXXX",</strong>
        "context": "vtex.login@2.x",
        "targetMessage": "My personalized message"
      }
    ]
  }
}</pre></code>

1. Where is the repository for the app?
2. Is there another way of finding the `srcMessage`?
3. What is the `srcMessage` for "Receber código de acesso por e-mail"?

**What have you tried so far?**  
Tried to find the repository.
Changed the message via CSS, however that's not ideal.

**Comment by iago1501** [comment]
Hello @jpesce, check this:

https://github.com/vtex-apps/login/blob/b0d705fda08b42b99486fbeba5accefce8421dda/messages/pt.json#L6

srcMessage is the label, like explained in our docs, in this specific case: "store/loginOptions.emailVerification"

You need to do something like this below:

```
{
  "saveArgs": {
    "to": "pt-BR",
    "messages": [
      {
        "srcLang": "en-DV",
        "srcMessage": "store/loginOptions.emailVerification",
        "context": "vtex.store-components@3.x",
        "targetMessage": "Your new text here"
      }
    ]
  }
}
```

**Comment by jpesce** [comment]
Hi @iago1501 , thanks for the reply, when I click your link it shows a 404 Page not found. Maybe the repo is restricted? That's why I'm not able to find the right `srcMessage` :)

But thanks for the answer, it worked!

In case someone needs for future reference, the query is the following (needed to change the `context` to the login app)
```
{
  "saveArgs": {
    "to": "pt-BR",
    "messages": [
      {
        "srcLang": "en-DV",
        "srcMessage": "store/loginOptions.emailVerification",
        "context": "vtex.login@2.x",
        "targetMessage": "Your new text here"
      }
    ]
  }
}
```

**Comment by iago1501** [comment]
That's it, thanks also to you!
