### ISSUE TITLE
[Styleguide] Expose modal classes through props.

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#53]
Former issue: [#676](https://github.com/vtex/styleguide/issues/676)

**Is your feature request related to a problem? Please describe.**
We need to be able to differentiate modals from one another; 

**Describe the solution you'd like**
We would like to be able to specify a unique class to the modal so we can style them accordingly;

**Comment by lbebber** [comment]
You mean, modals created using a `modal` block? Or modals created via React components?

**Comment by juliomoreira** [comment]
@lbebber React components.

**Comment by klzns** [comment]
You can nowt use [modal-layout](https://vtex.io/docs/components/layout/vtex.modal-layout) to achieve that.
