### ISSUE TITLE
vtex-apps / checkout: Logout button doesn't work

### ISSUE THREAD

**Issue by vtexdaniel** [vtex-apps/store-discussion#538]
**Describe the bug**
Sometimes the logout button from checkout doesn't work. Redirects to "Personal data" and redirect back without Logging out the user. Maybe on "Personal data" checks cookies or cache and the user is logged in again. Sometimes it works, but sometimes not.

**To Reproduce**

1. Go to 'https://distinctive.ro'
2. Login
3. Add something to cart
4. Go to checkout
5. Press "Nu esti tu? Iesi din cont" button

**Screenshots**
https://www.youtube.com/watch?v=NAU1K1qhjTI&feature=youtu.be

**Desktop environment (please complete the following information, if applicable):**
All devices

**Comment by klzns** [comment]
Same https://github.com/vtex-apps/checkout/issues/60
