### ISSUE TITLE
Styled Components with VTEX IO React 

### ISSUE THREAD

**Issue by hugocostadev** [vtex-apps/store-discussion#551]
Hi, I'm having some problems with VTEX IO and styled-components

I'm having a loading problem, the styled-components always load after all other styles, I think some SSR optimization is missing.

It's possible to check if the server is prepared for that? 
If you are using Next.js could be that: https://dev.to/rsanchezp/next-js-and-styled-components-style-loading-issue-3i68

In some big applications, it's preferred to use CSS in js instead of common css, which facilitated the development.

E.g Scenario: When creating a Skeleton component I'm not able to use styled-components because since it is not loaded right away the skeleton does not appear before the actual component.

**Comment by klzns** [comment]
Hi @hugocostadev, you are correct, we don't support styled-components during SSR. We don't intend to ship this right now.
