### ISSUE TITLE
modify the color of the loading bar

### ISSUE THREAD

**Issue by jorgerubik** [vtex-apps/store-discussion#560]
I would like to know how to change the color of the loading bar?

**Comment by rodrigogsn** [comment]
I believe that's the color `bg-action-primary` inside styles.json

**Comment by jorgerubik** [comment]
Thanks for the help, only that reviewing the file I only have this property: action-primary, I already changed the color but I did not update the color of the loading bar

**Comment by jorgerubik** [comment]
sorry i ran the vtex link again and it already did, thank you very much.
