### ISSUE TITLE
Getting this error in list-context.product-list: None or more than one app installed in this workspace implements the schema from vtex.search-graphql@0.43.0

### ISSUE THREAD

**Issue by arielapaula** [vtex-apps/store-discussion#562]
**Describe the bug**
I am getting this error while implementing the product-list-context.

**To Reproduce**
1. Add the dependencies in the manifest
2. call the block in the home.json:
`
  "store.home": {
    "blocks": [
      "list-context.image-list#home",
      "list-context.product-list#demo1",
      "flex-layout.row#promotional-info",
      "flex-layout.row#banner-home",
      "flex-layout.row#banner-brands",
      "flex-layout.row#newsletter"
    ]
  },`

2. Declare the block in the shelf.jsonc:
`{
  "product-summary.shelf#demo1": {
    "children": [
      "product-summary-name",
      "product-rating-inline",
      "product-summary-space",
      "product-summary-price",
      "product-summary-buy-button"
    ]
  },
  "list-context.product-list#demo1": {
    "blocks": [
      "product-summary.shelf#demo1"
    ],
    "children": [
      "slider-layout#demo-products"
    ],
    "props": {
      "category": "2"
    }
  },
  "slider-layout#demo-products": {
    "props": {
      "itemsPerPage": {
        "desktop": 1,
        "tablet": 1,
        "phone": 1
      },
      "blockClass": "shelf-container"
    }
  }
}`

**Expected behavior**
A shelf on related products

**Screenshots**
![Captura de pantalla de 2021-03-27 16-45-36](https://user-images.githubusercontent.com/36748003/112732960-eabbd780-8f1b-11eb-9b4c-b66a92fc6941.png)

**Desktop environment (please complete the following information, if applicable):**

 System:
    OS: Linux 5.4 Linux Mint 20.1 (Ulyssa)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 1.17 GB / 7.63 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.0 - /usr/bin/node
    Yarn: 1.22.10 - ~/node_modules/.bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 87.0

**Comment by klzns** [comment]
This happens when the account doesn't have any or more than one vtex.search-resolver

You can check that using `vtex ls` and looking for vtex.search-resolver, it should have only one version installed.

**Comment by arielapaula** [comment]
Thanks!
