### ISSUE TITLE
peerDependencies behaviour with site editor side effect

### ISSUE THREAD

**Issue by Git-the-Sanz** [vtex-apps/store-discussion#566]
**Is your feature request related to a problem? Please describe.**
When adding a peerDependency, it's mandatory to bump a major framework version.
It's a disruptive side effect that doing so deletes all custom configuration in the site editor.

**Describe the solution you'd like**
While not having a solution to persist/export site editor config, skip the major release requirement for peerDependencies

**Describe alternatives you've considered**
Make the developer/client acknowledge that introducing a peerDependency WITHOUT bumping a major release could potentially break something, instead of being a mandatory request.

**Additional context**
This is making the Site editor useless, as we cannot develop custom public apps for all our clients

**Comment by klzns** [comment]
Hi @Git-the-Sanz 

This can help:
https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-migrating-cms-settings-after-major-update
