### ISSUE TITLE
Allow product-specification render HTML

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#568]
**Is your feature request related to a problem? Please describe.**
In a number of scenarios it is useful to render HTML inside product specifications. The current implementation of product specification text escapes the HTML tags. For example:
<img width="386" alt="Screen Shot 2021-03-30 at 16 58 06" src="https://user-images.githubusercontent.com/1228352/113049252-ce1cdb00-9179-11eb-9d76-1b6f6f2993c8.png">

**Describe the solution you'd like**
Allow product specifications blocks to render HTML or create a new block that renders HTML

**Comment by jpesce** [comment]
@klzns The problem we talked about in Office Hours

**Comment by klzns** [comment]
@jpesce do you mind providing a workspace for tests?

**Comment by jpesce** [comment]
> @jpesce do you mind providing a workspace for tests? and a link to the product page in question

@klzns here it is: https://htmlspecification--oficinareserva.myvtex.com/catalogo-limonada---vol-1-azul-0046600516/p
<img width="388" alt="Screen Shot 2021-03-31 at 10 01 50" src="https://user-images.githubusercontent.com/1228352/113148360-226e9c00-9208-11eb-9faf-784bf65a16f4.png">

Thanks!
