### ISSUE TITLE
Product page constantly refreshing in a loop after link

### ISSUE THREAD

**Issue by rodrigogsn** [vtex-apps/store-discussion#572]
**Describe the bug**

Aftes linking the theme or making changes while linked (e.g. css) the page performs a full reload, but it "gets stuck" inside login page, constantly reloading. It seems it's trying to verify if I'm authenticated, but it never reaches to a conclusion nor let me put my credentials on.

Nonetheless, **I am already logged in:** if I stop this loop and browse the store manually, it successfully loads (until I link it again).

The path in my browser that keeps refreshing is this: https://prati--maeztraio.myvtex.com/_v/segment/admin-login/v1/login?returnUrl=/_v/segment/routing/vtex.store@2.x/product/97/prato-raso-greek-azul-navy---porto-brasil-29820/p?__device=tablet

But it has also happened with other products.

**To Reproduce**

I don't know exactly how to reproduce this. I've seen this in 2 accounts (`maeztraio` and `devnewbalance`) but I still don't know if this is related between them.
I've seen it happen only in PDP, while linking or manually refreshing the store.

I've tried cleaning browser history, remove cookies and sessions manually with Inspector. It has happened using Chrome and Vivaldi (chromium)

**Screenshots**

![image](https://user-images.githubusercontent.com/25557751/113923673-32195200-97bf-11eb-8da0-d9f043ade7bd.png)

| account   |  workspace   |
| - | - |
|  `maeztraio` |  `prati`  |

**Comment by klzns** [comment]
Hi, thanks for reporting. We are investigating the issue.

**Comment by klzns** [comment]
@rodrigogsn we fixed the issue!
