### ISSUE TITLE
[vtex.store-video] Muted property not working

### ISSUE THREAD

**Issue by JoKenPo** [vtex-apps/store-discussion#573]
**Describe the bug**
In the video app (vtex.store-video) apparently the mute prop is not working.
Even with it activated, it is not being considered on the front.

**To Reproduce**

1. Just insert a store-video block with the muted props as true.

**Expected behavior**
Was expected for the video to be muted for autoplay to work in chrome.

**Desktop environment:**

  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 806.44 MB / 7.81 GB
  Binaries:
    Node: 14.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\WINDOWS\system32\node_modules\.bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
    Internet Explorer: 11.0.19041.1

**Comment by klzns** [comment]
Hi @JoKenPo can you provide a link to a workspace with the issue? Thanks

**Comment by JoKenPo** [comment]
For sure.
You can see in this workspace:
https://devedu0704--hopelingerie.myvtex.com/

The second banner is a videos with autoplay and muted.
However, if it is in chrome, it will not autoplay precisely because muted is not working well

**Comment by luizfernandoargento** [comment]
Not work in Amazon aws media (mp4) too.
"loop": true,
"autoPlay": true,
"muted": false,
Workspace: https://luizdev1--docile.myvtex.com/
