### ISSUE TITLE
Where is the Prop "loading" at useProduct() context?

### ISSUE THREAD

**Issue by hugocostadev** [vtex-apps/store-discussion#575]
**What are you trying to accomplish? Please describe.**  
Previously I was using the property "loading" from useProduct() context, but I cannot find any more... 

**What have you tried so far?**  
I tried to use the "loading" prop on several PDP's

**Additional info**  
The loading prop exists in the productQuery

**Comment by klzns** [comment]
The fields that we have on Product Context are typed here:
https://github.com/vtex-apps/product-context/blob/master/react/ProductContextProvider.tsx#L37-L48

Not sure if we use to have it before 🤔
