### ISSUE TITLE
[google-customer-reviews] error in publish

### ISSUE THREAD

**Issue by mascDriver** [vtex-apps/store-discussion#576]
**What are you trying to accomplish? Please describe.**  
I have a problem when putting it into production using this app, returns the following error
```App build failed with message: Error with dependency vtex.google-customer-reviews@1.x: App cannot contain billing options: vtex.google-customer-reviews@1.x```
what can I do to fix?

| Account | Workspace |
|---|---|
|`tfcov3`|`baseteste`|

**Comment by klzns** [comment]
How is the `manifest.json` of your app?

Can you make sure it's a `peerDependency`?

More instructions here: https://github.com/vtex-apps/store-discussion/issues/502#issuecomment-747671568

**Comment by mascDriver** [comment]
yes
![image](https://user-images.githubusercontent.com/31291734/115292835-e22a7b80-a12c-11eb-90ce-f055cf5a0815.png)
but if i publish
```
16:36:08.182 - error: App build failed with message: It's not allowed change the current app PeerDependencies (direct or indirect) without releasing a new major version  
16:36:08.183 - error: Failed to publish tfcov3.clinicomprasio@1.3.9 
````

**Comment by klzns** [comment]
Yes, as explained in the comment linked above that's expected:

> Add the app to your theme peerDependency (when publishing this will require a new major version of the theme to be published, you will lose the site-editor settings, so you should update the app theme settings following this [tutorial](https://vtex.io/docs/recipes/development/migrating-CMS-settings-after-major-update)):

**Comment by mascDriver** [comment]
Will this migration take place in the wokspace of developer, production or master?

**Comment by mascDriver** [comment]
because if I couldn't launch the version of the app, I won't have access to it in other spaces, right?

**Comment by mascDriver** [comment]
the problem was that to add a peerDependencies it is necessary to release a major version and I was launching a patch, so if you do it `vtex release major stable` it will solve the problem
