### ISSUE TITLE
How do I migrate my custom favorite functionality to the Wishlist App? 

### ISSUE THREAD

**Issue by brendonguedes** [vtex-apps/store-discussion#578]
**What are you trying to accomplish? Please describe.**  
In the Consul Store, legacy. We had a feature to favor products on the product page and showcases that once clicked sent to the masterdata the user's email and the productId. We could consult this information at any time. Since we migrated to vtex IO2, we want to use the App Wish List, which performs this feature of favoring natively by vtex.
Can we merge the legacy database with the new wishlist database? If so, how?

**What have you tried so far?**  
With this question I intend to understand what would be the best way to implement the App WishList in my store and keep the functionality data that we had previously, now depreciated.

**Additional info**  
Add extra content here (code samples, screenshots,...)
Legacy functionalitiy
![image](https://user-images.githubusercontent.com/53941150/115460011-1f127300-a1fe-11eb-873d-9c23e58dd28d.png)

| Account | Workspace |
| ---|---|
|`Consul`|`https://brendondev--consul.myvtex.com/`|

**Comment by wender** [comment]
Hi @brendonguedes !
You can extract your data, convert it to the Json Schema that we use for the [wish-list](https://github.com/vtex-apps/wish-list) app and insert it at the **[wishlist](https://github.com/vtex-apps/wish-list/blob/c9a1860cd328da7fa8d541e76eccaff2ce64fb7c/dotnet/Data/WishListConstants.cs#L20)** entity

Notice that both Schema and Entity have the same name **wishlist**

Useful resources:
[https://developers.vtex.com/vtex-rest-api/reference/schemas#getschemabyname](https://developers.vtex.com/vtex-rest-api/reference/schemas#getschemabyname)

[https://developers.vtex.com/vtex-rest-api/reference/documents#createnewdocument](https://developers.vtex.com/vtex-rest-api/reference/documents#createnewdocument)
