### ISSUE TITLE
Bug wishlist add to list

### ISSUE THREAD

**Issue by stellassantos** [vtex-apps/store-discussion#583]
**Describe the bug**
When I click in the add-to-list-button to remove the product from my list, the button still red and the product in my wishlist.

**To Reproduce**

1. Go to 'https://devstella--shoulder.myvtex.com/saia-midi-evase-tencel-lavado-201091901/p'
2. Click on 'add-to-list-btn'
3. Click on 'add-to-list-btn' again

**Expected behavior**
The product is expected to be removed from the list, and icon change the background to white.

**Additional context**

**Comment by wender** [comment]
Hi @stellassantos I'm working on a fix to this, I'll let you know when it's deployed

**Comment by wender** [comment]
Fix deployed `vtex.wish-list@1.6.1`, thanks @stellassantos for letting us know
