### ISSUE TITLE
maxItemsPerPage always 10 per default

### ISSUE THREAD

**Issue by mroffe** [vtex-apps/store-discussion#59]
I try to configure the maximum number of items in department and category but it always takes the default value.

I've modified from block.js search-result # category an search-result # department "maxItemsPerPage": 20 (https://monosnap.com/file/iObpIQDvfSRnkGOuShfC2nPVSQbJ7l)
and from storefront (https://monosnap.com/file/iABZrrZe4pijxnOvtUPA3jnXkqMK81) but this always shows 10, as the documentation informs that it is the default value.

Workspace:
https://monosnap.com/file/TMtlohozEZVb22bmtKzEgnBxhQ3LSz

**Comment by denisebiscaro** [comment]
@mroffe This was a side-effect bug that was already solved and should be working properly. Please, let us know if this behavior is still taking place in your store.

**Comment by ccamargo2294** [comment]
Hey @mroffe, here we have a explanation about how to configure the maxItemPerPage in the blocks.json: https://github.com/vtex-apps/search-result#max-items-per-page-usage.
