### ISSUE TITLE
Wordpress Integration | All posts

### ISSUE THREAD

**Issue by joaopiramo** [vtex-apps/store-discussion#590]
Hello, my question is in the vtex.wordpress-integration component, I would like to know if you can make a page where I show all posts at once.

note: I tried to use store.blog-search-result, but I can't bring all posts at once.

**Comment by polishq** [comment]
Hi @joaopiramo , the block you'll want to use is `blog-all-posts.wordpress-all-posts`. Typically this would be placed on the `store.blog-home` page, but you should be able to place the block on any page in your store.
