### ISSUE TITLE
Missing Open Graph meta tags on custom pages

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#594]
**Is your feature request related to a problem? Please describe.**
On regular pages, we have open graph meta tags (`og:type`, `og:title`, `og:url`, `og:description`) that are rendered based on title, description etc:
<img width="925" alt="Screen Shot 2021-05-25 at 16 02 49" src="https://user-images.githubusercontent.com/1228352/119554245-d73db900-bd72-11eb-982d-561ba5a1023e.png">

However, on custom pages, the tags are missing. For example [on this page](https://www.oficinareserva.com/off):
<img width="875" alt="Screen Shot 2021-05-25 at 16 11 38" src="https://user-images.githubusercontent.com/1228352/119555234-00ab1480-bd74-11eb-8b54-647238e6f4cc.png">

**Describe the solution you'd like**
Add Open Graph meta tags to custom pages to improve SEO and improve sharing experience

**Comment by hugocostadev** [comment]
Hi @jpesce , maybe this app can help you: https://github.com/vtex-apps/open-graph
Never used, but seems to implement what you need!

**Comment by jpesce** [comment]
> Hi @jpesce , maybe this app can help you: https://github.com/vtex-apps/open-graph
> Never used, but seems to implement what you need!

Yes it does, thanks! :) My suggestion is to have them by default on all `store.custom` pages.
On office hours, the VTEX IO maintainers said it would be a good addition so hopefully they will implement it soon.

**Comment by gealcan** [comment]
Hi @hugocostadev , thanks for the tip !  
@victorhmp @igorbrasileiro The implementation was done in [#544](https://github.com/vtex-apps/store/pull/544). Could you please check if it is correct ?

**Comment by jpesce** [comment]
PR merged. Now custom pages have Open Graph tags 🕺
