### ISSUE TITLE
Getting this error in list-context.product-list

### ISSUE THREAD

**Issue by Fekleite** [vtex-apps/store-discussion#599]
**Describe the bug**
I am getting this error while implementing the product-list-context.

**To Reproduce**

1. Add the dependencies in the manifest
2. Call the block in the home.json:
```json
       {
          "store.home": {
            "blocks": [
              "list-context.image-list#full-slider",
              "slider-layout#tipbar",
              "rich-text#gender",
              "tab-layout#gender",
              "rich-text#novidades",
              "flex-layout.row#novidades",
              "responsive-layout.desktop#collection",
              "responsive-layout.mobile#collection",
              "rich-text#details",
              "responsive-layout.desktop#details",
              "responsive-layout.mobile#details",
              "flex-layout.row#linhas",
              "flex-layout.row#instagram"
            ]
          },
       }
```
3. Declare the block in the flex-layout.row#novidades:
```json
    "flex-layout.row#novidades": {
        "children": [
          "list-context.product-list#novidades"
        ]
      },
```
4. Declare the block in the list-context.product-list#novidades:
```json
 "list-context.product-list#novidades": {
    "blocks": [
      "product-summary.shelf"
    ],
    "children": [
      "slider-layout#shelf-novidades"
    ]
  },
```
5. Declare the block in the product-summary.shelf and slider-layout#shelf-novidades:
```json
 "product-summary.shelf": {
    "children": [
      "product-images",
      "product-summary-name",
      "product-selling-price",
      "product-installments",
      "add-to-cart-button"
    ]
  },

  "slider-layout#shelf-novidades": {
    "props": {
      "itemsPerPage": {
        "desktop": 4,
        "tablet": 2,
        "phone": 2
      },
      "infinite": true,
      "fullWidth": false,
      "blockClass": "novidades",
      "showNavigationArrows": "desktopOnly",
      "showPaginationDots": "desktopOnly"
    }
  },
```
6. Command vtex link

7. See error

**Expected behavior**
A shelf with products

**Screenshots**
![Screenshot (1)](https://user-images.githubusercontent.com/48728541/120192170-3b3c0380-c1f1-11eb-9d66-9e690b105814.png)

**Desktop environment (please complete the following information, if applicable):**

System:
    OS: Linux 5.11 Pop!_OS 20.04 LTS
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 3.19 GB / 15.45 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0.1

**Comment by iago1501** [comment]
You should install vtex.admin-search and vtex.search-resolver@1.x. After that, you will need to go to admin panel, search, integration settings: admin/search/integration-settings

And then, you should run new indexation, this will activate intelligent search for your store and the error should solve
