### ISSUE TITLE
Modifying New Credit Card Creation CSS?

### ISSUE THREAD

**Issue by JesuFernandez** [vtex-apps/store-discussion#6]
So, inside the account options, we have the payment methods, which include an iframe when you want to add a new card.

The matter is, when you use developer tools to see the classes to use, it shows that all classes come only from tachyons.css and not from a style.json class or a class you could use in a block css. (this means none of the two options listed before affect this button)

Is there a way to fix this and actually modify its CSS?

**Comment by fpsman** [comment]
This is related to the issue https://github.com/vtex-apps/my-account/issues/90 that I've reported.

It's similar to the behavior that we have on the checkout, an iframe that loads the content, but in the case of the checkout it has a custom CSS file to apply style inside the iframe.
