### ISSUE TITLE
RFC Condition block

### ISSUE THREAD

**Issue by klzns** [vtex-apps/store-discussion#60]
**Is your feature request related to a problem? Please describe.**

Sometimes the layout of the product page varies depending on the type of product.

**Describe the solution you'd like**

We propose the creation of a `conditional-layout` component, that renders something based on a condition.

Example of the blocks syntax:

```js
{
  "store.product": {
    "children": [
      "conditional-layout.product"
    ]
  },

  "conditional-layout.product": {
    "children": [
      "condition#kit",
      "condition#highlight",
      "condition.default",
    ]
  },

  "condition#kit": {
    "props": {
      "matching": "all",
      "conditions": [
        {
          "subject": "categoryId",
          "verb": "is",
          "object": 12
        }
      ]
    },
    "children": [ 
      "flex-layout.row#product-kit"
    ]
  },

  "condition#highlight": {
    "props": {
      "matching": "all",
      "conditions": [
        {
          "subject": "categoryId",
          "verb": "is",
          "object": 12
        }
      ]
    },
    "children": [ 
      "flex-layout.row#product-highlight"
    ]
  },

  "condition.default": {
    "children": [ 
      "flex-layout.row#product-default"
    ]
  }
}
```

`conditional-layout.product` would sniff child blocks props and check if a condition matched the product in context. If match, it would render the condition's children.

The idea is that `conditional-layout.product` would work like a switch, so if none match, it would render `condition.default`.

`conditional-layout` is `.product`, because we imagine that we would create conditional layouts based on contexts. Example `conditional-layout.sku-selector`, `conditional-layout.assembly-option`, etc.

**Describe alternatives you've considered**

We've also considered this syntax:

```js
{
  "conditional-layout.product#kit": {
    "props": {
      "matching": "all",
      "conditions": [
        {
          "subject": "categoryId"
          "verb": "is"
          "object": 10
        },
      ]
    }
    "blocks": [
      "condition-layout.true#1",
      "condition-layout.false#1"
    ]
  },

  "product-condition-layout.true#kit" {
    "children": [
      "flex-layout.row#product-kit"
    ]
  }

  "product-condition-layout.false#kit" {
    "children": [
      "conditional-layout.product#bar"
    ]
  },

  "conditional-layout.product#highlight": {
    "props": {
      "matching": "all",
      "conditions": [
        {
          "subject": "categoryId"
          "verb": "is"
          "object": 10
        },
      ]
    }
    "blocks": [
      "condition-layout.true#highlight",
      "condition-layout.false#highlight"
    ]
  },

  "product-condition-layout.true#kit" {
    "children": [
      "flex-layout.row#product-highlight"
    ]
  }

  "product-condition-layout.false#kit" {
    "children": [
      "flex-layout.row#product-default"
    ]
  }
}
```

This way we just need the current structure of children and blocks and React the usual way, but it's more verbose. This method is more life an `if` `else` chain, the first option is more like a `switch` `case`.

**Additional context**

This might be useful to render sku selectors, assembly options or other components that might  vary based on a criterion.

**Comment by klzns** [comment]
This feature will not be implemented. 

We will wait for a new feature that will cover this case which will allow changing the **page template** based on the product.

**Comment by klzns** [comment]
Aaand we are back to this proposal

**Comment by lbebber** [comment]
It must be noted that this proposal is being revived specifically for Product Details Page customisation for now, since it's a current need that doesn't have any good alternative for now, and the solution which we see is the ideal is coming on the medium/long term.

**Comment by kaisermann** [comment]
Just a remidner that when I was rewriting the `order-placed` app I stumbled upon one or two situations where the "ideal" solution would be a wrapper block that somehow understood a condition of its child. Since we don't have a better solution for now, as @lbebber, albeit not ideal, this looks good.

**Comment by denisebiscaro** [comment]
Finished - https://github.com/vtex-apps/condition-layout
