### ISSUE TITLE
Problems With Pixel App Template on CategoryView event

### ISSUE THREAD

**Issue by yagosenhorini** [vtex-apps/store-discussion#603]
I'm creating a pixel app based on the pixel template to integrate Dzarm Store (Hering Group) and Salesforce Einstein Recommendation Service (CRM Tool).

When I'm testing a category/search page, the events from category/department and internal search doesn't find the category id/name or the search term.

Is there a workaround to fix this issue or there is another way to implement these events?

Evidences:

index.tsx: https://prnt.sc/13ehwmb
console on department: https://prnt.sc/13ehztq

Account: dzarm
worskpace: yagosenhorini
Url: https://yagosenhorini--dzarm.myvtex.com/blusas?_q=blusa&map=ft

**Comment by kid-three** [comment]
Did you ever solve this?

**Comment by yagosenhorini** [comment]
> Did you ever solve this?

No, I have no idea about this problem.
I also tried a lot of temptatives but I can't go on in this case.

Do you have any idea about this?
