### ISSUE TITLE
product-summary-sku-selector problems

### ISSUE THREAD

**Issue by JoKenPo** [vtex-apps/store-discussion#605]
**What are you trying to accomplish? Please describe.**  
I'm developing a category page with size selection and buy button using existing blocks of "product-summary.shelf"

**What have you tried so far?**  
I'm having problems with the "product-summary-sku-selector". It always appears with the other sizes unavailable, but they are not. You can confirm this by accessing the same product on the product page

**Additional info**  
![image](https://user-images.githubusercontent.com/3427820/122453378-ab33e300-cf80-11eb-9341-49e8db11e54d.png)
Category page

![image](https://user-images.githubusercontent.com/3427820/122453486-c999de80-cf80-11eb-8efe-cf0f2e9448e1.png)
Product page

| Account | Workspace |
https://devedu--hoperesort.myvtex.com/mix-match

**Comment by IvanClementino** [comment]
Are you using "FIRST_AVAILABLE"? I believe this happens if it's not set to "ALL_AVAILABLE" or "ALL".

**Comment by JoKenPo** [comment]
The problem was just that. Thank you!

Just to describe: the problem is in the search that had the property "skusFilter":"FIRST_AVAILABLE"
