### ISSUE TITLE
Breadcrumbs in wrong order or not displaying

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#61]
**Describe the bug**
Sometimes breadcrumbs get out of order or do not display at all.

**To Reproduce**
1. Go to [Link](https://newbalance.myvtex.com/feminino/tenis);
2. See error

**Additional context**
We've investigated and our conclusion is that it may be related to the breadcrumb GraphQL resolver and probably have something to do with the `searchMetaData` properties having special characters. We don't know for sure;

**Comment by jgfidelis** [comment]
Fixed! 
![image](https://user-images.githubusercontent.com/4925068/61911423-d1c07f00-af0d-11e9-8a01-e18d52f8243a.png)

It was not a issue with the breadcrumb or our search.

The name of the category had an extra space, so it was called `"Tênis "`. This meat that the name of the slug was `tenis-`. So the query for category `tenis` was not working at all, or out methods were not finding a name for it, so it would return a null name.

We changed the name of the category in the db to `"Tênis"` and now everything is OK. We found another category had the same problem, fixed as well.

Thanks for the report!
