### ISSUE TITLE
Rendering HTML tags with id attribute on rich-text

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#62]
**Is your feature request related to a problem? Please describe.**
I need to have dynamic ids (configurable with storefront, not static) inside the rich-text content, to have anchor links to some content topic. Some Markdown implementations (like GitHub Flavored Markdown) allow us to create tags with id and they internally strip what is potentially dangerous, like script tags. Apparently, rich-text's version of markdown does not allow any HTML tags.
Or is there another way to add an `id` attribute to the rendered HTML without actually writing an HTML tag?
Having a clear explanation of what's possible to use on rich-text's markdown would also help a lot, because Markdown ecosystem is very fragmented and every version of it allows different options.

**Describe the solution you'd like**
I need a rendered output like this `<h1 id="infoPageContentTop">Introduction to Snowboards</h1>` to create anchor links for a menu.

**Describe alternatives you've considered**
N/A

**Additional context**
There's a menu with anchor links on [Erik's Bike Shop Snowboard Buying Guide](https://www.eriksbikeshop.com/snowboard-buying-guide.aspx) that I need to implement on a `store.custom` block with `rich-text`

**Comment by klzns** [comment]
Maybe we just need to automatically create the `id` attribute to h1, h2, h3, etc elements, just like GitHub does.

The code that needs to change is here:

https://github.com/vtex-apps/rich-text/blob/master/react/index.tsx#L169

**Comment by lbebber** [comment]
Care should be taken, though, with internationalization (i.e. should the `id` be the slugified text of the tag? if not, on what should it be based?)
