### ISSUE TITLE
Add option to order products by product cluster order on Shelf

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#63]
**Is your feature request related to a problem? Please describe.**
We've set the `productClusterOrder_${productClusterId}%20${(asc|desc)}` on shelves via `blocks.json` however when adding new configurations via Storefront the option is not in the list of available order by properties by design;

**Describe the solution you'd like**
We would like to be able to set this order by property via Storefront;

**Additional context**
CMS tutorial explaining how to order items by manual order [Link](https://help.vtex.com/known-issues/a-ordenacao-manual-de-colecao-nao-funciona?locale=pt)

**Comment by fabiofeichtinger** [comment]
Additional info: 
https://github.com/vtex-apps/shelf/blob/master/react/utils/OrdenationTypes.js

**Comment by denisebiscaro** [comment]
@juliomoreira @fabiofeichtinger please, could you detail how you've added this sort option in the blocks.json?

**Comment by juliomoreira** [comment]
@denisebiscaro like in the docs but replacing productClusterId by an actual id of a product cluster like so:

```json
{
  "shelf#home": {
    "props": {
      "orderBy": "productClusterOrder_141%20asc",
      ...
    }
  }
}
```

**Comment by juliomoreira** [comment]
@denisebiscaro just to be clear, we need this option to be selectable via Storefront;
