### ISSUE TITLE
Optimistic redirect of buy-button results in empty cart

### ISSUE THREAD

**Issue by gustavorosolem** [vtex-apps/store-discussion#64]
**Describe the bug**
When set `isOneClickBuy ` on `buy-button`, the component redirects to checkout in 500ms after the click, but due to this redirect, the request to add the product to cart may be canceled if it takes too long and you arrive at checkout without any product.

**Expected behavior**
Wait for the success return before redirect to checkout

**Additional context**
Some time the `addItem` query takes longer than usual, and when this happens, you see an empty cart.
![Carrin](https://user-images.githubusercontent.com/3163867/61484042-66f2cf00-a974-11e9-8b69-b49983619ea7.gif)

**Comment by jgfidelis** [comment]
@gustavorosolem se quiser, você pode fazer vc mesmo rapidinho
