### ISSUE TITLE
Wich VTEX hook to get the EAN code of a product inside minicartV2 ?

### ISSUE THREAD

**Issue by javier-puntocommerce** [vtex-apps/store-discussion#648]
**What are you trying to accomplish? Please describe.**  
Im using the minicartV2 app on my store inside this I need to show the product reference sku id and the product EAN code.
![image](https://user-images.githubusercontent.com/83361682/136708020-d7033716-94bb-4cac-b89e-98032380b0bf.png)

**What have you tried so far?**  
Already tried diferent props on "product-refreence" block. 
![image](https://user-images.githubusercontent.com/83361682/136708114-27522313-2027-4541-9447-4bc8d6f9da59.png)

As there are not a block to get this EAN inside the minicartV2 app I pretend to create a custom block for this, unfortunately I haven't found any hook to obtain this value yet

| tonypapelerias | devjav |
|---|---|
|`your account`|`your workspace`|

**Comment by carlosviniciusananias** [comment]
hi @javier-puntocommerce, how are you? the native block does not offer this prop that you want to use... alternative is to fork the product-list and add a prop for 'ean-code'
