### ISSUE TITLE
Add prop to disable lazy loading on product-summary-image

### ISSUE THREAD

**Issue by jpesce** [vtex-apps/store-discussion#649]
**What problem are you trying to solve?.**
Product-summay images are lazily loaded (`<img loading="lazy" .../>`), that means the browser fetches the image once it reaches a certain distance from the viewport. There are browsers that make this distance too conservative and breaks the user experience.

Consider a horizontal product slider without pagination that we want to show two products and a peak of the next one. With lazy loading, the peak of the next product may not be shown, depending on the browser's threshold and the amount of image shown:

<img src="https://user-images.githubusercontent.com/1228352/136797845-df83b366-1018-46ec-bb57-e7dde853ccd1.jpg" width="250" />

**Describe the solution you'd like**
Add a prop (`lazyLoad`) to `product-summary-image` that makes it possible to disable lazy loading. Default would be `true`.

**Why do you think this feature should be available to all stores?**
I think the scenario I pointed above is pretty common and the prop would allow more control over this behavior.

**Describe alternatives you've considered**
The only alternative I can think of is not to use the designed behavior. Either use pagination or increase the peak size (breaking the design).

**Additional context**
Here's the [code](https://github.com/vtex-apps/product-summary/blob/5af2d86be7c7f2c583b10f11ca237ff55c9cdaa3/react/ProductSummaryImage.tsx#L252) that needs to be changed. We would be happy to send a PR.

**Comment by iaronaraujo** [comment]
I believe this makes a lot of sense from the product point of view! Thank you a lot for this suggestion!
