### ISSUE TITLE
Locale switcher wont show languages from sales policies

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#65]
**Describe the bug**
Locale Switcher `Locales` query doesn't list languages from sales policies configuration;

**Expected behavior**
The Locale Switcher should match languages from sales policies configuration;

**Screenshots**
![download (1)](https://user-images.githubusercontent.com/1207017/61533686-f85d5200-aa03-11e9-96d8-8bb678abb015.png)

![Politica comercial](https://user-images.githubusercontent.com/1207017/61533783-39556680-aa04-11e9-9e89-e2151d4a3054.PNG)

**Additional context**
From our investigation it seems that the `Locales` query is returning an empty result thus the component fallbacks to the default options.

**Comment by Jeymisson** [comment]
There is this component: https://github.com/vtex-apps/locale-switcher, it should show languages setup on our new i18n app called `vtex.messages`.
@tlgimenes is preparing a feature that syncs messages' languages with sales policies' langs.

**Comment by fabiofeichtinger** [comment]
yes @Jeymisson, we're trying to use this feature but the languages are fixed here:
https://github.com/vtex-apps/locale-switcher/blob/master/react/components/index.js
