### ISSUE TITLE
What's the best way to use an app across different themes

### ISSUE THREAD

**Issue by miguel-rosa** [vtex-apps/store-discussion#653]
**What are you trying to accomplish? Please describe.**  
We have three different store templates, which are used in more than 20 stores. We're starting to separate the common components in apps, and we want to install them across the different themes, but without changing the vendor. We don't know what is the best practice for our case, how should be the vendors of the apps?

**What have you tried so far?**  
For now, we are changing the vendors of the apps at the moment of the releases but doesn't seem to be a good practice, another solution that we minded is to unify the vendors and use the apps as `peerDependencies`

| Account  |
|---|
|`motorolatemplateeu`|
|`motorolatemplateeub2b`|
|`motorolamea`|

**Comment by carlosviniciusananias** [comment]
hi miguel, how are you? I went through the same situation!!

an alternative to this is to create a **sponsor** account and only its child apps can install your apps.

in a simpler scenario you could just set **billingOptions** and enable its type as free... This would make your application public and available to be installed on any vendor from your *vendor.appname@version.app*.

**ps: the problem with enabling bilingOptions with type free is that any developer from another agency who knows their vendor name and app name can install in another environment.** 

this documentation can help you https://vtex.io/docs/recipes/development/setting-your-apps-billing-model/
