### ISSUE TITLE
Add prop analyticsProperties on store-link

### ISSUE THREAD

**Issue by gealcan** [vtex-apps/store-discussion#654]
**What problem are you trying to solve?.**
`store-Image` has an props `analyticsProperties` that can be enable. When enabled it is send an event to analytics when image was cliked . It's a way we can measure views and clicks on the image.
![Screenshot from 2021-10-26 13-56-00](https://user-images.githubusercontent.com/58344276/138927184-6729d96d-1d54-41dd-b10c-1f234b0bfe67.png)
However in a store banner I have a link component on the outside that contains the image and rich text component.
In this case the click was not made directly on the image and I do not receive the analytics measurements.
![Screenshot from 2021-10-26 14-29-06](https://user-images.githubusercontent.com/58344276/138930459-60ec7ca7-cd96-40cc-9f21-51e081a101fa.png)

**Describe the solution you'd like**
Adding the prop `analyticsProperties`  to the `store-link`  would solve the problem.

**Why do you think this feature should be available to all stores?**
In some cases it is common to use a larger click area besides the image

**Describe alternatives you've considered**
The only alternative I can think is adding the prop `analyticsProperties` to the `store-link` just as the `store-image` has.

**Additional context**
Here's the [code](https://github.com/vtex-apps/store-link/blob/master/react/StoreLink.tsx)  that needs to be changed. We would be happy to send a PR.

**Comment by iaronaraujo** [comment]
Hi @gealcan thank you for this suggestion! From the product point of view, this makes a lot of sense!

**Comment by icazevedo** [comment]
@gealcan looking into it from a technical standpoint, we don't think it makes a lot of sense for us to add this to store-link at this moment. What I and the team recommend you to do is to create a custom block that acts as a wrapper and fire the events you need to fire. This could be an invisible `<button>` html element or another element that accepts the `onClick` callback where you could put your logic.
