### ISSUE TITLE
Consuming external API on server without ssl in storefront

### ISSUE THREAD

**Issue by javier-puntocommerce** [vtex-apps/store-discussion#656]
**What are you trying to accomplish? 
Need to display specific options in city and state selects based on the postal code value, this options needs to be fetched from API located on the store owner serve  without SSL

**What have you tried so far?**  
Tried to fetch normaly but got this error:
Is there a way to make this fetch possible without adding SSL on that server?
![image](https://user-images.githubusercontent.com/83361682/139294251-02092fe9-2c0b-4f0f-80ab-4883d8c95f14.png)

**Additional info**  

| Account | Workspace |
|`tonypapelerias`|`devjav`|

**Comment by carlosviniciusananias** [comment]
this is caused by cors... you must configure enable server side cors. 

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/CORS
https://medium.com/@baphemot/understanding-cors-18ad6b478e2b

**Comment by javier-puntocommerce** [comment]
@carlosviniciusananias thanks had to add cors on header in the API response to make it work
