### ISSUE TITLE
Use useDevice hook from vtex.device-detector in vtex.store-footer

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#66]
**Describe the solution you'd like**
We would like to have the footer media-queries set dynamically by `vtex.device-detector` like you guys did in [`vtex.store-header`](https://github.com/vtex-apps/store-header/pull/98) additionally `vtex.device-detector` should be able to read break points defined in `styles.json` for better consistency.

**Comment by lbebber** [comment]
We already have a PR open for that (https://github.com/vtex-apps/store-footer/pull/78), just testing current published stores to check if it doesn't break anything.

Regarding:
> vtex.device-detector should be able to read break points defined in styles.json for better consistency

Could you open another topic here for that? It's something we have planned but we are not sure how to go about it yet.

**Comment by juliomoreira** [comment]
(Here)[https://github.com/vtex-apps/store-discussion/issues/70] @lbebber

**Comment by lbebber** [comment]
[This feature has been published](https://github.com/vtex-apps/store-footer/pull/78#issuecomment-516074993)
