### ISSUE TITLE
order-by.v2 does not work with search-result-layout.customQuery

### ISSUE THREAD

**Issue by brunotda** [vtex-apps/store-discussion#666]
**Describe the bug**
order-by.v2 not working with search-result-layout.customQuery

**To Reproduce**

1. Create a custom page with search-result-layout.customQuery and order-by.v2
2. Access the page
3. Click on the Order By element and change 
4. The url is changed, but the ordering is not applied.

**Expected behavior**
Order the products on the page

**Comment by Maik3345** [comment]
@brunotda we have the same problem, do you find any solution for this?

**Comment by iago1501** [comment]
Hello @brunotda , probably this is related to the search context, 

search-result-layout must be a block of store.custom, they can't use flex layouts under there, it's important to have it, it's a normal issue that we usually have, so, without more details this is the most i can give. So, as an example:

```
store.custom#test{
  "blocks": {
  "search-result-layout.customQuery...."
  }
}
```
