### ISSUE TITLE
Add filter quantity badge on mobile

### ISSUE THREAD

**Issue by pedrobernardina** [vtex-apps/store-discussion#669]
**What problem are you trying to solve?.**

At the search page, where products are shown, the user can apply different filters in order to get better results. On desktop, selected filters are displayed on the left side of the screen, and users always know how many filters they've applied. 

![Screenshot from 2022-01-06 10-39-05](https://user-images.githubusercontent.com/15324745/148391539-be91dafc-1b5e-4f39-a1d0-22504a5d27b3.png)

On mobile, the filters menu is inside a drawer, that is toggled by clicking a button. However, there is no indication if there's any active filter, forcing users to open the drawer in order to know how many filters they have applied.

![Screenshot from 2022-01-06 10-39-27](https://user-images.githubusercontent.com/15324745/148391565-d013a3a9-b2ed-47d9-a012-97ea54ab9cda.png)
![Screenshot from 2022-01-06 10-39-46](https://user-images.githubusercontent.com/15324745/148391567-ae23a29a-7f40-4b6b-a904-eeb78f3b5696.png)

**Describe the solution you'd like**

On mobile, we'd like to have a badge on top of the filters button, similar to what we have on MinicartIconButton, indicating how many filters the user has applied. It can be an optional prop, so it doesn't change the behaviour of other stores.

![image](https://user-images.githubusercontent.com/15324745/148391324-1278e3da-cdb9-40c6-a5c3-010ebfca9d66.png)
![Screenshot from 2022-01-06 10-38-32](https://user-images.githubusercontent.com/15324745/148392194-7677de65-7a12-473c-b63b-a15fe7c8998f.png)

**Why do you think this feature should be available to all stores?**

Mobile users would have a better user experience.

**Describe alternatives you've considered**

We read the docs and code of FilterNavigation.v3 to see if there was any way of enabling the desired behaviour, but there is none.

**Comment by pedrobernardina** [comment]
We've opened a pull request.

https://github.com/vtex-apps/search-result/pull/566

**Comment by igorbrasileiro** [comment]
Your proposal looks good, @pedrobernardina! Thank you

**Comment by pedrobernardina** [comment]
Implemented in https://github.com/vtex-apps/search-result/pull/566
