### ISSUE TITLE
Add CSS class namespace to results list wrapping tags in search bar

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#67]
**Is your feature request related to a problem? Please describe.**
We need to be able to customize the position and size of result list;

**Describe the solution you'd like**
We would like to have as many CSS class namespaces as possible to control the position and size of the result list but mainly in the wrapping `div`s that currently do that job; 

**Additional context**
![Tela_inteira_22_07_2019_10_58](https://user-images.githubusercontent.com/1207017/61740080-27f1be80-ad64-11e9-9c6c-622f3e91f06b.png)

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/store-components/pull/539
