### ISSUE TITLE
shelf.relatedProduct 2 items mobile

### ISSUE THREAD

**Issue by marmarquez** [vtex-apps/store-discussion#674]
I would like to know if I can modify the item that can be displayed per page for mobile, in the 'shelf.relatedProducts'. I only display 1, but I want 2.

In the props 'itemsPerPage' it is set only for dektop.

  "shelf.relatedProducts#1": {
    "blocks": ["product-summary.shelf#demo2"],
    "props": {
      "recommendation": "view",
      "productList": {
        "titleText": "Productos Relacionados I",
        "itemsPerPage": 4
      }
    }
  }

templatedev--delucca.myvtex.com/cafe-1820-clasico-cr-250gr/p

**Comment by IncognitaDev** [comment]
Hi, I have a [PR in product-summary](https://github.com/vtex-apps/product-summary/pull/347) wich have a alternative block to `shelf.relatedProducts` solving this type of problem, maybe this can help you cloning the branch, or help to get vtex attention to merge it.

**Comment by marmarquez** [comment]
Hello! Thanks for the reply. Then I realized that I could configure this from the site editor, it was very easy :)

**Comment by marmarquez** [comment]
Hello! Thanks for the reply. Then I realized that I could configure this from the site editor, it was very easy :)
