### ISSUE TITLE
Page product with error message #286

### ISSUE THREAD

**Issue by vitormetzner-LM** [vtex-apps/store-discussion#678]
when i click to enter a product i am getting an error message

"Something exploded: operationId = e483d43a-3d5f-4995-80a3-c661c07ab8d7
![error](https://user-images.githubusercontent.com/101183878/160187482-7faa032e-e790-4802-b6e3-9faae3db2fb0.jpeg)
"

To Reproduce

at home, I click on a product on the shelf to enter the product page

Expected behavior

open the product page

"vendor": "grupolamoda",
 "name": "grupolamoda-theme",
 workspace: grupolamoda

**Comment by vitorfarias001** [comment]
Resolved
