### ISSUE TITLE
Add prop to search result gallery on mobile to not turn into slider

### ISSUE THREAD

**Issue by pachecovit** [vtex-apps/store-discussion#68]
**Is your feature request related to a problem? Please describe.**
On several customers we need set the gallery shelfs in 2 columns on small screens, but, today the default is a shelf slider.

**Describe the solution you'd like**
Just add a boolean prop like 'sliderOnMobile'.

**Comment by denisebiscaro** [comment]
Hey @pachecovit ! Thanks for your suggestion.

Could you send us some examples and use cases - better if with images - of what you need? Just to make you necessity clearer.

**Comment by pachecovit** [comment]
@denisebiscaro, thanks for reply, but, we have found other solution for this issue and is not more necessary, please, consider this issue closed, thank you!

**Comment by denisebiscaro** [comment]
@pachecovit if you could share with us the workaround you've made, it would be great! :)

**Comment by pachecovit** [comment]
@denisebiscaro, sure! we've used 'search-result' component instead 'shelf' component, the result is more flexible to do what we needed
