### ISSUE TITLE
Update node engine to 12.22.12 (LTS)

### ISSUE THREAD

**Issue by pedrobernardina** [vtex-apps/store-discussion#682]
We need to use some fairly new libraries, that require a newer version of node engine than currently available. There are users on VTEX community with similar problems, but no solution was given.

VTEX runs node engine 12.16.1, and we would be updating minor versions, without any breaking changes. If possible to update the engine only for our account, that would be great as well.

Maybe it would be good for everyone if VTEX always kept the current major version updated with the latest LTS.

@jpesce for visibility

**Comment by brunoabreu** [comment]
Hi, Pedro! We tried to upgrade to v16 (active LTS) recently, but unfortunately, some of our services didn't perform well and we need to make some changes before upgrading.

In the meantime, we will try to update to 12.22.12 to allow the use of these libraries you mentioned.

**Comment by jpesce** [comment]
> In the meantime, we will try to update to 12.13.0 to allow the use of these libraries you mentioned.

Hi @brunoabreu , thanks for the reply!
Just to make sure, was that a typo? We need the latest v12 (erbium), that would be `v12.22.12` and not `v12.13.0`

**Comment by brunoabreu** [comment]
@jpesce just fixed :)

**Comment by jpesce** [comment]
@brunoabreu thanks! When you update to `v12.22.12` please let us know :) It's critical for a big app we’re working on.

**Comment by brunoabreu** [comment]
@jpesce done!
