### ISSUE TITLE
Product page redirecting to OLD(Default) cms page

### ISSUE THREAD

**Issue by ravimarici** [vtex-apps/store-discussion#684]
**What are you trying to accomplish? Please describe.**  
trying to create a new theme with product page

**What have you tried so far?**  
started with this https://learn.vtex.com/docs/course-basic-blocks-step01intro-lang-en 
to learn about it. home page is coming, but product page is going to OLD CMS page. can someone help me how to have my own PDP page.

**Additional info**  
Home Page:
![image](https://user-images.githubusercontent.com/102516623/170936304-1d759de2-5c58-4429-a6b9-26357057cadf.png)

PDP Page:
![image](https://user-images.githubusercontent.com/102516623/170936479-00236be9-8f08-4efd-899e-d2f1d411ab2e.png)

| Account | Workspace |
|---|---|
|maricisolutionspartnerin|games|

**Comment by ravimarici** [comment]
any update on this issue.

**Comment by brunotda** [comment]
Open a ticket on VTEX support.

**Comment by ravimarici** [comment]
okay thanks for the comment
