### ISSUE TITLE
Category menu won't follow order from admin

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#69]
**Describe the bug**
Category menu items order won't follow order set in admin interface;

**To Reproduce**
1. Follow [this tutorial](https://help.vtex.com/tutorial/disabling-and-reorganizing-categories?locale=en#object-object) to change categories order;
2. See that `category-menu` app items won't follow order set in admin; 

**Expected behavior**
The default order of items should be the order set manually in admin;

**Screenshots**
**Items order set by `category-menu` app**
![clara myvtex com_(iPhone 6_7_8)](https://user-images.githubusercontent.com/1207017/61976868-4bff0b00-afc3-11e9-8bc7-e3527a311216.png)
**Custom Order Set in Admin** 
![Screen Shot 2019-07-26 at 16 34 01](https://user-images.githubusercontent.com/1207017/61976938-751f9b80-afc3-11e9-8098-26a2be30c72b.png)
**Category Tree Catalog Request**
![Screen Shot 2019-07-26 at 16 34 18](https://user-images.githubusercontent.com/1207017/61976941-78b32280-afc3-11e9-9805-d35bf143db9d.png)

**Additional context**
We observed that the default order parameter is the category id and that the app uses the same order.

**Comment by hapoza** [comment]
@juliomoreira have you tried configuring each department on Storefront and ordering there? Or does it still orders by id anyways?

**Comment by baruchbucekt** [comment]
@klzns excuse me, that has been solved? I have the same issue right now

**Comment by klzns** [comment]
Hi @baruchbucekt, no.

category-menu app feature and bug fixes are frozen.

**Comment by baruchbucekt** [comment]
> Hi @baruchbucekt, no.
> 
> category-menu app feature and bug fixes are frozen.

Thanks, but what we can do to solve that?, I need order the categories like is on vtex, or what is your recommendation?
my site is https://vinndev--maraga.myvtex.com/
