### ISSUE TITLE
can't deploy app for releasing

### ISSUE THREAD

**Issue by ergineroglu** [vtex-apps/store-discussion#698]
**What are you trying to accomplish? Please describe.**  
We are a new app developer and trying to release first version of the app by following guidelines under:

- https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-8-makingyourpixelapppubliclyavailable
- https://developers.vtex.com/vtex-developer-docs/docs/vtex-io-documentation-deploying-the-app-stable-version

**What have you tried so far?**  
We have reacted to deploy state, but currently getting error in this step for following command:
```bash
$ vtex deploy segmentifypartneruk.segmentify@0.2.0
✔ Are you sure you want to deploy app segmentifypartneruk.segmentify@0.2.0 … yes
13:35:50.912 - error: Error patching publication metadata in new index: The state of segmentifypartneruk.segmentify@0.2.0 could not be patched: Cannot validate version which current state is different from Release Candidate
```

**Additional info**  
Name of the app is segmentify
details from manifest.json is given below:

```json
{
  "vendor": "segmentifypartneruk",
  "name": "segmentify",
  "version": "0.2.0",
  "title": "Segmentify",
  "description": "Segmentify App for Vtex Platform",
  "defaultLocale": "en-UK",
  "builders": {
    "pixel": "0.x",
    "messages": "1.x",
    "docs": "0.x",
    "react": "3.x",
    "store": "0.x"
  },
  "dependencies": {
    "vtex.pixel-interfaces": "1.x"
  },
  "billingOptions": {
    "free": true,
    "support": {
      "email": "support@segmentify.com",
      "url": "https://www.segmentify.com"
    },
    "availableCountries": ["*"]
  },
  "policies": [
    {
      "name": "pixel"
    }
  ],
  "settingsSchema": {
    "title": "Segmentify",
    "type": "object",
    "properties": {
      "apiKey": {
        "title": "Segmentify API Key",
        "description": "Enter your API Key for Segmentify",
        "type": "string"
      }
    }
  },
  "$schema": "https://raw.githubusercontent.com/vtex/node-vtex-api/master/gen/manifest.schema"
}
```

| Account | Workspace |
|---|---|
|`segmentifypartneruk`|`segmentifyprod`|

**Comment by polishq** [comment]
@ergineroglu Hi, thanks for the question. In this case you're getting an error message because the version you're trying to deploy has already been deployed. In other words, either you or someone else on your team previously successfully deployed version 0.2.0. Your release is complete!

**Comment by ergineroglu** [comment]
> 

thank you @polishq , I have missed I have already executed vtex deploy command without version included which I believe uses current version to deploy.
Now I can successfully finished promoting workspace and merged back to master.
