### ISSUE TITLE
Placing content in admin backend instead of blocks.json

### ISSUE THREAD

**Issue by tedtop** [vtex-apps/store-discussion#7]
We've been building large static content blocks as rich-text with Markdown with lots of \n escape characters. I understand there's a way to create this content in the admin backend. Would you please describe how to do this? Where does the content currently in the text prop go? And how do you tell the block to display the content from the admin backend?

**Comment by saviofelixmuniz** [comment]
Ya @tedtop, the best practice is not to put any content of sort on the blocks.json and instead provide it on the store-front. 
To do so, all you have to do is, go to /admin>Click on 'CMS'>'Storefront'.
Then find on the right panel the rich text block you want to edit. Just click on it, then edit the 'Text' box. 

![image](https://user-images.githubusercontent.com/18701182/59978533-91d74680-95b3-11e9-8ec6-09d739646ca7.png)
