### ISSUE TITLE
our app can't be installed on stores, urgent help is required

### ISSUE THREAD

**Issue by ergineroglu** [vtex-apps/store-discussion#702]
**Describe the bug**
We have updated our app and since then our app can't be installed from app store.

**To Reproduce**

1. Go to App Store, search for Segmentify App (link: https://apps.vtex.com/segmentifypartneruk-segmentify/p)
2. Click on "Get the App"
3. Scroll down and hit "Place Order" 
4.  Got error message "An error occurred while placing your order. Please try again."

**Expected behavior**
App should be installed without poroblem.

**Screenshots**
Details on [Loom](https://www.loom.com/share/97a2f21b12a44baab23c950ace82df01) 

We have also opened a forum post on Community: [link to post](https://community.vtex.com/t/customer-got-an-error-when-installing-our-app-from-app-store/36436) 

**Desktop environment (please complete the following information, if applicable):**

```
ergineroglu@EE-MacBook-Air:~/Repos/vtex-app (dev)$  npx envinfo --system --binaries --browsers
Need to install the following packages:
  envinfo@7.8.1
Ok to proceed? (y) y

  System:
    OS: macOS 13.2.1
    CPU: (8) arm64 Apple M1
    Memory: 153.63 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.6.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.4.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 112.0.5615.121
    Safari: 16.3
```

**Comment by lrodriguess** [comment]
Hi Ergin,
This is going to be treated in the ticketing system (ticket 801434)
tks
