### ISSUE TITLE
Logo & Image as SVG

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#71]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to use SVG on the logo and image blocks

**Describe the solution you'd like**
Allow [store-components/logo](https://github.com/vtex-apps/store-components/tree/master/react/components/Logo) and [store-components/image](https://github.com/vtex-apps/store-components/tree/master/react/components/Image) to use icons from `styles/iconpacks/iconpack.svg`

**Describe alternatives you've considered**
There's no way (or at least an easy way) to upload SVG files to VTEXImg CDN, thus this requires the need for an external CDN or converting the SVGs to PNGs

**Additional context**
N/A

**Comment by hapoza** [comment]
This issue could also be solved another way, if there was a vtex.admin-media-library app, with an UI to view, upload (and maybe possibly delete) all images that are available on vtex.file-manager-graphql. Similar to how [Wordpress Media Library](https://wordpress.org/support/article/media-library-screen/#media-library-grid-view) works, in that way we could upload images there and get the link to use on logo, image, etc.

**Comment by klzns** [comment]
cc @vtex-apps/pages-team
