### ISSUE TITLE
Create eBit badge app

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#75]
**Is your feature request related to a problem? Please describe.**
Some website certification and security badges (like eBit which is my use case) need to execute a script to show an up to date version of the badge instead of a static image.
Here's the sample code for eBit https://www.ebit.com.br/developer/codigo-da-medalha

**Describe the solution you'd like**
Create an app for eBit using the `shop-review-badge` interface

**Describe alternatives you've considered**
Using `sandbox`, which was also not possible

**Additional context**
![Anotação 2019-08-07 093046](https://user-images.githubusercontent.com/27775611/62622984-17aa1980-b8f6-11e9-8d95-8c899fcfaa90.png)

**Comment by luciannojunior** [comment]
It might be a good idea to have a set of default "badges" where you could just config with your `storeId` (for eBit) and it would work out-of-the-box, with the option to add custom badges as well.

**Comment by klzns** [comment]
We should create an for app for eBit using the https://github.com/vtex-apps/shop-review-interfaces

**Comment by hapoza** [comment]
I updated my issue message according to what you guys suggested, creating an ebit app. I was reading their docs and they also have a banner with a survey of the checkout process, so having that feature on order-placed would also be nice :)

https://www.ebit.com.br/developer/banner-ebit
