### ISSUE TITLE
[newsletter] Existing e-mail warning

### ISSUE THREAD

**Issue by kyoruu** [vtex-apps/store-discussion#76]
**Is your feature request related to a problem? Please describe.**
When I subscribe to a newsletter with an existing e-mail the component only returns a subscription confirmation.

**Describe the solution you'd like**
When subscribe to a newsletter, the component may detect if the e-mail is already in master data and returns an error message, like: "E-mail already registered"

**Comment by gustavorosolem** [comment]
I don't think the component needs to know if the user is already in the newsletter, what is the use case for this?
When the user is registering, doesn't matter if he is already in the list, he just want's to sign up.
He needs a warning just if this POST return a non success
I'm missing something?

**Comment by kyoruu** [comment]
I somehow agreed with you, but our costumer's layout asks for this feature.

**Comment by Klynger** [comment]
I discussed this feature, and we thought that this is not good and could be a security issue, so I'm closing this issue
