### ISSUE TITLE
FilterNavigator & orderBy buttons 'sticky' on small screens (mobile)

### ISSUE THREAD

**Issue by pachecovit** [vtex-apps/store-discussion#77]
**Is your feature request related to a problem? Please describe.**
On our most customers shop, they have fixed department filters buttons on top after user scrolldown on small screens.

**Describe the solution you'd like**
We need pass a prop like 'sticky: true' to search-result component.

**Additional context**
![Captura de Tela 2019-08-09 às 16 30 34](https://user-images.githubusercontent.com/6957485/62804261-242f9d00-bac3-11e9-88e3-812829c489c4.png)

**Comment by klzns** [comment]
Great suggestion!

**Comment by denisebiscaro** [comment]
This layout can be achieved with our new Sticky layout - https://github.com/vtex-apps/sticky-layout and Flexible search results
