### ISSUE TITLE
Minicart quantity selector value

### ISSUE THREAD

**Issue by rickrd** [vtex-apps/store-discussion#78]
**Describe the bug**
The product quantity value between the "-" and "+" is not appearing on mobile devices (tested with Iphone SE and Iphone 6S). 

**To Reproduce**
1. Access your IO store through mobile device
2. Add a product into minicart
3. Open minicart
3. See if product quantity value is visible

**Expected behavior**
It's expected the product quantity value to be visible and be modified by the quantity selector as well

**Screenshots**
![WhatsApp Image 2019-08-09 at 16 55 04](https://user-images.githubusercontent.com/15057760/62805966-e08b6200-bac7-11e9-9543-2f4b965faea0.jpeg)
![Captura de Tela 2019-08-09 às 16 51 53](https://user-images.githubusercontent.com/15057760/62806009-fb5dd680-bac7-11e9-994f-1eec79ba42c4.png)
![Captura de Tela 2019-08-09 às 16 53 16](https://user-images.githubusercontent.com/15057760/62805948-d79a9080-bac7-11e9-8dc7-9dd716aa8406.png)
I've tried to change background to black and color to white but the number wont show up.

**Smartphone (please complete the following information):**
 - Device: iPhone 6S, iPhone SE
 - Browser: Safari

**Comment by jgfidelis** [comment]
![image](https://user-images.githubusercontent.com/4925068/62980884-2c0e7a80-bdfe-11e9-88ec-d5af0ebb242c.png)

it seems like its OK here, where is this background: black coming from?

**Comment by rickarof** [comment]
Please pay attention on the following information about which device/S.O i've described and make sure you are running on the same device. It's actually occurring when i access https://storetheme.vtex.com and my own store-theme implementation through two different Apple mobile devices. (iPhone 6S and iPhone SE).
