### ISSUE TITLE
Store builder should warn about duplicate blocks

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#79]
**Is your feature request related to a problem? Please describe.**
Since we are now able to split `blocks.json` into multiple files, we started doing that for our apps in development. Somewhere during a conflict resolution, we ended up with two `logo#desktop` rules, one on `store/blocks.json` that was deleted before and moved to `store/blocks/header/header.json`. The old logo block on `blocks.json` was the one that showed up on the frontend.

**Describe the solution you'd like**
Store builder should have an error or warning message when there are duplicate blocks

**Comment by denisebiscaro** [comment]
https://github.com/vtex/builder-hub/pull/929
