### ISSUE TITLE
Uploading image assets and using it relatively

### ISSUE THREAD

**Issue by mjfernandezr** [vtex-apps/store-discussion#8]
Hello!

We're currently using VTEX.IO to set up our shop, but it seems any images we are implementing locally are not working at all. Thus our solution by now has been to upload directly to the CMS and using the absolute URL generated.

But is there a way to upload and use a relative source for them? Or is there an actual way to add local and make it work?

**Comment by saviofelixmuniz** [comment]
Hey @mjfernandezr,

Right now it's not currently possible to use images as public assets from code, thus using relative path on the filesystem. It's in our team roadmap but it's something that will probably take a while to be placed. So the best practice for doing this now is actually the way you're doing: using our CMS filesystem, getting a public URL and using it. 

I'll leave this question open and will close it once we have this feature!

**Comment by denisebiscaro** [comment]
https://vtex.io/docs/recipes/development/using-the-assets-builder
