### ISSUE TITLE
Duplicated category names

### ISSUE THREAD

**Issue by rickarof** [vtex-apps/store-discussion#82]
**Describe the bug**
When there's more than one subcategory with the same name registered in the category tree being children of the same departments, theres an unpredicted behavior occurring, which causes the selected filters that have duplicated names not to work as expected, actually the selected filters don't work at all, seems like the filter doesn't recognize them as registered categories and don't bring the respective products related to that category in the gallery.

**To Reproduce**
* Register two subcategories with the same name at the category tree, each one being children of different categories, but the same department.
* Go to your department page that's bringing the two subcategories with the same name
* Try to select one of the duplicated subcategories and see what happens

**Expected behavior**
It's expected that the selected duplicated subcategory can actually be recognized as a subcategory that can be used as a filter of the search result, regardless if there's another subcategory in the tree registered with the same name, because they're not the same and they have different products related to them.

**Screenshots**

![Captura de Tela 2019-08-13 às 17 17 06](https://user-images.githubusercontent.com/15057760/62974570-ec8c6200-bdee-11e9-9317-13b5eba2d488.png)
![Captura de Tela 2019-08-13 às 17 18 21](https://user-images.githubusercontent.com/15057760/62974571-ec8c6200-bdee-11e9-9158-2b990fa1b01f.png)
![Captura de Tela 2019-08-13 às 17 18 10](https://user-images.githubusercontent.com/15057760/62975253-5f4a0d00-bdf0-11e9-949f-11db843e6041.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome

**Comment by jgfidelis** [comment]
Are you using filter-navigator.v2?

**Comment by rickarof** [comment]
No, I just realized that by disattention i'm using the old filter-navigator. Now i've changed to v2 and the problem just can't be reproduced anymore. I'll close the issue, thanks!
