### ISSUE TITLE
Show product brand separately from product name

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#85]
**Is your feature request related to a problem? Please describe.**
On shelves and PDP pages, I need to show product brand on a different row and with different styles than product name

**Describe the solution you'd like**
There's two ways I thought possible:
1. Make vtex.store-components/ProductName flexible, making it possible to pick and choose which informations to show: product name, sku name, brand name and reference
2. Create a block and component specific for showing the brand

**Describe alternatives you've considered**
None without having an enterprise account, when the `showBrandName` prop is true, the brand name gets appended to the text content, making it impossible to style the brand name differently

**Additional context**
shelf
![Screenshot at Aug 16 01-07-11](https://user-images.githubusercontent.com/27775611/63143603-83ab1280-bfc5-11e9-9408-b3d6971bad10.png)

PDP
![Screenshot at Aug 16 01-17-18](https://user-images.githubusercontent.com/27775611/63143615-96254c00-bfc5-11e9-810d-b3d2b0a745fb.png)

**Comment by jgfidelis** [comment]
Doesn't product-brand defined here: https://github.com/vtex-apps/store-components/blob/master/store/interfaces.json, suit your needs?

**Comment by jgfidelis** [comment]
https://github.com/vtex-apps/store-components/tree/master/react/components/ProductBrand

**Comment by denisebiscaro** [comment]
I guess this component is not allowed on the Product Summary.... That's the problem hehe

**Comment by hapoza** [comment]
I didn't notice it was available on PDP, thanks!

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/product-summary/pull/179
