### ISSUE TITLE
Add quantity selector in shelf component

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#86]
**Is your feature request related to a problem? Please describe.**
I'd like to have a quantity selector in the shelf component to be used along with the `isOneClickBuy` parameter. 

This is very useful for stores that have a lot of products in the same order/cart and the products are bought in more than 1 qty. 

e.g. Grocery, Party supplies, etc.

I have an example in a VTEX CMS store that does it:
![image](https://user-images.githubusercontent.com/1374326/63204927-8ebc7c00-c073-11e9-8aee-b045ff302094.png)

The idea is that the user can choose the quantity before send the product to the cart (being redirected or not).

**Comment by denisebiscaro** [comment]
WIP https://github.com/vtex-apps/product-summary/pull/180
