### ISSUE TITLE
Minicart's scroll on mobile mode affects background page

### ISSUE THREAD

**Issue by denisebiscaro** [vtex-apps/store-discussion#88]
**Describe the bug**
When opening the minicart on mobile mode, the scroll affects the page on background, and not only the minicart.

**To Reproduce**
1. Open your website on mobile mode
2. Add one or two items to your minicart
3. Scroll down, and check that the scroll is actually scrolling the page in background.
![ScreenRecording2019-08-19at63125](https://user-images.githubusercontent.com/12139385/63301168-45a53b80-c2b0-11e9-8c69-1a4b6244827b.gif)

When the cart has many items, the scroll works properly:

![Screen Recording 2019-08-19 at 6 39 31 PM](https://user-images.githubusercontent.com/12139385/63301617-6326d500-c2b1-11e9-9dcf-82071f0bb199.gif)

**Expected behavior**
When all the items fit properly on the minicat on mobile mode, it shouldn't be possible to scroll the page when it is open. Currently, the scroll affects the page in background.

**Comment by Aarti43** [comment]
Could you please share the solution?
