### ISSUE TITLE
Allow disabling shelf slider on certain breakpoints

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#89]
**Is your feature request related to a problem? Please describe.**
I need to show a list of products on rows (similar to search-result's gallery) on large breakpoints, and keep the current shelf with slider behavior on smaller breakpoints.

**Describe the solution you'd like**
A prop similar to [slick's](http://kenwheeler.github.io/slick/) `responsive` and `unslick` options that allows disabling the slider on specific breakpoints.

**Describe alternatives you've considered**
Forcing with CSS does not work, other option is using a combination of search-result and shelf, which is hard to mantain and causes duplicate storefront configurations and queries on the frontend

**Comment by klzns** [comment]
You mean something like

Desktop
```
0 0 0 0
0 0 0 0
0 0 0 0
```
Mobile
```
< 0 0 >
```

(trying my best here 😬)

**Comment by fabiofeichtinger** [comment]
@klzns I don't know if this is the scenario that Dan needs, but I really have one situation similar to that.

**Comment by hapoza** [comment]
@klzns Yes, exactly!

**Comment by denisebiscaro** [comment]
I imagine that the best solution here would be to allow different layouts to mobile/desktop - as we already do with our header, for instance. What are your thoughts @hapoza @klzns?

**Comment by fabiofeichtinger** [comment]
Hello guys

I also have need, it's a similar context, but what I need is to disable the slider to **ALL** breakpoints, e.g.

1. Go to https://www.miniprix.ro/
2. On the home page, go to "Uite ce-i nou in magazin" section
3. Below this section, there is the shelf showing the products
4. The carousel is being rendered (https://flic.kr/p/2hbz7UL) on VTEX IO, however in active store (https://flic.kr/p/2hbyfDQ) the items has been shown below each other.

**Comment by hapoza** [comment]
@fabiofeichtinger You can use `search-result` instead of `shelf`.

**Comment by fabiofeichtinger** [comment]
Search-result does not fit our context of use as we need the tabs to select each collection or category of products, something only `shelf-tabbed` does

Example:

Each link above the shelf is a different collection.
![image](https://user-images.githubusercontent.com/1374326/65266288-2258f080-dae9-11e9-94f0-226dd2a4a82d.png)

**Comment by hapoza** [comment]
@fabiofeichtinger There's a new app, I haven't used with it yet to know if it will be useful for you, but: https://github.com/vtex-apps/tab-layout
