### ISSUE TITLE
Message center, translations and essentials?

### ISSUE THREAD

**Issue by mjfernandezr** [vtex-apps/store-discussion#9]
Hello!

We have been investigating, alongside our team, the creation of e-mails for our clients, but we have found the following issues:

1. Several of the e-mails are in Portuguese. Can we request VTEX to make an actual translation of them?
2. 63 templates is a lot! Is there a way to know which are priority mails so we focus on those first?

Thanks for your help!

**Comment by klzns** [comment]
I'm closing this issue since this is out of the scope of this repo. We are improving our README to add more context so it's easier to know what is appropriate to this channel.
