### ISSUE TITLE
How to override messages?

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#91]
**What are you trying to accomplish? Please describe.**  
Changing the "store/login.signIn" text for another string. 

**What have you tried so far?**  
I tried redefining that message with messages builder but it doesn't work, is this the intended way to override messages?
I added the builder `"messages": "1.x"` to manifest.json, created a messages folder in the store-theme root, and in it I created context.json and pt.json with values I got from https://github.com/vtex-apps/login/tree/master/messages, but the message stays the same when linking the app

**Additional info**  
context.json
```
{
  "store/login.signIn": "store/login.signIn"
}
```

pt.json
```
{
    "store/login.signIn": "Bem vindo! Faça seu Login"
}

```

| Account | Workspace |
|---|---|
|`paguemenosqa`|`qea`|

**Comment by klzns** [comment]
1. Install the app `vtex.admin-graphql-ide@3.x`
2. Open the GraphQL IDE Admin. Path: /admin/graphql-ide
3. Choose the app vtex.messages from the dropdown
4. Write the mutation:
```graphql
mutation Save($save: SaveArgs!){
  save(args: $save)
}
```
5. Scroll to the bottom of the page and click "Query variables"
6. Write the variables:
```graphql
{
  "save": {
    "to": "pt-BR",
    "messagesByProvider": [{
      "provider": "vtex.login@2.x",
      "messages": [{
        "id": "store/login.signIn",
        "content": "Bem vindo! Faça seu Login"
      }]
    }]
  }
}
```
7. Click the Play button to run the mutation.
8. Expect for the response:
```json
{
  "data": {
    "save": true
  }
}
```
9. Check the change in the store
![image](https://user-images.githubusercontent.com/284515/63456557-99856100-c425-11e9-9d32-fe15c210a8cc.png)

**Comment by hapoza** [comment]
@klzns Great, I'll try following your instructions asap!

**Comment by hapoza** [comment]
It worked, thank you
