### ISSUE TITLE
Missing 404 Page

### ISSUE THREAD

**Issue by fabiofeichtinger** [vtex-apps/store-discussion#92]
**Describe the bug**
I recently did a store migration from other platform to VTEX IO v2, and I've recently discovered that there's no 404 page when a user tries to access not existing product with the URL pattern `/not-found-product/p`

Example: https://storetheme.vtex.com/teste/p
![image](https://user-images.githubusercontent.com/1374326/63657558-eba5e980-c779-11e9-8145-cd13e3028486.png)

**Expected behavior**
On the old CMS when an user tries to access a not found URL from a product, it gets an "Empty Search" error. 

https://www.tokstok.com.br/teste/p - Redirects to -> https://www.tokstok.com.br/Sistema/404?ProductLinkNotFound=teste

But even for the old CMS it had a big problem, because this page (Sistema/404) responds with a HTTP Status Code 200, and the recommended behaviour is to respond with a 404 Status Code, to avoid search engines crawlers to index that page.

Google guidelines: https://support.google.com/webmasters/answer/93641?hl=en

**Comment by jgfidelis** [comment]
This is actually a bug, the old behaviour was correct, thanks for reporting, will take a look into this.

**Comment by pmartin-webimpacto** [comment]
It's possible to return a 404 code when product not exists? 
Our SEO team and our clients demand us . 

Thanks.

**Comment by denisebiscaro** [comment]
Now it's possible to set 404 status for product pages - https://vtex.io/docs/recipes/store-management/enabling-404-pages
