### ISSUE TITLE
Make the search-result components appear as spinners while products/page loading

### ISSUE THREAD

**Issue by rickrd** [vtex-apps/store-discussion#93]
**Is your feature request related to a problem? Please describe.**
We have experienced a strange behavior while accessing a category page through an apple mobile device, it turns out that the elements above the gallery (filter, orderBy, total products, etc..) are slightly breaking as in the loading they come close to each other. 

**Describe the solution you'd like**
Make the individual components or group of them, to appear as spinners while the page or the products is still loading, just like the gallery below.

**Comment by denisebiscaro** [comment]
fixed
