### ISSUE TITLE
Add "dropdown mode" to SKU Selector.

### ISSUE THREAD

**Issue by juliomoreira** [vtex-apps/store-discussion#96]
**Is your feature request related to a problem? Please describe.**
Depending on the type of variation if its values are large texts the "button mode" (current UI) can become cluttered.

**Describe the solution you'd like**
We would like to be able to specify a `mode` or `layoutMode` prop which would control if the variation should render buttons(current behavior) or a select/dropdown

**Additional context**
**Current UI With Large Text Values**
![Screen Shot 2019-08-30 at 10 27 45](https://user-images.githubusercontent.com/1207017/64024796-979c5b80-cb11-11e9-805a-8bb58af36b44.png)
**Example of a select/dropdown selector**
![Screen Shot 2019-08-30 at 10 34 03](https://user-images.githubusercontent.com/1207017/64024854-b995de00-cb11-11e9-95df-63cd0b6acb3f.png)

**Comment by fabiofeichtinger** [comment]
@denisebiscaro we need this feature for a project that we will launch next month, will it be delivery this month according with the milestone `10`?

**Comment by denisebiscaro** [comment]
https://github.com/vtex-apps/store-components/pull/645
