### ISSUE TITLE
Site Editor content keeps props from older store-theme versions

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#98]
**Describe the bug**
On Site Editor, if a content for a block is edited and saved, and afterwards a new version of the store-theme app is published with new props for that block, the old props persist. I found this problem when changing the `maxItems` prop for a `shelf` block from 4 to 5, but it never updated on the master workspace.

**To Reproduce**
1. Go to Site Editor and create or edit a content, save it.
2. On store-theme's blocks.json, edit a prop for a block that is not on the contentSchema (not editable on Site Editor), and publish/install the new app version.
3. Now the blocks that were previously saved on the master workspace will still have the old props settings

**Expected behavior**
Changes to props on blocks.json should be propagated to the master workspace, if they are not on contentSchema.

**Additional context**
There is a workaround, which is to create a new content and that will then get the new props, but all the content that was saved before the change in blocks.json will be permanently stuck with the "ghost" props. 👻

**Comment by thiagomurakami** [comment]
Hi @hapoza 👋 

Just to get some clarification, does this bug happen when you create *any* content? Or only when you edit that specific property?

If the property is on the schema _and_ the user edits it, the expected behavior is that the user configuration will always have precedence over the `blocks.json`, otherwise, every theme release would wipe the user defined contents.

**Comment by hapoza** [comment]
I agree that the user configuration should have priority, but shouldn't it be only for what's editable on the form?
I will try to reproduce the same behavior with other contents and let you know if it persists or if it was just an isolated case
