### ISSUE TITLE
Add classes for BuyButton's Toast message

### ISSUE THREAD

**Issue by hapoza** [vtex-apps/store-discussion#99]
**Is your feature request related to a problem? Please describe.**
The Toast message that shows up when a product is added to the cart does not have classes that can be used with styles builder, it's only possible with :global rules.

**Describe the solution you'd like**
Add a class for Toast

**Describe alternatives you've considered**
Using global rules which are fragile.

**Additional context**
![Screenshot at Sep 06 09-00-10](https://user-images.githubusercontent.com/27775611/64426502-100c9a80-d085-11e9-90d2-6adeeb1a6644.png)

**Comment by klzns** [comment]
What would you like to style?

**Comment by hapoza** [comment]
We had to vertically align the text (which relates to #100 ), and change the text case of the button (it was a clien'ts request 😅 )

**Comment by iaronaraujo** [comment]
https://github.com/vtex/styleguide/pull/838

**Comment by iaronaraujo** [comment]
Solved
